routes = routes or {}
routes.BreakingNewsWarmupRoute = {}
routes.BreakingNewsWarmupRoute.checkpoints = {}
routes.BreakingNewsWarmupRoute.checkpoints[1] = {}
routes.BreakingNewsWarmupRoute.checkpoints[1].position = vec.vector(-340.4149, 19.63365, 1058.072, 1)
routes.BreakingNewsWarmupRoute.checkpoints[1].heading = 1.694638
routes.BreakingNewsWarmupRoute.checkpoints[1].roadName = "dt_10l_south_01 AI Road 6"
routes.BreakingNewsWarmupRoute.checkpoints[2] = {}
routes.BreakingNewsWarmupRoute.checkpoints[2].position = vec.vector(-257.4396, 18.31252, 1047.856, 1)
routes.BreakingNewsWarmupRoute.checkpoints[2].heading = 1.692184
routes.BreakingNewsWarmupRoute.checkpoints[2].roadName = "dt_10l_south_01 AI Road 5"
routes.BreakingNewsWarmupRoute.checkpoints[3] = {}
routes.BreakingNewsWarmupRoute.checkpoints[3].position = vec.vector(-149.8869, 19.4159, 1146.245, 1)
routes.BreakingNewsWarmupRoute.checkpoints[3].heading = 0.2189864
routes.BreakingNewsWarmupRoute.checkpoints[3].roadName = "dt_10l_centre_02 AI Road 0"
routes.BreakingNewsWarmupRoute.checkpoints[4] = {}
routes.BreakingNewsWarmupRoute.checkpoints[4].position = vec.vector(-205.7378, 21.9586, 1232.228, 1)
routes.BreakingNewsWarmupRoute.checkpoints[4].heading = -1.395801
routes.BreakingNewsWarmupRoute.checkpoints[4].roadName = "dt_shortcut_03a AI Road 2"
routes.BreakingNewsWarmupRoute.checkpoints[5] = {}
routes.BreakingNewsWarmupRoute.checkpoints[5].position = vec.vector(-416.5112, 23.68785, 1241.576, 1)
routes.BreakingNewsWarmupRoute.checkpoints[5].heading = -1.57767
routes.BreakingNewsWarmupRoute.checkpoints[5].roadName = "dt_shortcut_03a AI Road 1"
routes.BreakingNewsWarmupRoute.checkpoints[6] = {}
routes.BreakingNewsWarmupRoute.checkpoints[6].position = vec.vector(-646.1646, 30.29311, 1232.912, 1)
routes.BreakingNewsWarmupRoute.checkpoints[6].heading = -1.627994
routes.BreakingNewsWarmupRoute.checkpoints[6].roadName = "dt_shortcut_03a AI Road 0"
routes.BreakingNewsWarmupRoute.checkpoints[7] = {}
routes.BreakingNewsWarmupRoute.checkpoints[7].position = vec.vector(-709.3057, 27.85398, 1156.329, 1)
routes.BreakingNewsWarmupRoute.checkpoints[7].heading = -2.920179
routes.BreakingNewsWarmupRoute.checkpoints[7].roadName = "dt_4l_south_03 AI Road 4"
routes.BreakingNewsWarmupRoute.checkpoints[8] = {}
routes.BreakingNewsWarmupRoute.checkpoints[8].position = vec.vector(-552.6284, 23.35346, 1083.248, 1)
routes.BreakingNewsWarmupRoute.checkpoints[8].heading = 1.684442
routes.BreakingNewsWarmupRoute.checkpoints[8].roadName = "dt_10l_south_01 AI Road 8"
routes.BreakingNewsWarmupRoute.checkpoints[9] = {}
routes.BreakingNewsWarmupRoute.checkpoints[9].position = vec.vector(-353.6448, 20.05494, 1059.731, 1)
routes.BreakingNewsWarmupRoute.checkpoints[9].heading = 1.695477
routes.BreakingNewsWarmupRoute.checkpoints[9].roadName = "dt_10l_south_01 AI Road 6"
routes.BreakingNewsWarmupRoute.arrows = {}
routes.BreakingNewsWarmupRoute.roads = {}
routes.BreakingNewsWarmupRoute.roads[1] = {}
routes.BreakingNewsWarmupRoute.roads[1].road = "dt_10l_south_01 AI Road 6"
routes.BreakingNewsWarmupRoute.roads[1].direction = "against"
routes.BreakingNewsWarmupRoute.roads[2] = {}
routes.BreakingNewsWarmupRoute.roads[2].road = "dt_10l_south_01 AI Road 5"
routes.BreakingNewsWarmupRoute.roads[2].direction = "against"
routes.BreakingNewsWarmupRoute.roads[3] = {}
routes.BreakingNewsWarmupRoute.roads[3].road = "dt_10l_centre_02 AI Road 0"
routes.BreakingNewsWarmupRoute.roads[3].direction = "with"
routes.BreakingNewsWarmupRoute.roads[4] = {}
routes.BreakingNewsWarmupRoute.roads[4].road = "dt_shortcut_03a AI Road 2"
routes.BreakingNewsWarmupRoute.roads[4].direction = "against"
routes.BreakingNewsWarmupRoute.roads[5] = {}
routes.BreakingNewsWarmupRoute.roads[5].road = "dt_shortcut_03a AI Road 1"
routes.BreakingNewsWarmupRoute.roads[5].direction = "against"
routes.BreakingNewsWarmupRoute.roads[6] = {}
routes.BreakingNewsWarmupRoute.roads[6].road = "dt_shortcut_03a AI Road 0"
routes.BreakingNewsWarmupRoute.roads[6].direction = "against"
routes.BreakingNewsWarmupRoute.roads[7] = {}
routes.BreakingNewsWarmupRoute.roads[7].road = "dt_4l_south_03 AI Road 4"
routes.BreakingNewsWarmupRoute.roads[7].direction = "with"
routes.BreakingNewsWarmupRoute.roads[8] = {}
routes.BreakingNewsWarmupRoute.roads[8].road = "dt_10l_south_01 AI Road 8"
routes.BreakingNewsWarmupRoute.roads[8].direction = "against"
routes.BreakingNewsWarmupRoute.roads[9] = {}
routes.BreakingNewsWarmupRoute.roads[9].road = "dt_10l_south_01 AI Road 7"
routes.BreakingNewsWarmupRoute.roads[9].direction = "against"
