routes = routes or {}
routes["Escape the law warmup"] = {}
routes["Escape the law warmup"].checkpoints = {}
routes["Escape the law warmup"].checkpoints[1] = {}
routes["Escape the law warmup"].checkpoints[1].position = vec.vector(-417.7364, 21.05256, 789.3914, 1)
routes["Escape the law warmup"].checkpoints[1].heading = 0.7967188
routes["Escape the law warmup"].checkpoints[1].roadName = "dt_10l_centre_01 AI Road 5"
routes["Escape the law warmup"].checkpoints[2] = {}
routes["Escape the law warmup"].checkpoints[2].position = vec.vector(-155.453, 33.54507, 862.8145, 1)
routes["Escape the law warmup"].checkpoints[2].heading = 1.749537
routes["Escape the law warmup"].checkpoints[2].roadName = "dt_6l_centre_03 AI Road 0"
routes["Escape the law warmup"].checkpoints[3] = {}
routes["Escape the law warmup"].checkpoints[3].position = vec.vector(-70.64106, 51.02299, 754.2299, 1)
routes["Escape the law warmup"].checkpoints[3].heading = -2.902584
routes["Escape the law warmup"].checkpoints[3].roadName = "dt_6l_centre_01 AI Road 2"
routes["Escape the law warmup"].checkpoints[4] = {}
routes["Escape the law warmup"].checkpoints[4].position = vec.vector(-180.416, 52.39889, 512.7545, 1)
routes["Escape the law warmup"].checkpoints[4].heading = -2.717569
routes["Escape the law warmup"].checkpoints[4].roadName = "dt_6l_centre_01 AI Road 1"
routes["Escape the law warmup"].checkpoints[5] = {}
routes["Escape the law warmup"].checkpoints[5].position = vec.vector(-368.9597, 50.95, 421.1413, 1)
routes["Escape the law warmup"].checkpoints[5].heading = -1.284848
routes["Escape the law warmup"].checkpoints[5].roadName = "dt_4l_centre_05 AI Road 2"
routes["Escape the law warmup"].checkpoints[6] = {}
routes["Escape the law warmup"].checkpoints[6].position = vec.vector(-457.9212, 35.10592, 578.4261, 1)
routes["Escape the law warmup"].checkpoints[6].heading = 0.1366772
routes["Escape the law warmup"].checkpoints[6].roadName = "dt_shortcut_06 AI Road 0"
routes["Escape the law warmup"].arrows = {}
routes["Escape the law warmup"].roads = {}
routes["Escape the law warmup"].roads[1] = {}
routes["Escape the law warmup"].roads[1].road = "dt_10l_centre_01 AI Road 5"
routes["Escape the law warmup"].roads[1].direction = "with"
routes["Escape the law warmup"].roads[2] = {}
routes["Escape the law warmup"].roads[2].road = "dt_6l_centre_03 AI Road 0"
routes["Escape the law warmup"].roads[2].direction = "with"
routes["Escape the law warmup"].roads[3] = {}
routes["Escape the law warmup"].roads[3].road = "dt_6l_centre_01 AI Road 2"
routes["Escape the law warmup"].roads[3].direction = "against"
routes["Escape the law warmup"].roads[4] = {}
routes["Escape the law warmup"].roads[4].road = "dt_6l_centre_01 AI Road 1"
routes["Escape the law warmup"].roads[4].direction = "against"
routes["Escape the law warmup"].roads[5] = {}
routes["Escape the law warmup"].roads[5].road = "dt_4l_centre_05 AI Road 2"
routes["Escape the law warmup"].roads[5].direction = "against"
routes["Escape the law warmup"].roads[6] = {}
routes["Escape the law warmup"].roads[6].road = "dt_shortcut_06 AI Road 0"
routes["Escape the law warmup"].roads[6].direction = "with"
routes["Meet the Heat evader loop"] = {}
routes["Meet the Heat evader loop"].checkpoints = {}
routes["Meet the Heat evader loop"].checkpoints[1] = {}
routes["Meet the Heat evader loop"].checkpoints[1].position = vec.vector(1105.311, 5.974995, 676.4214, 1)
routes["Meet the Heat evader loop"].checkpoints[1].heading = 2.247962
routes["Meet the Heat evader loop"].checkpoints[1].roadName = "dt_10l_east_01 AI Road 11"
routes["Meet the Heat evader loop"].checkpoints[2] = {}
routes["Meet the Heat evader loop"].checkpoints[2].position = vec.vector(1253.248, 5.974995, 851.4429, 1)
routes["Meet the Heat evader loop"].checkpoints[2].heading = 0.3970865
routes["Meet the Heat evader loop"].checkpoints[2].roadName = "dt_mt_join_01 AI Road 1"
routes["Meet the Heat evader loop"].checkpoints[3] = {}
routes["Meet the Heat evader loop"].checkpoints[3].position = vec.vector(967.6992, 5.974996, 1162.448, 1)
routes["Meet the Heat evader loop"].checkpoints[3].heading = -0.8596899
routes["Meet the Heat evader loop"].checkpoints[3].roadName = "mt_10l_south_02 AI Road 1"
routes["Meet the Heat evader loop"].checkpoints[4] = {}
routes["Meet the Heat evader loop"].checkpoints[4].position = vec.vector(735.8732, 5.974996, 1259.991, 1)
routes["Meet the Heat evader loop"].checkpoints[4].heading = -2.320168
routes["Meet the Heat evader loop"].checkpoints[4].roadName = "sanfran_shortcut_06 AI Road 1"
routes["Meet the Heat evader loop"].checkpoints[5] = {}
routes["Meet the Heat evader loop"].checkpoints[5].position = vec.vector(710.9565, 5.974996, 1012.565, 1)
routes["Meet the Heat evader loop"].checkpoints[5].heading = 2.286153
routes["Meet the Heat evader loop"].checkpoints[5].roadName = "dt_10l_south_03 AI Road 1"
routes["Meet the Heat evader loop"].checkpoints[6] = {}
routes["Meet the Heat evader loop"].checkpoints[6].position = vec.vector(998.7036, 5.974996, 763.4759, 1)
routes["Meet the Heat evader loop"].checkpoints[6].heading = 2.257863
routes["Meet the Heat evader loop"].checkpoints[6].roadName = "dt_10l_east_01 AI Road 12"
routes["Meet the Heat evader loop"].arrows = {}
routes["Meet the Heat evader loop"].roads = {}
routes["Meet the Heat evader loop"].roads[1] = {}
routes["Meet the Heat evader loop"].roads[1].road = "dt_10l_east_01 AI Road 11"
routes["Meet the Heat evader loop"].roads[1].direction = "against"
routes["Meet the Heat evader loop"].roads[2] = {}
routes["Meet the Heat evader loop"].roads[2].road = "dt_mt_join_01 AI Road 0"
routes["Meet the Heat evader loop"].roads[2].direction = "with"
routes["Meet the Heat evader loop"].roads[3] = {}
routes["Meet the Heat evader loop"].roads[3].road = "dt_mt_join_01 AI Road 1"
routes["Meet the Heat evader loop"].roads[3].direction = "with"
routes["Meet the Heat evader loop"].roads[4] = {}
routes["Meet the Heat evader loop"].roads[4].road = "mt_10l_south_02 AI Road 3"
routes["Meet the Heat evader loop"].roads[4].direction = "against"
routes["Meet the Heat evader loop"].roads[5] = {}
routes["Meet the Heat evader loop"].roads[5].road = "mt_10l_south_02 AI Road 2"
routes["Meet the Heat evader loop"].roads[5].direction = "against"
routes["Meet the Heat evader loop"].roads[6] = {}
routes["Meet the Heat evader loop"].roads[6].road = "mt_10l_south_02 AI Road 1"
routes["Meet the Heat evader loop"].roads[6].direction = "against"
routes["Meet the Heat evader loop"].roads[7] = {}
routes["Meet the Heat evader loop"].roads[7].road = "sanfran_shortcut_06 AI Road 1"
routes["Meet the Heat evader loop"].roads[7].direction = "against"
routes["Meet the Heat evader loop"].roads[8] = {}
routes["Meet the Heat evader loop"].roads[8].road = "sanfran_shortcut_06 AI Road 0"
routes["Meet the Heat evader loop"].roads[8].direction = "against"
routes["Meet the Heat evader loop"].roads[9] = {}
routes["Meet the Heat evader loop"].roads[9].road = "dt_10l_south_03 AI Road 1"
routes["Meet the Heat evader loop"].roads[9].direction = "against"
routes["Meet the Heat evader loop"].roads[10] = {}
routes["Meet the Heat evader loop"].roads[10].road = "dt_10l_south_03 AI Road 0"
routes["Meet the Heat evader loop"].roads[10].direction = "against"
routes["Meet the Heat evader loop"].roads[11] = {}
routes["Meet the Heat evader loop"].roads[11].road = "dt_10l_east_01 AI Road 14"
routes["Meet the Heat evader loop"].roads[11].direction = "against"
routes["Meet the Heat evader loop"].roads[12] = {}
routes["Meet the Heat evader loop"].roads[12].road = "dt_10l_east_01 AI Road 13"
routes["Meet the Heat evader loop"].roads[12].direction = "against"
routes["Meet the Heat evader loop"].roads[13] = {}
routes["Meet the Heat evader loop"].roads[13].road = "dt_10l_east_01 AI Road 12"
routes["Meet the Heat evader loop"].roads[13].direction = "against"
