routes = routes or {}
routes.ExpositionPostCrashJerichoChaseRoute = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[1] = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[1].position = vec.vector(-885.5446, 66.86259, 2108.061, 1)
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[1].heading = -2.66509
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[1].roadName = "dt_4l_west_06 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[2] = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[2].position = vec.vector(-948.6172, 66.74996, 1779.564, 1)
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[2].heading = -2.772929
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[2].roadName = "dt_4l_south_06 AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[3] = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[3].position = vec.vector(-1051.947, 53.75, 1498.521, 1)
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[3].heading = -2.906719
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[3].roadName = "dt_4l_south_02b AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[4] = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[4].position = vec.vector(-1144.426, 45.83047, 1065.971, 1)
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[4].heading = -2.984022
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[4].roadName = "dt_4l_west_08 AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[5] = {}
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[5].position = vec.vector(-1444.518, 41.90711, 1007.463, 1)
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[5].heading = -3.019542
routes.ExpositionPostCrashJerichoChaseRoute.checkpoints[5].roadName = "dt_alleyway_04 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.arrows = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[1] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[1].road = "dt_4l_west_06 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[1].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[2] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[2].road = "dt_4l_south_05bb AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[2].direction = "with"
routes.ExpositionPostCrashJerichoChaseRoute.roads[3] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[3].road = "dt_4l_south_06 AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.roads[3].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[4] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[4].road = "dt_4l_south_06 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[4].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[5] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[5].road = "dt_4l_south_02b AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.roads[5].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[6] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[6].road = "dt_4l_south_02b AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[6].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[7] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[7].road = "dt_shortcut_30 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[7].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[8] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[8].road = "dt_4l_west_08 AI Road 1"
routes.ExpositionPostCrashJerichoChaseRoute.roads[8].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[9] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[9].road = "chinatown_04 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[9].direction = "with"
routes.ExpositionPostCrashJerichoChaseRoute.roads[10] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[10].road = "r359_shortcut AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[10].direction = "against"
routes.ExpositionPostCrashJerichoChaseRoute.roads[11] = {}
routes.ExpositionPostCrashJerichoChaseRoute.roads[11].road = "dt_alleyway_04 AI Road 0"
routes.ExpositionPostCrashJerichoChaseRoute.roads[11].direction = "against"
routes.JerichoStart = {}
routes.JerichoStart.checkpoints = {}
routes.JerichoStart.checkpoints[1] = {}
routes.JerichoStart.checkpoints[1].position = vec.vector(-848.0193, 66.96736, 2180.755, 1)
routes.JerichoStart.checkpoints[1].heading = -2.665071
routes.JerichoStart.checkpoints[1].roadName = "dt_4l_west_06 AI Road 1"
routes.JerichoStart.arrows = {}
routes.JerichoStart.roads = {}
routes.JerichoStart.roads[1] = {}
routes.JerichoStart.roads[1].road = "mt_4l_west_01 AI Road 2"
routes.JerichoStart.roads[1].direction = "with"
routes.JerichoStart.roads[2] = {}
routes.JerichoStart.roads[2].road = "dt_4l_west_06 AI Road 1"
routes.JerichoStart.roads[2].direction = "against"
routes["Wake up cops"] = {}
routes["Wake up cops"].checkpoints = {}
routes["Wake up cops"].checkpoints[1] = {}
routes["Wake up cops"].checkpoints[1].position = vec.vector(-1502.62, 118.75, 2681.391, 1)
routes["Wake up cops"].checkpoints[1].heading = -0.4701556
routes["Wake up cops"].checkpoints[1].roadName = "sutro_4l_centre_02 AI Road 4"
routes["Wake up cops"].arrows = {}
routes["Wake up cops"].roads = {}
routes["Wake up cops"].roads[1] = {}
routes["Wake up cops"].roads[1].road = "mt_4l_west_01 AI Road 2"
routes["Wake up cops"].roads[1].direction = "with"
routes["Wake up cops"].roads[2] = {}
routes["Wake up cops"].roads[2].road = "mt_4l_west_01 AI Road 3"
routes["Wake up cops"].roads[2].direction = "with"
routes["Wake up cops"].roads[3] = {}
routes["Wake up cops"].roads[3].road = "mt_4l_west_01 AI Road 4"
routes["Wake up cops"].roads[3].direction = "with"
routes["Wake up cops"].roads[4] = {}
routes["Wake up cops"].roads[4].road = "sutro_mt_join_01 AI Road 0"
routes["Wake up cops"].roads[4].direction = "with"
routes["Wake up cops"].roads[5] = {}
routes["Wake up cops"].roads[5].road = "sutro_4l_centre_02 AI Road 4"
routes["Wake up cops"].roads[5].direction = "against"
routes["Wake up cop 3"] = {}
routes["Wake up cop 3"].checkpoints = {}
routes["Wake up cop 3"].checkpoints[1] = {}
routes["Wake up cop 3"].checkpoints[1].position = vec.vector(-1017.806, 53.75, 1600.944, 1)
routes["Wake up cop 3"].checkpoints[1].heading = -2.760687
routes["Wake up cop 3"].checkpoints[1].roadName = "dt_4l_south_06 AI Road 0"
routes["Wake up cop 3"].checkpoints[2] = {}
routes["Wake up cop 3"].checkpoints[2].position = vec.vector(-1912.148, 60.25, 1656.287, 1)
routes["Wake up cop 3"].checkpoints[2].heading = -1.463386
routes["Wake up cop 3"].checkpoints[2].roadName = "ggp_6l_east_02 AI Road 1"
routes["Wake up cop 3"].arrows = {}
routes["Wake up cop 3"].roads = {}
routes["Wake up cop 3"].roads[1] = {}
routes["Wake up cop 3"].roads[1].road = "dt_4l_south_05ba AI Road 1"
routes["Wake up cop 3"].roads[1].direction = "with"
routes["Wake up cop 3"].roads[2] = {}
routes["Wake up cop 3"].roads[2].road = "dt_4l_south_05bb AI Road 0"
routes["Wake up cop 3"].roads[2].direction = "with"
routes["Wake up cop 3"].roads[3] = {}
routes["Wake up cop 3"].roads[3].road = "dt_4l_south_06 AI Road 1"
routes["Wake up cop 3"].roads[3].direction = "against"
routes["Wake up cop 3"].roads[4] = {}
routes["Wake up cop 3"].roads[4].road = "dt_4l_south_06 AI Road 0"
routes["Wake up cop 3"].roads[4].direction = "against"
routes["Wake up cop 3"].roads[5] = {}
routes["Wake up cop 3"].roads[5].road = "mt_10l_north_01a AI Road 2"
routes["Wake up cop 3"].roads[5].direction = "against"
routes["Wake up cop 3"].roads[6] = {}
routes["Wake up cop 3"].roads[6].road = "mt_10l_north_01a AI Road 1"
routes["Wake up cop 3"].roads[6].direction = "against"
routes["Wake up cop 3"].roads[7] = {}
routes["Wake up cop 3"].roads[7].road = "mt_10l_north_01a AI Road 0"
routes["Wake up cop 3"].roads[7].direction = "against"
routes["Wake up cop 3"].roads[8] = {}
routes["Wake up cop 3"].roads[8].road = "ggp_6l_east_02 AI Road 2"
routes["Wake up cop 3"].roads[8].direction = "against"
routes["Wake up cop 3"].roads[9] = {}
routes["Wake up cop 3"].roads[9].road = "ggp_6l_east_02 AI Road 1"
routes["Wake up cop 3"].roads[9].direction = "against"
