routes = routes or {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1].position = vec.vector(1293.161, 8.249997, 2496.704, 1)
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1].heading = 2.264945
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1].roadName = "mt_10l_south_01 AI Road 0"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1].roadWidth = 44
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[1].distance = 44.96026
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2].position = vec.vector(1320.021, 9.230405, 2287.241, 1)
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2].heading = -2.408566
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2].roadName = "mt_10l_centre_03b AI Road 5"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2].roadWidth = 59
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[2].distance = 313.0417
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3].position = vec.vector(1232.287, 31.49115, 1799.615, 1)
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3].heading = 2.290118
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3].roadName = "highway01_16b AI Road 18"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3].roadWidth = 62
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.checkpoints[3].distance = 923.5126
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.arrows = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[1] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[1].road = "mt_10l_south_01 AI Road 0"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[1].direction = "with"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[2] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[2].road = "mt_10l_centre_03b AI Road 6"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[2].direction = "against"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[3] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[3].road = "mt_10l_centre_03b AI Road 5"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[3].direction = "against"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[4] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[4].road = "bb_sliproad_03 AI Road 0"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[4].direction = "with"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[5] = {}
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[5].road = "highway01_16b AI Road 18"
routes.Exposition_01_Forty_Adam_Thirty_Mission_Route.roads[5].direction = "with"
