routes = routes or {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1] = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].position = vec.vector(140.9019, 28.20673, 1845.243, 1)
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].heading = -1.013333
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].roadName = "mt_shortcut_02a AI Road 0"
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].roadWidth = 12
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].displayWidth = 4
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[1].distance = 186.4238
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2] = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].position = vec.vector(-115.8857, 31.45712, 2011.007, 1)
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].heading = -0.968646
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].roadName = "mt_shortcut_02a AI Road 0"
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].roadWidth = 12
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].displayWidth = 4
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.checkpoints[2].distance = 485.5557
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.arrows = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[1] = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[1].road = "mt_shortcut_02a AI Road 0"
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[1].direction = "against"
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[2] = {}
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[2].road = "mt_6l_w_02a AI Road 0"
routes.ExpositionPreCrashJerichoChaseTannerAlleywayRoute.roads[2].direction = "against"
