routes = routes or {}
routes.DowntownSprintRoute = {}
routes.DowntownSprintRoute.checkpoints = {}
routes.DowntownSprintRoute.checkpoints[1] = {}
routes.DowntownSprintRoute.checkpoints[1].position = vec.vector(542.925, 19.38967, 1964.743, 1)
routes.DowntownSprintRoute.checkpoints[1].heading = 2.265311
routes.DowntownSprintRoute.checkpoints[1].roadName = "mt_shortcut_13 AI Road 0"
routes.DowntownSprintRoute.checkpoints[2] = {}
routes.DowntownSprintRoute.checkpoints[2].position = vec.vector(705.9519, 14.81207, 1798.097, 1)
routes.DowntownSprintRoute.checkpoints[2].heading = -2.400871
routes.DowntownSprintRoute.checkpoints[2].roadName = "r305_shortcut_test_01 AI Road 0"
routes.DowntownSprintRoute.checkpoints[3] = {}
routes.DowntownSprintRoute.checkpoints[3].position = vec.vector(490.8867, 18.00697, 1866.403, 1)
routes.DowntownSprintRoute.checkpoints[3].heading = -0.964389
routes.DowntownSprintRoute.checkpoints[3].roadName = "mt_6l_centre_01 AI Road 6"
routes.DowntownSprintRoute.checkpoints[4] = {}
routes.DowntownSprintRoute.checkpoints[4].position = vec.vector(279.8651, 32.05, 2026.606, 1)
routes.DowntownSprintRoute.checkpoints[4].heading = 0.7103912
routes.DowntownSprintRoute.checkpoints[4].roadName = "mt_shortcut_04 AI Road 0"
routes.DowntownSprintRoute.checkpoints[5] = {}
routes.DowntownSprintRoute.checkpoints[5].position = vec.vector(406.67, 28, 2245.689, 1)
routes.DowntownSprintRoute.checkpoints[5].heading = -0.8393318
routes.DowntownSprintRoute.checkpoints[5].roadName = "mt_non-drivable AI Road 0"
routes.DowntownSprintRoute.checkpoints[6] = {}
routes.DowntownSprintRoute.checkpoints[6].position = vec.vector(266.9467, 34.25, 2403.331, 1)
routes.DowntownSprintRoute.checkpoints[6].heading = 0.6770949
routes.DowntownSprintRoute.checkpoints[6].roadName = "mt_10l_centre_02 AI Road 2"
routes.DowntownSprintRoute.checkpoints[7] = {}
routes.DowntownSprintRoute.checkpoints[7].position = vec.vector(-110.7328, 44, 2605.961, 1)
routes.DowntownSprintRoute.checkpoints[7].heading = -2.650353
routes.DowntownSprintRoute.checkpoints[7].roadName = "mt_shortcut_07 AI Road 0"
routes.DowntownSprintRoute.checkpoints[8] = {}
routes.DowntownSprintRoute.checkpoints[8].position = vec.vector(-128.7563, 43.77866, 2465.336, 1)
routes.DowntownSprintRoute.checkpoints[8].heading = 2.047874
routes.DowntownSprintRoute.checkpoints[8].roadName = "mt_shortcut_05 AI Road 0"
routes.DowntownSprintRoute.checkpoints[9] = {}
routes.DowntownSprintRoute.checkpoints[9].position = vec.vector(150.3861, 40.74999, 2259.422, 1)
routes.DowntownSprintRoute.checkpoints[9].heading = -2.464364
routes.DowntownSprintRoute.checkpoints[9].roadName = "mt_10l_centre_02 AI Road 0"
routes.DowntownSprintRoute.checkpoints[10] = {}
routes.DowntownSprintRoute.checkpoints[10].position = vec.vector(74.26661, 40.74999, 2103.627, 1)
routes.DowntownSprintRoute.checkpoints[10].heading = 2.087404
routes.DowntownSprintRoute.checkpoints[10].roadName = "mt_6l_centre_01 AI Road 5"
routes.DowntownSprintRoute.checkpoints[11] = {}
routes.DowntownSprintRoute.checkpoints[11].position = vec.vector(555.8216, 18.00904, 1856.938, 1)
routes.DowntownSprintRoute.checkpoints[11].heading = 0.7513105
routes.DowntownSprintRoute.checkpoints[11].roadName = "mt_6l_centre_04 AI Road 6"
routes.DowntownSprintRoute.checkpoints[12] = {}
routes.DowntownSprintRoute.checkpoints[12].position = vec.vector(666.642, 18.00904, 2022.42, 1)
routes.DowntownSprintRoute.checkpoints[12].heading = -0.8623692
routes.DowntownSprintRoute.checkpoints[12].roadName = "mt_non-drivable AI Road 1"
routes.DowntownSprintRoute.checkpoints[13] = {}
routes.DowntownSprintRoute.checkpoints[13].position = vec.vector(409.1411, 28.17452, 2183.141, 1)
routes.DowntownSprintRoute.checkpoints[13].heading = -2.451116
routes.DowntownSprintRoute.checkpoints[13].roadName = "mt_shortcut_04 AI Road 1"
routes.DowntownSprintRoute.checkpoints[14] = {}
routes.DowntownSprintRoute.checkpoints[14].position = vec.vector(505.4186, 22.43372, 1995.984, 1)
routes.DowntownSprintRoute.checkpoints[14].heading = 2.265312
routes.DowntownSprintRoute.checkpoints[14].roadName = "mt_shortcut_13 AI Road 0"
routes.DowntownSprintRoute.arrows = {}
routes.DowntownSprintRoute.arrows[1] = {}
routes.DowntownSprintRoute.arrows[1].position = vec.vector(725.6293, 12.5, 1815.879, 1)
routes.DowntownSprintRoute.arrows[1].heading = -2.382504
routes.DowntownSprintRoute.arrows[1].checkpointStart = 1
routes.DowntownSprintRoute.arrows[1].checkpointEnd = 2
routes.DowntownSprintRoute.arrows[1].modelId = 78
routes.DowntownSprintRoute.arrows[2] = {}
routes.DowntownSprintRoute.arrows[2].position = vec.vector(638.7031, 9, 1723.243, 1)
routes.DowntownSprintRoute.arrows[2].heading = -0.8508781
routes.DowntownSprintRoute.arrows[2].checkpointStart = 2
routes.DowntownSprintRoute.arrows[2].checkpointEnd = 3
routes.DowntownSprintRoute.arrows[2].modelId = 78
routes.DowntownSprintRoute.arrows[3] = {}
routes.DowntownSprintRoute.arrows[3].position = vec.vector(520.5256, 15.01, 1817.817, 1)
routes.DowntownSprintRoute.arrows[3].heading = -0.8379813
routes.DowntownSprintRoute.arrows[3].checkpointStart = 2
routes.DowntownSprintRoute.arrows[3].checkpointEnd = 3
routes.DowntownSprintRoute.arrows[3].modelId = 78
routes.DowntownSprintRoute.arrows[4] = {}
routes.DowntownSprintRoute.arrows[4].position = vec.vector(248.6422, 29.05, 2008.718, 1)
routes.DowntownSprintRoute.arrows[4].heading = 0.6991927
routes.DowntownSprintRoute.arrows[4].checkpointStart = 3
routes.DowntownSprintRoute.arrows[4].checkpointEnd = 4
routes.DowntownSprintRoute.arrows[4].modelId = 78
routes.DowntownSprintRoute.arrows[5] = {}
routes.DowntownSprintRoute.arrows[5].position = vec.vector(446.9134, 25, 2227.312, 1)
routes.DowntownSprintRoute.arrows[5].heading = -0.8459304
routes.DowntownSprintRoute.arrows[5].checkpointStart = 4
routes.DowntownSprintRoute.arrows[5].checkpointEnd = 5
routes.DowntownSprintRoute.arrows[5].modelId = 219
routes.DowntownSprintRoute.arrows[6] = {}
routes.DowntownSprintRoute.arrows[6].position = vec.vector(234.5402, 31.25, 2391.775, 1)
routes.DowntownSprintRoute.arrows[6].heading = 0.6928796
routes.DowntownSprintRoute.arrows[6].checkpointStart = 5
routes.DowntownSprintRoute.arrows[6].checkpointEnd = 6
routes.DowntownSprintRoute.arrows[6].modelId = 78
routes.DowntownSprintRoute.arrows[7] = {}
routes.DowntownSprintRoute.arrows[7].position = vec.vector(321.6785, 31.25, 2483.618, 1)
routes.DowntownSprintRoute.arrows[7].heading = -0.8960555
routes.DowntownSprintRoute.arrows[7].checkpointStart = 6
routes.DowntownSprintRoute.arrows[7].checkpointEnd = 7
routes.DowntownSprintRoute.arrows[7].modelId = 219
routes.DowntownSprintRoute.arrows[8] = {}
routes.DowntownSprintRoute.arrows[8].position = vec.vector(-107.16, 41, 2648.289, 1)
routes.DowntownSprintRoute.arrows[8].heading = -2.743965
routes.DowntownSprintRoute.arrows[8].checkpointStart = 6
routes.DowntownSprintRoute.arrows[8].checkpointEnd = 7
routes.DowntownSprintRoute.arrows[8].modelId = 78
routes.DowntownSprintRoute.arrows[9] = {}
routes.DowntownSprintRoute.arrows[9].position = vec.vector(-174.2383, 40, 2483.291, 1)
routes.DowntownSprintRoute.arrows[9].heading = 2.048627
routes.DowntownSprintRoute.arrows[9].checkpointStart = 7
routes.DowntownSprintRoute.arrows[9].checkpointEnd = 8
routes.DowntownSprintRoute.arrows[9].modelId = 78
routes.DowntownSprintRoute.arrows[10] = {}
routes.DowntownSprintRoute.arrows[10].position = vec.vector(184.5354, 37.75, 2269.982, 1)
routes.DowntownSprintRoute.arrows[10].heading = -2.454775
routes.DowntownSprintRoute.arrows[10].checkpointStart = 8
routes.DowntownSprintRoute.arrows[10].checkpointEnd = 9
routes.DowntownSprintRoute.arrows[10].modelId = 219
routes.DowntownSprintRoute.arrows[11] = {}
routes.DowntownSprintRoute.arrows[11].position = vec.vector(31.3946, 37.75, 2107.582, 1)
routes.DowntownSprintRoute.arrows[11].heading = 2.108081
routes.DowntownSprintRoute.arrows[11].checkpointStart = 9
routes.DowntownSprintRoute.arrows[11].checkpointEnd = 10
routes.DowntownSprintRoute.arrows[11].modelId = 219
routes.DowntownSprintRoute.arrows[12] = {}
routes.DowntownSprintRoute.arrows[12].position = vec.vector(548.2225, 14.5, 1822.902, 1)
routes.DowntownSprintRoute.arrows[12].heading = 0.7657928
routes.DowntownSprintRoute.arrows[12].checkpointStart = 10
routes.DowntownSprintRoute.arrows[12].checkpointEnd = 11
routes.DowntownSprintRoute.arrows[12].modelId = 219
routes.DowntownSprintRoute.arrows[13] = {}
routes.DowntownSprintRoute.arrows[13].position = vec.vector(703.0203, 15, 2015.02, 1)
routes.DowntownSprintRoute.arrows[13].heading = -0.8721364
routes.DowntownSprintRoute.arrows[13].checkpointStart = 11
routes.DowntownSprintRoute.arrows[13].checkpointEnd = 12
routes.DowntownSprintRoute.arrows[13].modelId = 219
routes.DowntownSprintRoute.arrows[14] = {}
routes.DowntownSprintRoute.arrows[14].position = vec.vector(428.1732, 25, 2225.844, 1)
routes.DowntownSprintRoute.arrows[14].heading = -2.456975
routes.DowntownSprintRoute.arrows[14].checkpointStart = 12
routes.DowntownSprintRoute.arrows[14].checkpointEnd = 13
routes.DowntownSprintRoute.arrows[14].modelId = 78
routes.DowntownSprintRoute.arrows[15] = {}
routes.DowntownSprintRoute.arrows[15].position = vec.vector(348.8856, 26.78, 2111.178, 1)
routes.DowntownSprintRoute.arrows[15].heading = 2.245537
routes.DowntownSprintRoute.arrows[15].checkpointStart = 13
routes.DowntownSprintRoute.arrows[15].checkpointEnd = 14
routes.DowntownSprintRoute.arrows[15].modelId = 78
routes.DowntownSprintRoute.arrows[16] = {}
routes.DowntownSprintRoute.arrows[16].position = vec.vector(622.9553, 15, 1925.2, 1)
routes.DowntownSprintRoute.arrows[16].heading = 2.284887
routes.DowntownSprintRoute.arrows[16].checkpointStart = 1
routes.DowntownSprintRoute.arrows[16].checkpointEnd = 2
routes.DowntownSprintRoute.arrows[16].modelId = 78
routes.DowntownSprintRoute.arrows[17] = {}
routes.DowntownSprintRoute.arrows[17].position = vec.vector(601.2017, 15, 1904.04, 1)
routes.DowntownSprintRoute.arrows[17].heading = 2.226492
routes.DowntownSprintRoute.arrows[17].checkpointStart = 1
routes.DowntownSprintRoute.arrows[17].checkpointEnd = 2
routes.DowntownSprintRoute.arrows[17].modelId = 78
routes.DowntownSprintRoute.arrows[18] = {}
routes.DowntownSprintRoute.arrows[18].position = vec.vector(548.4153, 15.01, 1852.657, 1)
routes.DowntownSprintRoute.arrows[18].heading = -0.9272955
routes.DowntownSprintRoute.arrows[18].checkpointStart = 2
routes.DowntownSprintRoute.arrows[18].checkpointEnd = 3
routes.DowntownSprintRoute.arrows[18].modelId = 78
routes.DowntownSprintRoute.roads = {}
routes.DowntownSprintRoute.roads[1] = {}
routes.DowntownSprintRoute.roads[1].road = "mt_shortcut_13 AI Road 0"
routes.DowntownSprintRoute.roads[1].direction = "with"
routes.DowntownSprintRoute.roads[2] = {}
routes.DowntownSprintRoute.roads[2].road = "r305_shortcut_test_02 AI Road 0"
routes.DowntownSprintRoute.roads[2].direction = "with"
routes.DowntownSprintRoute.roads[3] = {}
routes.DowntownSprintRoute.roads[3].road = "r305_shortcut_test_01 AI Road 0"
routes.DowntownSprintRoute.roads[3].direction = "against"
routes.DowntownSprintRoute.roads[4] = {}
routes.DowntownSprintRoute.roads[4].road = "mt_6l_centre_01 AI Road 7"
routes.DowntownSprintRoute.roads[4].direction = "against"
routes.DowntownSprintRoute.roads[5] = {}
routes.DowntownSprintRoute.roads[5].road = "mt_6l_centre_01 AI Road 6"
routes.DowntownSprintRoute.roads[5].direction = "against"
routes.DowntownSprintRoute.roads[6] = {}
routes.DowntownSprintRoute.roads[6].road = "mt_shortcut_04 AI Road 0"
routes.DowntownSprintRoute.roads[6].direction = "with"
routes.DowntownSprintRoute.roads[7] = {}
routes.DowntownSprintRoute.roads[7].road = "mt_shortcut_04 AI Road 1"
routes.DowntownSprintRoute.roads[7].direction = "with"
routes.DowntownSprintRoute.roads[8] = {}
routes.DowntownSprintRoute.roads[8].road = "mt_non-drivable AI Road 0"
routes.DowntownSprintRoute.roads[8].direction = "against"
routes.DowntownSprintRoute.roads[9] = {}
routes.DowntownSprintRoute.roads[9].road = "mt_10l_centre_02 AI Road 2"
routes.DowntownSprintRoute.roads[9].direction = "with"
routes.DowntownSprintRoute.roads[10] = {}
routes.DowntownSprintRoute.roads[10].road = "mt_10l_centre_02 AI Road 3"
routes.DowntownSprintRoute.roads[10].direction = "with"
routes.DowntownSprintRoute.roads[11] = {}
routes.DowntownSprintRoute.roads[11].road = "sutro_6l_east_08 AI Road 2"
routes.DowntownSprintRoute.roads[11].direction = "against"
routes.DowntownSprintRoute.roads[12] = {}
routes.DowntownSprintRoute.roads[12].road = "sutro_6l_east_08 AI Road 1"
routes.DowntownSprintRoute.roads[12].direction = "against"
routes.DowntownSprintRoute.roads[13] = {}
routes.DowntownSprintRoute.roads[13].road = "sutro_6l_east_08 AI Road 0"
routes.DowntownSprintRoute.roads[13].direction = "against"
routes.DowntownSprintRoute.roads[14] = {}
routes.DowntownSprintRoute.roads[14].road = "mt_shortcut_07 AI Road 0"
routes.DowntownSprintRoute.roads[14].direction = "against"
routes.DowntownSprintRoute.roads[15] = {}
routes.DowntownSprintRoute.roads[15].road = "mt_shortcut_05 AI Road 0"
routes.DowntownSprintRoute.roads[15].direction = "with"
routes.DowntownSprintRoute.roads[16] = {}
routes.DowntownSprintRoute.roads[16].road = "mt_10l_centre_02 AI Road 0"
routes.DowntownSprintRoute.roads[16].direction = "against"
routes.DowntownSprintRoute.roads[17] = {}
routes.DowntownSprintRoute.roads[17].road = "mt_6l_centre_01 AI Road 5"
routes.DowntownSprintRoute.roads[17].direction = "with"
routes.DowntownSprintRoute.roads[18] = {}
routes.DowntownSprintRoute.roads[18].road = "mt_6l_centre_01 AI Road 6"
routes.DowntownSprintRoute.roads[18].direction = "with"
routes.DowntownSprintRoute.roads[19] = {}
routes.DowntownSprintRoute.roads[19].road = "mt_6l_centre_04 AI Road 6"
routes.DowntownSprintRoute.roads[19].direction = "with"
routes.DowntownSprintRoute.roads[20] = {}
routes.DowntownSprintRoute.roads[20].road = "mt_6l_centre_04 AI Road 7"
routes.DowntownSprintRoute.roads[20].direction = "with"
routes.DowntownSprintRoute.roads[21] = {}
routes.DowntownSprintRoute.roads[21].road = "mt_non-drivable AI Road 1"
routes.DowntownSprintRoute.roads[21].direction = "against"
routes.DowntownSprintRoute.roads[22] = {}
routes.DowntownSprintRoute.roads[22].road = "mt_shortcut_04 AI Road 1"
routes.DowntownSprintRoute.roads[22].direction = "against"
