routes = routes or {}
routes.HardcoreChallengeRoute = {}
routes.HardcoreChallengeRoute.checkpoints = {}
routes.HardcoreChallengeRoute.checkpoints[1] = {}
routes.HardcoreChallengeRoute.checkpoints[1].position = vec.vector(-2968.596, 56.54364, -1374.176, 1)
routes.HardcoreChallengeRoute.checkpoints[1].heading = 2.962494
routes.HardcoreChallengeRoute.checkpoints[1].roadName = "highway01_15 AI Road 11"
routes.HardcoreChallengeRoute.checkpoints[2] = {}
routes.HardcoreChallengeRoute.checkpoints[2].position = vec.vector(-2818.766, 41.49238, -2207.242, 1)
routes.HardcoreChallengeRoute.checkpoints[2].heading = 2.959729
routes.HardcoreChallengeRoute.checkpoints[2].roadName = "highway01_15 AI Road 16"
routes.HardcoreChallengeRoute.checkpoints[3] = {}
routes.HardcoreChallengeRoute.checkpoints[3].position = vec.vector(-2929.886, 80.1811, -2786.373, 1)
routes.HardcoreChallengeRoute.checkpoints[3].heading = -2.282748
routes.HardcoreChallengeRoute.checkpoints[3].roadName = "highway01_15 AI Road 20"
routes.HardcoreChallengeRoute.checkpoints[4] = {}
routes.HardcoreChallengeRoute.checkpoints[4].position = vec.vector(-2776.928, 110.0448, -3103.845, 1)
routes.HardcoreChallengeRoute.checkpoints[4].heading = 2.459386
routes.HardcoreChallengeRoute.checkpoints[4].roadName = "highway01_15 AI Road 26"
routes.HardcoreChallengeRoute.checkpoints[5] = {}
routes.HardcoreChallengeRoute.checkpoints[5].position = vec.vector(-2692.865, 126.3812, -3318.712, 1)
routes.HardcoreChallengeRoute.checkpoints[5].heading = 3.124421
routes.HardcoreChallengeRoute.checkpoints[5].roadName = "highway01_15 AI Road 26"
routes.HardcoreChallengeRoute.checkpoints[6] = {}
routes.HardcoreChallengeRoute.checkpoints[6].position = vec.vector(-2545.342, 147.9173, -3514.001, 1)
routes.HardcoreChallengeRoute.checkpoints[6].heading = 1.90408
routes.HardcoreChallengeRoute.checkpoints[6].roadName = "highway01_15 AI Road 28"
routes.HardcoreChallengeRoute.checkpoints[7] = {}
routes.HardcoreChallengeRoute.checkpoints[7].position = vec.vector(-2283.411, 150.7114, -3694.432, 1)
routes.HardcoreChallengeRoute.checkpoints[7].heading = 2.412222
routes.HardcoreChallengeRoute.checkpoints[7].roadName = "highway01_15 AI Road 30"
routes.HardcoreChallengeRoute.checkpoints[8] = {}
routes.HardcoreChallengeRoute.checkpoints[8].position = vec.vector(-1522.861, 130.0191, -3755.371, 1)
routes.HardcoreChallengeRoute.checkpoints[8].heading = 1.415049
routes.HardcoreChallengeRoute.checkpoints[8].roadName = "highway01_15 AI Road 37"
routes.HardcoreChallengeRoute.checkpoints[9] = {}
routes.HardcoreChallengeRoute.checkpoints[9].position = vec.vector(-978.1089, 66.85559, -3615.871, 1)
routes.HardcoreChallengeRoute.checkpoints[9].heading = 1.221518
routes.HardcoreChallengeRoute.checkpoints[9].roadName = "highway01_15 AI Road 40"
routes.HardcoreChallengeRoute.checkpoints[10] = {}
routes.HardcoreChallengeRoute.checkpoints[10].position = vec.vector(-106.2401, 42.19492, -2929.766, 1)
routes.HardcoreChallengeRoute.checkpoints[10].heading = 0.9466807
routes.HardcoreChallengeRoute.checkpoints[10].roadName = "highway01_15 AI Road 45"
routes.HardcoreChallengeRoute.checkpoints[11] = {}
routes.HardcoreChallengeRoute.checkpoints[11].position = vec.vector(257.927, 26.4333, -2674.205, 1)
routes.HardcoreChallengeRoute.checkpoints[11].heading = 1.024753
routes.HardcoreChallengeRoute.checkpoints[11].roadName = "highway01_15 AI Road 47"
routes.HardcoreChallengeRoute.checkpoints[12] = {}
routes.HardcoreChallengeRoute.checkpoints[12].position = vec.vector(724.1257, 24.5, -2570.172, 1)
routes.HardcoreChallengeRoute.checkpoints[12].heading = 1.410509
routes.HardcoreChallengeRoute.checkpoints[12].roadName = "highway01_15 AI Road 49"
routes.HardcoreChallengeRoute.checkpoints[13] = {}
routes.HardcoreChallengeRoute.checkpoints[13].position = vec.vector(1277.133, 29.42124, -2482.114, 1)
routes.HardcoreChallengeRoute.checkpoints[13].heading = 1.423603
routes.HardcoreChallengeRoute.checkpoints[13].roadName = "highway01_15 AI Road 51"
routes.HardcoreChallengeRoute.checkpoints[14] = {}
routes.HardcoreChallengeRoute.checkpoints[14].position = vec.vector(1785.121, 31.95943, -2481.562, 1)
routes.HardcoreChallengeRoute.checkpoints[14].heading = 2.108694
routes.HardcoreChallengeRoute.checkpoints[14].roadName = "highway01_15 AI Road 54"
routes.HardcoreChallengeRoute.checkpoints[15] = {}
routes.HardcoreChallengeRoute.checkpoints[15].position = vec.vector(2352.353, 35.29008, -2464.456, 1)
routes.HardcoreChallengeRoute.checkpoints[15].heading = 1.48548
routes.HardcoreChallengeRoute.checkpoints[15].roadName = "highway01_15 AI Road 57"
routes.HardcoreChallengeRoute.checkpoints[16] = {}
routes.HardcoreChallengeRoute.checkpoints[16].position = vec.vector(2807.659, 6.009089, -1988.936, 1)
routes.HardcoreChallengeRoute.checkpoints[16].heading = 0.4301116
routes.HardcoreChallengeRoute.checkpoints[16].roadName = "highway01_15 AI Road 61"
routes.HardcoreChallengeRoute.checkpoints[17] = {}
routes.HardcoreChallengeRoute.checkpoints[17].position = vec.vector(3195.751, 6, -1372.759, 1)
routes.HardcoreChallengeRoute.checkpoints[17].heading = 0.1076716
routes.HardcoreChallengeRoute.checkpoints[17].roadName = "superhighway_split_03 AI Road 3"
routes.HardcoreChallengeRoute.checkpoints[18] = {}
routes.HardcoreChallengeRoute.checkpoints[18].position = vec.vector(2828.073, 20, -816.0886, 1)
routes.HardcoreChallengeRoute.checkpoints[18].heading = -1.121395
routes.HardcoreChallengeRoute.checkpoints[18].roadName = "superhighway_road_01 AI Road 1"
routes.HardcoreChallengeRoute.checkpoints[19] = {}
routes.HardcoreChallengeRoute.checkpoints[19].position = vec.vector(2706.441, 32.30267, -392.3344, 1)
routes.HardcoreChallengeRoute.checkpoints[19].heading = 0.4266042
routes.HardcoreChallengeRoute.checkpoints[19].roadName = "superhighway_road_01 AI Road 3"
routes.HardcoreChallengeRoute.checkpoints[20] = {}
routes.HardcoreChallengeRoute.checkpoints[20].position = vec.vector(2982.386, 23.69736, 949.8026, 1)
routes.HardcoreChallengeRoute.checkpoints[20].heading = -1.137222
routes.HardcoreChallengeRoute.checkpoints[20].roadName = "highway01_16b AI Road 28"
routes.HardcoreChallengeRoute.checkpoints[21] = {}
routes.HardcoreChallengeRoute.checkpoints[21].position = vec.vector(2359.258, 47.94397, 1233.455, 1)
routes.HardcoreChallengeRoute.checkpoints[21].heading = -1.141751
routes.HardcoreChallengeRoute.checkpoints[21].roadName = "highway01_16b AI Road 25"
routes.HardcoreChallengeRoute.checkpoints[22] = {}
routes.HardcoreChallengeRoute.checkpoints[22].position = vec.vector(1588.325, 43.45198, 1586.107, 1)
routes.HardcoreChallengeRoute.checkpoints[22].heading = -1.141738
routes.HardcoreChallengeRoute.checkpoints[22].roadName = "highway01_16b AI Road 21"
routes.HardcoreChallengeRoute.checkpoints[23] = {}
routes.HardcoreChallengeRoute.checkpoints[23].position = vec.vector(1155.155, 27.88529, 1869.198, 1)
routes.HardcoreChallengeRoute.checkpoints[23].heading = -0.8306569
routes.HardcoreChallengeRoute.checkpoints[23].roadName = "highway01_16b AI Road 19"
routes.HardcoreChallengeRoute.checkpoints[24] = {}
routes.HardcoreChallengeRoute.checkpoints[24].position = vec.vector(219.7949, 52.01903, 2634.526, 1)
routes.HardcoreChallengeRoute.checkpoints[24].heading = -1.071788
routes.HardcoreChallengeRoute.checkpoints[24].roadName = "highway01_16b AI Road 16"
routes.HardcoreChallengeRoute.checkpoints[25] = {}
routes.HardcoreChallengeRoute.checkpoints[25].position = vec.vector(-405.6883, 76.34312, 2684.636, 1)
routes.HardcoreChallengeRoute.checkpoints[25].heading = -2.288996
routes.HardcoreChallengeRoute.checkpoints[25].roadName = "highway01_16b AI Road 10"
routes.HardcoreChallengeRoute.checkpoints[26] = {}
routes.HardcoreChallengeRoute.checkpoints[26].position = vec.vector(-770.8736, 76.90778, 1950.755, 1)
routes.HardcoreChallengeRoute.checkpoints[26].heading = -2.760474
routes.HardcoreChallengeRoute.checkpoints[26].roadName = "highway01_16b AI Road 3"
routes.HardcoreChallengeRoute.checkpoints[27] = {}
routes.HardcoreChallengeRoute.checkpoints[27].position = vec.vector(-1042, 57, 1091.538, 1)
routes.HardcoreChallengeRoute.checkpoints[27].heading = -2.775086
routes.HardcoreChallengeRoute.checkpoints[27].roadName = "highway01_16b AI Road 1"
routes.HardcoreChallengeRoute.checkpoints[28] = {}
routes.HardcoreChallengeRoute.checkpoints[28].position = vec.vector(-2324.471, 47.25, 352.498, 1)
routes.HardcoreChallengeRoute.checkpoints[28].heading = -1.808878
routes.HardcoreChallengeRoute.checkpoints[28].roadName = "highway01_15 AI Road 0"
routes.HardcoreChallengeRoute.checkpoints[29] = {}
routes.HardcoreChallengeRoute.checkpoints[29].position = vec.vector(-2961.265, 43.60848, 197.0041, 1)
routes.HardcoreChallengeRoute.checkpoints[29].heading = -1.800538
routes.HardcoreChallengeRoute.checkpoints[29].roadName = "highway01_15 AI Road 4"
routes.HardcoreChallengeRoute.checkpoints[30] = {}
routes.HardcoreChallengeRoute.checkpoints[30].position = vec.vector(-3130.947, 65.06305, -461.184, 1)
routes.HardcoreChallengeRoute.checkpoints[30].heading = 2.966186
routes.HardcoreChallengeRoute.checkpoints[30].roadName = "highway01_15 AI Road 7"
routes.HardcoreChallengeRoute.checkpoints[31] = {}
routes.HardcoreChallengeRoute.checkpoints[31].position = vec.vector(-3009.077, 65.63822, -1144.688, 1)
routes.HardcoreChallengeRoute.checkpoints[31].heading = 2.968916
routes.HardcoreChallengeRoute.checkpoints[31].roadName = "highway01_15 AI Road 10"
routes.HardcoreChallengeRoute.arrows = {}
routes.HardcoreChallengeRoute.arrows[1] = {}
routes.HardcoreChallengeRoute.arrows[1].position = vec.vector(-2741.706, 72, -2605.856, 1)
routes.HardcoreChallengeRoute.arrows[1].heading = -2.637966
routes.HardcoreChallengeRoute.arrows[1].modelId = 78
routes.HardcoreChallengeRoute.arrows[2] = {}
routes.HardcoreChallengeRoute.arrows[2].position = vec.vector(-3032.593, 89, -2942.838, 1)
routes.HardcoreChallengeRoute.arrows[2].heading = 2.670133
routes.HardcoreChallengeRoute.arrows[2].modelId = 78
routes.HardcoreChallengeRoute.arrows[3] = {}
routes.HardcoreChallengeRoute.arrows[3].position = vec.vector(-2690.597, 135, -3475.942, 1)
routes.HardcoreChallengeRoute.arrows[3].heading = 1.999061
routes.HardcoreChallengeRoute.arrows[3].modelId = 78
routes.HardcoreChallengeRoute.arrows[4] = {}
routes.HardcoreChallengeRoute.arrows[4].position = vec.vector(-2388.676, 150, -3549.863, 1)
routes.HardcoreChallengeRoute.arrows[4].heading = 2.456975
routes.HardcoreChallengeRoute.arrows[4].modelId = 78
routes.HardcoreChallengeRoute.arrows[5] = {}
routes.HardcoreChallengeRoute.arrows[5].position = vec.vector(-1538.229, 52.5, 769.6895, 1)
routes.HardcoreChallengeRoute.arrows[5].heading = -1.352127
routes.HardcoreChallengeRoute.arrows[5].modelId = 78
routes.HardcoreChallengeRoute.arrows[6] = {}
routes.HardcoreChallengeRoute.arrows[6].position = vec.vector(-2790.523, 102.92, -3043.968, 1)
routes.HardcoreChallengeRoute.arrows[6].heading = 2.774419
routes.HardcoreChallengeRoute.arrows[6].modelId = 78
routes.HardcoreChallengeRoute.arrows[7] = {}
routes.HardcoreChallengeRoute.arrows[7].position = vec.vector(-2213.828, 147, -3756.356, 1)
routes.HardcoreChallengeRoute.arrows[7].heading = 1.772114
routes.HardcoreChallengeRoute.arrows[7].modelId = 78
routes.HardcoreChallengeRoute.arrows[8] = {}
routes.HardcoreChallengeRoute.arrows[8].position = vec.vector(2633.094, 20.5, -632.3068, 1)
routes.HardcoreChallengeRoute.arrows[8].heading = 0.1555947
routes.HardcoreChallengeRoute.arrows[8].modelId = 78
routes.HardcoreChallengeRoute.arrows[9] = {}
routes.HardcoreChallengeRoute.arrows[9].position = vec.vector(-1636.662, 55.25, 809.3439, 1)
routes.HardcoreChallengeRoute.arrows[9].heading = -2.308611
routes.HardcoreChallengeRoute.arrows[9].horizontalArrow = true
routes.HardcoreChallengeRoute.arrows[9].modelId = 78
routes.HardcoreChallengeRoute.arrows[10] = {}
routes.HardcoreChallengeRoute.arrows[10].position = vec.vector(-1849.68, 57.43, 608.7859, 1)
routes.HardcoreChallengeRoute.arrows[10].heading = -2.14011
routes.HardcoreChallengeRoute.arrows[10].modelId = 78
routes.HardcoreChallengeRoute.arrows[11] = {}
routes.HardcoreChallengeRoute.arrows[11].position = vec.vector(-3189.411, 39.5, 97.15331, 1)
routes.HardcoreChallengeRoute.arrows[11].heading = -2.819842
routes.HardcoreChallengeRoute.arrows[11].modelId = 78
routes.HardcoreChallengeRoute.arrows[12] = {}
routes.HardcoreChallengeRoute.arrows[12].position = vec.vector(2732.44, 12.3, -2348.377, 1)
routes.HardcoreChallengeRoute.arrows[12].heading = 0.3487708
routes.HardcoreChallengeRoute.arrows[12].modelId = 78
routes.HardcoreChallengeRoute.arrows[13] = {}
routes.HardcoreChallengeRoute.arrows[13].position = vec.vector(-252.4353, 69.5, 2754.284, 1)
routes.HardcoreChallengeRoute.arrows[13].heading = -1.916352
routes.HardcoreChallengeRoute.arrows[13].modelId = 78
routes.HardcoreChallengeRoute.roads = {}
routes.HardcoreChallengeRoute.roads[1] = {}
routes.HardcoreChallengeRoute.roads[1].road = "highway01_15 AI Road 11"
routes.HardcoreChallengeRoute.roads[1].direction = "with"
routes.HardcoreChallengeRoute.roads[2] = {}
routes.HardcoreChallengeRoute.roads[2].road = "highway01_15 AI Road 12"
routes.HardcoreChallengeRoute.roads[2].direction = "with"
routes.HardcoreChallengeRoute.roads[3] = {}
routes.HardcoreChallengeRoute.roads[3].road = "highway01_15 AI Road 13"
routes.HardcoreChallengeRoute.roads[3].direction = "with"
routes.HardcoreChallengeRoute.roads[4] = {}
routes.HardcoreChallengeRoute.roads[4].road = "highway01_15 AI Road 14"
routes.HardcoreChallengeRoute.roads[4].direction = "with"
routes.HardcoreChallengeRoute.roads[5] = {}
routes.HardcoreChallengeRoute.roads[5].road = "highway01_15 AI Road 15"
routes.HardcoreChallengeRoute.roads[5].direction = "with"
routes.HardcoreChallengeRoute.roads[6] = {}
routes.HardcoreChallengeRoute.roads[6].road = "highway01_15 AI Road 16"
routes.HardcoreChallengeRoute.roads[6].direction = "with"
routes.HardcoreChallengeRoute.roads[7] = {}
routes.HardcoreChallengeRoute.roads[7].road = "highway01_15 AI Road 17"
routes.HardcoreChallengeRoute.roads[7].direction = "with"
routes.HardcoreChallengeRoute.roads[8] = {}
routes.HardcoreChallengeRoute.roads[8].road = "highway01_15 AI Road 18"
routes.HardcoreChallengeRoute.roads[8].direction = "with"
routes.HardcoreChallengeRoute.roads[9] = {}
routes.HardcoreChallengeRoute.roads[9].road = "highway01_15 AI Road 19"
routes.HardcoreChallengeRoute.roads[9].direction = "with"
routes.HardcoreChallengeRoute.roads[10] = {}
routes.HardcoreChallengeRoute.roads[10].road = "highway01_15 AI Road 20"
routes.HardcoreChallengeRoute.roads[10].direction = "with"
routes.HardcoreChallengeRoute.roads[11] = {}
routes.HardcoreChallengeRoute.roads[11].road = "highway01_15 AI Road 21"
routes.HardcoreChallengeRoute.roads[11].direction = "with"
routes.HardcoreChallengeRoute.roads[12] = {}
routes.HardcoreChallengeRoute.roads[12].road = "highway01_15 AI Road 22"
routes.HardcoreChallengeRoute.roads[12].direction = "with"
routes.HardcoreChallengeRoute.roads[13] = {}
routes.HardcoreChallengeRoute.roads[13].road = "highway01_15 AI Road 23"
routes.HardcoreChallengeRoute.roads[13].direction = "with"
routes.HardcoreChallengeRoute.roads[14] = {}
routes.HardcoreChallengeRoute.roads[14].road = "highway01_15 AI Road 24"
routes.HardcoreChallengeRoute.roads[14].direction = "with"
routes.HardcoreChallengeRoute.roads[15] = {}
routes.HardcoreChallengeRoute.roads[15].road = "highway01_15 AI Road 25"
routes.HardcoreChallengeRoute.roads[15].direction = "with"
routes.HardcoreChallengeRoute.roads[16] = {}
routes.HardcoreChallengeRoute.roads[16].road = "highway01_15 AI Road 26"
routes.HardcoreChallengeRoute.roads[16].direction = "with"
routes.HardcoreChallengeRoute.roads[17] = {}
routes.HardcoreChallengeRoute.roads[17].road = "highway01_15 AI Road 27"
routes.HardcoreChallengeRoute.roads[17].direction = "with"
routes.HardcoreChallengeRoute.roads[18] = {}
routes.HardcoreChallengeRoute.roads[18].road = "highway01_15 AI Road 28"
routes.HardcoreChallengeRoute.roads[18].direction = "with"
routes.HardcoreChallengeRoute.roads[19] = {}
routes.HardcoreChallengeRoute.roads[19].road = "highway01_15 AI Road 29"
routes.HardcoreChallengeRoute.roads[19].direction = "with"
routes.HardcoreChallengeRoute.roads[20] = {}
routes.HardcoreChallengeRoute.roads[20].road = "highway01_15 AI Road 30"
routes.HardcoreChallengeRoute.roads[20].direction = "with"
routes.HardcoreChallengeRoute.roads[21] = {}
routes.HardcoreChallengeRoute.roads[21].road = "highway01_15 AI Road 31"
routes.HardcoreChallengeRoute.roads[21].direction = "with"
routes.HardcoreChallengeRoute.roads[22] = {}
routes.HardcoreChallengeRoute.roads[22].road = "highway01_15 AI Road 32"
routes.HardcoreChallengeRoute.roads[22].direction = "with"
routes.HardcoreChallengeRoute.roads[23] = {}
routes.HardcoreChallengeRoute.roads[23].road = "highway01_15 AI Road 33"
routes.HardcoreChallengeRoute.roads[23].direction = "with"
routes.HardcoreChallengeRoute.roads[24] = {}
routes.HardcoreChallengeRoute.roads[24].road = "highway01_15 AI Road 34"
routes.HardcoreChallengeRoute.roads[24].direction = "with"
routes.HardcoreChallengeRoute.roads[25] = {}
routes.HardcoreChallengeRoute.roads[25].road = "highway01_15 AI Road 35"
routes.HardcoreChallengeRoute.roads[25].direction = "with"
routes.HardcoreChallengeRoute.roads[26] = {}
routes.HardcoreChallengeRoute.roads[26].road = "highway01_15 AI Road 36"
routes.HardcoreChallengeRoute.roads[26].direction = "with"
routes.HardcoreChallengeRoute.roads[27] = {}
routes.HardcoreChallengeRoute.roads[27].road = "highway01_15 AI Road 37"
routes.HardcoreChallengeRoute.roads[27].direction = "with"
routes.HardcoreChallengeRoute.roads[28] = {}
routes.HardcoreChallengeRoute.roads[28].road = "highway01_15 AI Road 38"
routes.HardcoreChallengeRoute.roads[28].direction = "with"
routes.HardcoreChallengeRoute.roads[29] = {}
routes.HardcoreChallengeRoute.roads[29].road = "highway01_15 AI Road 39"
routes.HardcoreChallengeRoute.roads[29].direction = "with"
routes.HardcoreChallengeRoute.roads[30] = {}
routes.HardcoreChallengeRoute.roads[30].road = "highway01_15 AI Road 40"
routes.HardcoreChallengeRoute.roads[30].direction = "with"
routes.HardcoreChallengeRoute.roads[31] = {}
routes.HardcoreChallengeRoute.roads[31].road = "highway01_15 AI Road 41"
routes.HardcoreChallengeRoute.roads[31].direction = "with"
routes.HardcoreChallengeRoute.roads[32] = {}
routes.HardcoreChallengeRoute.roads[32].road = "highway01_15 AI Road 42"
routes.HardcoreChallengeRoute.roads[32].direction = "with"
routes.HardcoreChallengeRoute.roads[33] = {}
routes.HardcoreChallengeRoute.roads[33].road = "highway01_15 AI Road 43"
routes.HardcoreChallengeRoute.roads[33].direction = "with"
routes.HardcoreChallengeRoute.roads[34] = {}
routes.HardcoreChallengeRoute.roads[34].road = "highway01_15 AI Road 44"
routes.HardcoreChallengeRoute.roads[34].direction = "with"
routes.HardcoreChallengeRoute.roads[35] = {}
routes.HardcoreChallengeRoute.roads[35].road = "highway01_15 AI Road 45"
routes.HardcoreChallengeRoute.roads[35].direction = "with"
routes.HardcoreChallengeRoute.roads[36] = {}
routes.HardcoreChallengeRoute.roads[36].road = "highway01_15 AI Road 46"
routes.HardcoreChallengeRoute.roads[36].direction = "with"
routes.HardcoreChallengeRoute.roads[37] = {}
routes.HardcoreChallengeRoute.roads[37].road = "highway01_15 AI Road 47"
routes.HardcoreChallengeRoute.roads[37].direction = "with"
routes.HardcoreChallengeRoute.roads[38] = {}
routes.HardcoreChallengeRoute.roads[38].road = "highway01_15 AI Road 48"
routes.HardcoreChallengeRoute.roads[38].direction = "with"
routes.HardcoreChallengeRoute.roads[39] = {}
routes.HardcoreChallengeRoute.roads[39].road = "highway01_15 AI Road 49"
routes.HardcoreChallengeRoute.roads[39].direction = "with"
routes.HardcoreChallengeRoute.roads[40] = {}
routes.HardcoreChallengeRoute.roads[40].road = "highway01_15 AI Road 50"
routes.HardcoreChallengeRoute.roads[40].direction = "with"
routes.HardcoreChallengeRoute.roads[41] = {}
routes.HardcoreChallengeRoute.roads[41].road = "highway01_15 AI Road 51"
routes.HardcoreChallengeRoute.roads[41].direction = "with"
routes.HardcoreChallengeRoute.roads[42] = {}
routes.HardcoreChallengeRoute.roads[42].road = "highway01_15 AI Road 52"
routes.HardcoreChallengeRoute.roads[42].direction = "with"
routes.HardcoreChallengeRoute.roads[43] = {}
routes.HardcoreChallengeRoute.roads[43].road = "highway01_15 AI Road 53"
routes.HardcoreChallengeRoute.roads[43].direction = "with"
routes.HardcoreChallengeRoute.roads[44] = {}
routes.HardcoreChallengeRoute.roads[44].road = "highway01_15 AI Road 54"
routes.HardcoreChallengeRoute.roads[44].direction = "with"
routes.HardcoreChallengeRoute.roads[45] = {}
routes.HardcoreChallengeRoute.roads[45].road = "highway01_15 AI Road 55"
routes.HardcoreChallengeRoute.roads[45].direction = "with"
routes.HardcoreChallengeRoute.roads[46] = {}
routes.HardcoreChallengeRoute.roads[46].road = "highway01_15 AI Road 56"
routes.HardcoreChallengeRoute.roads[46].direction = "with"
routes.HardcoreChallengeRoute.roads[47] = {}
routes.HardcoreChallengeRoute.roads[47].road = "highway01_15 AI Road 57"
routes.HardcoreChallengeRoute.roads[47].direction = "with"
routes.HardcoreChallengeRoute.roads[48] = {}
routes.HardcoreChallengeRoute.roads[48].road = "highway01_15 AI Road 58"
routes.HardcoreChallengeRoute.roads[48].direction = "with"
routes.HardcoreChallengeRoute.roads[49] = {}
routes.HardcoreChallengeRoute.roads[49].road = "highway01_15 AI Road 59"
routes.HardcoreChallengeRoute.roads[49].direction = "with"
routes.HardcoreChallengeRoute.roads[50] = {}
routes.HardcoreChallengeRoute.roads[50].road = "highway01_15 AI Road 60"
routes.HardcoreChallengeRoute.roads[50].direction = "with"
routes.HardcoreChallengeRoute.roads[51] = {}
routes.HardcoreChallengeRoute.roads[51].road = "highway01_15 AI Road 61"
routes.HardcoreChallengeRoute.roads[51].direction = "with"
routes.HardcoreChallengeRoute.roads[52] = {}
routes.HardcoreChallengeRoute.roads[52].road = "highway01_15 AI Road 62"
routes.HardcoreChallengeRoute.roads[52].direction = "with"
routes.HardcoreChallengeRoute.roads[53] = {}
routes.HardcoreChallengeRoute.roads[53].road = "superhighway_split_03 AI Road 6"
routes.HardcoreChallengeRoute.roads[53].direction = "against"
routes.HardcoreChallengeRoute.roads[54] = {}
routes.HardcoreChallengeRoute.roads[54].road = "superhighway_split_03 AI Road 5"
routes.HardcoreChallengeRoute.roads[54].direction = "against"
routes.HardcoreChallengeRoute.roads[55] = {}
routes.HardcoreChallengeRoute.roads[55].road = "superhighway_split_03 AI Road 4"
routes.HardcoreChallengeRoute.roads[55].direction = "against"
routes.HardcoreChallengeRoute.roads[56] = {}
routes.HardcoreChallengeRoute.roads[56].road = "superhighway_split_03 AI Road 3"
routes.HardcoreChallengeRoute.roads[56].direction = "against"
routes.HardcoreChallengeRoute.roads[57] = {}
routes.HardcoreChallengeRoute.roads[57].road = "superhighway_split_03 AI Road 2"
routes.HardcoreChallengeRoute.roads[57].direction = "against"
routes.HardcoreChallengeRoute.roads[58] = {}
routes.HardcoreChallengeRoute.roads[58].road = "superhighway_split_03 AI Road 1"
routes.HardcoreChallengeRoute.roads[58].direction = "against"
routes.HardcoreChallengeRoute.roads[59] = {}
routes.HardcoreChallengeRoute.roads[59].road = "superhighway_split_03 AI Road 0"
routes.HardcoreChallengeRoute.roads[59].direction = "against"
routes.HardcoreChallengeRoute.roads[60] = {}
routes.HardcoreChallengeRoute.roads[60].road = "superhighway_road_01 AI Road 0"
routes.HardcoreChallengeRoute.roads[60].direction = "with"
routes.HardcoreChallengeRoute.roads[61] = {}
routes.HardcoreChallengeRoute.roads[61].road = "superhighway_road_01 AI Road 1"
routes.HardcoreChallengeRoute.roads[61].direction = "with"
routes.HardcoreChallengeRoute.roads[62] = {}
routes.HardcoreChallengeRoute.roads[62].road = "superhighway_road_01 AI Road 2"
routes.HardcoreChallengeRoute.roads[62].direction = "with"
routes.HardcoreChallengeRoute.roads[63] = {}
routes.HardcoreChallengeRoute.roads[63].road = "superhighway_road_01 AI Road 3"
routes.HardcoreChallengeRoute.roads[63].direction = "with"
routes.HardcoreChallengeRoute.roads[64] = {}
routes.HardcoreChallengeRoute.roads[64].road = "superhighway_road_01 AI Road 4"
routes.HardcoreChallengeRoute.roads[64].direction = "with"
routes.HardcoreChallengeRoute.roads[65] = {}
routes.HardcoreChallengeRoute.roads[65].road = "superhighway_road_01 AI Road 5"
routes.HardcoreChallengeRoute.roads[65].direction = "with"
routes.HardcoreChallengeRoute.roads[66] = {}
routes.HardcoreChallengeRoute.roads[66].road = "superhighway_road_01 AI Road 6"
routes.HardcoreChallengeRoute.roads[66].direction = "with"
routes.HardcoreChallengeRoute.roads[67] = {}
routes.HardcoreChallengeRoute.roads[67].road = "superhighway_split_01 AI Road 3"
routes.HardcoreChallengeRoute.roads[67].direction = "against"
routes.HardcoreChallengeRoute.roads[68] = {}
routes.HardcoreChallengeRoute.roads[68].road = "superhighway_split_01 AI Road 2"
routes.HardcoreChallengeRoute.roads[68].direction = "against"
routes.HardcoreChallengeRoute.roads[69] = {}
routes.HardcoreChallengeRoute.roads[69].road = "superhighway_split_01 AI Road 1"
routes.HardcoreChallengeRoute.roads[69].direction = "against"
routes.HardcoreChallengeRoute.roads[70] = {}
routes.HardcoreChallengeRoute.roads[70].road = "superhighway_split_01 AI Road 0"
routes.HardcoreChallengeRoute.roads[70].direction = "against"
routes.HardcoreChallengeRoute.roads[71] = {}
routes.HardcoreChallengeRoute.roads[71].road = "highway01_16b AI Road 29"
routes.HardcoreChallengeRoute.roads[71].direction = "against"
routes.HardcoreChallengeRoute.roads[72] = {}
routes.HardcoreChallengeRoute.roads[72].road = "highway01_16b AI Road 28"
routes.HardcoreChallengeRoute.roads[72].direction = "against"
routes.HardcoreChallengeRoute.roads[73] = {}
routes.HardcoreChallengeRoute.roads[73].road = "highway01_16b AI Road 27"
routes.HardcoreChallengeRoute.roads[73].direction = "against"
routes.HardcoreChallengeRoute.roads[74] = {}
routes.HardcoreChallengeRoute.roads[74].road = "highway01_16b AI Road 26"
routes.HardcoreChallengeRoute.roads[74].direction = "against"
routes.HardcoreChallengeRoute.roads[75] = {}
routes.HardcoreChallengeRoute.roads[75].road = "highway01_16b AI Road 25"
routes.HardcoreChallengeRoute.roads[75].direction = "against"
routes.HardcoreChallengeRoute.roads[76] = {}
routes.HardcoreChallengeRoute.roads[76].road = "highway01_16b AI Road 24"
routes.HardcoreChallengeRoute.roads[76].direction = "against"
routes.HardcoreChallengeRoute.roads[77] = {}
routes.HardcoreChallengeRoute.roads[77].road = "highway01_16b AI Road 23"
routes.HardcoreChallengeRoute.roads[77].direction = "against"
routes.HardcoreChallengeRoute.roads[78] = {}
routes.HardcoreChallengeRoute.roads[78].road = "highway01_16b AI Road 22"
routes.HardcoreChallengeRoute.roads[78].direction = "against"
routes.HardcoreChallengeRoute.roads[79] = {}
routes.HardcoreChallengeRoute.roads[79].road = "highway01_16b AI Road 21"
routes.HardcoreChallengeRoute.roads[79].direction = "against"
routes.HardcoreChallengeRoute.roads[80] = {}
routes.HardcoreChallengeRoute.roads[80].road = "highway01_16b AI Road 20"
routes.HardcoreChallengeRoute.roads[80].direction = "against"
routes.HardcoreChallengeRoute.roads[81] = {}
routes.HardcoreChallengeRoute.roads[81].road = "highway01_16b AI Road 19"
routes.HardcoreChallengeRoute.roads[81].direction = "against"
routes.HardcoreChallengeRoute.roads[82] = {}
routes.HardcoreChallengeRoute.roads[82].road = "highway01_16b AI Road 18"
routes.HardcoreChallengeRoute.roads[82].direction = "against"
routes.HardcoreChallengeRoute.roads[83] = {}
routes.HardcoreChallengeRoute.roads[83].road = "highway01_16b AI Road 17"
routes.HardcoreChallengeRoute.roads[83].direction = "against"
routes.HardcoreChallengeRoute.roads[84] = {}
routes.HardcoreChallengeRoute.roads[84].road = "highway01_16b AI Road 16"
routes.HardcoreChallengeRoute.roads[84].direction = "against"
routes.HardcoreChallengeRoute.roads[85] = {}
routes.HardcoreChallengeRoute.roads[85].road = "highway01_16b AI Road 15"
routes.HardcoreChallengeRoute.roads[85].direction = "against"
routes.HardcoreChallengeRoute.roads[86] = {}
routes.HardcoreChallengeRoute.roads[86].road = "highway01_16b AI Road 14"
routes.HardcoreChallengeRoute.roads[86].direction = "against"
routes.HardcoreChallengeRoute.roads[87] = {}
routes.HardcoreChallengeRoute.roads[87].road = "highway01_16b AI Road 13"
routes.HardcoreChallengeRoute.roads[87].direction = "against"
routes.HardcoreChallengeRoute.roads[88] = {}
routes.HardcoreChallengeRoute.roads[88].road = "highway01_16b AI Road 12"
routes.HardcoreChallengeRoute.roads[88].direction = "against"
routes.HardcoreChallengeRoute.roads[89] = {}
routes.HardcoreChallengeRoute.roads[89].road = "highway01_16b AI Road 11"
routes.HardcoreChallengeRoute.roads[89].direction = "against"
routes.HardcoreChallengeRoute.roads[90] = {}
routes.HardcoreChallengeRoute.roads[90].road = "highway01_16b AI Road 10"
routes.HardcoreChallengeRoute.roads[90].direction = "against"
routes.HardcoreChallengeRoute.roads[91] = {}
routes.HardcoreChallengeRoute.roads[91].road = "highway01_16b AI Road 9"
routes.HardcoreChallengeRoute.roads[91].direction = "against"
routes.HardcoreChallengeRoute.roads[92] = {}
routes.HardcoreChallengeRoute.roads[92].road = "highway01_16b AI Road 8"
routes.HardcoreChallengeRoute.roads[92].direction = "against"
routes.HardcoreChallengeRoute.roads[93] = {}
routes.HardcoreChallengeRoute.roads[93].road = "highway01_16b AI Road 7"
routes.HardcoreChallengeRoute.roads[93].direction = "against"
routes.HardcoreChallengeRoute.roads[94] = {}
routes.HardcoreChallengeRoute.roads[94].road = "highway01_16b AI Road 6"
routes.HardcoreChallengeRoute.roads[94].direction = "against"
routes.HardcoreChallengeRoute.roads[95] = {}
routes.HardcoreChallengeRoute.roads[95].road = "highway01_16b AI Road 5"
routes.HardcoreChallengeRoute.roads[95].direction = "against"
routes.HardcoreChallengeRoute.roads[96] = {}
routes.HardcoreChallengeRoute.roads[96].road = "highway01_16b AI Road 4"
routes.HardcoreChallengeRoute.roads[96].direction = "against"
routes.HardcoreChallengeRoute.roads[97] = {}
routes.HardcoreChallengeRoute.roads[97].road = "highway01_16b AI Road 3"
routes.HardcoreChallengeRoute.roads[97].direction = "against"
routes.HardcoreChallengeRoute.roads[98] = {}
routes.HardcoreChallengeRoute.roads[98].road = "highway01_16b AI Road 2"
routes.HardcoreChallengeRoute.roads[98].direction = "against"
routes.HardcoreChallengeRoute.roads[99] = {}
routes.HardcoreChallengeRoute.roads[99].road = "highway01_16b AI Road 1"
routes.HardcoreChallengeRoute.roads[99].direction = "against"
routes.HardcoreChallengeRoute.roads[100] = {}
routes.HardcoreChallengeRoute.roads[100].road = "highway01_16b AI Road 0"
routes.HardcoreChallengeRoute.roads[100].direction = "against"
routes.HardcoreChallengeRoute.roads[101] = {}
routes.HardcoreChallengeRoute.roads[101].road = "highway_split_sanfran_01 AI Road 0"
routes.HardcoreChallengeRoute.roads[101].direction = "with"
routes.HardcoreChallengeRoute.roads[102] = {}
routes.HardcoreChallengeRoute.roads[102].road = "highway_split_sanfran_01 AI Road 1"
routes.HardcoreChallengeRoute.roads[102].direction = "with"
routes.HardcoreChallengeRoute.roads[103] = {}
routes.HardcoreChallengeRoute.roads[103].road = "highway_split_sanfran_01 AI Road 2"
routes.HardcoreChallengeRoute.roads[103].direction = "with"
routes.HardcoreChallengeRoute.roads[104] = {}
routes.HardcoreChallengeRoute.roads[104].road = "highway_split_sanfran_01 AI Road 3"
routes.HardcoreChallengeRoute.roads[104].direction = "with"
routes.HardcoreChallengeRoute.roads[105] = {}
routes.HardcoreChallengeRoute.roads[105].road = "highway_split_sanfran_01 AI Road 4"
routes.HardcoreChallengeRoute.roads[105].direction = "with"
routes.HardcoreChallengeRoute.roads[106] = {}
routes.HardcoreChallengeRoute.roads[106].road = "highway_split_sanfran_01 AI Road 5"
routes.HardcoreChallengeRoute.roads[106].direction = "with"
routes.HardcoreChallengeRoute.roads[107] = {}
routes.HardcoreChallengeRoute.roads[107].road = "highway01_15 AI Road 0"
routes.HardcoreChallengeRoute.roads[107].direction = "with"
routes.HardcoreChallengeRoute.roads[108] = {}
routes.HardcoreChallengeRoute.roads[108].road = "highway01_15 AI Road 1"
routes.HardcoreChallengeRoute.roads[108].direction = "with"
routes.HardcoreChallengeRoute.roads[109] = {}
routes.HardcoreChallengeRoute.roads[109].road = "highway01_15 AI Road 2"
routes.HardcoreChallengeRoute.roads[109].direction = "with"
routes.HardcoreChallengeRoute.roads[110] = {}
routes.HardcoreChallengeRoute.roads[110].road = "highway01_15 AI Road 3"
routes.HardcoreChallengeRoute.roads[110].direction = "with"
routes.HardcoreChallengeRoute.roads[111] = {}
routes.HardcoreChallengeRoute.roads[111].road = "highway01_15 AI Road 4"
routes.HardcoreChallengeRoute.roads[111].direction = "with"
routes.HardcoreChallengeRoute.roads[112] = {}
routes.HardcoreChallengeRoute.roads[112].road = "highway01_15 AI Road 5"
routes.HardcoreChallengeRoute.roads[112].direction = "with"
routes.HardcoreChallengeRoute.roads[113] = {}
routes.HardcoreChallengeRoute.roads[113].road = "highway01_15 AI Road 6"
routes.HardcoreChallengeRoute.roads[113].direction = "with"
routes.HardcoreChallengeRoute.roads[114] = {}
routes.HardcoreChallengeRoute.roads[114].road = "highway01_15 AI Road 7"
routes.HardcoreChallengeRoute.roads[114].direction = "with"
routes.HardcoreChallengeRoute.roads[115] = {}
routes.HardcoreChallengeRoute.roads[115].road = "highway01_15 AI Road 8"
routes.HardcoreChallengeRoute.roads[115].direction = "with"
routes.HardcoreChallengeRoute.roads[116] = {}
routes.HardcoreChallengeRoute.roads[116].road = "highway01_15 AI Road 9"
routes.HardcoreChallengeRoute.roads[116].direction = "with"
routes.HardcoreChallengeRoute.roads[117] = {}
routes.HardcoreChallengeRoute.roads[117].road = "highway01_15 AI Road 10"
routes.HardcoreChallengeRoute.roads[117].direction = "with"
