routes = routes or {}
routes.RussianHillTakedownRoute = {}
routes.RussianHillTakedownRoute.checkpoints = {}
routes.RussianHillTakedownRoute.checkpoints[1] = {}
routes.RussianHillTakedownRoute.checkpoints[1].position = vec.vector(-1062.206, 14.75532, 151.012, 1)
routes.RussianHillTakedownRoute.checkpoints[1].heading = 0.7898943
routes.RussianHillTakedownRoute.checkpoints[1].roadName = "dt_10l_centre_01 AI Road 1"
routes.RussianHillTakedownRoute.checkpoints[2] = {}
routes.RussianHillTakedownRoute.checkpoints[2].position = vec.vector(-887.5056, 16.99999, 270.7642, 1)
routes.RussianHillTakedownRoute.checkpoints[2].heading = 1.721199
routes.RussianHillTakedownRoute.checkpoints[2].roadName = "dt_4l_centre_12 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[3] = {}
routes.RussianHillTakedownRoute.checkpoints[3].position = vec.vector(-526.0752, 70.00032, 233.6162, 1)
routes.RussianHillTakedownRoute.checkpoints[3].heading = 0.219726
routes.RussianHillTakedownRoute.checkpoints[3].roadName = "dt_4l_centre_09 AI Road 2"
routes.RussianHillTakedownRoute.checkpoints[4] = {}
routes.RussianHillTakedownRoute.checkpoints[4].position = vec.vector(-451.5652, 50.94997, 445.0056, 1)
routes.RussianHillTakedownRoute.checkpoints[4].heading = 1.847624
routes.RussianHillTakedownRoute.checkpoints[4].roadName = "dt_4l_centre_05 AI Road 2"
routes.RussianHillTakedownRoute.checkpoints[5] = {}
routes.RussianHillTakedownRoute.checkpoints[5].position = vec.vector(-249.6798, 60.00013, 327.8581, 1)
routes.RussianHillTakedownRoute.checkpoints[5].heading = -2.866082
routes.RussianHillTakedownRoute.checkpoints[5].roadName = "dt_6l_centre_01 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[6] = {}
routes.RussianHillTakedownRoute.checkpoints[6].position = vec.vector(-249.3466, 70.00054, 163.1483, 1)
routes.RussianHillTakedownRoute.checkpoints[6].heading = 1.751755
routes.RussianHillTakedownRoute.checkpoints[6].roadName = "dt_4l_east_04 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[7] = {}
routes.RussianHillTakedownRoute.checkpoints[7].position = vec.vector(194.9136, 51.18758, 85.78074, 1)
routes.RussianHillTakedownRoute.checkpoints[7].heading = 1.587283
routes.RussianHillTakedownRoute.checkpoints[7].roadName = "dt_4l_east_04 AI Road 2"
routes.RussianHillTakedownRoute.checkpoints[8] = {}
routes.RussianHillTakedownRoute.checkpoints[8].position = vec.vector(217.2643, 68.582, 265.2455, 1)
routes.RussianHillTakedownRoute.checkpoints[8].heading = -1.315415
routes.RussianHillTakedownRoute.checkpoints[8].roadName = "dt_shortcut_coit_01 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[9] = {}
routes.RussianHillTakedownRoute.checkpoints[9].position = vec.vector(-32.74283, 36.52529, 328.1246, 1)
routes.RussianHillTakedownRoute.checkpoints[9].heading = -1.299949
routes.RussianHillTakedownRoute.checkpoints[9].roadName = "dt_4l_centre_13 AI Road 1"
routes.RussianHillTakedownRoute.checkpoints[10] = {}
routes.RussianHillTakedownRoute.checkpoints[10].position = vec.vector(-214.9913, 60.00009, 433.5895, 1)
routes.RussianHillTakedownRoute.checkpoints[10].heading = 0.3515064
routes.RussianHillTakedownRoute.checkpoints[10].roadName = "dt_6l_centre_01 AI Road 1"
routes.RussianHillTakedownRoute.checkpoints[11] = {}
routes.RussianHillTakedownRoute.checkpoints[11].position = vec.vector(-73.90842, 43.05933, 848.9958, 1)
routes.RussianHillTakedownRoute.checkpoints[11].heading = -1.417078
routes.RussianHillTakedownRoute.checkpoints[11].roadName = "dt_6l_centre_03 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[12] = {}
routes.RussianHillTakedownRoute.checkpoints[12].position = vec.vector(-351.0655, 18.01337, 853.9568, 1)
routes.RussianHillTakedownRoute.checkpoints[12].heading = -2.337185
routes.RussianHillTakedownRoute.checkpoints[12].roadName = "dt_10l_centre_01 AI Road 5"
routes.RussianHillTakedownRoute.checkpoints[13] = {}
routes.RussianHillTakedownRoute.checkpoints[13].position = vec.vector(-587.7313, 25.04591, 621.074, 1)
routes.RussianHillTakedownRoute.checkpoints[13].heading = -2.351516
routes.RussianHillTakedownRoute.checkpoints[13].roadName = "dt_10l_centre_01 AI Road 4"
routes.RussianHillTakedownRoute.checkpoints[14] = {}
routes.RussianHillTakedownRoute.checkpoints[14].position = vec.vector(-856.9946, 19.73624, 404.1027, 1)
routes.RussianHillTakedownRoute.checkpoints[14].heading = -1.322569
routes.RussianHillTakedownRoute.checkpoints[14].roadName = "dt_shortcut_05 AI Road 0"
routes.RussianHillTakedownRoute.checkpoints[15] = {}
routes.RussianHillTakedownRoute.checkpoints[15].position = vec.vector(-1384.319, 37.5, 496.1681, 1)
routes.RussianHillTakedownRoute.checkpoints[15].heading = -2.935621
routes.RussianHillTakedownRoute.checkpoints[15].roadName = "dt_8l_centre_01ab AI Road 2"
routes.RussianHillTakedownRoute.checkpoints[16] = {}
routes.RussianHillTakedownRoute.checkpoints[16].position = vec.vector(-1411.249, 31.2457, 271.4011, 1)
routes.RussianHillTakedownRoute.checkpoints[16].heading = 2.637689
routes.RussianHillTakedownRoute.checkpoints[16].roadName = "dt_8l_centre_01ab AI Road 1"
routes.RussianHillTakedownRoute.checkpoints[17] = {}
routes.RussianHillTakedownRoute.checkpoints[17].position = vec.vector(-1176.399, 15.60845, 149.4073, 1)
routes.RussianHillTakedownRoute.checkpoints[17].heading = 1.732833
routes.RussianHillTakedownRoute.checkpoints[17].roadName = "dt_8l_centre_01ab AI Road 0"
routes.RussianHillTakedownRoute.arrows = {}
routes.RussianHillTakedownRoute.roads = {}
routes.RussianHillTakedownRoute.roads[1] = {}
routes.RussianHillTakedownRoute.roads[1].road = "dt_10l_centre_01 AI Road 1"
routes.RussianHillTakedownRoute.roads[1].direction = "with"
routes.RussianHillTakedownRoute.roads[2] = {}
routes.RussianHillTakedownRoute.roads[2].road = "dt_4l_centre_12 AI Road 0"
routes.RussianHillTakedownRoute.roads[2].direction = "with"
routes.RussianHillTakedownRoute.roads[3] = {}
routes.RussianHillTakedownRoute.roads[3].road = "dt_4l_centre_12 AI Road 1"
routes.RussianHillTakedownRoute.roads[3].direction = "with"
routes.RussianHillTakedownRoute.roads[4] = {}
routes.RussianHillTakedownRoute.roads[4].road = "dt_4l_centre_09 AI Road 2"
routes.RussianHillTakedownRoute.roads[4].direction = "with"
routes.RussianHillTakedownRoute.roads[5] = {}
routes.RussianHillTakedownRoute.roads[5].road = "dt_4l_centre_05 AI Road 2"
routes.RussianHillTakedownRoute.roads[5].direction = "with"
routes.RussianHillTakedownRoute.roads[6] = {}
routes.RussianHillTakedownRoute.roads[6].road = "dt_6l_centre_01 AI Road 0"
routes.RussianHillTakedownRoute.roads[6].direction = "against"
routes.RussianHillTakedownRoute.roads[7] = {}
routes.RussianHillTakedownRoute.roads[7].road = "dt_4l_east_04 AI Road 0"
routes.RussianHillTakedownRoute.roads[7].direction = "with"
routes.RussianHillTakedownRoute.roads[8] = {}
routes.RussianHillTakedownRoute.roads[8].road = "dt_4l_east_04 AI Road 1"
routes.RussianHillTakedownRoute.roads[8].direction = "with"
routes.RussianHillTakedownRoute.roads[9] = {}
routes.RussianHillTakedownRoute.roads[9].road = "dt_4l_east_04 AI Road 2"
routes.RussianHillTakedownRoute.roads[9].direction = "with"
routes.RussianHillTakedownRoute.roads[10] = {}
routes.RussianHillTakedownRoute.roads[10].road = "dt_shortcut_coit_01 AI Road 0"
routes.RussianHillTakedownRoute.roads[10].direction = "against"
routes.RussianHillTakedownRoute.roads[11] = {}
routes.RussianHillTakedownRoute.roads[11].road = "dt_4l_centre_13 AI Road 1"
routes.RussianHillTakedownRoute.roads[11].direction = "against"
routes.RussianHillTakedownRoute.roads[12] = {}
routes.RussianHillTakedownRoute.roads[12].road = "dt_4l_centre_13 AI Road 0"
routes.RussianHillTakedownRoute.roads[12].direction = "against"
routes.RussianHillTakedownRoute.roads[13] = {}
routes.RussianHillTakedownRoute.roads[13].road = "dt_6l_centre_01 AI Road 1"
routes.RussianHillTakedownRoute.roads[13].direction = "with"
routes.RussianHillTakedownRoute.roads[14] = {}
routes.RussianHillTakedownRoute.roads[14].road = "dt_6l_centre_01 AI Road 2"
routes.RussianHillTakedownRoute.roads[14].direction = "with"
routes.RussianHillTakedownRoute.roads[15] = {}
routes.RussianHillTakedownRoute.roads[15].road = "dt_6l_centre_03 AI Road 0"
routes.RussianHillTakedownRoute.roads[15].direction = "against"
routes.RussianHillTakedownRoute.roads[16] = {}
routes.RussianHillTakedownRoute.roads[16].road = "dt_10l_centre_01 AI Road 5"
routes.RussianHillTakedownRoute.roads[16].direction = "against"
routes.RussianHillTakedownRoute.roads[17] = {}
routes.RussianHillTakedownRoute.roads[17].road = "dt_10l_centre_01 AI Road 4"
routes.RussianHillTakedownRoute.roads[17].direction = "against"
routes.RussianHillTakedownRoute.roads[18] = {}
routes.RussianHillTakedownRoute.roads[18].road = "dt_10l_centre_01 AI Road 3"
routes.RussianHillTakedownRoute.roads[18].direction = "against"
routes.RussianHillTakedownRoute.roads[19] = {}
routes.RussianHillTakedownRoute.roads[19].road = "dt_shortcut_05 AI Road 0"
routes.RussianHillTakedownRoute.roads[19].direction = "with"
routes.RussianHillTakedownRoute.roads[20] = {}
routes.RussianHillTakedownRoute.roads[20].road = "dt_shortcut_05 AI Road 1"
routes.RussianHillTakedownRoute.roads[20].direction = "with"
routes.RussianHillTakedownRoute.roads[21] = {}
routes.RussianHillTakedownRoute.roads[21].road = "dt_alleyway_03 AI Road 0"
routes.RussianHillTakedownRoute.roads[21].direction = "against"
routes.RussianHillTakedownRoute.roads[22] = {}
routes.RussianHillTakedownRoute.roads[22].road = "dt_8l_centre_01ab AI Road 2"
routes.RussianHillTakedownRoute.roads[22].direction = "against"
routes.RussianHillTakedownRoute.roads[23] = {}
routes.RussianHillTakedownRoute.roads[23].road = "dt_8l_centre_01ab AI Road 1"
routes.RussianHillTakedownRoute.roads[23].direction = "against"
routes.RussianHillTakedownRoute.roads[24] = {}
routes.RussianHillTakedownRoute.roads[24].road = "dt_8l_centre_01ab AI Road 0"
routes.RussianHillTakedownRoute.roads[24].direction = "against"
