routes = routes or {}
routes.TeamColoursTutorialRoute = {}
routes.TeamColoursTutorialRoute.checkpoints = {}
routes.TeamColoursTutorialRoute.checkpoints[1] = {}
routes.TeamColoursTutorialRoute.checkpoints[1].position = vec.vector(316.0017, 8.095724, -142.3375, 1)
routes.TeamColoursTutorialRoute.checkpoints[1].heading = 2.550897
routes.TeamColoursTutorialRoute.checkpoints[1].roadName = "dt_8l_centre_01aa AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[2] = {}
routes.TeamColoursTutorialRoute.checkpoints[2].position = vec.vector(638.3707, 6.384207, -167.5303, 1)
routes.TeamColoursTutorialRoute.checkpoints[2].heading = 1.053064
routes.TeamColoursTutorialRoute.checkpoints[2].roadName = "dt_10l_east_01 AI Road 7"
routes.TeamColoursTutorialRoute.checkpoints[3] = {}
routes.TeamColoursTutorialRoute.checkpoints[3].position = vec.vector(726.7973, 7.033201, -36.1104, 1)
routes.TeamColoursTutorialRoute.checkpoints[3].heading = -0.3793799
routes.TeamColoursTutorialRoute.checkpoints[3].roadName = "dt_6l_east_01 AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[4] = {}
routes.TeamColoursTutorialRoute.checkpoints[4].position = vec.vector(435.4805, 50.92259, 91.87756, 1)
routes.TeamColoursTutorialRoute.checkpoints[4].heading = -0.3348221
routes.TeamColoursTutorialRoute.checkpoints[4].roadName = "dt_4l_east_02 AI Road 1"
routes.TeamColoursTutorialRoute.checkpoints[5] = {}
routes.TeamColoursTutorialRoute.checkpoints[5].position = vec.vector(468.2632, 55.01775, 393.28, 1)
routes.TeamColoursTutorialRoute.checkpoints[5].heading = -1.010346
routes.TeamColoursTutorialRoute.checkpoints[5].roadName = "dt_4l_east_04 AI Road 3"
routes.TeamColoursTutorialRoute.checkpoints[6] = {}
routes.TeamColoursTutorialRoute.checkpoints[6].position = vec.vector(270.7784, 69.47495, 221.9753, 1)
routes.TeamColoursTutorialRoute.checkpoints[6].heading = 2.653226
routes.TeamColoursTutorialRoute.checkpoints[6].roadName = "dt_4l_east_04 AI Road 2"
routes.TeamColoursTutorialRoute.checkpoints[7] = {}
routes.TeamColoursTutorialRoute.checkpoints[7].position = vec.vector(5.30686, 34.938, 156.3706, 1)
routes.TeamColoursTutorialRoute.checkpoints[7].heading = 0.1626097
routes.TeamColoursTutorialRoute.checkpoints[7].roadName = "dt_8l_centre_02 AI Road 2"
routes.TeamColoursTutorialRoute.checkpoints[8] = {}
routes.TeamColoursTutorialRoute.checkpoints[8].position = vec.vector(46.59161, 34.82779, 353.9517, 1)
routes.TeamColoursTutorialRoute.checkpoints[8].heading = 0.2773687
routes.TeamColoursTutorialRoute.checkpoints[8].roadName = "dt_8l_centre_02 AI Road 3"
routes.TeamColoursTutorialRoute.checkpoints[9] = {}
routes.TeamColoursTutorialRoute.checkpoints[9].position = vec.vector(189.2715, 31.68329, 478.3747, 1)
routes.TeamColoursTutorialRoute.checkpoints[9].heading = 1.203739
routes.TeamColoursTutorialRoute.checkpoints[9].roadName = "dt_8l_centre_02 AI Road 4"
routes.TeamColoursTutorialRoute.checkpoints[10] = {}
routes.TeamColoursTutorialRoute.checkpoints[10].position = vec.vector(274.4912, 32.02784, 611.9092, 1)
routes.TeamColoursTutorialRoute.checkpoints[10].heading = -1.374874
routes.TeamColoursTutorialRoute.checkpoints[10].roadName = "dt_4l_centre_01 AI Road 2"
routes.TeamColoursTutorialRoute.checkpoints[11] = {}
routes.TeamColoursTutorialRoute.checkpoints[11].position = vec.vector(-148.9885, 50.82721, 561.874, 1)
routes.TeamColoursTutorialRoute.checkpoints[11].heading = -2.405428
routes.TeamColoursTutorialRoute.checkpoints[11].roadName = "dt_6l_centre_01 AI Road 1"
routes.TeamColoursTutorialRoute.checkpoints[12] = {}
routes.TeamColoursTutorialRoute.checkpoints[12].position = vec.vector(-269.8837, 70.00015, 255.0046, 1)
routes.TeamColoursTutorialRoute.checkpoints[12].heading = -2.871051
routes.TeamColoursTutorialRoute.checkpoints[12].roadName = "dt_6l_centre_01 AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[13] = {}
routes.TeamColoursTutorialRoute.checkpoints[13].position = vec.vector(-306.1609, 70, -0.5220678, 1)
routes.TeamColoursTutorialRoute.checkpoints[13].heading = 1.882279
routes.TeamColoursTutorialRoute.checkpoints[13].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[14] = {}
routes.TeamColoursTutorialRoute.checkpoints[14].position = vec.vector(-249.6574, 59.7812, 3.85891, 1)
routes.TeamColoursTutorialRoute.checkpoints[14].heading = -2.858762
routes.TeamColoursTutorialRoute.checkpoints[14].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[15] = {}
routes.TeamColoursTutorialRoute.checkpoints[15].position = vec.vector(-218.9539, 52.15949, -5.367224, 1)
routes.TeamColoursTutorialRoute.checkpoints[15].heading = 0.5184817
routes.TeamColoursTutorialRoute.checkpoints[15].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[16] = {}
routes.TeamColoursTutorialRoute.checkpoints[16].position = vec.vector(-190.3995, 45.13428, -14.5442, 1)
routes.TeamColoursTutorialRoute.checkpoints[16].heading = -2.883699
routes.TeamColoursTutorialRoute.checkpoints[16].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[17] = {}
routes.TeamColoursTutorialRoute.checkpoints[17].position = vec.vector(-159.015, 36.94699, -26.89677, 1)
routes.TeamColoursTutorialRoute.checkpoints[17].heading = 0.5348851
routes.TeamColoursTutorialRoute.checkpoints[17].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[18] = {}
routes.TeamColoursTutorialRoute.checkpoints[18].position = vec.vector(-127.3937, 30.00368, -35.75863, 1)
routes.TeamColoursTutorialRoute.checkpoints[18].heading = -2.903864
routes.TeamColoursTutorialRoute.checkpoints[18].roadName = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.checkpoints[19] = {}
routes.TeamColoursTutorialRoute.checkpoints[19].position = vec.vector(120.4398, 15.94951, -61.76233, 1)
routes.TeamColoursTutorialRoute.checkpoints[19].heading = 1.646088
routes.TeamColoursTutorialRoute.checkpoints[19].roadName = "dt_8l_centre_01aa AI Road 0"
routes.TeamColoursTutorialRoute.arrows = {}
routes.TeamColoursTutorialRoute.arrows[1] = {}
routes.TeamColoursTutorialRoute.arrows[1].position = vec.vector(390.6716, 2.5, -299.2098, 1)
routes.TeamColoursTutorialRoute.arrows[1].heading = 1.255181
routes.TeamColoursTutorialRoute.arrows[1].checkpointStart = 1
routes.TeamColoursTutorialRoute.arrows[1].checkpointEnd = 2
routes.TeamColoursTutorialRoute.arrows[1].modelId = 219
routes.TeamColoursTutorialRoute.arrows[2] = {}
routes.TeamColoursTutorialRoute.arrows[2].position = vec.vector(759.6934, 4.5, -83.94675, 1)
routes.TeamColoursTutorialRoute.arrows[2].heading = -0.3752714
routes.TeamColoursTutorialRoute.arrows[2].checkpointStart = 2
routes.TeamColoursTutorialRoute.arrows[2].checkpointEnd = 3
routes.TeamColoursTutorialRoute.arrows[2].modelId = 219
routes.TeamColoursTutorialRoute.arrows[3] = {}
routes.TeamColoursTutorialRoute.arrows[3].position = vec.vector(691.4759, 4.5, 63.91948, 1)
routes.TeamColoursTutorialRoute.arrows[3].heading = -1.951303
routes.TeamColoursTutorialRoute.arrows[3].checkpointStart = 3
routes.TeamColoursTutorialRoute.arrows[3].checkpointEnd = 4
routes.TeamColoursTutorialRoute.arrows[3].modelId = 219
routes.TeamColoursTutorialRoute.arrows[4] = {}
routes.TeamColoursTutorialRoute.arrows[4].position = vec.vector(504.6997, 51.5, 387.334, 1)
routes.TeamColoursTutorialRoute.arrows[4].heading = -0.9551762
routes.TeamColoursTutorialRoute.arrows[4].checkpointStart = 4
routes.TeamColoursTutorialRoute.arrows[4].checkpointEnd = 5
routes.TeamColoursTutorialRoute.arrows[4].modelId = 78
routes.TeamColoursTutorialRoute.arrows[5] = {}
routes.TeamColoursTutorialRoute.arrows[5].position = vec.vector(231.0716, 66, 271.9969, 1)
routes.TeamColoursTutorialRoute.arrows[5].heading = 2.703801
routes.TeamColoursTutorialRoute.arrows[5].checkpointStart = 5
routes.TeamColoursTutorialRoute.arrows[5].checkpointEnd = 6
routes.TeamColoursTutorialRoute.arrows[5].modelId = 78
routes.TeamColoursTutorialRoute.arrows[6] = {}
routes.TeamColoursTutorialRoute.arrows[6].position = vec.vector(-21.05711, 32.5, 120.7106, 1)
routes.TeamColoursTutorialRoute.arrows[6].heading = 0.1838175
routes.TeamColoursTutorialRoute.arrows[6].checkpointStart = 6
routes.TeamColoursTutorialRoute.arrows[6].checkpointEnd = 7
routes.TeamColoursTutorialRoute.arrows[6].modelId = 78
routes.TeamColoursTutorialRoute.arrows[7] = {}
routes.TeamColoursTutorialRoute.arrows[7].position = vec.vector(96.44989, 29, 456.4017, 1)
routes.TeamColoursTutorialRoute.arrows[7].heading = 1.177739
routes.TeamColoursTutorialRoute.arrows[7].checkpointStart = 8
routes.TeamColoursTutorialRoute.arrows[7].checkpointEnd = 9
routes.TeamColoursTutorialRoute.arrows[7].modelId = 78
routes.TeamColoursTutorialRoute.arrows[8] = {}
routes.TeamColoursTutorialRoute.arrows[8].position = vec.vector(322.2185, 29, 618.2975, 1)
routes.TeamColoursTutorialRoute.arrows[8].heading = -1.352127
routes.TeamColoursTutorialRoute.arrows[8].checkpointStart = 9
routes.TeamColoursTutorialRoute.arrows[8].checkpointEnd = 10
routes.TeamColoursTutorialRoute.arrows[8].modelId = 219
routes.TeamColoursTutorialRoute.arrows[9] = {}
routes.TeamColoursTutorialRoute.arrows[9].position = vec.vector(-204.7581, 58, 374.5745, 1)
routes.TeamColoursTutorialRoute.arrows[9].heading = -2.727086
routes.TeamColoursTutorialRoute.arrows[9].horizontalArrow = true
routes.TeamColoursTutorialRoute.arrows[9].checkpointStart = 11
routes.TeamColoursTutorialRoute.arrows[9].checkpointEnd = 12
routes.TeamColoursTutorialRoute.arrows[9].modelId = 78
routes.TeamColoursTutorialRoute.arrows[10] = {}
routes.TeamColoursTutorialRoute.arrows[10].position = vec.vector(-267.1583, 68, 164.6094, 1)
routes.TeamColoursTutorialRoute.arrows[10].heading = -2.863293
routes.TeamColoursTutorialRoute.arrows[10].horizontalArrow = true
routes.TeamColoursTutorialRoute.arrows[10].checkpointStart = 12
routes.TeamColoursTutorialRoute.arrows[10].checkpointEnd = 13
routes.TeamColoursTutorialRoute.arrows[10].modelId = 78
routes.TeamColoursTutorialRoute.arrows[11] = {}
routes.TeamColoursTutorialRoute.arrows[11].position = vec.vector(-338.5766, 67, 1.841506, 1)
routes.TeamColoursTutorialRoute.arrows[11].heading = 1.825979
routes.TeamColoursTutorialRoute.arrows[11].checkpointStart = 12
routes.TeamColoursTutorialRoute.arrows[11].checkpointEnd = 13
routes.TeamColoursTutorialRoute.arrows[11].modelId = 219
routes.TeamColoursTutorialRoute.arrows[12] = {}
routes.TeamColoursTutorialRoute.arrows[12].position = vec.vector(-115.3892, 49.5, 689.6338, 1)
routes.TeamColoursTutorialRoute.arrows[12].heading = -2.926777
routes.TeamColoursTutorialRoute.arrows[12].checkpointStart = 10
routes.TeamColoursTutorialRoute.arrows[12].checkpointEnd = 11
routes.TeamColoursTutorialRoute.arrows[12].modelId = 219
routes.TeamColoursTutorialRoute.arrows[13] = {}
routes.TeamColoursTutorialRoute.arrows[13].position = vec.vector(-248.5466, 61.73348, 47.38881, 1)
routes.TeamColoursTutorialRoute.arrows[13].heading = 2.025684
routes.TeamColoursTutorialRoute.arrows[13].checkpointStart = 13
routes.TeamColoursTutorialRoute.arrows[13].checkpointEnd = 14
routes.TeamColoursTutorialRoute.arrows[13].modelId = 78
routes.TeamColoursTutorialRoute.arrows[14] = {}
routes.TeamColoursTutorialRoute.arrows[14].position = vec.vector(-251.1519, 53.30396, -38.15093, 1)
routes.TeamColoursTutorialRoute.arrows[14].heading = 1.758577
routes.TeamColoursTutorialRoute.arrows[14].checkpointStart = 14
routes.TeamColoursTutorialRoute.arrows[14].checkpointEnd = 15
routes.TeamColoursTutorialRoute.arrows[14].modelId = 78
routes.TeamColoursTutorialRoute.arrows[15] = {}
routes.TeamColoursTutorialRoute.arrows[15].position = vec.vector(-189.4937, 45.37445, 26.54664, 1)
routes.TeamColoursTutorialRoute.arrows[15].heading = 2.008656
routes.TeamColoursTutorialRoute.arrows[15].checkpointStart = 15
routes.TeamColoursTutorialRoute.arrows[15].checkpointEnd = 16
routes.TeamColoursTutorialRoute.arrows[15].modelId = 78
routes.TeamColoursTutorialRoute.arrows[16] = {}
routes.TeamColoursTutorialRoute.arrows[16].position = vec.vector(-188.6253, 37.44493, -61.59837, 1)
routes.TeamColoursTutorialRoute.arrows[16].heading = 1.680041
routes.TeamColoursTutorialRoute.arrows[16].checkpointStart = 16
routes.TeamColoursTutorialRoute.arrows[16].checkpointEnd = 17
routes.TeamColoursTutorialRoute.arrows[16].modelId = 78
routes.TeamColoursTutorialRoute.arrows[17] = {}
routes.TeamColoursTutorialRoute.arrows[17].position = vec.vector(-128.2698, 30.837, 4.401835, 1)
routes.TeamColoursTutorialRoute.arrows[17].heading = 1.969641
routes.TeamColoursTutorialRoute.arrows[17].checkpointStart = 17
routes.TeamColoursTutorialRoute.arrows[17].checkpointEnd = 18
routes.TeamColoursTutorialRoute.arrows[17].modelId = 78
routes.TeamColoursTutorialRoute.arrows[18] = {}
routes.TeamColoursTutorialRoute.arrows[18].position = vec.vector(-126.0987, 22.90749, -85.04581, 1)
routes.TeamColoursTutorialRoute.arrows[18].heading = 1.616634
routes.TeamColoursTutorialRoute.arrows[18].checkpointStart = 18
routes.TeamColoursTutorialRoute.arrows[18].checkpointEnd = 19
routes.TeamColoursTutorialRoute.arrows[18].modelId = 78
routes.TeamColoursTutorialRoute.arrows[19] = {}
routes.TeamColoursTutorialRoute.arrows[19].position = vec.vector(-29.72988, 16, -62.64207, 1)
routes.TeamColoursTutorialRoute.arrows[19].heading = 1.652249
routes.TeamColoursTutorialRoute.arrows[19].checkpointStart = 18
routes.TeamColoursTutorialRoute.arrows[19].checkpointEnd = 19
routes.TeamColoursTutorialRoute.arrows[19].modelId = 78
routes.TeamColoursTutorialRoute.arrows[20] = {}
routes.TeamColoursTutorialRoute.arrows[20].position = vec.vector(-25.6904, 16, -37.89198, 1)
routes.TeamColoursTutorialRoute.arrows[20].heading = 1.732634
routes.TeamColoursTutorialRoute.arrows[20].checkpointStart = 18
routes.TeamColoursTutorialRoute.arrows[20].checkpointEnd = 19
routes.TeamColoursTutorialRoute.arrows[20].modelId = 78
routes.TeamColoursTutorialRoute.arrows[21] = {}
routes.TeamColoursTutorialRoute.arrows[21].position = vec.vector(-261.6509, 58, 389.0777, 1)
routes.TeamColoursTutorialRoute.arrows[21].heading = -2.922924
routes.TeamColoursTutorialRoute.arrows[21].checkpointStart = 11
routes.TeamColoursTutorialRoute.arrows[21].checkpointEnd = 12
routes.TeamColoursTutorialRoute.arrows[21].modelId = 78
routes.TeamColoursTutorialRoute.arrows[22] = {}
routes.TeamColoursTutorialRoute.arrows[22].position = vec.vector(-322.4279, 68, 174.8599, 1)
routes.TeamColoursTutorialRoute.arrows[22].heading = -2.929161
routes.TeamColoursTutorialRoute.arrows[22].checkpointStart = 12
routes.TeamColoursTutorialRoute.arrows[22].checkpointEnd = 13
routes.TeamColoursTutorialRoute.arrows[22].modelId = 78
routes.TeamColoursTutorialRoute.roads = {}
routes.TeamColoursTutorialRoute.roads[1] = {}
routes.TeamColoursTutorialRoute.roads[1].road = "dt_8l_centre_01aa AI Road 0"
routes.TeamColoursTutorialRoute.roads[1].direction = "against"
routes.TeamColoursTutorialRoute.roads[2] = {}
routes.TeamColoursTutorialRoute.roads[2].road = "dt_10l_east_01 AI Road 7"
routes.TeamColoursTutorialRoute.roads[2].direction = "with"
routes.TeamColoursTutorialRoute.roads[3] = {}
routes.TeamColoursTutorialRoute.roads[3].road = "dt_6l_east_01 AI Road 0"
routes.TeamColoursTutorialRoute.roads[3].direction = "with"
routes.TeamColoursTutorialRoute.roads[4] = {}
routes.TeamColoursTutorialRoute.roads[4].road = "dt_4l_east_02 AI Road 2"
routes.TeamColoursTutorialRoute.roads[4].direction = "against"
routes.TeamColoursTutorialRoute.roads[5] = {}
routes.TeamColoursTutorialRoute.roads[5].road = "dt_4l_east_02 AI Road 1"
routes.TeamColoursTutorialRoute.roads[5].direction = "against"
routes.TeamColoursTutorialRoute.roads[6] = {}
routes.TeamColoursTutorialRoute.roads[6].road = "dt_4l_east_02 AI Road 0"
routes.TeamColoursTutorialRoute.roads[6].direction = "against"
routes.TeamColoursTutorialRoute.roads[7] = {}
routes.TeamColoursTutorialRoute.roads[7].road = "dt_4l_east_04 AI Road 3"
routes.TeamColoursTutorialRoute.roads[7].direction = "against"
routes.TeamColoursTutorialRoute.roads[8] = {}
routes.TeamColoursTutorialRoute.roads[8].road = "dt_4l_east_04 AI Road 2"
routes.TeamColoursTutorialRoute.roads[8].direction = "against"
routes.TeamColoursTutorialRoute.roads[9] = {}
routes.TeamColoursTutorialRoute.roads[9].road = "dt_8l_centre_02 AI Road 2"
routes.TeamColoursTutorialRoute.roads[9].direction = "with"
routes.TeamColoursTutorialRoute.roads[10] = {}
routes.TeamColoursTutorialRoute.roads[10].road = "dt_8l_centre_02 AI Road 3"
routes.TeamColoursTutorialRoute.roads[10].direction = "with"
routes.TeamColoursTutorialRoute.roads[11] = {}
routes.TeamColoursTutorialRoute.roads[11].road = "dt_8l_centre_02 AI Road 4"
routes.TeamColoursTutorialRoute.roads[11].direction = "with"
routes.TeamColoursTutorialRoute.roads[12] = {}
routes.TeamColoursTutorialRoute.roads[12].road = "dt_4l_centre_01 AI Road 2"
routes.TeamColoursTutorialRoute.roads[12].direction = "against"
routes.TeamColoursTutorialRoute.roads[13] = {}
routes.TeamColoursTutorialRoute.roads[13].road = "dt_4l_centre_01 AI Road 1"
routes.TeamColoursTutorialRoute.roads[13].direction = "against"
routes.TeamColoursTutorialRoute.roads[14] = {}
routes.TeamColoursTutorialRoute.roads[14].road = "dt_6l_centre_01 AI Road 1"
routes.TeamColoursTutorialRoute.roads[14].direction = "against"
routes.TeamColoursTutorialRoute.roads[15] = {}
routes.TeamColoursTutorialRoute.roads[15].road = "dt_6l_centre_01 AI Road 0"
routes.TeamColoursTutorialRoute.roads[15].direction = "against"
routes.TeamColoursTutorialRoute.roads[16] = {}
routes.TeamColoursTutorialRoute.roads[16].road = "dt_6l_north_01 AI Road 3"
routes.TeamColoursTutorialRoute.roads[16].direction = "against"
routes.TeamColoursTutorialRoute.roads[17] = {}
routes.TeamColoursTutorialRoute.roads[17].road = "lombard_street AI Road 0"
routes.TeamColoursTutorialRoute.roads[17].direction = "with"
