routes = routes or {}
routes["Team colours route"] = {}
routes["Team colours route"].checkpoints = {}
routes["Team colours route"].checkpoints[1] = {}
routes["Team colours route"].checkpoints[1].position = vec.vector(-2949.732, 60.24998, 2434.044, 1)
routes["Team colours route"].checkpoints[1].heading = -1.58726
routes["Team colours route"].checkpoints[1].roadName = "sutro_8l_north_01 AI Road 8"
routes["Team colours route"].checkpoints[1].roadWidth = 44
routes["Team colours route"].checkpoints[2] = {}
routes["Team colours route"].checkpoints[2].position = vec.vector(-2396.146, 79.74998, 2322.413, 1)
routes["Team colours route"].checkpoints[2].heading = -1.850813
routes["Team colours route"].checkpoints[2].roadName = "sutro_8l_north_01 AI Road 9"
routes["Team colours route"].checkpoints[2].roadWidth = 44
routes["Team colours route"].checkpoints[3] = {}
routes["Team colours route"].checkpoints[3].position = vec.vector(-1874.036, 75.0262, 2057.332, 1)
routes["Team colours route"].checkpoints[3].heading = -1.827011
routes["Team colours route"].checkpoints[3].roadName = "dt_10l_south_02b AI Road 0"
routes["Team colours route"].checkpoints[3].roadWidth = 44
routes["Team colours route"].checkpoints[4] = {}
routes["Team colours route"].checkpoints[4].position = vec.vector(-1502.435, 66.75, 1987.348, 1)
routes["Team colours route"].checkpoints[4].heading = -0.3826137
routes["Team colours route"].checkpoints[4].roadName = "dt_8l_centre_01b AI Road 0"
routes["Team colours route"].checkpoints[4].roadWidth = 44
routes["Team colours route"].checkpoints[5] = {}
routes["Team colours route"].checkpoints[5].position = vec.vector(-1460.392, 66.75, 2241.987, 1)
routes["Team colours route"].checkpoints[5].heading = 1.350285
routes["Team colours route"].checkpoints[5].roadName = "sutro_dt_join_03 AI Road 0"
routes["Team colours route"].checkpoints[5].roadWidth = 29
routes["Team colours route"].checkpoints[6] = {}
routes["Team colours route"].checkpoints[6].position = vec.vector(-1840.42, 96.26729, 2353.479, 1)
routes["Team colours route"].checkpoints[6].heading = 1.368593
routes["Team colours route"].checkpoints[6].roadName = "sutro_dt_join_03 AI Road 1"
routes["Team colours route"].checkpoints[6].roadWidth = 29
routes["Team colours route"].checkpoints[7] = {}
routes["Team colours route"].checkpoints[7].position = vec.vector(-2198.849, 96.85432, 2495.51, 1)
routes["Team colours route"].checkpoints[7].heading = 1.480301
routes["Team colours route"].checkpoints[7].roadName = "storm_drain_02 AI Road 0"
routes["Team colours route"].checkpoints[7].roadWidth = 20
routes["Team colours route"].checkpoints[8] = {}
routes["Team colours route"].checkpoints[8].position = vec.vector(-2016.369, 100.4392, 3003.348, 1)
routes["Team colours route"].checkpoints[8].heading = -0.02450085
routes["Team colours route"].checkpoints[8].roadName = "storm_drain_05 AI Road 0"
routes["Team colours route"].checkpoints[8].roadWidth = 20
routes["Team colours route"].checkpoints[9] = {}
routes["Team colours route"].checkpoints[9].position = vec.vector(-2025.953, 125.25, 3319.283, 1)
routes["Team colours route"].checkpoints[9].heading = 0.08109188
routes["Team colours route"].checkpoints[9].roadName = "sutro_4l_centre_04 AI Road 1"
routes["Team colours route"].checkpoints[9].roadWidth = 29
routes["Team colours route"].checkpoints[10] = {}
routes["Team colours route"].checkpoints[10].position = vec.vector(-2540.471, 163.1209, 3595.639, 1)
routes["Team colours route"].checkpoints[10].heading = 1.57465
routes["Team colours route"].checkpoints[10].roadName = "sutro_6l_south_01a AI Road 1"
routes["Team colours route"].checkpoints[10].roadWidth = 36
routes["Team colours route"].checkpoints[11] = {}
routes["Team colours route"].checkpoints[11].position = vec.vector(-2934.473, 112.0838, 3262.156, 1)
routes["Team colours route"].checkpoints[11].heading = -2.247722
routes["Team colours route"].checkpoints[11].roadName = "sutro_6l_south_01a AI Road 0"
routes["Team colours route"].checkpoints[11].roadWidth = 36
routes["Team colours route"].checkpoints[12] = {}
routes["Team colours route"].checkpoints[12].position = vec.vector(-2788.526, 105.7501, 3092.269, 1)
routes["Team colours route"].checkpoints[12].heading = 2.399405
routes["Team colours route"].checkpoints[12].roadName = "sutro_8l_centre_06a AI Road 1"
routes["Team colours route"].checkpoints[12].roadWidth = 36
routes["Team colours route"].checkpoints[13] = {}
routes["Team colours route"].checkpoints[13].position = vec.vector(-2845.443, 104.4416, 2886.446, 1)
routes["Team colours route"].checkpoints[13].heading = 2.184448
routes["Team colours route"].checkpoints[13].roadName = "sutro_shortcut_11 AI Road 0"
routes["Team colours route"].checkpoints[13].roadWidth = 14
routes["Team colours route"].checkpoints[14] = {}
routes["Team colours route"].checkpoints[14].position = vec.vector(-2975.503, 92.74975, 2674.157, 1)
routes["Team colours route"].checkpoints[14].heading = 3.010509
routes["Team colours route"].checkpoints[14].roadName = "sutro_west_02 AI Road 0"
routes["Team colours route"].checkpoints[14].roadWidth = 29
routes["Team colours route"].roads = {}
routes["Team colours route"].roads[1] = {}
routes["Team colours route"].roads[1].road = "sutro_8l_north_01 AI Road 8"
routes["Team colours route"].roads[1].direction = "with"
routes["Team colours route"].roads[2] = {}
routes["Team colours route"].roads[2].road = "sutro_8l_north_01 AI Road 9"
routes["Team colours route"].roads[2].direction = "with"
routes["Team colours route"].roads[3] = {}
routes["Team colours route"].roads[3].road = "dt_10l_south_02b AI Road 0"
routes["Team colours route"].roads[3].direction = "with"
routes["Team colours route"].roads[4] = {}
routes["Team colours route"].roads[4].road = "dt_10l_south_02b AI Road 1"
routes["Team colours route"].roads[4].direction = "with"
routes["Team colours route"].roads[5] = {}
routes["Team colours route"].roads[5].road = "dt_8l_centre_01b AI Road 0"
routes["Team colours route"].roads[5].direction = "with"
routes["Team colours route"].roads[6] = {}
routes["Team colours route"].roads[6].road = "sutro_dt_join_03 AI Road 0"
routes["Team colours route"].roads[6].direction = "with"
routes["Team colours route"].roads[7] = {}
routes["Team colours route"].roads[7].road = "sutro_dt_join_03 AI Road 1"
routes["Team colours route"].roads[7].direction = "with"
routes["Team colours route"].roads[8] = {}
routes["Team colours route"].roads[8].road = "sutro_dt_join_03 AI Road 2"
routes["Team colours route"].roads[8].direction = "with"
routes["Team colours route"].roads[9] = {}
routes["Team colours route"].roads[9].road = "storm_drain_02 AI Road 0"
routes["Team colours route"].roads[9].direction = "with"
routes["Team colours route"].roads[10] = {}
routes["Team colours route"].roads[10].road = "storm_drain_05 AI Road 0"
routes["Team colours route"].roads[10].direction = "with"
routes["Team colours route"].roads[11] = {}
routes["Team colours route"].roads[11].road = "sutro_4l_centre_04 AI Road 1"
routes["Team colours route"].roads[11].direction = "with"
routes["Team colours route"].roads[12] = {}
routes["Team colours route"].roads[12].road = "sutro_6l_south_01a AI Road 1"
routes["Team colours route"].roads[12].direction = "against"
routes["Team colours route"].roads[13] = {}
routes["Team colours route"].roads[13].road = "sutro_6l_south_01a AI Road 0"
routes["Team colours route"].roads[13].direction = "against"
routes["Team colours route"].roads[14] = {}
routes["Team colours route"].roads[14].road = "sutro_8l_centre_06a AI Road 1"
routes["Team colours route"].roads[14].direction = "against"
routes["Team colours route"].roads[15] = {}
routes["Team colours route"].roads[15].road = "sutro_shortcut_11 AI Road 0"
routes["Team colours route"].roads[15].direction = "against"
routes["Team colours route"].roads[16] = {}
routes["Team colours route"].roads[16].road = "sutro_west_02 AI Road 0"
routes["Team colours route"].roads[16].direction = "against"
