routes = routes or {}
routes.TheDriverRoute = {}
routes.TheDriverRoute.checkpoints = {}
routes.TheDriverRoute.checkpoints[1] = {}
routes.TheDriverRoute.checkpoints[1].position = vec.vector(472.3336, 7.74261, 1342.072, 1)
routes.TheDriverRoute.checkpoints[1].heading = -2.449048
routes.TheDriverRoute.checkpoints[1].roadName = "barcelero_alleyway_01 AI Road 0"
routes.TheDriverRoute.checkpoints[2] = {}
routes.TheDriverRoute.checkpoints[2].position = vec.vector(-90.50063, 41.11034, 1731.418, 1)
routes.TheDriverRoute.checkpoints[2].heading = 0.8802897
routes.TheDriverRoute.checkpoints[2].roadName = "r333_shortcut_02 AI Road 0"
routes.TheDriverRoute.checkpoints[3] = {}
routes.TheDriverRoute.checkpoints[3].position = vec.vector(-441.2258, 40.74999, 2069.042, 1)
routes.TheDriverRoute.checkpoints[3].heading = 0.5704314
routes.TheDriverRoute.checkpoints[3].roadName = "mt_6l_w_02a AI Road 0"
routes.TheDriverRoute.checkpoints[4] = {}
routes.TheDriverRoute.checkpoints[4].position = vec.vector(-225.1676, 41.59711, 2399.611, 1)
routes.TheDriverRoute.checkpoints[4].heading = 0.531681
routes.TheDriverRoute.checkpoints[4].roadName = "mt_6l_w_02b AI Road 0"
routes.TheDriverRoute.checkpoints[5] = {}
routes.TheDriverRoute.checkpoints[5].position = vec.vector(15.37607, 41.72158, 2386.01, 1)
routes.TheDriverRoute.checkpoints[5].heading = 2.071798
routes.TheDriverRoute.checkpoints[5].roadName = "mt_shortcut_05 AI Road 0"
routes.TheDriverRoute.checkpoints[6] = {}
routes.TheDriverRoute.checkpoints[6].position = vec.vector(662.7761, 8.250002, 2882.808, 1)
routes.TheDriverRoute.checkpoints[6].heading = 0.717487
routes.TheDriverRoute.checkpoints[6].roadName = "sutro_4l_east_02 AI Road 0"
routes.TheDriverRoute.checkpoints[7] = {}
routes.TheDriverRoute.checkpoints[7].position = vec.vector(579.7083, 8.250002, 3090.826, 1)
routes.TheDriverRoute.checkpoints[7].heading = -0.8906881
routes.TheDriverRoute.checkpoints[7].roadName = "sutro_4l_east_01 AI Road 1"
routes.TheDriverRoute.checkpoints[8] = {}
routes.TheDriverRoute.checkpoints[8].position = vec.vector(441.123, 12.08136, 3258.831, 1)
routes.TheDriverRoute.checkpoints[8].heading = 0.009414347
routes.TheDriverRoute.checkpoints[8].roadName = "r247_shortcut_01 AI Road 0"
routes.TheDriverRoute.checkpoints[9] = {}
routes.TheDriverRoute.checkpoints[9].position = vec.vector(565.0445, 8.25, 3610, 1)
routes.TheDriverRoute.checkpoints[9].heading = 1.570796
routes.TheDriverRoute.checkpoints[9].roadName = "r219_helper_01 AI Road 0"
routes.TheDriverRoute.checkpoints[10] = {}
routes.TheDriverRoute.checkpoints[10].position = vec.vector(978.7045, 8.249998, 3530.701, 1)
routes.TheDriverRoute.checkpoints[10].heading = 1.570796
routes.TheDriverRoute.checkpoints[10].roadName = "sutro_10l_se_01_01 AI Road 5"
routes.TheDriverRoute.arrows = {}
routes.TheDriverRoute.roads = {}
routes.TheDriverRoute.roads[1] = {}
routes.TheDriverRoute.roads[1].road = "barcelero_alleyway_01 AI Road 0"
routes.TheDriverRoute.roads[1].direction = "against"
routes.TheDriverRoute.roads[2] = {}
routes.TheDriverRoute.roads[2].road = "dt_10l_south_03 AI Road 4"
routes.TheDriverRoute.roads[2].direction = "with"
routes.TheDriverRoute.roads[3] = {}
routes.TheDriverRoute.roads[3].road = "dt_10l_south_03 AI Road 5"
routes.TheDriverRoute.roads[3].direction = "with"
routes.TheDriverRoute.roads[4] = {}
routes.TheDriverRoute.roads[4].road = "dt_10l_south_03 AI Road 6"
routes.TheDriverRoute.roads[4].direction = "with"
routes.TheDriverRoute.roads[5] = {}
routes.TheDriverRoute.roads[5].road = "_unnamed road 0x285ef3b6 : 0xa6bf1200 AI Road 0"
routes.TheDriverRoute.roads[5].direction = "with"
routes.TheDriverRoute.roads[6] = {}
routes.TheDriverRoute.roads[6].road = "r333_shortcut_02 AI Road 0"
routes.TheDriverRoute.roads[6].direction = "with"
routes.TheDriverRoute.roads[7] = {}
routes.TheDriverRoute.roads[7].road = "mt_4l_south_03 AI Road 1"
routes.TheDriverRoute.roads[7].direction = "with"
routes.TheDriverRoute.roads[8] = {}
routes.TheDriverRoute.roads[8].road = "mt_4l_south_03 AI Road 2"
routes.TheDriverRoute.roads[8].direction = "with"
routes.TheDriverRoute.roads[9] = {}
routes.TheDriverRoute.roads[9].road = "mt_4l_west_01 AI Road 0"
routes.TheDriverRoute.roads[9].direction = "with"
routes.TheDriverRoute.roads[10] = {}
routes.TheDriverRoute.roads[10].road = "mt_6l_w_02a AI Road 0"
routes.TheDriverRoute.roads[10].direction = "with"
routes.TheDriverRoute.roads[11] = {}
routes.TheDriverRoute.roads[11].road = "mt_6l_w_02a AI Road 1"
routes.TheDriverRoute.roads[11].direction = "with"
routes.TheDriverRoute.roads[12] = {}
routes.TheDriverRoute.roads[12].road = "mt_6l_w_02b AI Road 0"
routes.TheDriverRoute.roads[12].direction = "with"
routes.TheDriverRoute.roads[13] = {}
routes.TheDriverRoute.roads[13].road = "mt_shortcut_05 AI Road 0"
routes.TheDriverRoute.roads[13].direction = "with"
routes.TheDriverRoute.roads[14] = {}
routes.TheDriverRoute.roads[14].road = "mt_10l_centre_02 AI Road 1"
routes.TheDriverRoute.roads[14].direction = "with"
routes.TheDriverRoute.roads[15] = {}
routes.TheDriverRoute.roads[15].road = "mt_10l_centre_02 AI Road 2"
routes.TheDriverRoute.roads[15].direction = "with"
routes.TheDriverRoute.roads[16] = {}
routes.TheDriverRoute.roads[16].road = "mt_10l_centre_02 AI Road 3"
routes.TheDriverRoute.roads[16].direction = "with"
routes.TheDriverRoute.roads[17] = {}
routes.TheDriverRoute.roads[17].road = "mt_10l_centre_02 AI Road 4"
routes.TheDriverRoute.roads[17].direction = "with"
routes.TheDriverRoute.roads[18] = {}
routes.TheDriverRoute.roads[18].road = "surto_mt_join_03 AI Road 0"
routes.TheDriverRoute.roads[18].direction = "with"
routes.TheDriverRoute.roads[19] = {}
routes.TheDriverRoute.roads[19].road = "sutro_4l_east_02 AI Road 0"
routes.TheDriverRoute.roads[19].direction = "with"
routes.TheDriverRoute.roads[20] = {}
routes.TheDriverRoute.roads[20].road = "r247_shortcut_02 AI Road 0"
routes.TheDriverRoute.roads[20].direction = "with"
routes.TheDriverRoute.roads[21] = {}
routes.TheDriverRoute.roads[21].road = "sutro_4l_east_01 AI Road 1"
routes.TheDriverRoute.roads[21].direction = "against"
routes.TheDriverRoute.roads[22] = {}
routes.TheDriverRoute.roads[22].road = "r247_shortcut_01 AI Road 0"
routes.TheDriverRoute.roads[22].direction = "with"
routes.TheDriverRoute.roads[23] = {}
routes.TheDriverRoute.roads[23].road = "sutro_6l_east_02 AI Road 1"
routes.TheDriverRoute.roads[23].direction = "with"
routes.TheDriverRoute.roads[24] = {}
routes.TheDriverRoute.roads[24].road = "sutro_shortcut_e_08 AI Road 0"
routes.TheDriverRoute.roads[24].direction = "with"
routes.TheDriverRoute.roads[25] = {}
routes.TheDriverRoute.roads[25].road = "sutro_shortcut_e_08 AI Road 1"
routes.TheDriverRoute.roads[25].direction = "with"
routes.TheDriverRoute.roads[26] = {}
routes.TheDriverRoute.roads[26].road = "sutro_6l_east_04 AI Road 0"
routes.TheDriverRoute.roads[26].direction = "with"
routes.TheDriverRoute.roads[27] = {}
routes.TheDriverRoute.roads[27].road = "r219_helper_01 AI Road 0"
routes.TheDriverRoute.roads[27].direction = "against"
routes.TheDriverRoute.roads[28] = {}
routes.TheDriverRoute.roads[28].road = "sutro_6l_south_01b AI Road 5"
routes.TheDriverRoute.roads[28].direction = "with"
routes.TheDriverRoute.roads[29] = {}
routes.TheDriverRoute.roads[29].road = "sutro_10l_se_01_01 AI Road 5"
routes.TheDriverRoute.roads[29].direction = "with"
routes.TheDriverLoop = {}
routes.TheDriverLoop.checkpoints = {}
routes.TheDriverLoop.checkpoints[1] = {}
routes.TheDriverLoop.checkpoints[1].position = vec.vector(987.0892, 8.249998, 3530.699, 1)
routes.TheDriverLoop.checkpoints[1].heading = 1.571027
routes.TheDriverLoop.checkpoints[1].roadName = "sutro_10l_se_01_01 AI Road 5"
routes.TheDriverLoop.checkpoints[2] = {}
routes.TheDriverLoop.checkpoints[2].position = vec.vector(1135.79, 8.249998, 3612.609, 1)
routes.TheDriverLoop.checkpoints[2].heading = 0
routes.TheDriverLoop.checkpoints[2].roadName = "sutro_8l_east_04 AI Road 2"
routes.TheDriverLoop.checkpoints[3] = {}
routes.TheDriverLoop.checkpoints[3].position = vec.vector(1084.597, 8.249998, 3829.155, 1)
routes.TheDriverLoop.checkpoints[3].heading = 0.8480212
routes.TheDriverLoop.checkpoints[3].roadName = "sutro_4l_east_04 AI Road 1"
routes.TheDriverLoop.checkpoints[4] = {}
routes.TheDriverLoop.checkpoints[4].position = vec.vector(1085.481, 8.249998, 3982.769, 1)
routes.TheDriverLoop.checkpoints[4].heading = -2.354953
routes.TheDriverLoop.checkpoints[4].roadName = "sutro_shortcut_e_05 AI Road 2"
routes.TheDriverLoop.checkpoints[5] = {}
routes.TheDriverLoop.checkpoints[5].position = vec.vector(753.8198, 8.249998, 4131.909, 1)
routes.TheDriverLoop.checkpoints[5].heading = -2.503747
routes.TheDriverLoop.checkpoints[5].roadName = "sutro_4l_east_04 AI Road 3"
routes.TheDriverLoop.checkpoints[6] = {}
routes.TheDriverLoop.checkpoints[6].position = vec.vector(755.1365, 8.249998, 4053.425, 1)
routes.TheDriverLoop.checkpoints[6].heading = 2.282202
routes.TheDriverLoop.checkpoints[6].roadName = "sutro_8l_east_04 AI Road 5"
routes.TheDriverLoop.checkpoints[7] = {}
routes.TheDriverLoop.checkpoints[7].position = vec.vector(865.1735, 8.249998, 3904.061, 1)
routes.TheDriverLoop.checkpoints[7].heading = -2.362312
routes.TheDriverLoop.checkpoints[7].roadName = "sutro_shortcut_e_04 AI Road 1"
routes.TheDriverLoop.checkpoints[8] = {}
routes.TheDriverLoop.checkpoints[8].position = vec.vector(826.9835, 8.249998, 3808.228, 1)
routes.TheDriverLoop.checkpoints[8].heading = 2.361233
routes.TheDriverLoop.checkpoints[8].roadName = "sutro_6l_south_01b AI Road 2"
routes.TheDriverLoop.checkpoints[9] = {}
routes.TheDriverLoop.checkpoints[9].position = vec.vector(993.7381, 8.249998, 3846.919, 1)
routes.TheDriverLoop.checkpoints[9].heading = 2.346901
routes.TheDriverLoop.checkpoints[9].roadName = "sutro_8l_east_04 AI Road 3"
routes.TheDriverLoop.checkpoints[10] = {}
routes.TheDriverLoop.checkpoints[10].position = vec.vector(972.4368, 8.25, 3685.402, 1)
routes.TheDriverLoop.checkpoints[10].heading = 1.797584
routes.TheDriverLoop.checkpoints[10].roadName = "sutro_shortcut_e_06 AI Road 0"
routes.TheDriverLoop.arrows = {}
routes.TheDriverLoop.roads = {}
routes.TheDriverLoop.roads[1] = {}
routes.TheDriverLoop.roads[1].road = "sutro_10l_se_01_01 AI Road 5"
routes.TheDriverLoop.roads[1].direction = "with"
routes.TheDriverLoop.roads[2] = {}
routes.TheDriverLoop.roads[2].road = "sutro_10l_se_01_01 AI Road 6"
routes.TheDriverLoop.roads[2].direction = "with"
routes.TheDriverLoop.roads[3] = {}
routes.TheDriverLoop.roads[3].road = "sutro_8l_east_04 AI Road 2"
routes.TheDriverLoop.roads[3].direction = "with"
routes.TheDriverLoop.roads[4] = {}
routes.TheDriverLoop.roads[4].road = "sutro_4l_east_04 AI Road 1"
routes.TheDriverLoop.roads[4].direction = "with"
routes.TheDriverLoop.roads[5] = {}
routes.TheDriverLoop.roads[5].road = "sutro_shortcut_e_05 AI Road 2"
routes.TheDriverLoop.roads[5].direction = "against"
routes.TheDriverLoop.roads[6] = {}
routes.TheDriverLoop.roads[6].road = "sutro_shortcut_e_02 AI Road 0"
routes.TheDriverLoop.roads[6].direction = "with"
routes.TheDriverLoop.roads[7] = {}
routes.TheDriverLoop.roads[7].road = "sutro_shortcut_e_02 AI Road 1"
routes.TheDriverLoop.roads[7].direction = "with"
routes.TheDriverLoop.roads[8] = {}
routes.TheDriverLoop.roads[8].road = "sutro_4l_east_04 AI Road 3"
routes.TheDriverLoop.roads[8].direction = "with"
routes.TheDriverLoop.roads[9] = {}
routes.TheDriverLoop.roads[9].road = "sutro_8l_east_04 AI Road 5"
routes.TheDriverLoop.roads[9].direction = "against"
routes.TheDriverLoop.roads[10] = {}
routes.TheDriverLoop.roads[10].road = "sutro_shortcut_e_04 AI Road 1"
routes.TheDriverLoop.roads[10].direction = "with"
routes.TheDriverLoop.roads[11] = {}
routes.TheDriverLoop.roads[11].road = "sutro_6l_south_01b AI Road 2"
routes.TheDriverLoop.roads[11].direction = "with"
routes.TheDriverLoop.roads[12] = {}
routes.TheDriverLoop.roads[12].road = "sutro_shortcut_e_05 AI Road 0"
routes.TheDriverLoop.roads[12].direction = "with"
routes.TheDriverLoop.roads[13] = {}
routes.TheDriverLoop.roads[13].road = "sutro_8l_east_04 AI Road 3"
routes.TheDriverLoop.roads[13].direction = "against"
routes.TheDriverLoop.roads[14] = {}
routes.TheDriverLoop.roads[14].road = "sutro_4l_east_04 AI Road 0"
routes.TheDriverLoop.roads[14].direction = "against"
routes.TheDriverLoop.roads[15] = {}
routes.TheDriverLoop.roads[15].road = "sutro_shortcut_e_06 AI Road 0"
routes.TheDriverLoop.roads[15].direction = "with"
