routes = routes or {}
routes.TheGetawayLoop = {}
routes.TheGetawayLoop.checkpoints = {}
routes.TheGetawayLoop.checkpoints[1] = {}
routes.TheGetawayLoop.checkpoints[1].position = vec.vector(-418.7243, 47.24998, 1486.551, 1)
routes.TheGetawayLoop.checkpoints[1].heading = 0.5349275
routes.TheGetawayLoop.checkpoints[1].roadName = "mt_10l_centre_04 AI Road 0"
routes.TheGetawayLoop.checkpoints[2] = {}
routes.TheGetawayLoop.checkpoints[2].position = vec.vector(-263.2255, 46.33886, 1667.898, 1)
routes.TheGetawayLoop.checkpoints[2].heading = 1.873723
routes.TheGetawayLoop.checkpoints[2].roadName = "dt_10l_south_03 AI Road 7"
routes.TheGetawayLoop.checkpoints[3] = {}
routes.TheGetawayLoop.checkpoints[3].position = vec.vector(-80.33317, 40.80619, 1741.001, 1)
routes.TheGetawayLoop.checkpoints[3].heading = 0.848674
routes.TheGetawayLoop.checkpoints[3].roadName = "r333_shortcut_02 AI Road 0"
routes.TheGetawayLoop.checkpoints[4] = {}
routes.TheGetawayLoop.checkpoints[4].position = vec.vector(37.07067, 40.74998, 1717.097, 1)
routes.TheGetawayLoop.checkpoints[4].heading = -2.553588
routes.TheGetawayLoop.checkpoints[4].roadName = "sanfran_shortcut_02 AI Road 0"
routes.TheGetawayLoop.checkpoints[5] = {}
routes.TheGetawayLoop.checkpoints[5].position = vec.vector(-6.329527, 40.74403, 1584.241, 1)
routes.TheGetawayLoop.checkpoints[5].heading = 1.998212
routes.TheGetawayLoop.checkpoints[5].roadName = "dt_10l_south_03 AI Road 5"
routes.TheGetawayLoop.checkpoints[6] = {}
routes.TheGetawayLoop.checkpoints[6].position = vec.vector(440.5327, 8, 1303.195, 1)
routes.TheGetawayLoop.checkpoints[6].heading = 0.6848945
routes.TheGetawayLoop.checkpoints[6].roadName = "barcelero_alleyway_01 AI Road 0"
routes.TheGetawayLoop.checkpoints[7] = {}
routes.TheGetawayLoop.checkpoints[7].position = vec.vector(549.3677, 6.577719, 1374.766, 1)
routes.TheGetawayLoop.checkpoints[7].heading = 2.289584
routes.TheGetawayLoop.checkpoints[7].roadName = "embargedero_shortcut_02 AI Road 0"
routes.TheGetawayLoop.checkpoints[8] = {}
routes.TheGetawayLoop.checkpoints[8].position = vec.vector(818.3856, 5.975001, 1089.163, 1)
routes.TheGetawayLoop.checkpoints[8].heading = -2.428077
routes.TheGetawayLoop.checkpoints[8].roadName = "embargedero_shortcut_05 AI Road 0"
routes.TheGetawayLoop.checkpoints[9] = {}
routes.TheGetawayLoop.checkpoints[9].position = vec.vector(504.5879, 8.410021, 1089.583, 1)
routes.TheGetawayLoop.checkpoints[9].heading = -1.624457
routes.TheGetawayLoop.checkpoints[9].roadName = "dt_shortcut_02 AI Road 0"
routes.TheGetawayLoop.checkpoints[10] = {}
routes.TheGetawayLoop.checkpoints[10].position = vec.vector(162.3068, 20.27761, 1149.312, 1)
routes.TheGetawayLoop.checkpoints[10].heading = -1.347605
routes.TheGetawayLoop.checkpoints[10].roadName = "dt_shortcut_03b AI Road 1"
routes.TheGetawayLoop.checkpoints[11] = {}
routes.TheGetawayLoop.checkpoints[11].position = vec.vector(-158.7616, 18, 1106.587, 1)
routes.TheGetawayLoop.checkpoints[11].heading = -2.918243
routes.TheGetawayLoop.checkpoints[11].roadName = "dt_10l_centre_02 AI Road 0"
routes.TheGetawayLoop.checkpoints[12] = {}
routes.TheGetawayLoop.checkpoints[12].position = vec.vector(-524.8517, 24.11209, 1147.861, 1)
routes.TheGetawayLoop.checkpoints[12].heading = 0.0778214
routes.TheGetawayLoop.checkpoints[12].roadName = "r361_helper_03 AI Road 0"
routes.TheGetawayLoop.checkpoints[13] = {}
routes.TheGetawayLoop.checkpoints[13].position = vec.vector(-470.0204, 41.57585, 1394.013, 1)
routes.TheGetawayLoop.checkpoints[13].heading = 0.4823064
routes.TheGetawayLoop.checkpoints[13].roadName = "dt_shortcut_19 AI Road 1"
routes.TheGetawayLoop.arrows = {}
routes.TheGetawayLoop.roads = {}
routes.TheGetawayLoop.roads[1] = {}
routes.TheGetawayLoop.roads[1].road = "mt_10l_centre_04 AI Road 0"
routes.TheGetawayLoop.roads[1].direction = "with"
routes.TheGetawayLoop.roads[2] = {}
routes.TheGetawayLoop.roads[2].road = "mt_10l_centre_04 AI Road 1"
routes.TheGetawayLoop.roads[2].direction = "with"
routes.TheGetawayLoop.roads[3] = {}
routes.TheGetawayLoop.roads[3].road = "dt_10l_south_03 AI Road 7"
routes.TheGetawayLoop.roads[3].direction = "against"
routes.TheGetawayLoop.roads[4] = {}
routes.TheGetawayLoop.roads[4].road = "_unnamed road 0x285ef3b6 : 0xa6bf1200 AI Road 0"
routes.TheGetawayLoop.roads[4].direction = "with"
routes.TheGetawayLoop.roads[5] = {}
routes.TheGetawayLoop.roads[5].road = "r333_shortcut_02 AI Road 0"
routes.TheGetawayLoop.roads[5].direction = "with"
routes.TheGetawayLoop.roads[6] = {}
routes.TheGetawayLoop.roads[6].road = "mt_4l_south_03 AI Road 0"
routes.TheGetawayLoop.roads[6].direction = "against"
routes.TheGetawayLoop.roads[7] = {}
routes.TheGetawayLoop.roads[7].road = "sanfran_shortcut_02 AI Road 0"
routes.TheGetawayLoop.roads[7].direction = "against"
routes.TheGetawayLoop.roads[8] = {}
routes.TheGetawayLoop.roads[8].road = "dt_10l_south_03 AI Road 5"
routes.TheGetawayLoop.roads[8].direction = "against"
routes.TheGetawayLoop.roads[9] = {}
routes.TheGetawayLoop.roads[9].road = "dt_10l_south_03 AI Road 4"
routes.TheGetawayLoop.roads[9].direction = "against"
routes.TheGetawayLoop.roads[10] = {}
routes.TheGetawayLoop.roads[10].road = "barcelero_alleyway_01 AI Road 0"
routes.TheGetawayLoop.roads[10].direction = "with"
routes.TheGetawayLoop.roads[11] = {}
routes.TheGetawayLoop.roads[11].road = "embargedero_shortcut_02 AI Road 0"
routes.TheGetawayLoop.roads[11].direction = "with"
routes.TheGetawayLoop.roads[12] = {}
routes.TheGetawayLoop.roads[12].road = "embargedero_shortcut_02 AI Road 1"
routes.TheGetawayLoop.roads[12].direction = "with"
routes.TheGetawayLoop.roads[13] = {}
routes.TheGetawayLoop.roads[13].road = "embargedero_shortcut_05 AI Road 0"
routes.TheGetawayLoop.roads[13].direction = "against"
routes.TheGetawayLoop.roads[14] = {}
routes.TheGetawayLoop.roads[14].road = "dt_10l_south_03 AI Road 1"
routes.TheGetawayLoop.roads[14].direction = "with"
routes.TheGetawayLoop.roads[15] = {}
routes.TheGetawayLoop.roads[15].road = "dt_shortcut_02 AI Road 0"
routes.TheGetawayLoop.roads[15].direction = "against"
routes.TheGetawayLoop.roads[16] = {}
routes.TheGetawayLoop.roads[16].road = "dt_shortcut_03b AI Road 2"
routes.TheGetawayLoop.roads[16].direction = "against"
routes.TheGetawayLoop.roads[17] = {}
routes.TheGetawayLoop.roads[17].road = "dt_shortcut_03b AI Road 1"
routes.TheGetawayLoop.roads[17].direction = "against"
routes.TheGetawayLoop.roads[18] = {}
routes.TheGetawayLoop.roads[18].road = "dt_shortcut_03b AI Road 0"
routes.TheGetawayLoop.roads[18].direction = "against"
routes.TheGetawayLoop.roads[19] = {}
routes.TheGetawayLoop.roads[19].road = "dt_10l_centre_02 AI Road 0"
routes.TheGetawayLoop.roads[19].direction = "against"
routes.TheGetawayLoop.roads[20] = {}
routes.TheGetawayLoop.roads[20].road = "dt_10l_south_01 AI Road 5"
routes.TheGetawayLoop.roads[20].direction = "with"
routes.TheGetawayLoop.roads[21] = {}
routes.TheGetawayLoop.roads[21].road = "dt_10l_south_01 AI Road 6"
routes.TheGetawayLoop.roads[21].direction = "with"
routes.TheGetawayLoop.roads[22] = {}
routes.TheGetawayLoop.roads[22].road = "dt_10l_south_01 AI Road 7"
routes.TheGetawayLoop.roads[22].direction = "with"
routes.TheGetawayLoop.roads[23] = {}
routes.TheGetawayLoop.roads[23].road = "r361_helper_03 AI Road 0"
routes.TheGetawayLoop.roads[23].direction = "with"
routes.TheGetawayLoop.roads[24] = {}
routes.TheGetawayLoop.roads[24].road = "dt_shortcut_19 AI Road 0"
routes.TheGetawayLoop.roads[24].direction = "with"
routes.TheGetawayLoop.roads[25] = {}
routes.TheGetawayLoop.roads[25].road = "dt_shortcut_19 AI Road 1"
routes.TheGetawayLoop.roads[25].direction = "with"
routes.TheGetawayRoute = {}
routes.TheGetawayRoute.checkpoints = {}
routes.TheGetawayRoute.checkpoints[1] = {}
routes.TheGetawayRoute.checkpoints[1].position = vec.vector(-898.8644, 68.59012, 2275.962, 1)
routes.TheGetawayRoute.checkpoints[1].heading = 2.08543
routes.TheGetawayRoute.checkpoints[1].roadName = "mt_4l_west_01 AI Road 3"
routes.TheGetawayRoute.checkpoints[2] = {}
routes.TheGetawayRoute.checkpoints[2].position = vec.vector(-850.6604, 66.95999, 2175.638, 1)
routes.TheGetawayRoute.checkpoints[2].heading = -2.665018
routes.TheGetawayRoute.checkpoints[2].roadName = "dt_4l_west_06 AI Road 1"
routes.TheGetawayRoute.checkpoints[3] = {}
routes.TheGetawayRoute.checkpoints[3].position = vec.vector(-900.6552, 66.60154, 1994.643, 1)
routes.TheGetawayRoute.checkpoints[3].heading = 2.034956
routes.TheGetawayRoute.checkpoints[3].roadName = "dt_shortcut_25 AI Road 0"
routes.TheGetawayRoute.checkpoints[4] = {}
routes.TheGetawayRoute.checkpoints[4].position = vec.vector(-738.0029, 52.83129, 1687.886, 1)
routes.TheGetawayRoute.checkpoints[4].heading = -2.656209
routes.TheGetawayRoute.checkpoints[4].roadName = "mt_6l_w_04 AI Road 1"
routes.TheGetawayRoute.checkpoints[5] = {}
routes.TheGetawayRoute.checkpoints[5].position = vec.vector(-475.9285, 47.24998, 1468.937, 1)
routes.TheGetawayRoute.checkpoints[5].heading = 1.697363
routes.TheGetawayRoute.checkpoints[5].roadName = "mt_10l_north_01a AI Road 5"
routes.TheGetawayRoute.arrows = {}
routes.TheGetawayRoute.roads = {}
routes.TheGetawayRoute.roads[1] = {}
routes.TheGetawayRoute.roads[1].road = "mt_4l_west_01 AI Road 3"
routes.TheGetawayRoute.roads[1].direction = "against"
routes.TheGetawayRoute.roads[2] = {}
routes.TheGetawayRoute.roads[2].road = "dt_4l_west_06 AI Road 1"
routes.TheGetawayRoute.roads[2].direction = "against"
routes.TheGetawayRoute.roads[3] = {}
routes.TheGetawayRoute.roads[3].road = "dt_4l_west_06 AI Road 0"
routes.TheGetawayRoute.roads[3].direction = "against"
routes.TheGetawayRoute.roads[4] = {}
routes.TheGetawayRoute.roads[4].road = "dt_shortcut_25 AI Road 0"
routes.TheGetawayRoute.roads[4].direction = "with"
routes.TheGetawayRoute.roads[5] = {}
routes.TheGetawayRoute.roads[5].road = "mt_6l_w_04 AI Road 2"
routes.TheGetawayRoute.roads[5].direction = "against"
routes.TheGetawayRoute.roads[6] = {}
routes.TheGetawayRoute.roads[6].road = "mt_6l_w_04 AI Road 1"
routes.TheGetawayRoute.roads[6].direction = "against"
routes.TheGetawayRoute.roads[7] = {}
routes.TheGetawayRoute.roads[7].road = "mt_6l_w_04 AI Road 0"
routes.TheGetawayRoute.roads[7].direction = "against"
routes.TheGetawayRoute.roads[8] = {}
routes.TheGetawayRoute.roads[8].road = "mt_10l_north_01a AI Road 4"
routes.TheGetawayRoute.roads[8].direction = "with"
routes.TheGetawayRoute.roads[9] = {}
routes.TheGetawayRoute.roads[9].road = "mt_10l_north_01a AI Road 5"
routes.TheGetawayRoute.roads[9].direction = "with"
