routes = routes or {}
routes.Uplaych3Route = {}
routes.Uplaych3Route.checkpoints = {}
routes.Uplaych3Route.checkpoints[1] = {}
routes.Uplaych3Route.checkpoints[1].position = vec.vector(-3128.409, 65.55931, -475.5573, 1)
routes.Uplaych3Route.checkpoints[1].heading = 2.966293
routes.Uplaych3Route.checkpoints[1].roadName = "highway01_15 AI Road 7"
routes.Uplaych3Route.arrows = {}
routes.Uplaych3Route.roads = {}
routes.Uplaych3Route.roads[1] = {}
routes.Uplaych3Route.roads[1].road = "mt_6l_centre_04 AI Road 6"
routes.Uplaych3Route.roads[1].direction = "against"
routes.Uplaych3Route.roads[2] = {}
routes.Uplaych3Route.roads[2].road = "mt_6l_centre_01 AI Road 6"
routes.Uplaych3Route.roads[2].direction = "against"
routes.Uplaych3Route.roads[3] = {}
routes.Uplaych3Route.roads[3].road = "mt_6l_centre_01 AI Road 5"
routes.Uplaych3Route.roads[3].direction = "against"
routes.Uplaych3Route.roads[4] = {}
routes.Uplaych3Route.roads[4].road = "mt_10l_centre_01 AI Road 0"
routes.Uplaych3Route.roads[4].direction = "against"
routes.Uplaych3Route.roads[5] = {}
routes.Uplaych3Route.roads[5].road = "mt_10l_centre_04 AI Road 2"
routes.Uplaych3Route.roads[5].direction = "against"
routes.Uplaych3Route.roads[6] = {}
routes.Uplaych3Route.roads[6].road = "dt_10l_south_02b AI Road 9"
routes.Uplaych3Route.roads[6].direction = "against"
routes.Uplaych3Route.roads[7] = {}
routes.Uplaych3Route.roads[7].road = "dt_10l_south_02b AI Road 8"
routes.Uplaych3Route.roads[7].direction = "against"
routes.Uplaych3Route.roads[8] = {}
routes.Uplaych3Route.roads[8].road = "mt_sliproad_02 AI Road 0"
routes.Uplaych3Route.roads[8].direction = "against"
routes.Uplaych3Route.roads[9] = {}
routes.Uplaych3Route.roads[9].road = "highway01_16b AI Road 2"
routes.Uplaych3Route.roads[9].direction = "against"
routes.Uplaych3Route.roads[10] = {}
routes.Uplaych3Route.roads[10].road = "highway01_16b AI Road 1"
routes.Uplaych3Route.roads[10].direction = "against"
routes.Uplaych3Route.roads[11] = {}
routes.Uplaych3Route.roads[11].road = "highway01_16b AI Road 0"
routes.Uplaych3Route.roads[11].direction = "against"
routes.Uplaych3Route.roads[12] = {}
routes.Uplaych3Route.roads[12].road = "highway_split_sanfran_01 AI Road 0"
routes.Uplaych3Route.roads[12].direction = "with"
routes.Uplaych3Route.roads[13] = {}
routes.Uplaych3Route.roads[13].road = "highway_split_sanfran_01 AI Road 1"
routes.Uplaych3Route.roads[13].direction = "with"
routes.Uplaych3Route.roads[14] = {}
routes.Uplaych3Route.roads[14].road = "highway_split_sanfran_01 AI Road 2"
routes.Uplaych3Route.roads[14].direction = "with"
routes.Uplaych3Route.roads[15] = {}
routes.Uplaych3Route.roads[15].road = "highway_split_sanfran_01 AI Road 3"
routes.Uplaych3Route.roads[15].direction = "with"
routes.Uplaych3Route.roads[16] = {}
routes.Uplaych3Route.roads[16].road = "highway_split_sanfran_01 AI Road 4"
routes.Uplaych3Route.roads[16].direction = "with"
routes.Uplaych3Route.roads[17] = {}
routes.Uplaych3Route.roads[17].road = "highway_split_sanfran_01 AI Road 5"
routes.Uplaych3Route.roads[17].direction = "with"
routes.Uplaych3Route.roads[18] = {}
routes.Uplaych3Route.roads[18].road = "highway01_15 AI Road 0"
routes.Uplaych3Route.roads[18].direction = "with"
routes.Uplaych3Route.roads[19] = {}
routes.Uplaych3Route.roads[19].road = "highway01_15 AI Road 1"
routes.Uplaych3Route.roads[19].direction = "with"
routes.Uplaych3Route.roads[20] = {}
routes.Uplaych3Route.roads[20].road = "highway01_15 AI Road 2"
routes.Uplaych3Route.roads[20].direction = "with"
routes.Uplaych3Route.roads[21] = {}
routes.Uplaych3Route.roads[21].road = "highway01_15 AI Road 3"
routes.Uplaych3Route.roads[21].direction = "with"
routes.Uplaych3Route.roads[22] = {}
routes.Uplaych3Route.roads[22].road = "highway01_15 AI Road 4"
routes.Uplaych3Route.roads[22].direction = "with"
routes.Uplaych3Route.roads[23] = {}
routes.Uplaych3Route.roads[23].road = "highway01_15 AI Road 5"
routes.Uplaych3Route.roads[23].direction = "with"
routes.Uplaych3Route.roads[24] = {}
routes.Uplaych3Route.roads[24].road = "highway01_15 AI Road 6"
routes.Uplaych3Route.roads[24].direction = "with"
routes.Uplaych3Route.roads[25] = {}
routes.Uplaych3Route.roads[25].road = "highway01_15 AI Road 7"
routes.Uplaych3Route.roads[25].direction = "with"
