routes = routes or {}
routes["Final fight jericho escape route"] = {}
routes["Final fight jericho escape route"].checkpoints = {}
routes["Final fight jericho escape route"].checkpoints[1] = {}
routes["Final fight jericho escape route"].checkpoints[1].position = vec.vector(238.6696, 17.90204, 987.2465, 1)
routes["Final fight jericho escape route"].checkpoints[1].heading = 1.688383
routes["Final fight jericho escape route"].checkpoints[1].roadName = "dt_10l_south_01 AI Road 2"
routes["Final fight jericho escape route"].checkpoints[2] = {}
routes["Final fight jericho escape route"].checkpoints[2].position = vec.vector(1114.046, 5.974995, 669.3826, 1)
routes["Final fight jericho escape route"].checkpoints[2].heading = 2.253636
routes["Final fight jericho escape route"].checkpoints[2].roadName = "dt_10l_east_01 AI Road 11"
routes["Final fight jericho escape route"].checkpoints[3] = {}
routes["Final fight jericho escape route"].checkpoints[3].position = vec.vector(795.9921, 6.590937, -56.28732, 1)
routes["Final fight jericho escape route"].checkpoints[3].heading = -2.299633
routes["Final fight jericho escape route"].checkpoints[3].roadName = "dt_10l_east_01 AI Road 8"
routes["Final fight jericho escape route"].checkpoints[4] = {}
routes["Final fight jericho escape route"].checkpoints[4].position = vec.vector(-304.5471, 3.535175, -237.1736, 1)
routes["Final fight jericho escape route"].checkpoints[4].heading = -1.40128
routes["Final fight jericho escape route"].checkpoints[4].roadName = "dt_10l_east_01 AI Road 3"
routes["Final fight jericho escape route"].checkpoints[5] = {}
routes["Final fight jericho escape route"].checkpoints[5].position = vec.vector(-1791.351, 4.999999, -203.6178, 1)
routes["Final fight jericho escape route"].checkpoints[5].heading = -1.724464
routes["Final fight jericho escape route"].checkpoints[5].roadName = "ggp_8l_north_03 AI Road 1"
routes["Final fight jericho escape route"].checkpoints[6] = {}
routes["Final fight jericho escape route"].checkpoints[6].position = vec.vector(-3375.786, 9.436087, -51.85445, 1)
routes["Final fight jericho escape route"].checkpoints[6].heading = -0.3596632
routes["Final fight jericho escape route"].checkpoints[6].roadName = "ggp_8l_west_01 AI Road 6"
routes["Final fight jericho escape route"].checkpoints[7] = {}
routes["Final fight jericho escape route"].checkpoints[7].position = vec.vector(-4367.562, 27.75007, 998.6981, 1)
routes["Final fight jericho escape route"].checkpoints[7].heading = -0.6616697
routes["Final fight jericho escape route"].checkpoints[7].roadName = "ggp_8l_west_01 AI Road 0"
routes["Final fight jericho escape route"].checkpoints[8] = {}
routes["Final fight jericho escape route"].checkpoints[8].position = vec.vector(-1740.281, 51.71817, 1245.961, 1)
routes["Final fight jericho escape route"].checkpoints[8].heading = 1.739894
routes["Final fight jericho escape route"].checkpoints[8].roadName = "dt_10l_south_01 AI Road 15"
routes["Final fight jericho escape route"].checkpoints[9] = {}
routes["Final fight jericho escape route"].checkpoints[9].position = vec.vector(-947.8689, 40.75, 1127.376, 1)
routes["Final fight jericho escape route"].checkpoints[9].heading = 1.692098
routes["Final fight jericho escape route"].checkpoints[9].roadName = "dt_10l_south_01 AI Road 11"
routes["Final fight jericho escape route"].checkpoints[10] = {}
routes["Final fight jericho escape route"].checkpoints[10].position = vec.vector(110.4929, 17.99261, 1002.83, 1)
routes["Final fight jericho escape route"].checkpoints[10].heading = 1.712846
routes["Final fight jericho escape route"].checkpoints[10].roadName = "dt_10l_south_01 AI Road 3"
routes["Final fight jericho escape route"].arrows = {}
routes["Final fight jericho escape route"].roads = {}
routes["Final fight jericho escape route"].roads[1] = {}
routes["Final fight jericho escape route"].roads[1].road = "dt_10l_south_01 AI Road 2"
routes["Final fight jericho escape route"].roads[1].direction = "against"
routes["Final fight jericho escape route"].roads[2] = {}
routes["Final fight jericho escape route"].roads[2].road = "dt_10l_south_01 AI Road 1"
routes["Final fight jericho escape route"].roads[2].direction = "against"
routes["Final fight jericho escape route"].roads[3] = {}
routes["Final fight jericho escape route"].roads[3].road = "dt_10l_south_01 AI Road 0"
routes["Final fight jericho escape route"].roads[3].direction = "against"
routes["Final fight jericho escape route"].roads[4] = {}
routes["Final fight jericho escape route"].roads[4].road = "dt_10l_east_01 AI Road 14"
routes["Final fight jericho escape route"].roads[4].direction = "against"
routes["Final fight jericho escape route"].roads[5] = {}
routes["Final fight jericho escape route"].roads[5].road = "dt_10l_east_01 AI Road 13"
routes["Final fight jericho escape route"].roads[5].direction = "against"
routes["Final fight jericho escape route"].roads[6] = {}
routes["Final fight jericho escape route"].roads[6].road = "dt_10l_east_01 AI Road 12"
routes["Final fight jericho escape route"].roads[6].direction = "against"
routes["Final fight jericho escape route"].roads[7] = {}
routes["Final fight jericho escape route"].roads[7].road = "dt_10l_east_01 AI Road 11"
routes["Final fight jericho escape route"].roads[7].direction = "against"
routes["Final fight jericho escape route"].roads[8] = {}
routes["Final fight jericho escape route"].roads[8].road = "dt_10l_east_01 AI Road 10"
routes["Final fight jericho escape route"].roads[8].direction = "against"
routes["Final fight jericho escape route"].roads[9] = {}
routes["Final fight jericho escape route"].roads[9].road = "dt_10l_east_01 AI Road 9"
routes["Final fight jericho escape route"].roads[9].direction = "against"
routes["Final fight jericho escape route"].roads[10] = {}
routes["Final fight jericho escape route"].roads[10].road = "dt_10l_east_01 AI Road 8"
routes["Final fight jericho escape route"].roads[10].direction = "against"
routes["Final fight jericho escape route"].roads[11] = {}
routes["Final fight jericho escape route"].roads[11].road = "dt_10l_east_01 AI Road 7"
routes["Final fight jericho escape route"].roads[11].direction = "against"
routes["Final fight jericho escape route"].roads[12] = {}
routes["Final fight jericho escape route"].roads[12].road = "dt_10l_east_01 AI Road 6"
routes["Final fight jericho escape route"].roads[12].direction = "against"
routes["Final fight jericho escape route"].roads[13] = {}
routes["Final fight jericho escape route"].roads[13].road = "dt_10l_east_01 AI Road 5"
routes["Final fight jericho escape route"].roads[13].direction = "against"
routes["Final fight jericho escape route"].roads[14] = {}
routes["Final fight jericho escape route"].roads[14].road = "dt_10l_east_01 AI Road 4"
routes["Final fight jericho escape route"].roads[14].direction = "against"
routes["Final fight jericho escape route"].roads[15] = {}
routes["Final fight jericho escape route"].roads[15].road = "dt_10l_east_01 AI Road 3"
routes["Final fight jericho escape route"].roads[15].direction = "against"
routes["Final fight jericho escape route"].roads[16] = {}
routes["Final fight jericho escape route"].roads[16].road = "dt_10l_east_01 AI Road 2"
routes["Final fight jericho escape route"].roads[16].direction = "against"
routes["Final fight jericho escape route"].roads[17] = {}
routes["Final fight jericho escape route"].roads[17].road = "dt_10l_east_01 AI Road 1"
routes["Final fight jericho escape route"].roads[17].direction = "against"
routes["Final fight jericho escape route"].roads[18] = {}
routes["Final fight jericho escape route"].roads[18].road = "dt_10l_east_01 AI Road 0"
routes["Final fight jericho escape route"].roads[18].direction = "against"
routes["Final fight jericho escape route"].roads[19] = {}
routes["Final fight jericho escape route"].roads[19].road = "dt_8l_north_04 AI Road 2"
routes["Final fight jericho escape route"].roads[19].direction = "against"
routes["Final fight jericho escape route"].roads[20] = {}
routes["Final fight jericho escape route"].roads[20].road = "dt_8l_north_04 AI Road 1"
routes["Final fight jericho escape route"].roads[20].direction = "against"
routes["Final fight jericho escape route"].roads[21] = {}
routes["Final fight jericho escape route"].roads[21].road = "ggp_8l_north_03 AI Road 1"
routes["Final fight jericho escape route"].roads[21].direction = "against"
routes["Final fight jericho escape route"].roads[22] = {}
routes["Final fight jericho escape route"].roads[22].road = "ggp_8l_north_03 AI Road 0"
routes["Final fight jericho escape route"].roads[22].direction = "against"
routes["Final fight jericho escape route"].roads[23] = {}
routes["Final fight jericho escape route"].roads[23].road = "ggp_8l_west_01 AI Road 10"
routes["Final fight jericho escape route"].roads[23].direction = "against"
routes["Final fight jericho escape route"].roads[24] = {}
routes["Final fight jericho escape route"].roads[24].road = "ggp_8l_west_01 AI Road 9"
routes["Final fight jericho escape route"].roads[24].direction = "against"
routes["Final fight jericho escape route"].roads[25] = {}
routes["Final fight jericho escape route"].roads[25].road = "ggp_8l_west_01 AI Road 8"
routes["Final fight jericho escape route"].roads[25].direction = "against"
routes["Final fight jericho escape route"].roads[26] = {}
routes["Final fight jericho escape route"].roads[26].road = "ggp_8l_west_01 AI Road 7"
routes["Final fight jericho escape route"].roads[26].direction = "against"
routes["Final fight jericho escape route"].roads[27] = {}
routes["Final fight jericho escape route"].roads[27].road = "ggp_8l_west_01 AI Road 6"
routes["Final fight jericho escape route"].roads[27].direction = "against"
routes["Final fight jericho escape route"].roads[28] = {}
routes["Final fight jericho escape route"].roads[28].road = "ggp_8l_west_01 AI Road 5"
routes["Final fight jericho escape route"].roads[28].direction = "against"
routes["Final fight jericho escape route"].roads[29] = {}
routes["Final fight jericho escape route"].roads[29].road = "ggp_8l_west_01 AI Road 4"
routes["Final fight jericho escape route"].roads[29].direction = "against"
routes["Final fight jericho escape route"].roads[30] = {}
routes["Final fight jericho escape route"].roads[30].road = "ggp_8l_west_01 AI Road 3"
routes["Final fight jericho escape route"].roads[30].direction = "against"
routes["Final fight jericho escape route"].roads[31] = {}
routes["Final fight jericho escape route"].roads[31].road = "ggp_8l_west_01 AI Road 2"
routes["Final fight jericho escape route"].roads[31].direction = "against"
routes["Final fight jericho escape route"].roads[32] = {}
routes["Final fight jericho escape route"].roads[32].road = "ggp_8l_west_01 AI Road 1"
routes["Final fight jericho escape route"].roads[32].direction = "against"
routes["Final fight jericho escape route"].roads[33] = {}
routes["Final fight jericho escape route"].roads[33].road = "ggp_8l_west_01 AI Road 0"
routes["Final fight jericho escape route"].roads[33].direction = "against"
routes["Final fight jericho escape route"].roads[34] = {}
routes["Final fight jericho escape route"].roads[34].road = "ggp_10l_centre_01 AI Road 0"
routes["Final fight jericho escape route"].roads[34].direction = "with"
routes["Final fight jericho escape route"].roads[35] = {}
routes["Final fight jericho escape route"].roads[35].road = "ggp_10l_centre_01 AI Road 1"
routes["Final fight jericho escape route"].roads[35].direction = "with"
routes["Final fight jericho escape route"].roads[36] = {}
routes["Final fight jericho escape route"].roads[36].road = "ggp_10l_centre_01 AI Road 2"
routes["Final fight jericho escape route"].roads[36].direction = "with"
routes["Final fight jericho escape route"].roads[37] = {}
routes["Final fight jericho escape route"].roads[37].road = "ggp_10l_centre_01 AI Road 3"
routes["Final fight jericho escape route"].roads[37].direction = "with"
routes["Final fight jericho escape route"].roads[38] = {}
routes["Final fight jericho escape route"].roads[38].road = "ggp_10l_centre_01 AI Road 4"
routes["Final fight jericho escape route"].roads[38].direction = "with"
routes["Final fight jericho escape route"].roads[39] = {}
routes["Final fight jericho escape route"].roads[39].road = "ggp_10l_centre_01 AI Road 5"
routes["Final fight jericho escape route"].roads[39].direction = "with"
routes["Final fight jericho escape route"].roads[40] = {}
routes["Final fight jericho escape route"].roads[40].road = "ggp_10l_centre_01 AI Road 6"
routes["Final fight jericho escape route"].roads[40].direction = "with"
routes["Final fight jericho escape route"].roads[41] = {}
routes["Final fight jericho escape route"].roads[41].road = "ggp_10l_centre_01 AI Road 7"
routes["Final fight jericho escape route"].roads[41].direction = "with"
routes["Final fight jericho escape route"].roads[42] = {}
routes["Final fight jericho escape route"].roads[42].road = "ggp_10l_centre_01 AI Road 8"
routes["Final fight jericho escape route"].roads[42].direction = "with"
routes["Final fight jericho escape route"].roads[43] = {}
routes["Final fight jericho escape route"].roads[43].road = "dt_10l_south_01 AI Road 18"
routes["Final fight jericho escape route"].roads[43].direction = "against"
routes["Final fight jericho escape route"].roads[44] = {}
routes["Final fight jericho escape route"].roads[44].road = "dt_10l_south_01 AI Road 17"
routes["Final fight jericho escape route"].roads[44].direction = "against"
routes["Final fight jericho escape route"].roads[45] = {}
routes["Final fight jericho escape route"].roads[45].road = "dt_10l_south_01 AI Road 16"
routes["Final fight jericho escape route"].roads[45].direction = "against"
routes["Final fight jericho escape route"].roads[46] = {}
routes["Final fight jericho escape route"].roads[46].road = "dt_10l_south_01 AI Road 15"
routes["Final fight jericho escape route"].roads[46].direction = "against"
routes["Final fight jericho escape route"].roads[47] = {}
routes["Final fight jericho escape route"].roads[47].road = "dt_10l_south_01 AI Road 14"
routes["Final fight jericho escape route"].roads[47].direction = "against"
routes["Final fight jericho escape route"].roads[48] = {}
routes["Final fight jericho escape route"].roads[48].road = "dt_10l_south_01 AI Road 13"
routes["Final fight jericho escape route"].roads[48].direction = "against"
routes["Final fight jericho escape route"].roads[49] = {}
routes["Final fight jericho escape route"].roads[49].road = "dt_10l_south_01 AI Road 12"
routes["Final fight jericho escape route"].roads[49].direction = "against"
routes["Final fight jericho escape route"].roads[50] = {}
routes["Final fight jericho escape route"].roads[50].road = "dt_10l_south_01 AI Road 11"
routes["Final fight jericho escape route"].roads[50].direction = "against"
routes["Final fight jericho escape route"].roads[51] = {}
routes["Final fight jericho escape route"].roads[51].road = "dt_10l_south_01 AI Road 10"
routes["Final fight jericho escape route"].roads[51].direction = "against"
routes["Final fight jericho escape route"].roads[52] = {}
routes["Final fight jericho escape route"].roads[52].road = "dt_10l_south_01 AI Road 9"
routes["Final fight jericho escape route"].roads[52].direction = "against"
routes["Final fight jericho escape route"].roads[53] = {}
routes["Final fight jericho escape route"].roads[53].road = "dt_10l_south_01 AI Road 8"
routes["Final fight jericho escape route"].roads[53].direction = "against"
routes["Final fight jericho escape route"].roads[54] = {}
routes["Final fight jericho escape route"].roads[54].road = "dt_10l_south_01 AI Road 7"
routes["Final fight jericho escape route"].roads[54].direction = "against"
routes["Final fight jericho escape route"].roads[55] = {}
routes["Final fight jericho escape route"].roads[55].road = "dt_10l_south_01 AI Road 6"
routes["Final fight jericho escape route"].roads[55].direction = "against"
routes["Final fight jericho escape route"].roads[56] = {}
routes["Final fight jericho escape route"].roads[56].road = "dt_10l_south_01 AI Road 5"
routes["Final fight jericho escape route"].roads[56].direction = "against"
routes["Final fight jericho escape route"].roads[57] = {}
routes["Final fight jericho escape route"].roads[57].road = "dt_10l_south_01 AI Road 4"
routes["Final fight jericho escape route"].roads[57].direction = "against"
routes["Final fight jericho escape route"].roads[58] = {}
routes["Final fight jericho escape route"].roads[58].road = "dt_10l_south_01 AI Road 3"
routes["Final fight jericho escape route"].roads[58].direction = "against"
