routes = routes or {}
routes["Felony lure warmup"] = {}
routes["Felony lure warmup"].checkpoints = {}
routes["Felony lure warmup"].checkpoints[1] = {}
routes["Felony lure warmup"].checkpoints[1].position = vec.vector(1105.946, 5.974995, 675.9121, 1)
routes["Felony lure warmup"].checkpoints[1].heading = -0.8933522
routes["Felony lure warmup"].checkpoints[1].roadName = "dt_10l_east_01 AI Road 11"
routes["Felony lure warmup"].checkpoints[2] = {}
routes["Felony lure warmup"].checkpoints[2].position = vec.vector(811.4128, 18.29649, 598.4586, 1)
routes["Felony lure warmup"].checkpoints[2].heading = -2.756795
routes["Felony lure warmup"].checkpoints[2].roadName = "dt_6l_east_01 AI Road 3"
routes["Felony lure warmup"].checkpoints[3] = {}
routes["Felony lure warmup"].checkpoints[3].position = vec.vector(831.258, 10.31445, 199.1681, 1)
routes["Felony lure warmup"].checkpoints[3].heading = 1.694584
routes["Felony lure warmup"].checkpoints[3].roadName = "dt_4l_east_01 AI Road 0"
routes["Felony lure warmup"].checkpoints[4] = {}
routes["Felony lure warmup"].checkpoints[4].position = vec.vector(1119.487, 5.975, 528.3156, 1)
routes["Felony lure warmup"].checkpoints[4].heading = 0.3659398
routes["Felony lure warmup"].checkpoints[4].roadName = "dt_10l_east_01 AI Road 10"
routes["Felony lure warmup"].arrows = {}
routes["Felony lure warmup"].roads = {}
routes["Felony lure warmup"].roads[1] = {}
routes["Felony lure warmup"].roads[1].road = "dt_10l_east_01 AI Road 11"
routes["Felony lure warmup"].roads[1].direction = "with"
routes["Felony lure warmup"].roads[2] = {}
routes["Felony lure warmup"].roads[2].road = "dt_10l_east_01 AI Road 12"
routes["Felony lure warmup"].roads[2].direction = "with"
routes["Felony lure warmup"].roads[3] = {}
routes["Felony lure warmup"].roads[3].road = "dt_6l_east_01 AI Road 4"
routes["Felony lure warmup"].roads[3].direction = "against"
routes["Felony lure warmup"].roads[4] = {}
routes["Felony lure warmup"].roads[4].road = "dt_6l_east_01 AI Road 3"
routes["Felony lure warmup"].roads[4].direction = "against"
routes["Felony lure warmup"].roads[5] = {}
routes["Felony lure warmup"].roads[5].road = "dt_6l_east_01 AI Road 2"
routes["Felony lure warmup"].roads[5].direction = "against"
routes["Felony lure warmup"].roads[6] = {}
routes["Felony lure warmup"].roads[6].road = "dt_4l_east_01 AI Road 0"
routes["Felony lure warmup"].roads[6].direction = "with"
routes["Felony lure warmup"].roads[7] = {}
routes["Felony lure warmup"].roads[7].road = "dt_10l_east_01 AI Road 9"
routes["Felony lure warmup"].roads[7].direction = "with"
routes["Felony lure warmup"].roads[8] = {}
routes["Felony lure warmup"].roads[8].road = "dt_10l_east_01 AI Road 10"
routes["Felony lure warmup"].roads[8].direction = "with"
