routes = routes or {}
routes["Final destination route"] = {}
routes["Final destination route"].checkpoints = {}
routes["Final destination route"].checkpoints[1] = {}
routes["Final destination route"].checkpoints[1].position = vec.vector(-2545.695, 35, 336.5477, 1)
routes["Final destination route"].checkpoints[1].heading = -0.3647603
routes["Final destination route"].checkpoints[1].roadName = "ggp_4l_nw_14 AI Road 1"
routes["Final destination route"].checkpoints[2] = {}
routes["Final destination route"].checkpoints[2].position = vec.vector(-2324.202, 64.74528, 1109.406, 1)
routes["Final destination route"].checkpoints[2].heading = 1.706879
routes["Final destination route"].checkpoints[2].roadName = "ggp_4l_nw_09 AI Road 1"
routes["Final destination route"].checkpoints[3] = {}
routes["Final destination route"].checkpoints[3].position = vec.vector(-2270.717, 48.05074, 684.1364, 1)
routes["Final destination route"].checkpoints[3].heading = 2.977483
routes["Final destination route"].checkpoints[3].roadName = "ggp_8l_ne_02 AI Road 1"
routes["Final destination route"].checkpoints[4] = {}
routes["Final destination route"].checkpoints[4].position = vec.vector(-2446.419, 22.72822, 75.94799, 1)
routes["Final destination route"].checkpoints[4].heading = -0.3560051
routes["Final destination route"].checkpoints[4].roadName = "ggp_4l_nw_14 AI Road 0"
routes["Final destination route"].arrows = {}
routes["Final destination route"].roads = {}
routes["Final destination route"].roads[1] = {}
routes["Final destination route"].roads[1].road = "ggp_4l_nw_14 AI Road 1"
routes["Final destination route"].roads[1].direction = "with"
routes["Final destination route"].roads[2] = {}
routes["Final destination route"].roads[2].road = "ggp_4l_nw_13 AI Road 0"
routes["Final destination route"].roads[2].direction = "with"
routes["Final destination route"].roads[3] = {}
routes["Final destination route"].roads[3].road = "ggp_4l_nw_13 AI Road 1"
routes["Final destination route"].roads[3].direction = "with"
routes["Final destination route"].roads[4] = {}
routes["Final destination route"].roads[4].road = "ggp_4l_nw_13 AI Road 2"
routes["Final destination route"].roads[4].direction = "with"
routes["Final destination route"].roads[5] = {}
routes["Final destination route"].roads[5].road = "ggp_4l_nw_13 AI Road 3"
routes["Final destination route"].roads[5].direction = "with"
routes["Final destination route"].roads[6] = {}
routes["Final destination route"].roads[6].road = "ggp_4l_nw_09 AI Road 1"
routes["Final destination route"].roads[6].direction = "with"
routes["Final destination route"].roads[7] = {}
routes["Final destination route"].roads[7].road = "ggp_8l_ne_02 AI Road 3"
routes["Final destination route"].roads[7].direction = "against"
routes["Final destination route"].roads[8] = {}
routes["Final destination route"].roads[8].road = "ggp_8l_ne_02 AI Road 2"
routes["Final destination route"].roads[8].direction = "against"
routes["Final destination route"].roads[9] = {}
routes["Final destination route"].roads[9].road = "ggp_8l_ne_02 AI Road 1"
routes["Final destination route"].roads[9].direction = "against"
routes["Final destination route"].roads[10] = {}
routes["Final destination route"].roads[10].road = "ggp_8l_ne_02 AI Road 0"
routes["Final destination route"].roads[10].direction = "against"
routes["Final destination route"].roads[11] = {}
routes["Final destination route"].roads[11].road = "ggp_8l_ne_01 AI Road 0"
routes["Final destination route"].roads[11].direction = "with"
routes["Final destination route"].roads[12] = {}
routes["Final destination route"].roads[12].road = "ggp_8l_ne_01 AI Road 1"
routes["Final destination route"].roads[12].direction = "with"
routes["Final destination route"].roads[13] = {}
routes["Final destination route"].roads[13].road = "ggp_4l_nw_18 AI Road 0"
routes["Final destination route"].roads[13].direction = "against"
routes["Final destination route"].roads[14] = {}
routes["Final destination route"].roads[14].road = "ggp_4l_nw_14 AI Road 0"
routes["Final destination route"].roads[14].direction = "with"
