routes = routes or {}
routes.SpeedRaceWarmUpRoute = {}
routes.SpeedRaceWarmUpRoute.checkpoints = {}
routes.SpeedRaceWarmUpRoute.checkpoints[1] = {}
routes.SpeedRaceWarmUpRoute.checkpoints[1].position = vec.vector(-1110.618, 165.2912, 3911.353, 1)
routes.SpeedRaceWarmUpRoute.checkpoints[1].heading = 1.11798
routes.SpeedRaceWarmUpRoute.checkpoints[1].roadName = "sanfran_shortcut_27 AI Road 0"
routes.SpeedRaceWarmUpRoute.checkpoints[2] = {}
routes.SpeedRaceWarmUpRoute.checkpoints[2].position = vec.vector(-317.9247, 77.5, 4060.778, 1)
routes.SpeedRaceWarmUpRoute.checkpoints[2].heading = -0.4276923
routes.SpeedRaceWarmUpRoute.checkpoints[2].roadName = "sanfran_shortcut_27 AI Road 1"
routes.SpeedRaceWarmUpRoute.checkpoints[3] = {}
routes.SpeedRaceWarmUpRoute.checkpoints[3].position = vec.vector(-425.7673, 97.61214, 4452.191, 1)
routes.SpeedRaceWarmUpRoute.checkpoints[3].heading = -1.901822
routes.SpeedRaceWarmUpRoute.checkpoints[3].roadName = "sanfran_shortcut_27 AI Road 2"
routes.SpeedRaceWarmUpRoute.checkpoints[4] = {}
routes.SpeedRaceWarmUpRoute.checkpoints[4].position = vec.vector(-908.688, 173.5193, 4496.51, 1)
routes.SpeedRaceWarmUpRoute.checkpoints[4].heading = -1.496028
routes.SpeedRaceWarmUpRoute.checkpoints[4].roadName = "sanfran_shortcut_27 AI Road 4"
routes.SpeedRaceWarmUpRoute.checkpoints[5] = {}
routes.SpeedRaceWarmUpRoute.checkpoints[5].position = vec.vector(-1309.894, 169.6304, 3934.072, 1)
routes.SpeedRaceWarmUpRoute.checkpoints[5].heading = 2.261828
routes.SpeedRaceWarmUpRoute.checkpoints[5].roadName = "marin_shortcut_23 AI Road 1"
routes.SpeedRaceWarmUpRoute.arrows = {}
routes.SpeedRaceWarmUpRoute.roads = {}
routes.SpeedRaceWarmUpRoute.roads[1] = {}
routes.SpeedRaceWarmUpRoute.roads[1].road = "sanfran_shortcut_27 AI Road 0"
routes.SpeedRaceWarmUpRoute.roads[1].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[2] = {}
routes.SpeedRaceWarmUpRoute.roads[2].road = "sanfran_shortcut_27 AI Road 1"
routes.SpeedRaceWarmUpRoute.roads[2].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[3] = {}
routes.SpeedRaceWarmUpRoute.roads[3].road = "sanfran_shortcut_27 AI Road 2"
routes.SpeedRaceWarmUpRoute.roads[3].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[4] = {}
routes.SpeedRaceWarmUpRoute.roads[4].road = "sutro_dukes_of_hazard AI Road 0"
routes.SpeedRaceWarmUpRoute.roads[4].direction = "against"
routes.SpeedRaceWarmUpRoute.roads[5] = {}
routes.SpeedRaceWarmUpRoute.roads[5].road = "sanfran_shortcut_27 AI Road 4"
routes.SpeedRaceWarmUpRoute.roads[5].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[6] = {}
routes.SpeedRaceWarmUpRoute.roads[6].road = "sanfran_shortcut_27 AI Road 5"
routes.SpeedRaceWarmUpRoute.roads[6].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[7] = {}
routes.SpeedRaceWarmUpRoute.roads[7].road = "sanfran_shortcut_27 AI Road 6"
routes.SpeedRaceWarmUpRoute.roads[7].direction = "with"
routes.SpeedRaceWarmUpRoute.roads[8] = {}
routes.SpeedRaceWarmUpRoute.roads[8].road = "marin_shortcut_23 AI Road 1"
routes.SpeedRaceWarmUpRoute.roads[8].direction = "with"
