routes = routes or {}
routes.InTheNickOfTimeMissionRoute = {}
routes.InTheNickOfTimeMissionRoute.checkpoints = {}
routes.InTheNickOfTimeMissionRoute.checkpoints[1] = {}
routes.InTheNickOfTimeMissionRoute.checkpoints[1].position = vec.vector(-962.0087, 63.47788, 2164.172, 1)
routes.InTheNickOfTimeMissionRoute.checkpoints[1].heading = -1.102568
routes.InTheNickOfTimeMissionRoute.checkpoints[1].roadName = "r302_helper_01 AI Road 0"
routes.InTheNickOfTimeMissionRoute.arrows = {}
routes.InTheNickOfTimeMissionRoute.roads = {}
routes.InTheNickOfTimeMissionRoute.roads[1] = {}
routes.InTheNickOfTimeMissionRoute.roads[1].road = "ggp_4l_nw_03 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[1].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[2] = {}
routes.InTheNickOfTimeMissionRoute.roads[2].road = "ggp_4l_nw_03 AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[2].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[3] = {}
routes.InTheNickOfTimeMissionRoute.roads[3].road = "gg_shortcut_10 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[3].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[4] = {}
routes.InTheNickOfTimeMissionRoute.roads[4].road = "ggp_4l_se_06 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[4].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[5] = {}
routes.InTheNickOfTimeMissionRoute.roads[5].road = "ggp_4l_se_06 AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[5].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[6] = {}
routes.InTheNickOfTimeMissionRoute.roads[6].road = "ggp_4l_se_06 AI Road 2"
routes.InTheNickOfTimeMissionRoute.roads[6].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[7] = {}
routes.InTheNickOfTimeMissionRoute.roads[7].road = "ggp_4l_se_06 AI Road 3"
routes.InTheNickOfTimeMissionRoute.roads[7].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[8] = {}
routes.InTheNickOfTimeMissionRoute.roads[8].road = "ggp_4l_se_06 AI Road 4"
routes.InTheNickOfTimeMissionRoute.roads[8].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[9] = {}
routes.InTheNickOfTimeMissionRoute.roads[9].road = "ggp_4l_se_06 AI Road 5"
routes.InTheNickOfTimeMissionRoute.roads[9].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[10] = {}
routes.InTheNickOfTimeMissionRoute.roads[10].road = "dt_shortcut_22 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[10].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[11] = {}
routes.InTheNickOfTimeMissionRoute.roads[11].road = "dt_shortcut_22 AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[11].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[12] = {}
routes.InTheNickOfTimeMissionRoute.roads[12].road = "dt_4l_south_04 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[12].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[13] = {}
routes.InTheNickOfTimeMissionRoute.roads[13].road = "dt_4l_south_03 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[13].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[14] = {}
routes.InTheNickOfTimeMissionRoute.roads[14].road = "dt_4l_south_03 AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[14].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[15] = {}
routes.InTheNickOfTimeMissionRoute.roads[15].road = "dt_4l_south_02b AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[15].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[16] = {}
routes.InTheNickOfTimeMissionRoute.roads[16].road = "dt_4l_south_02b AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[16].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[17] = {}
routes.InTheNickOfTimeMissionRoute.roads[17].road = "dt_4l_south_06 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[17].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[18] = {}
routes.InTheNickOfTimeMissionRoute.roads[18].road = "dt_4l_south_06 AI Road 1"
routes.InTheNickOfTimeMissionRoute.roads[18].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[19] = {}
routes.InTheNickOfTimeMissionRoute.roads[19].road = "dt_4l_south_05bb AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[19].direction = "against"
routes.InTheNickOfTimeMissionRoute.roads[20] = {}
routes.InTheNickOfTimeMissionRoute.roads[20].road = "dt_4l_west_06 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[20].direction = "with"
routes.InTheNickOfTimeMissionRoute.roads[21] = {}
routes.InTheNickOfTimeMissionRoute.roads[21].road = "r302_helper_01 AI Road 0"
routes.InTheNickOfTimeMissionRoute.roads[21].direction = "against"
routes.InTheNickOfTimeGetawayRoute = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[1] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[1].position = vec.vector(-1524.313, 66.74652, 1873.682, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[1].heading = -2.954354
routes.InTheNickOfTimeGetawayRoute.checkpoints[1].roadName = "dt__8l_west_01 AI Road 14"
routes.InTheNickOfTimeGetawayRoute.checkpoints[2] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[2].position = vec.vector(-1566.31, 63.49998, 1667.22, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[2].heading = -2.935301
routes.InTheNickOfTimeGetawayRoute.checkpoints[2].roadName = "dt__8l_west_01 AI Road 12"
routes.InTheNickOfTimeGetawayRoute.checkpoints[3] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[3].position = vec.vector(-1635.788, 63.49211, 1625.344, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[3].heading = -1.459046
routes.InTheNickOfTimeGetawayRoute.checkpoints[3].roadName = "ggp_6l_east_02 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.checkpoints[4] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[4].position = vec.vector(-1912.847, 60.25, 1656.363, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[4].heading = -1.463407
routes.InTheNickOfTimeGetawayRoute.checkpoints[4].roadName = "ggp_6l_east_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[5] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[5].position = vec.vector(-2209.363, 60.24998, 1692.035, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[5].heading = -1.401202
routes.InTheNickOfTimeGetawayRoute.checkpoints[5].roadName = "ggp_4l_se_04 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[6] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[6].position = vec.vector(-2452.106, 60.25, 1741.628, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[6].heading = -1.371603
routes.InTheNickOfTimeGetawayRoute.checkpoints[6].roadName = "ggp_4l_se_04 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[7] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[7].position = vec.vector(-2668.733, 60.25, 1755.637, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[7].heading = -1.545718
routes.InTheNickOfTimeGetawayRoute.checkpoints[7].roadName = "ggp_4l_se_04 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.checkpoints[8] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[8].position = vec.vector(-2960.474, 53.75, 1969.299, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[8].heading = -1.935319
routes.InTheNickOfTimeGetawayRoute.checkpoints[8].roadName = "ggp_4l_se_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[9] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[9].position = vec.vector(-3231.638, 47.25, 1953.034, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[9].heading = -0.7863461
routes.InTheNickOfTimeGetawayRoute.checkpoints[9].roadName = "ggp_4l_se_05 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.checkpoints[10] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[10].position = vec.vector(-3439.917, 47.24993, 2007.996, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[10].heading = -2.28568
routes.InTheNickOfTimeGetawayRoute.checkpoints[10].roadName = "ggp_4l_sw_03 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[11] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[11].position = vec.vector(-3790.664, 37.49999, 1853.425, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[11].heading = -2.309733
routes.InTheNickOfTimeGetawayRoute.checkpoints[11].roadName = "ggp_6l_west_01 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[12] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[12].position = vec.vector(-3785.287, 37.35941, 1616.639, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[12].heading = 1.94583
routes.InTheNickOfTimeGetawayRoute.checkpoints[12].roadName = "ggp_4l_sw_06 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[13] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[13].position = vec.vector(-3426.453, 40.74999, 1543.656, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[13].heading = 2.155598
routes.InTheNickOfTimeGetawayRoute.checkpoints[13].roadName = "ggp_8l_centre_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[14] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[14].position = vec.vector(-3188.516, 48.67806, 1460.927, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[14].heading = 1.596459
routes.InTheNickOfTimeGetawayRoute.checkpoints[14].roadName = "ggp_8l_centre_02 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[15] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[15].position = vec.vector(-2944.038, 57.58423, 1358.2, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[15].heading = 1.520978
routes.InTheNickOfTimeGetawayRoute.checkpoints[15].roadName = "ggp_10l_centre_01 AI Road 5"
routes.InTheNickOfTimeGetawayRoute.checkpoints[16] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[16].position = vec.vector(-2688.728, 66.73856, 1367.98, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[16].heading = 1.569684
routes.InTheNickOfTimeGetawayRoute.checkpoints[16].roadName = "ggp_10l_centre_01 AI Road 6"
routes.InTheNickOfTimeGetawayRoute.checkpoints[17] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[17].position = vec.vector(-2625, 66.72433, 1447.248, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[17].heading = 0
routes.InTheNickOfTimeGetawayRoute.checkpoints[17].roadName = "ggp_6l_north_05 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[18] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[18].position = vec.vector(-2625, 64.66475, 1599.282, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[18].heading = 0
routes.InTheNickOfTimeGetawayRoute.checkpoints[18].roadName = "ggp_6l_north_05 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.checkpoints[19] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[19].position = vec.vector(-2625, 61.30155, 1863.532, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[19].heading = 0
routes.InTheNickOfTimeGetawayRoute.checkpoints[19].roadName = "ggp_6l_north_05 AI Road 3"
routes.InTheNickOfTimeGetawayRoute.checkpoints[20] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[20].position = vec.vector(-2625, 66.42139, 2012.252, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[20].heading = 0
routes.InTheNickOfTimeGetawayRoute.checkpoints[20].roadName = "ggp_6l_north_05 AI Road 4"
routes.InTheNickOfTimeGetawayRoute.checkpoints[21] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[21].position = vec.vector(-2500.208, 66.75, 2108, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[21].heading = -1.570796
routes.InTheNickOfTimeGetawayRoute.checkpoints[21].roadName = "ggp_10l_south_05 AI Road 4"
routes.InTheNickOfTimeGetawayRoute.checkpoints[22] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[22].position = vec.vector(-2813.873, 60.25, 2152.937, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[22].heading = 0
routes.InTheNickOfTimeGetawayRoute.checkpoints[22].roadName = "ggp_4l_se_02 AI Road 3"
routes.InTheNickOfTimeGetawayRoute.checkpoints[23] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[23].position = vec.vector(-2773.844, 60.40463, 2217.433, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[23].heading = 1.596222
routes.InTheNickOfTimeGetawayRoute.checkpoints[23].roadName = "sutro_6l_west_01 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.checkpoints[24] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[24].position = vec.vector(-2508.509, 76.6933, 2238.561, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[24].heading = 0.8331243
routes.InTheNickOfTimeGetawayRoute.checkpoints[24].roadName = "sutro_6l_west_01 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[25] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[25].position = vec.vector(-2392.935, 79.74998, 2320.738, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[25].heading = 2.051788
routes.InTheNickOfTimeGetawayRoute.checkpoints[25].roadName = "sutro_8l_north_01 AI Road 10"
routes.InTheNickOfTimeGetawayRoute.checkpoints[26] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[26].position = vec.vector(-1974.929, 79.75014, 2105.294, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[26].heading = 2.014543
routes.InTheNickOfTimeGetawayRoute.checkpoints[26].roadName = "dt_10l_south_02b AI Road 0"
routes.InTheNickOfTimeGetawayRoute.checkpoints[27] = {}
routes.InTheNickOfTimeGetawayRoute.checkpoints[27].position = vec.vector(-1719.065, 73.24999, 1983.614, 1)
routes.InTheNickOfTimeGetawayRoute.checkpoints[27].heading = 2.005159
routes.InTheNickOfTimeGetawayRoute.checkpoints[27].roadName = "dt_10l_south_02b AI Road 1"
routes.InTheNickOfTimeGetawayRoute.arrows = {}
routes.InTheNickOfTimeGetawayRoute.roads = {}
routes.InTheNickOfTimeGetawayRoute.roads[1] = {}
routes.InTheNickOfTimeGetawayRoute.roads[1].road = "dt__8l_west_01 AI Road 14"
routes.InTheNickOfTimeGetawayRoute.roads[1].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[2] = {}
routes.InTheNickOfTimeGetawayRoute.roads[2].road = "dt__8l_west_01 AI Road 13"
routes.InTheNickOfTimeGetawayRoute.roads[2].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[3] = {}
routes.InTheNickOfTimeGetawayRoute.roads[3].road = "dt__8l_west_01 AI Road 12"
routes.InTheNickOfTimeGetawayRoute.roads[3].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[4] = {}
routes.InTheNickOfTimeGetawayRoute.roads[4].road = "ggp_6l_east_02 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[4].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[5] = {}
routes.InTheNickOfTimeGetawayRoute.roads[5].road = "ggp_6l_east_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[5].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[6] = {}
routes.InTheNickOfTimeGetawayRoute.roads[6].road = "ggp_6l_east_02 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[6].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[7] = {}
routes.InTheNickOfTimeGetawayRoute.roads[7].road = "ggp_4l_se_04 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[7].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[8] = {}
routes.InTheNickOfTimeGetawayRoute.roads[8].road = "ggp_4l_se_04 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[8].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[9] = {}
routes.InTheNickOfTimeGetawayRoute.roads[9].road = "ggp_4l_se_04 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[9].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[10] = {}
routes.InTheNickOfTimeGetawayRoute.roads[10].road = "ggp_4l_se_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[10].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[11] = {}
routes.InTheNickOfTimeGetawayRoute.roads[11].road = "ggp_4l_se_02 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[11].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[12] = {}
routes.InTheNickOfTimeGetawayRoute.roads[12].road = "ggp_4l_se_05 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[12].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[13] = {}
routes.InTheNickOfTimeGetawayRoute.roads[13].road = "ggp_4l_sw_03 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[13].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[14] = {}
routes.InTheNickOfTimeGetawayRoute.roads[14].road = "ggp_6l_west_01 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[14].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[15] = {}
routes.InTheNickOfTimeGetawayRoute.roads[15].road = "ggp_4l_sw_06 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[15].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[16] = {}
routes.InTheNickOfTimeGetawayRoute.roads[16].road = "ggp_8l_centre_02 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[16].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[17] = {}
routes.InTheNickOfTimeGetawayRoute.roads[17].road = "ggp_8l_centre_02 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[17].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[18] = {}
routes.InTheNickOfTimeGetawayRoute.roads[18].road = "ggp_10l_centre_01 AI Road 5"
routes.InTheNickOfTimeGetawayRoute.roads[18].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[19] = {}
routes.InTheNickOfTimeGetawayRoute.roads[19].road = "ggp_10l_centre_01 AI Road 6"
routes.InTheNickOfTimeGetawayRoute.roads[19].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[20] = {}
routes.InTheNickOfTimeGetawayRoute.roads[20].road = "ggp_6l_north_05 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[20].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[21] = {}
routes.InTheNickOfTimeGetawayRoute.roads[21].road = "ggp_6l_north_05 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[21].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[22] = {}
routes.InTheNickOfTimeGetawayRoute.roads[22].road = "ggp_6l_north_05 AI Road 3"
routes.InTheNickOfTimeGetawayRoute.roads[22].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[23] = {}
routes.InTheNickOfTimeGetawayRoute.roads[23].road = "ggp_6l_north_05 AI Road 4"
routes.InTheNickOfTimeGetawayRoute.roads[23].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[24] = {}
routes.InTheNickOfTimeGetawayRoute.roads[24].road = "ggp_10l_south_05 AI Road 5"
routes.InTheNickOfTimeGetawayRoute.roads[24].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[25] = {}
routes.InTheNickOfTimeGetawayRoute.roads[25].road = "ggp_4l_se_02 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[25].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[26] = {}
routes.InTheNickOfTimeGetawayRoute.roads[26].road = "ggp_4l_se_04 AI Road 2"
routes.InTheNickOfTimeGetawayRoute.roads[26].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[27] = {}
routes.InTheNickOfTimeGetawayRoute.roads[27].road = "ggp_4l_se_04 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[27].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[28] = {}
routes.InTheNickOfTimeGetawayRoute.roads[28].road = "ggp_6l_north_01 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[28].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[29] = {}
routes.InTheNickOfTimeGetawayRoute.roads[29].road = "ggp_6l_north_01 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[29].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[30] = {}
routes.InTheNickOfTimeGetawayRoute.roads[30].road = "ggp_10l_south_05 AI Road 4"
routes.InTheNickOfTimeGetawayRoute.roads[30].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[31] = {}
routes.InTheNickOfTimeGetawayRoute.roads[31].road = "ggp_10l_south_05 AI Road 5"
routes.InTheNickOfTimeGetawayRoute.roads[31].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[32] = {}
routes.InTheNickOfTimeGetawayRoute.roads[32].road = "ggp_4l_se_02 AI Road 3"
routes.InTheNickOfTimeGetawayRoute.roads[32].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[33] = {}
routes.InTheNickOfTimeGetawayRoute.roads[33].road = "sutro_6l_west_01 AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[33].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[34] = {}
routes.InTheNickOfTimeGetawayRoute.roads[34].road = "sutro_6l_west_01 AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[34].direction = "against"
routes.InTheNickOfTimeGetawayRoute.roads[35] = {}
routes.InTheNickOfTimeGetawayRoute.roads[35].road = "sutro_8l_north_01 AI Road 10"
routes.InTheNickOfTimeGetawayRoute.roads[35].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[36] = {}
routes.InTheNickOfTimeGetawayRoute.roads[36].road = "dt_10l_south_02b AI Road 0"
routes.InTheNickOfTimeGetawayRoute.roads[36].direction = "with"
routes.InTheNickOfTimeGetawayRoute.roads[37] = {}
routes.InTheNickOfTimeGetawayRoute.roads[37].road = "dt_10l_south_02b AI Road 1"
routes.InTheNickOfTimeGetawayRoute.roads[37].direction = "with"
routes.InTheNickOfTimeWarmupRoute = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[1] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[1].position = vec.vector(-3528.548, 66.75, 1029.848, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[1].heading = -0.8856749
routes.InTheNickOfTimeWarmupRoute.checkpoints[1].roadName = "ggp_6l_north_02 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.checkpoints[2] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[2].position = vec.vector(-3797.689, 56.5538, 1128.953, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[2].heading = -1.194204
routes.InTheNickOfTimeWarmupRoute.checkpoints[2].roadName = "ggp_6l_north_02 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.checkpoints[3] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[3].position = vec.vector(-4083.72, 33.96007, 1281.936, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[3].heading = -1.697077
routes.InTheNickOfTimeWarmupRoute.checkpoints[3].roadName = "ggp_10l_centre_01 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.checkpoints[4] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[4].position = vec.vector(-4343.296, 29.67605, 1186.39, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[4].heading = -2.332568
routes.InTheNickOfTimeWarmupRoute.checkpoints[4].roadName = "ggp_10l_centre_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.checkpoints[5] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[5].position = vec.vector(-4361.634, 27.75008, 991.5937, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[5].heading = 2.476417
routes.InTheNickOfTimeWarmupRoute.checkpoints[5].roadName = "ggp_8l_west_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.checkpoints[6] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[6].position = vec.vector(-4183.994, 32.91742, 1015.673, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[6].heading = 0.9531831
routes.InTheNickOfTimeWarmupRoute.checkpoints[6].roadName = "ggp_4l_nw_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.checkpoints[7] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[7].position = vec.vector(-3987.02, 46.34107, 965.1121, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[7].heading = 2.363821
routes.InTheNickOfTimeWarmupRoute.checkpoints[7].roadName = "ggp_4l_nw_01 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.checkpoints[8] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[8].position = vec.vector(-3781.73, 60.35985, 920.9956, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[8].heading = 1.5301
routes.InTheNickOfTimeWarmupRoute.checkpoints[8].roadName = "ggp_4l_nw_01 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.checkpoints[9] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[9].position = vec.vector(-3556.241, 57.76365, 757.5411, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[9].heading = 2.776412
routes.InTheNickOfTimeWarmupRoute.checkpoints[9].roadName = "ggp_4l_nw_04 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.checkpoints[10] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[10].position = vec.vector(-3414.924, 43.76623, 650.973, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[10].heading = 1.979084
routes.InTheNickOfTimeWarmupRoute.checkpoints[10].roadName = "ggp_4l_nw_04 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.checkpoints[11] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[11].position = vec.vector(-3254.541, 49.7445, 665.0598, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[11].heading = 0.6300427
routes.InTheNickOfTimeWarmupRoute.checkpoints[11].roadName = "ggp_4l_nw_05 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.checkpoints[12] = {}
routes.InTheNickOfTimeWarmupRoute.checkpoints[12].position = vec.vector(-3345.848, 72.84235, 788.9659, 1)
routes.InTheNickOfTimeWarmupRoute.checkpoints[12].heading = -0.8824038
routes.InTheNickOfTimeWarmupRoute.checkpoints[12].roadName = "ggp_6l_north_02 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.arrows = {}
routes.InTheNickOfTimeWarmupRoute.roads = {}
routes.InTheNickOfTimeWarmupRoute.roads[1] = {}
routes.InTheNickOfTimeWarmupRoute.roads[1].road = "ggp_6l_north_02 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.roads[1].direction = "against"
routes.InTheNickOfTimeWarmupRoute.roads[2] = {}
routes.InTheNickOfTimeWarmupRoute.roads[2].road = "ggp_6l_north_02 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.roads[2].direction = "against"
routes.InTheNickOfTimeWarmupRoute.roads[3] = {}
routes.InTheNickOfTimeWarmupRoute.roads[3].road = "ggp_10l_centre_01 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.roads[3].direction = "against"
routes.InTheNickOfTimeWarmupRoute.roads[4] = {}
routes.InTheNickOfTimeWarmupRoute.roads[4].road = "ggp_10l_centre_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.roads[4].direction = "against"
routes.InTheNickOfTimeWarmupRoute.roads[5] = {}
routes.InTheNickOfTimeWarmupRoute.roads[5].road = "ggp_8l_west_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.roads[5].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[6] = {}
routes.InTheNickOfTimeWarmupRoute.roads[6].road = "ggp_4l_nw_01 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.roads[6].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[7] = {}
routes.InTheNickOfTimeWarmupRoute.roads[7].road = "ggp_4l_nw_01 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.roads[7].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[8] = {}
routes.InTheNickOfTimeWarmupRoute.roads[8].road = "ggp_4l_nw_01 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.roads[8].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[9] = {}
routes.InTheNickOfTimeWarmupRoute.roads[9].road = "ggp_4l_nw_04 AI Road 1"
routes.InTheNickOfTimeWarmupRoute.roads[9].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[10] = {}
routes.InTheNickOfTimeWarmupRoute.roads[10].road = "ggp_4l_nw_04 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.roads[10].direction = "with"
routes.InTheNickOfTimeWarmupRoute.roads[11] = {}
routes.InTheNickOfTimeWarmupRoute.roads[11].road = "ggp_4l_nw_05 AI Road 0"
routes.InTheNickOfTimeWarmupRoute.roads[11].direction = "against"
routes.InTheNickOfTimeWarmupRoute.roads[12] = {}
routes.InTheNickOfTimeWarmupRoute.roads[12].road = "ggp_6l_north_02 AI Road 2"
routes.InTheNickOfTimeWarmupRoute.roads[12].direction = "against"
