routes = routes or {}
routes["Peroxide Convoy Tanker 1 Route"] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[1] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[1].position = vec.vector(-3098.421, 57, 2438.531, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[1].heading = 1.597417
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[1].roadName = "sutro_8l_north_01 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[2] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[2].position = vec.vector(-2519.675, 79.74985, 2376.264, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[2].heading = 1.782496
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[2].roadName = "sutro_8l_north_01 AI Road 9"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[3] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[3].position = vec.vector(-2120.385, 79.75, 2178.502, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[3].heading = 2.051774
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[3].roadName = "sutro_8l_north_01 AI Road 10"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[4] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[4].position = vec.vector(-1828.84, 73.25004, 2035.847, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[4].heading = 2.014555
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[4].roadName = "dt_10l_south_02b AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[5] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[5].position = vec.vector(-1583.891, 66.75004, 1937.02, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[5].heading = 1.864156
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[5].roadName = "dt_10l_south_02b AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[6] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[6].position = vec.vector(-1267.688, 66.75, 1893.107, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[6].heading = 1.702121
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[6].roadName = "dt_10l_south_02b AI Road 3"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[7] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[7].position = vec.vector(-572.6439, 59.645, 1761.946, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[7].heading = 1.848979
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[7].roadName = "dt_10l_south_02b AI Road 8"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[8] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[8].position = vec.vector(-76.02746, 34.22195, 1470.876, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[8].heading = -2.918597
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[8].roadName = "dt_10l_centre_02 AI Road 2"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[9] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[9].position = vec.vector(-289.2298, 18.71507, 1051.772, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[9].heading = -1.447782
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[9].roadName = "dt_10l_south_01 AI Road 5"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[10] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[10].position = vec.vector(-1368.615, 47.11729, 1182.621, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[10].heading = -1.411003
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[10].roadName = "dt_10l_south_01 AI Road 13"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[11] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[11].position = vec.vector(-1779.615, 52.22483, 1252.676, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[11].heading = -1.401694
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[11].roadName = "dt_10l_south_01 AI Road 16"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[12] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[12].position = vec.vector(-2013.069, 55.54982, 1292.671, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[12].heading = -1.405448
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[12].roadName = "dt_10l_south_01 AI Road 17"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[13] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[13].position = vec.vector(-2144.842, 60.25, 1542.023, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[13].heading = 0.06408611
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[13].roadName = "ggp_10l_east_01 AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[14] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[14].position = vec.vector(-2292.776, 60.24999, 1707.77, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[14].heading = -1.372159
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[14].roadName = "ggp_4l_se_04 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[15] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[15].position = vec.vector(-2418.295, 64.54069, 1999.33, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[15].heading = -0.2439846
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[15].roadName = "ggp_6l_north_01 AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[16] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[16].position = vec.vector(-3098.603, 60.25, 2094.794, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[16].heading = -1.570815
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[16].roadName = "ggp_10l_south_05 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[17] = {}
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[17].position = vec.vector(-3238.894, 51.51151, 2218.922, 1)
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[17].heading = 0.6026813
routes["Peroxide Convoy Tanker 1 Route"].checkpoints[17].roadName = "ggp_10l_south_01 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].arrows = {}
routes["Peroxide Convoy Tanker 1 Route"].roads = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[1] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[1].road = "sutro_8l_north_01 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].roads[1].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[2] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[2].road = "sutro_8l_north_01 AI Road 8"
routes["Peroxide Convoy Tanker 1 Route"].roads[2].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[3] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[3].road = "sutro_8l_north_01 AI Road 9"
routes["Peroxide Convoy Tanker 1 Route"].roads[3].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[4] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[4].road = "sutro_8l_north_01 AI Road 10"
routes["Peroxide Convoy Tanker 1 Route"].roads[4].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[5] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[5].road = "dt_10l_south_02b AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[5].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[6] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[6].road = "dt_10l_south_02b AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].roads[6].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[7] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[7].road = "dt_10l_south_02b AI Road 2"
routes["Peroxide Convoy Tanker 1 Route"].roads[7].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[8] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[8].road = "dt_10l_south_02b AI Road 3"
routes["Peroxide Convoy Tanker 1 Route"].roads[8].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[9] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[9].road = "dt_10l_south_02b AI Road 4"
routes["Peroxide Convoy Tanker 1 Route"].roads[9].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[10] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[10].road = "dt_10l_south_02b AI Road 5"
routes["Peroxide Convoy Tanker 1 Route"].roads[10].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[11] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[11].road = "dt_10l_south_02b AI Road 6"
routes["Peroxide Convoy Tanker 1 Route"].roads[11].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[12] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[12].road = "dt_10l_south_02b AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].roads[12].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[13] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[13].road = "dt_10l_south_02b AI Road 8"
routes["Peroxide Convoy Tanker 1 Route"].roads[13].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[14] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[14].road = "dt_10l_south_02b AI Road 9"
routes["Peroxide Convoy Tanker 1 Route"].roads[14].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[15] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[15].road = "dt_10l_south_03 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].roads[15].direction = "against"
routes["Peroxide Convoy Tanker 1 Route"].roads[16] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[16].road = "dt_10l_south_03 AI Road 6"
routes["Peroxide Convoy Tanker 1 Route"].roads[16].direction = "against"
routes["Peroxide Convoy Tanker 1 Route"].roads[17] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[17].road = "dt_10l_centre_02 AI Road 2"
routes["Peroxide Convoy Tanker 1 Route"].roads[17].direction = "against"
routes["Peroxide Convoy Tanker 1 Route"].roads[18] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[18].road = "dt_10l_centre_02 AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].roads[18].direction = "against"
routes["Peroxide Convoy Tanker 1 Route"].roads[19] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[19].road = "dt_10l_centre_02 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[19].direction = "against"
routes["Peroxide Convoy Tanker 1 Route"].roads[20] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[20].road = "dt_10l_south_01 AI Road 5"
routes["Peroxide Convoy Tanker 1 Route"].roads[20].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[21] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[21].road = "dt_10l_south_01 AI Road 6"
routes["Peroxide Convoy Tanker 1 Route"].roads[21].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[22] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[22].road = "dt_10l_south_01 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].roads[22].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[23] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[23].road = "dt_10l_south_01 AI Road 8"
routes["Peroxide Convoy Tanker 1 Route"].roads[23].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[24] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[24].road = "dt_10l_south_01 AI Road 9"
routes["Peroxide Convoy Tanker 1 Route"].roads[24].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[25] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[25].road = "dt_10l_south_01 AI Road 10"
routes["Peroxide Convoy Tanker 1 Route"].roads[25].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[26] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[26].road = "dt_10l_south_01 AI Road 11"
routes["Peroxide Convoy Tanker 1 Route"].roads[26].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[27] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[27].road = "dt_10l_south_01 AI Road 12"
routes["Peroxide Convoy Tanker 1 Route"].roads[27].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[28] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[28].road = "dt_10l_south_01 AI Road 13"
routes["Peroxide Convoy Tanker 1 Route"].roads[28].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[29] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[29].road = "dt_10l_south_01 AI Road 14"
routes["Peroxide Convoy Tanker 1 Route"].roads[29].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[30] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[30].road = "dt_10l_south_01 AI Road 15"
routes["Peroxide Convoy Tanker 1 Route"].roads[30].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[31] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[31].road = "dt_10l_south_01 AI Road 16"
routes["Peroxide Convoy Tanker 1 Route"].roads[31].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[32] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[32].road = "dt_10l_south_01 AI Road 17"
routes["Peroxide Convoy Tanker 1 Route"].roads[32].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[33] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[33].road = "dt_10l_south_01 AI Road 18"
routes["Peroxide Convoy Tanker 1 Route"].roads[33].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[34] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[34].road = "ggp_10l_east_01 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[34].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[35] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[35].road = "ggp_10l_east_01 AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].roads[35].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[36] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[36].road = "ggp_4l_se_04 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[36].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[37] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[37].road = "ggp_6l_north_01 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[37].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[38] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[38].road = "ggp_6l_north_01 AI Road 1"
routes["Peroxide Convoy Tanker 1 Route"].roads[38].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[39] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[39].road = "ggp_10l_south_05 AI Road 4"
routes["Peroxide Convoy Tanker 1 Route"].roads[39].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[40] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[40].road = "ggp_10l_south_05 AI Road 5"
routes["Peroxide Convoy Tanker 1 Route"].roads[40].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[41] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[41].road = "ggp_10l_south_05 AI Road 6"
routes["Peroxide Convoy Tanker 1 Route"].roads[41].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[42] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[42].road = "ggp_10l_south_05 AI Road 7"
routes["Peroxide Convoy Tanker 1 Route"].roads[42].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[43] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[43].road = "ggp_10l_south_05 AI Road 8"
routes["Peroxide Convoy Tanker 1 Route"].roads[43].direction = "with"
routes["Peroxide Convoy Tanker 1 Route"].roads[44] = {}
routes["Peroxide Convoy Tanker 1 Route"].roads[44].road = "ggp_10l_south_01 AI Road 0"
routes["Peroxide Convoy Tanker 1 Route"].roads[44].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[1] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[1].position = vec.vector(-723.7711, 76.5, 2069.229, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[1].heading = 0.3732099
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[1].roadName = "highway01_16b AI Road 5"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[2] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[2].position = vec.vector(-611.8446, 76.5, 2327.648, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[2].heading = 0.4115814
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[2].roadName = "highway01_16b AI Road 6"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[3] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[3].position = vec.vector(-546.9646, 76.5, 2473.648, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[3].heading = 0.4239599
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[3].roadName = "highway01_16b AI Road 7"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[4] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[4].position = vec.vector(-270.3554, 74.35603, 2748.823, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[4].heading = 1.290385
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[4].roadName = "highway01_16b AI Road 11"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[5] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[5].position = vec.vector(552.9882, 45.60094, 2411.218, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[5].heading = 2.215356
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[5].roadName = "highway01_16b AI Road 17"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[6] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[6].position = vec.vector(1303.349, 35.91437, 1738.917, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[6].heading = 2.27809
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[6].roadName = "highway01_16b AI Road 20"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[7] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[7].position = vec.vector(1758.225, 45.07714, 1508.386, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[7].heading = 1.999843
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[7].roadName = "highway01_16b AI Road 22"
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[8] = {}
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[8].position = vec.vector(2477.508, 45.82185, 1179.354, 1)
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[8].heading = 1.99985
routes["Peroxide Convoy Tanker 2 Route"].checkpoints[8].roadName = "highway01_16b AI Road 26"
routes["Peroxide Convoy Tanker 2 Route"].arrows = {}
routes["Peroxide Convoy Tanker 2 Route"].roads = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[1] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[1].road = "highway01_16b AI Road 5"
routes["Peroxide Convoy Tanker 2 Route"].roads[1].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[2] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[2].road = "highway01_16b AI Road 6"
routes["Peroxide Convoy Tanker 2 Route"].roads[2].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[3] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[3].road = "highway01_16b AI Road 7"
routes["Peroxide Convoy Tanker 2 Route"].roads[3].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[4] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[4].road = "highway01_16b AI Road 8"
routes["Peroxide Convoy Tanker 2 Route"].roads[4].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[5] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[5].road = "highway01_16b AI Road 9"
routes["Peroxide Convoy Tanker 2 Route"].roads[5].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[6] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[6].road = "highway01_16b AI Road 10"
routes["Peroxide Convoy Tanker 2 Route"].roads[6].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[7] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[7].road = "highway01_16b AI Road 11"
routes["Peroxide Convoy Tanker 2 Route"].roads[7].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[8] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[8].road = "highway01_16b AI Road 12"
routes["Peroxide Convoy Tanker 2 Route"].roads[8].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[9] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[9].road = "highway01_16b AI Road 13"
routes["Peroxide Convoy Tanker 2 Route"].roads[9].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[10] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[10].road = "highway01_16b AI Road 14"
routes["Peroxide Convoy Tanker 2 Route"].roads[10].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[11] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[11].road = "highway01_16b AI Road 15"
routes["Peroxide Convoy Tanker 2 Route"].roads[11].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[12] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[12].road = "highway01_16b AI Road 16"
routes["Peroxide Convoy Tanker 2 Route"].roads[12].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[13] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[13].road = "highway01_16b AI Road 17"
routes["Peroxide Convoy Tanker 2 Route"].roads[13].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[14] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[14].road = "highway01_16b AI Road 18"
routes["Peroxide Convoy Tanker 2 Route"].roads[14].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[15] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[15].road = "highway01_16b AI Road 19"
routes["Peroxide Convoy Tanker 2 Route"].roads[15].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[16] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[16].road = "highway01_16b AI Road 20"
routes["Peroxide Convoy Tanker 2 Route"].roads[16].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[17] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[17].road = "highway01_16b AI Road 21"
routes["Peroxide Convoy Tanker 2 Route"].roads[17].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[18] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[18].road = "highway01_16b AI Road 22"
routes["Peroxide Convoy Tanker 2 Route"].roads[18].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[19] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[19].road = "highway01_16b AI Road 23"
routes["Peroxide Convoy Tanker 2 Route"].roads[19].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[20] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[20].road = "highway01_16b AI Road 24"
routes["Peroxide Convoy Tanker 2 Route"].roads[20].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[21] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[21].road = "highway01_16b AI Road 25"
routes["Peroxide Convoy Tanker 2 Route"].roads[21].direction = "with"
routes["Peroxide Convoy Tanker 2 Route"].roads[22] = {}
routes["Peroxide Convoy Tanker 2 Route"].roads[22].road = "highway01_16b AI Road 26"
routes["Peroxide Convoy Tanker 2 Route"].roads[22].direction = "with"
