routes = routes or {}
routes["Peroxide convoy warmup"] = {}
routes["Peroxide convoy warmup"].checkpoints = {}
routes["Peroxide convoy warmup"].checkpoints[1] = {}
routes["Peroxide convoy warmup"].checkpoints[1].position = vec.vector(-3798.399, 28.36278, 2634.093, 1)
routes["Peroxide convoy warmup"].checkpoints[1].heading = 1.346255
routes["Peroxide convoy warmup"].checkpoints[1].roadName = "ggp_10l_south_02 AI Road 2"
routes["Peroxide convoy warmup"].checkpoints[2] = {}
routes["Peroxide convoy warmup"].checkpoints[2].position = vec.vector(-3752.912, 40.83797, 2732.441, 1)
routes["Peroxide convoy warmup"].checkpoints[2].heading = -0.2772729
routes["Peroxide convoy warmup"].checkpoints[2].roadName = "sutro_shortcut_19 AI Road 6"
routes["Peroxide convoy warmup"].checkpoints[3] = {}
routes["Peroxide convoy warmup"].checkpoints[3].position = vec.vector(-3792.725, 60.14656, 2877.25, 1)
routes["Peroxide convoy warmup"].checkpoints[3].heading = -0.2714442
routes["Peroxide convoy warmup"].checkpoints[3].roadName = "sutro_shortcut_19 AI Road 5"
routes["Peroxide convoy warmup"].checkpoints[4] = {}
routes["Peroxide convoy warmup"].checkpoints[4].position = vec.vector(-3869.494, 53.12437, 2889.826, 1)
routes["Peroxide convoy warmup"].checkpoints[4].heading = -1.872571
routes["Peroxide convoy warmup"].checkpoints[4].roadName = "sutro_4l_west_02 AI Road 1"
routes["Peroxide convoy warmup"].checkpoints[5] = {}
routes["Peroxide convoy warmup"].checkpoints[5].position = vec.vector(-3939.633, 48.01378, 2821.702, 1)
routes["Peroxide convoy warmup"].checkpoints[5].heading = 2.897693
routes["Peroxide convoy warmup"].checkpoints[5].roadName = "sutro_8l_north_01 AI Road 2"
routes["Peroxide convoy warmup"].checkpoints[6] = {}
routes["Peroxide convoy warmup"].checkpoints[6].position = vec.vector(-3906.542, 30.45996, 2691.359, 1)
routes["Peroxide convoy warmup"].checkpoints[6].heading = 2.886192
routes["Peroxide convoy warmup"].checkpoints[6].roadName = "sutro_8l_north_01 AI Road 3"
routes["Peroxide convoy warmup"].arrows = {}
routes["Peroxide convoy warmup"].roads = {}
routes["Peroxide convoy warmup"].roads[1] = {}
routes["Peroxide convoy warmup"].roads[1].road = "ggp_10l_south_02 AI Road 2"
routes["Peroxide convoy warmup"].roads[1].direction = "against"
routes["Peroxide convoy warmup"].roads[2] = {}
routes["Peroxide convoy warmup"].roads[2].road = "sutro_shortcut_19 AI Road 6"
routes["Peroxide convoy warmup"].roads[2].direction = "against"
routes["Peroxide convoy warmup"].roads[3] = {}
routes["Peroxide convoy warmup"].roads[3].road = "sutro_shortcut_19 AI Road 5"
routes["Peroxide convoy warmup"].roads[3].direction = "against"
routes["Peroxide convoy warmup"].roads[4] = {}
routes["Peroxide convoy warmup"].roads[4].road = "sutro_4l_west_02 AI Road 1"
routes["Peroxide convoy warmup"].roads[4].direction = "with"
routes["Peroxide convoy warmup"].roads[5] = {}
routes["Peroxide convoy warmup"].roads[5].road = "sutro_8l_north_01 AI Road 2"
routes["Peroxide convoy warmup"].roads[5].direction = "with"
routes["Peroxide convoy warmup"].roads[6] = {}
routes["Peroxide convoy warmup"].roads[6].road = "sutro_8l_north_01 AI Road 3"
routes["Peroxide convoy warmup"].roads[6].direction = "with"
