routes = routes or {}
routes["Tanner and jones 3 warmup"] = {}
routes["Tanner and jones 3 warmup"].checkpoints = {}
routes["Tanner and jones 3 warmup"].checkpoints[1] = {}
routes["Tanner and jones 3 warmup"].checkpoints[1].position = vec.vector(-1293.484, 34.22142, 350.0063, 1)
routes["Tanner and jones 3 warmup"].checkpoints[1].heading = -1.375248
routes["Tanner and jones 3 warmup"].checkpoints[1].roadName = "dt_6l_west_03b AI Road 0"
routes["Tanner and jones 3 warmup"].checkpoints[2] = {}
routes["Tanner and jones 3 warmup"].checkpoints[2].position = vec.vector(-1293.091, 23.90849, 169.7233, 1)
routes["Tanner and jones 3 warmup"].checkpoints[2].heading = 1.76432
routes["Tanner and jones 3 warmup"].checkpoints[2].roadName = "dt_8l_centre_01ab AI Road 0"
routes["Tanner and jones 3 warmup"].checkpoints[3] = {}
routes["Tanner and jones 3 warmup"].checkpoints[3].position = vec.vector(-1124.078, 27.76618, 315.6979, 1)
routes["Tanner and jones 3 warmup"].checkpoints[3].heading = -1.361082
routes["Tanner and jones 3 warmup"].checkpoints[3].roadName = "dt_4l_west_06b AI Road 0"
routes["Tanner and jones 3 warmup"].arrows = {}
routes["Tanner and jones 3 warmup"].roads = {}
routes["Tanner and jones 3 warmup"].roads[1] = {}
routes["Tanner and jones 3 warmup"].roads[1].road = "dt_6l_west_03b AI Road 0"
routes["Tanner and jones 3 warmup"].roads[1].direction = "against"
routes["Tanner and jones 3 warmup"].roads[2] = {}
routes["Tanner and jones 3 warmup"].roads[2].road = "dt_8l_centre_01ab AI Road 1"
routes["Tanner and jones 3 warmup"].roads[2].direction = "against"
routes["Tanner and jones 3 warmup"].roads[3] = {}
routes["Tanner and jones 3 warmup"].roads[3].road = "dt_8l_centre_01ab AI Road 0"
routes["Tanner and jones 3 warmup"].roads[3].direction = "against"
routes["Tanner and jones 3 warmup"].roads[4] = {}
routes["Tanner and jones 3 warmup"].roads[4].road = "dt_10l_centre_01 AI Road 1"
routes["Tanner and jones 3 warmup"].roads[4].direction = "with"
routes["Tanner and jones 3 warmup"].roads[5] = {}
routes["Tanner and jones 3 warmup"].roads[5].road = "dt_4l_west_06b AI Road 1"
routes["Tanner and jones 3 warmup"].roads[5].direction = "against"
routes["Tanner and jones 3 warmup"].roads[6] = {}
routes["Tanner and jones 3 warmup"].roads[6].road = "dt_4l_west_06b AI Road 0"
routes["Tanner and jones 3 warmup"].roads[6].direction = "against"
