routes = routes or {}
routes["Paranoia route"] = {}
routes["Paranoia route"].checkpoints = {}
routes["Paranoia route"].checkpoints[1] = {}
routes["Paranoia route"].checkpoints[1].position = vec.vector(782.7906, 5.975, 1171.102, 1)
routes["Paranoia route"].checkpoints[1].heading = -0.848473
routes["Paranoia route"].checkpoints[1].roadName = "embargedero_shortcut_02 AI Road 1"
routes["Paranoia route"].checkpoints[2] = {}
routes["Paranoia route"].checkpoints[2].position = vec.vector(649.7254, 5.974995, 1179.842, 1)
routes["Paranoia route"].checkpoints[2].heading = -2.320136
routes["Paranoia route"].checkpoints[2].roadName = "sanfran_shortcut_06 AI Road 0"
routes["Paranoia route"].checkpoints[3] = {}
routes["Paranoia route"].checkpoints[3].position = vec.vector(342.4877, 13.07957, 1110.999, 1)
routes["Paranoia route"].checkpoints[3].heading = -1.385442
routes["Paranoia route"].checkpoints[3].roadName = "dt_shortcut_03b AI Road 2"
routes["Paranoia route"].checkpoints[4] = {}
routes["Paranoia route"].checkpoints[4].position = vec.vector(85.40423, 22.41927, 1096.101, 1)
routes["Paranoia route"].checkpoints[4].heading = -2.971049
routes["Paranoia route"].checkpoints[4].roadName = "dt_mt_join_unfinished AI Road 0"
routes["Paranoia route"].checkpoints[5] = {}
routes["Paranoia route"].checkpoints[5].position = vec.vector(-52.96608, 18, 1021.72, 1)
routes["Paranoia route"].checkpoints[5].heading = -1.465215
routes["Paranoia route"].checkpoints[5].roadName = "dt_10l_south_01 AI Road 4"
routes["Paranoia route"].checkpoints[6] = {}
routes["Paranoia route"].checkpoints[6].position = vec.vector(-289.6523, 18.72071, 1051.824, 1)
routes["Paranoia route"].checkpoints[6].heading = -1.447765
routes["Paranoia route"].checkpoints[6].roadName = "dt_10l_south_01 AI Road 5"
routes["Paranoia route"].checkpoints[7] = {}
routes["Paranoia route"].checkpoints[7].position = vec.vector(-556.1949, 23.43396, 1083.655, 1)
routes["Paranoia route"].checkpoints[7].heading = -1.457149
routes["Paranoia route"].checkpoints[7].roadName = "dt_10l_south_01 AI Road 8"
routes["Paranoia route"].checkpoints[8] = {}
routes["Paranoia route"].checkpoints[8].position = vec.vector(-831.9387, 34.79145, 1020.598, 1)
routes["Paranoia route"].checkpoints[8].heading = -2.84429
routes["Paranoia route"].checkpoints[8].roadName = "chinatown_02 AI Road 1"
routes["Paranoia route"].checkpoints[9] = {}
routes["Paranoia route"].checkpoints[9].position = vec.vector(-890.3167, 36.80934, 830.4339, 1)
routes["Paranoia route"].checkpoints[9].heading = -2.843551
routes["Paranoia route"].checkpoints[9].roadName = "chinatown_02 AI Road 0"
routes["Paranoia route"].checkpoints[10] = {}
routes["Paranoia route"].checkpoints[10].position = vec.vector(-864.695, 42.23594, 650.3254, 1)
routes["Paranoia route"].checkpoints[10].heading = -2.758321
routes["Paranoia route"].checkpoints[10].roadName = "dt_4l_centre_10 AI Road 0"
routes["Paranoia route"].checkpoints[11] = {}
routes["Paranoia route"].checkpoints[11].position = vec.vector(-762.8002, 23.2014, 447.6137, 1)
routes["Paranoia route"].checkpoints[11].heading = -2.351123
routes["Paranoia route"].checkpoints[11].roadName = "dt_10l_centre_01 AI Road 3"
routes["Paranoia route"].checkpoints[12] = {}
routes["Paranoia route"].checkpoints[12].position = vec.vector(-872.0433, 18.28046, 339.8369, 1)
routes["Paranoia route"].checkpoints[12].heading = -2.342498
routes["Paranoia route"].checkpoints[12].roadName = "dt_10l_centre_01 AI Road 2"
routes["Paranoia route"].checkpoints[13] = {}
routes["Paranoia route"].checkpoints[13].position = vec.vector(-1077.568, 19.76089, 306.6261, 1)
routes["Paranoia route"].checkpoints[13].heading = -1.378598
routes["Paranoia route"].checkpoints[13].roadName = "dt_4l_west_06b AI Road 0"
routes["Paranoia route"].checkpoints[14] = {}
routes["Paranoia route"].checkpoints[14].position = vec.vector(-1258.881, 31.80801, 495.3798, 1)
routes["Paranoia route"].checkpoints[14].heading = -1.388581
routes["Paranoia route"].checkpoints[14].roadName = "dt_alleyway_03 AI Road 0"
routes["Paranoia route"].checkpoints[15] = {}
routes["Paranoia route"].checkpoints[15].position = vec.vector(-1463.745, 35.18301, 532.3626, 1)
routes["Paranoia route"].checkpoints[15].heading = -1.405434
routes["Paranoia route"].checkpoints[15].roadName = "dt_shortcut_32 AI Road 0"
routes["Paranoia route"].checkpoints[16] = {}
routes["Paranoia route"].checkpoints[16].position = vec.vector(-1536.03, 38.65583, 628.6755, 1)
routes["Paranoia route"].checkpoints[16].heading = 0.08960906
routes["Paranoia route"].checkpoints[16].roadName = "dt_shortcut_31 AI Road 0"
routes["Paranoia route"].checkpoints[17] = {}
routes["Paranoia route"].checkpoints[17].position = vec.vector(-1799.515, 55.75292, 741.7527, 1)
routes["Paranoia route"].checkpoints[17].heading = -1.17183
routes["Paranoia route"].checkpoints[17].roadName = "ggp_4l_se_07 AI Road 0"
routes["Paranoia route"].checkpoints[18] = {}
routes["Paranoia route"].checkpoints[18].position = vec.vector(-2021.178, 63.90822, 874.4688, 1)
routes["Paranoia route"].checkpoints[18].heading = -1.026236
routes["Paranoia route"].checkpoints[18].roadName = "ggp_4l_ne_04b AI Road 2"
routes["Paranoia route"].checkpoints[19] = {}
routes["Paranoia route"].checkpoints[19].position = vec.vector(-2256.952, 63.89224, 965.0327, 1)
routes["Paranoia route"].checkpoints[19].heading = -1.476982
routes["Paranoia route"].checkpoints[19].roadName = "gg_shortcut_02a AI Road 0"
routes["Paranoia route"].checkpoints[20] = {}
routes["Paranoia route"].checkpoints[20].position = vec.vector(-2593.152, 67.80429, 992.9573, 1)
routes["Paranoia route"].checkpoints[20].heading = -1.408858
routes["Paranoia route"].checkpoints[20].roadName = "gg_shortcut_02b AI Road 1"
routes["Paranoia route"].checkpoints[21] = {}
routes["Paranoia route"].checkpoints[21].position = vec.vector(-2892.34, 65.34854, 930.0665, 1)
routes["Paranoia route"].checkpoints[21].heading = 3.049114
routes["Paranoia route"].checkpoints[21].roadName = "ggp_8l_centre_03 AI Road 1"
routes["Paranoia route"].checkpoints[22] = {}
routes["Paranoia route"].checkpoints[22].position = vec.vector(-3064.196, 63.23012, 776.3703, 1)
routes["Paranoia route"].checkpoints[22].heading = -1.825739
routes["Paranoia route"].checkpoints[22].roadName = "ggp_6l_north_02 AI Road 3"
routes["Paranoia route"].checkpoints[23] = {}
routes["Paranoia route"].checkpoints[23].position = vec.vector(-3350.728, 73.46207, 793.0495, 1)
routes["Paranoia route"].checkpoints[23].heading = -0.7597861
routes["Paranoia route"].checkpoints[23].roadName = "ggp_6l_north_02 AI Road 2"
routes["Paranoia route"].checkpoints[24] = {}
routes["Paranoia route"].checkpoints[24].position = vec.vector(-3536.303, 65.27926, 900.299, 1)
routes["Paranoia route"].checkpoints[24].heading = -1.525478
routes["Paranoia route"].checkpoints[24].roadName = "ggp_shortcut_06 AI Road 0"
routes["Paranoia route"].arrows = {}
routes["Paranoia route"].roads = {}
routes["Paranoia route"].roads[1] = {}
routes["Paranoia route"].roads[1].road = "embargedero_shortcut_02 AI Road 1"
routes["Paranoia route"].roads[1].direction = "against"
routes["Paranoia route"].roads[2] = {}
routes["Paranoia route"].roads[2].road = "sanfran_shortcut_06 AI Road 0"
routes["Paranoia route"].roads[2].direction = "against"
routes["Paranoia route"].roads[3] = {}
routes["Paranoia route"].roads[3].road = "dt_shortcut_02 AI Road 0"
routes["Paranoia route"].roads[3].direction = "against"
routes["Paranoia route"].roads[4] = {}
routes["Paranoia route"].roads[4].road = "dt_shortcut_03b AI Road 2"
routes["Paranoia route"].roads[4].direction = "against"
routes["Paranoia route"].roads[5] = {}
routes["Paranoia route"].roads[5].road = "dt_shortcut_03b AI Road 1"
routes["Paranoia route"].roads[5].direction = "against"
routes["Paranoia route"].roads[6] = {}
routes["Paranoia route"].roads[6].road = "dt_mt_join_unfinished AI Road 0"
routes["Paranoia route"].roads[6].direction = "against"
routes["Paranoia route"].roads[7] = {}
routes["Paranoia route"].roads[7].road = "dt_10l_south_01 AI Road 4"
routes["Paranoia route"].roads[7].direction = "with"
routes["Paranoia route"].roads[8] = {}
routes["Paranoia route"].roads[8].road = "dt_10l_south_01 AI Road 5"
routes["Paranoia route"].roads[8].direction = "with"
routes["Paranoia route"].roads[9] = {}
routes["Paranoia route"].roads[9].road = "dt_10l_south_01 AI Road 6"
routes["Paranoia route"].roads[9].direction = "with"
routes["Paranoia route"].roads[10] = {}
routes["Paranoia route"].roads[10].road = "dt_10l_south_01 AI Road 7"
routes["Paranoia route"].roads[10].direction = "with"
routes["Paranoia route"].roads[11] = {}
routes["Paranoia route"].roads[11].road = "dt_10l_south_01 AI Road 8"
routes["Paranoia route"].roads[11].direction = "with"
routes["Paranoia route"].roads[12] = {}
routes["Paranoia route"].roads[12].road = "dt_10l_south_01 AI Road 9"
routes["Paranoia route"].roads[12].direction = "with"
routes["Paranoia route"].roads[13] = {}
routes["Paranoia route"].roads[13].road = "chinatown_02 AI Road 1"
routes["Paranoia route"].roads[13].direction = "against"
routes["Paranoia route"].roads[14] = {}
routes["Paranoia route"].roads[14].road = "chinatown_02 AI Road 0"
routes["Paranoia route"].roads[14].direction = "against"
routes["Paranoia route"].roads[15] = {}
routes["Paranoia route"].roads[15].road = "dt_4l_centre_03 AI Road 1"
routes["Paranoia route"].roads[15].direction = "with"
routes["Paranoia route"].roads[16] = {}
routes["Paranoia route"].roads[16].road = "dt_4l_centre_10 AI Road 0"
routes["Paranoia route"].roads[16].direction = "against"
routes["Paranoia route"].roads[17] = {}
routes["Paranoia route"].roads[17].road = "dt_4l_centre_04 AI Road 2"
routes["Paranoia route"].roads[17].direction = "with"
routes["Paranoia route"].roads[18] = {}
routes["Paranoia route"].roads[18].road = "dt_10l_centre_01 AI Road 3"
routes["Paranoia route"].roads[18].direction = "against"
routes["Paranoia route"].roads[19] = {}
routes["Paranoia route"].roads[19].road = "dt_10l_centre_01 AI Road 2"
routes["Paranoia route"].roads[19].direction = "against"
routes["Paranoia route"].roads[20] = {}
routes["Paranoia route"].roads[20].road = "dt_4l_west_06b AI Road 1"
routes["Paranoia route"].roads[20].direction = "against"
routes["Paranoia route"].roads[21] = {}
routes["Paranoia route"].roads[21].road = "dt_4l_west_06b AI Road 0"
routes["Paranoia route"].roads[21].direction = "against"
routes["Paranoia route"].roads[22] = {}
routes["Paranoia route"].roads[22].road = "dt_6l_west_01 AI Road 0"
routes["Paranoia route"].roads[22].direction = "with"
routes["Paranoia route"].roads[23] = {}
routes["Paranoia route"].roads[23].road = "dt_alleyway_03 AI Road 0"
routes["Paranoia route"].roads[23].direction = "against"
routes["Paranoia route"].roads[24] = {}
routes["Paranoia route"].roads[24].road = "dt_shortcut_32 AI Road 0"
routes["Paranoia route"].roads[24].direction = "against"
routes["Paranoia route"].roads[25] = {}
routes["Paranoia route"].roads[25].road = "dt_shortcut_31 AI Road 0"
routes["Paranoia route"].roads[25].direction = "against"
routes["Paranoia route"].roads[26] = {}
routes["Paranoia route"].roads[26].road = "dt_4l_centre_08 AI Road 0"
routes["Paranoia route"].roads[26].direction = "against"
routes["Paranoia route"].roads[27] = {}
routes["Paranoia route"].roads[27].road = "ggp_4l_se_07 AI Road 0"
routes["Paranoia route"].roads[27].direction = "against"
routes["Paranoia route"].roads[28] = {}
routes["Paranoia route"].roads[28].road = "ggp_4l_ne_04b AI Road 0"
routes["Paranoia route"].roads[28].direction = "with"
routes["Paranoia route"].roads[29] = {}
routes["Paranoia route"].roads[29].road = "ggp_4l_ne_04b AI Road 1"
routes["Paranoia route"].roads[29].direction = "with"
routes["Paranoia route"].roads[30] = {}
routes["Paranoia route"].roads[30].road = "ggp_4l_ne_04b AI Road 2"
routes["Paranoia route"].roads[30].direction = "with"
routes["Paranoia route"].roads[31] = {}
routes["Paranoia route"].roads[31].road = "ggp_4l_ne_04b AI Road 3"
routes["Paranoia route"].roads[31].direction = "with"
routes["Paranoia route"].roads[32] = {}
routes["Paranoia route"].roads[32].road = "ggp_4l_ne_04b AI Road 4"
routes["Paranoia route"].roads[32].direction = "with"
routes["Paranoia route"].roads[33] = {}
routes["Paranoia route"].roads[33].road = "gg_shortcut_02a AI Road 0"
routes["Paranoia route"].roads[33].direction = "with"
routes["Paranoia route"].roads[34] = {}
routes["Paranoia route"].roads[34].road = "gg_shortcut_02a AI Road 1"
routes["Paranoia route"].roads[34].direction = "with"
routes["Paranoia route"].roads[35] = {}
routes["Paranoia route"].roads[35].road = "gg_shortcut_02b AI Road 0"
routes["Paranoia route"].roads[35].direction = "with"
routes["Paranoia route"].roads[36] = {}
routes["Paranoia route"].roads[36].road = "gg_shortcut_02b AI Road 1"
routes["Paranoia route"].roads[36].direction = "with"
routes["Paranoia route"].roads[37] = {}
routes["Paranoia route"].roads[37].road = "gg_shortcut_02b AI Road 2"
routes["Paranoia route"].roads[37].direction = "with"
routes["Paranoia route"].roads[38] = {}
routes["Paranoia route"].roads[38].road = "ggp_shortcut_07 AI Road 3"
routes["Paranoia route"].roads[38].direction = "against"
routes["Paranoia route"].roads[39] = {}
routes["Paranoia route"].roads[39].road = "ggp_8l_centre_03 AI Road 1"
routes["Paranoia route"].roads[39].direction = "against"
routes["Paranoia route"].roads[40] = {}
routes["Paranoia route"].roads[40].road = "ggp_8l_centre_03 AI Road 0"
routes["Paranoia route"].roads[40].direction = "against"
routes["Paranoia route"].roads[41] = {}
routes["Paranoia route"].roads[41].road = "ggp_6l_north_02 AI Road 3"
routes["Paranoia route"].roads[41].direction = "against"
routes["Paranoia route"].roads[42] = {}
routes["Paranoia route"].roads[42].road = "ggp_6l_north_02 AI Road 2"
routes["Paranoia route"].roads[42].direction = "against"
routes["Paranoia route"].roads[43] = {}
routes["Paranoia route"].roads[43].road = "ggp_shortcut_06 AI Road 0"
routes["Paranoia route"].roads[43].direction = "against"
