routes = routes or {}
routes.WreckedEvidenceWarmupRoute = {}
routes.WreckedEvidenceWarmupRoute.checkpoints = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[1] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[1].position = vec.vector(-1393.996, 34.34471, 448.1978, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[1].heading = 0.2016322
routes.WreckedEvidenceWarmupRoute.checkpoints[1].roadName = "dt_8l_centre_01ab AI Road 2"
routes.WreckedEvidenceWarmupRoute.checkpoints[2] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[2].position = vec.vector(-1352.882, 42.375, 638.3593, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[2].heading = 0.2254235
routes.WreckedEvidenceWarmupRoute.checkpoints[2].roadName = "dt_8l_centre_01ab AI Road 4"
routes.WreckedEvidenceWarmupRoute.checkpoints[3] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[3].position = vec.vector(-1450.605, 42.42964, 700.5549, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[3].heading = -1.36612
routes.WreckedEvidenceWarmupRoute.checkpoints[3].roadName = "dt_4l_centre_08 AI Road 1"
routes.WreckedEvidenceWarmupRoute.checkpoints[4] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[4].position = vec.vector(-1574.614, 45.08865, 721.6426, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[4].heading = -1.465721
routes.WreckedEvidenceWarmupRoute.checkpoints[4].roadName = "dt_4l_centre_08 AI Road 0"
routes.WreckedEvidenceWarmupRoute.checkpoints[5] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[5].position = vec.vector(-1690.433, 45.69685, 605.6697, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[5].heading = -3.127949
routes.WreckedEvidenceWarmupRoute.checkpoints[5].roadName = "dt__8l_west_01 AI Road 5"
routes.WreckedEvidenceWarmupRoute.checkpoints[6] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[6].position = vec.vector(-1691.282, 41.05079, 517.968, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[6].heading = -3.132394
routes.WreckedEvidenceWarmupRoute.checkpoints[6].roadName = "dt__8l_west_01 AI Road 4"
routes.WreckedEvidenceWarmupRoute.checkpoints[7] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[7].position = vec.vector(-1692.215, 31.10692, 312.5625, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[7].heading = -3.137608
routes.WreckedEvidenceWarmupRoute.checkpoints[7].roadName = "dt__8l_west_01 AI Road 3"
routes.WreckedEvidenceWarmupRoute.checkpoints[8] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[8].position = vec.vector(-1692.508, 27.43324, 238.4155, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[8].heading = -3.13765
routes.WreckedEvidenceWarmupRoute.checkpoints[8].roadName = "dt__8l_west_01 AI Road 2"
routes.WreckedEvidenceWarmupRoute.checkpoints[9] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[9].position = vec.vector(-1692.601, 19.70505, 99.49592, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[9].heading = 3.141593
routes.WreckedEvidenceWarmupRoute.checkpoints[9].roadName = "dt__8l_west_01 AI Road 1"
routes.WreckedEvidenceWarmupRoute.checkpoints[10] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[10].position = vec.vector(-1682.259, 9.010722, -77.88372, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[10].heading = 2.921606
routes.WreckedEvidenceWarmupRoute.checkpoints[10].roadName = "dt_8l_north_04 AI Road 0"
routes.WreckedEvidenceWarmupRoute.checkpoints[11] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[11].position = vec.vector(-1467.439, 4.999999, -159.7316, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[11].heading = 1.441531
routes.WreckedEvidenceWarmupRoute.checkpoints[11].roadName = "dt_8l_north_04 AI Road 1"
routes.WreckedEvidenceWarmupRoute.checkpoints[12] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[12].position = vec.vector(-1208.202, 9.938437, 6.373925, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[12].heading = 0.7900817
routes.WreckedEvidenceWarmupRoute.checkpoints[12].roadName = "dt_10l_centre_01 AI Road 0"
routes.WreckedEvidenceWarmupRoute.checkpoints[13] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[13].position = vec.vector(-1019.926, 15.66622, 192.8991, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[13].heading = 0.7900905
routes.WreckedEvidenceWarmupRoute.checkpoints[13].roadName = "dt_10l_centre_01 AI Road 1"
routes.WreckedEvidenceWarmupRoute.checkpoints[14] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[14].position = vec.vector(-1002.128, 17, 292.3536, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[14].heading = -1.38487
routes.WreckedEvidenceWarmupRoute.checkpoints[14].roadName = "dt_4l_west_06b AI Road 1"
routes.WreckedEvidenceWarmupRoute.checkpoints[15] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[15].position = vec.vector(-1073.661, 19.07546, 305.8665, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[15].heading = -1.378652
routes.WreckedEvidenceWarmupRoute.checkpoints[15].roadName = "dt_4l_west_06b AI Road 0"
routes.WreckedEvidenceWarmupRoute.checkpoints[16] = {}
routes.WreckedEvidenceWarmupRoute.checkpoints[16].position = vec.vector(-1303.615, 34.24443, 352.0136, 1)
routes.WreckedEvidenceWarmupRoute.checkpoints[16].heading = -1.375249
routes.WreckedEvidenceWarmupRoute.checkpoints[16].roadName = "dt_6l_west_03b AI Road 0"
routes.WreckedEvidenceWarmupRoute.arrows = {}
routes.WreckedEvidenceWarmupRoute.roads = {}
routes.WreckedEvidenceWarmupRoute.roads[1] = {}
routes.WreckedEvidenceWarmupRoute.roads[1].road = "dt_8l_centre_01ab AI Road 2"
routes.WreckedEvidenceWarmupRoute.roads[1].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[2] = {}
routes.WreckedEvidenceWarmupRoute.roads[2].road = "dt_8l_centre_01ab AI Road 3"
routes.WreckedEvidenceWarmupRoute.roads[2].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[3] = {}
routes.WreckedEvidenceWarmupRoute.roads[3].road = "dt_8l_centre_01ab AI Road 4"
routes.WreckedEvidenceWarmupRoute.roads[3].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[4] = {}
routes.WreckedEvidenceWarmupRoute.roads[4].road = "dt_4l_centre_08 AI Road 2"
routes.WreckedEvidenceWarmupRoute.roads[4].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[5] = {}
routes.WreckedEvidenceWarmupRoute.roads[5].road = "dt_4l_centre_08 AI Road 1"
routes.WreckedEvidenceWarmupRoute.roads[5].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[6] = {}
routes.WreckedEvidenceWarmupRoute.roads[6].road = "dt_4l_centre_08 AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[6].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[7] = {}
routes.WreckedEvidenceWarmupRoute.roads[7].road = "dt__8l_west_01 AI Road 6"
routes.WreckedEvidenceWarmupRoute.roads[7].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[8] = {}
routes.WreckedEvidenceWarmupRoute.roads[8].road = "dt__8l_west_01 AI Road 5"
routes.WreckedEvidenceWarmupRoute.roads[8].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[9] = {}
routes.WreckedEvidenceWarmupRoute.roads[9].road = "dt__8l_west_01 AI Road 4"
routes.WreckedEvidenceWarmupRoute.roads[9].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[10] = {}
routes.WreckedEvidenceWarmupRoute.roads[10].road = "dt__8l_west_01 AI Road 3"
routes.WreckedEvidenceWarmupRoute.roads[10].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[11] = {}
routes.WreckedEvidenceWarmupRoute.roads[11].road = "dt__8l_west_01 AI Road 2"
routes.WreckedEvidenceWarmupRoute.roads[11].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[12] = {}
routes.WreckedEvidenceWarmupRoute.roads[12].road = "dt__8l_west_01 AI Road 1"
routes.WreckedEvidenceWarmupRoute.roads[12].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[13] = {}
routes.WreckedEvidenceWarmupRoute.roads[13].road = "dt__8l_west_01 AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[13].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[14] = {}
routes.WreckedEvidenceWarmupRoute.roads[14].road = "dt_8l_north_04 AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[14].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[15] = {}
routes.WreckedEvidenceWarmupRoute.roads[15].road = "dt_8l_north_04 AI Road 1"
routes.WreckedEvidenceWarmupRoute.roads[15].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[16] = {}
routes.WreckedEvidenceWarmupRoute.roads[16].road = "dt_8l_north_04 AI Road 2"
routes.WreckedEvidenceWarmupRoute.roads[16].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[17] = {}
routes.WreckedEvidenceWarmupRoute.roads[17].road = "dt_10l_centre_01 AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[17].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[18] = {}
routes.WreckedEvidenceWarmupRoute.roads[18].road = "dt_10l_centre_01 AI Road 1"
routes.WreckedEvidenceWarmupRoute.roads[18].direction = "with"
routes.WreckedEvidenceWarmupRoute.roads[19] = {}
routes.WreckedEvidenceWarmupRoute.roads[19].road = "dt_4l_west_06b AI Road 1"
routes.WreckedEvidenceWarmupRoute.roads[19].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[20] = {}
routes.WreckedEvidenceWarmupRoute.roads[20].road = "dt_4l_west_06b AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[20].direction = "against"
routes.WreckedEvidenceWarmupRoute.roads[21] = {}
routes.WreckedEvidenceWarmupRoute.roads[21].road = "dt_6l_west_03b AI Road 0"
routes.WreckedEvidenceWarmupRoute.roads[21].direction = "against"
