routes = routes or {}
routes["Epilogue tanner route"] = {}
routes["Epilogue tanner route"].checkpoints = {}
routes["Epilogue tanner route"].checkpoints[1] = {}
routes["Epilogue tanner route"].checkpoints[1].position = vec.vector(1151.862, 28.78798, 1816.504, 1)
routes["Epilogue tanner route"].checkpoints[1].heading = -1.040166
routes["Epilogue tanner route"].checkpoints[1].roadName = "bb_sliproad_02 AI Road 0"
routes["Epilogue tanner route"].checkpoints[2] = {}
routes["Epilogue tanner route"].checkpoints[2].position = vec.vector(997.7608, 5.974995, 1507.059, 1)
routes["Epilogue tanner route"].checkpoints[2].heading = 0.775135
routes["Epilogue tanner route"].checkpoints[2].roadName = "mt_6l_e_02 AI Road 1"
routes["Epilogue tanner route"].arrows = {}
routes["Epilogue tanner route"].roads = {}
routes["Epilogue tanner route"].roads[1] = {}
routes["Epilogue tanner route"].roads[1].road = "superhighway_split_01 AI Road 0"
routes["Epilogue tanner route"].roads[1].direction = "against"
routes["Epilogue tanner route"].roads[2] = {}
routes["Epilogue tanner route"].roads[2].road = "highway01_16b AI Road 29"
routes["Epilogue tanner route"].roads[2].direction = "against"
routes["Epilogue tanner route"].roads[3] = {}
routes["Epilogue tanner route"].roads[3].road = "highway01_16b AI Road 28"
routes["Epilogue tanner route"].roads[3].direction = "against"
routes["Epilogue tanner route"].roads[4] = {}
routes["Epilogue tanner route"].roads[4].road = "highway01_16b AI Road 27"
routes["Epilogue tanner route"].roads[4].direction = "against"
routes["Epilogue tanner route"].roads[5] = {}
routes["Epilogue tanner route"].roads[5].road = "highway01_16b AI Road 26"
routes["Epilogue tanner route"].roads[5].direction = "against"
routes["Epilogue tanner route"].roads[6] = {}
routes["Epilogue tanner route"].roads[6].road = "highway01_16b AI Road 25"
routes["Epilogue tanner route"].roads[6].direction = "against"
routes["Epilogue tanner route"].roads[7] = {}
routes["Epilogue tanner route"].roads[7].road = "highway01_16b AI Road 24"
routes["Epilogue tanner route"].roads[7].direction = "against"
routes["Epilogue tanner route"].roads[8] = {}
routes["Epilogue tanner route"].roads[8].road = "highway01_16b AI Road 23"
routes["Epilogue tanner route"].roads[8].direction = "against"
routes["Epilogue tanner route"].roads[9] = {}
routes["Epilogue tanner route"].roads[9].road = "highway01_16b AI Road 22"
routes["Epilogue tanner route"].roads[9].direction = "against"
routes["Epilogue tanner route"].roads[10] = {}
routes["Epilogue tanner route"].roads[10].road = "highway01_16b AI Road 21"
routes["Epilogue tanner route"].roads[10].direction = "against"
routes["Epilogue tanner route"].roads[11] = {}
routes["Epilogue tanner route"].roads[11].road = "highway01_16b AI Road 20"
routes["Epilogue tanner route"].roads[11].direction = "against"
routes["Epilogue tanner route"].roads[12] = {}
routes["Epilogue tanner route"].roads[12].road = "bb_sliproad_02 AI Road 0"
routes["Epilogue tanner route"].roads[12].direction = "against"
routes["Epilogue tanner route"].roads[13] = {}
routes["Epilogue tanner route"].roads[13].road = "mt_10l_centre_03b AI Road 1"
routes["Epilogue tanner route"].roads[13].direction = "against"
routes["Epilogue tanner route"].roads[14] = {}
routes["Epilogue tanner route"].roads[14].road = "mt_10l_centre_03b AI Road 0"
routes["Epilogue tanner route"].roads[14].direction = "against"
routes["Epilogue tanner route"].roads[15] = {}
routes["Epilogue tanner route"].roads[15].road = "mt_10l_south_02 AI Road 0"
routes["Epilogue tanner route"].roads[15].direction = "with"
routes["Epilogue tanner route"].roads[16] = {}
routes["Epilogue tanner route"].roads[16].road = "mt_6l_e_02 AI Road 0"
routes["Epilogue tanner route"].roads[16].direction = "with"
routes["Epilogue tanner route"].roads[17] = {}
routes["Epilogue tanner route"].roads[17].road = "mt_6l_e_02 AI Road 1"
routes["Epilogue tanner route"].roads[17].direction = "with"
routes["Civ route 1"] = {}
routes["Civ route 1"].checkpoints = {}
routes["Civ route 1"].checkpoints[1] = {}
routes["Civ route 1"].checkpoints[1].position = vec.vector(446.5909, 8, 1310.797, 1)
routes["Civ route 1"].checkpoints[1].heading = -2.473502
routes["Civ route 1"].checkpoints[1].roadName = "barcelero_alleyway_01 AI Road 0"
routes["Civ route 1"].arrows = {}
routes["Civ route 1"].roads = {}
routes["Civ route 1"].roads[1] = {}
routes["Civ route 1"].roads[1].road = "highway01_16b AI Road 21"
routes["Civ route 1"].roads[1].direction = "against"
routes["Civ route 1"].roads[2] = {}
routes["Civ route 1"].roads[2].road = "highway01_16b AI Road 20"
routes["Civ route 1"].roads[2].direction = "against"
routes["Civ route 1"].roads[3] = {}
routes["Civ route 1"].roads[3].road = "bb_sliproad_02 AI Road 0"
routes["Civ route 1"].roads[3].direction = "against"
routes["Civ route 1"].roads[4] = {}
routes["Civ route 1"].roads[4].road = "mt_10l_centre_03b AI Road 1"
routes["Civ route 1"].roads[4].direction = "against"
routes["Civ route 1"].roads[5] = {}
routes["Civ route 1"].roads[5].road = "mt_10l_centre_03b AI Road 0"
routes["Civ route 1"].roads[5].direction = "against"
routes["Civ route 1"].roads[6] = {}
routes["Civ route 1"].roads[6].road = "barcelero_alleyway_01 AI Road 1"
routes["Civ route 1"].roads[6].direction = "against"
routes["Civ route 1"].roads[7] = {}
routes["Civ route 1"].roads[7].road = "barcelero_alleyway_01 AI Road 0"
routes["Civ route 1"].roads[7].direction = "against"
routes["Impatient 1"] = {}
routes["Impatient 1"].checkpoints = {}
routes["Impatient 1"].checkpoints[1] = {}
routes["Impatient 1"].checkpoints[1].position = vec.vector(2678.383, 30.21342, -453.4354, 1)
routes["Impatient 1"].checkpoints[1].heading = -2.820848
routes["Impatient 1"].checkpoints[1].roadName = "superhighway_road_01 AI Road 3"
routes["Impatient 1"].checkpoints[2] = {}
routes["Impatient 1"].checkpoints[2].position = vec.vector(2794.943, 20, -800.081, 1)
routes["Impatient 1"].checkpoints[2].heading = 2.020761
routes["Impatient 1"].checkpoints[2].roadName = "superhighway_road_01 AI Road 1"
routes["Impatient 1"].arrows = {}
routes["Impatient 1"].roads = {}
routes["Impatient 1"].roads[1] = {}
routes["Impatient 1"].roads[1].road = "superhighway_road_01 AI Road 3"
routes["Impatient 1"].roads[1].direction = "against"
routes["Impatient 1"].roads[2] = {}
routes["Impatient 1"].roads[2].road = "superhighway_road_01 AI Road 2"
routes["Impatient 1"].roads[2].direction = "against"
routes["Impatient 1"].roads[3] = {}
routes["Impatient 1"].roads[3].road = "superhighway_road_01 AI Road 1"
routes["Impatient 1"].roads[3].direction = "against"
routes["Second cop chase"] = {}
routes["Second cop chase"].checkpoints = {}
routes["Second cop chase"].checkpoints[1] = {}
routes["Second cop chase"].checkpoints[1].position = vec.vector(645.1876, 5.974995, 1175.62, 1)
routes["Second cop chase"].checkpoints[1].heading = -2.320139
routes["Second cop chase"].checkpoints[1].roadName = "sanfran_shortcut_06 AI Road 0"
routes["Second cop chase"].arrows = {}
routes["Second cop chase"].roads = {}
routes["Second cop chase"].roads[1] = {}
routes["Second cop chase"].roads[1].road = "mt_6l_e_02 AI Road 0"
routes["Second cop chase"].roads[1].direction = "against"
routes["Second cop chase"].roads[2] = {}
routes["Second cop chase"].roads[2].road = "sanfran_shortcut_06 AI Road 1"
routes["Second cop chase"].roads[2].direction = "against"
routes["Second cop chase"].roads[3] = {}
routes["Second cop chase"].roads[3].road = "sanfran_shortcut_06 AI Road 0"
routes["Second cop chase"].roads[3].direction = "against"
