routes = routes or {}
routes["Epilogue jericho"] = {}
routes["Epilogue jericho"].checkpoints = {}
routes["Epilogue jericho"].checkpoints[1] = {}
routes["Epilogue jericho"].checkpoints[1].position = vec.vector(1159.13, 5.974995, 1662.762, 1)
routes["Epilogue jericho"].checkpoints[1].heading = 0.808474
routes["Epilogue jericho"].checkpoints[1].roadName = "mt_6l_e_02 AI Road 3"
routes["Epilogue jericho"].checkpoints[2] = {}
routes["Epilogue jericho"].checkpoints[2].position = vec.vector(1384.172, 5.974996, 1877.645, 1)
routes["Epilogue jericho"].checkpoints[2].heading = 0.8084874
routes["Epilogue jericho"].checkpoints[2].roadName = "mt_6l_e_02 AI Road 5"
routes["Epilogue jericho"].checkpoints[3] = {}
routes["Epilogue jericho"].checkpoints[3].position = vec.vector(1476.808, 6.011291, 2062.521, 1)
routes["Epilogue jericho"].checkpoints[3].heading = 0.02552572
routes["Epilogue jericho"].checkpoints[3].roadName = "mt_10l_south_01 AI Road 1"
routes["Epilogue jericho"].checkpoints[4] = {}
routes["Epilogue jericho"].checkpoints[4].position = vec.vector(1480.848, 7.387692, 2224.29, 1)
routes["Epilogue jericho"].checkpoints[4].heading = 0.02376166
routes["Epilogue jericho"].checkpoints[4].roadName = "mt_10l_south_01 AI Road 1"
routes["Epilogue jericho"].checkpoints[5] = {}
routes["Epilogue jericho"].checkpoints[5].position = vec.vector(1319.003, 8.249997, 2474.863, 1)
routes["Epilogue jericho"].checkpoints[5].heading = -0.8700861
routes["Epilogue jericho"].checkpoints[5].roadName = "mt_10l_south_01 AI Road 0"
routes["Epilogue jericho"].checkpoints[6] = {}
routes["Epilogue jericho"].checkpoints[6].position = vec.vector(1317.648, 8.250001, 2655.811, 1)
routes["Epilogue jericho"].checkpoints[6].heading = 0.6225731
routes["Epilogue jericho"].checkpoints[6].roadName = "sutro_10l_se_01_01 AI Road 10"
routes["Epilogue jericho"].checkpoints[7] = {}
routes["Epilogue jericho"].checkpoints[7].position = vec.vector(1307.085, 8.250001, 2919.635, 1)
routes["Epilogue jericho"].checkpoints[7].heading = -0.06545511
routes["Epilogue jericho"].checkpoints[7].roadName = "sutro_shortcut_07 AI Road 3"
routes["Epilogue jericho"].checkpoints[8] = {}
routes["Epilogue jericho"].checkpoints[8].position = vec.vector(1305.007, 8.25, 3110.781, 1)
routes["Epilogue jericho"].checkpoints[8].heading = -0.004640492
routes["Epilogue jericho"].checkpoints[8].roadName = "sutro_shortcut_07 AI Road 3"
routes["Epilogue jericho"].checkpoints[9] = {}
routes["Epilogue jericho"].checkpoints[9].position = vec.vector(1275.42, 8.25, 3312.961, 1)
routes["Epilogue jericho"].checkpoints[9].heading = -0.6567225
routes["Epilogue jericho"].checkpoints[9].roadName = "sutro_shortcut_07 AI Road 2"
routes["Epilogue jericho"].checkpoints[10] = {}
routes["Epilogue jericho"].checkpoints[10].position = vec.vector(895.1965, 8.401382, 3355, 1)
routes["Epilogue jericho"].checkpoints[10].heading = -1.570796
routes["Epilogue jericho"].checkpoints[10].roadName = "sutro_6l_east_02 AI Road 3"
routes["Epilogue jericho"].checkpoints[11] = {}
routes["Epilogue jericho"].checkpoints[11].position = vec.vector(788.1776, 10.25167, 3355, 1)
routes["Epilogue jericho"].checkpoints[11].heading = -1.570796
routes["Epilogue jericho"].checkpoints[11].roadName = "sutro_6l_east_02 AI Road 2"
routes["Epilogue jericho"].checkpoints[12] = {}
routes["Epilogue jericho"].checkpoints[12].position = vec.vector(486.8961, 14.75, 3355, 1)
routes["Epilogue jericho"].checkpoints[12].heading = -1.570796
routes["Epilogue jericho"].checkpoints[12].roadName = "sutro_6l_east_02 AI Road 1"
routes["Epilogue jericho"].checkpoints[13] = {}
routes["Epilogue jericho"].checkpoints[13].position = vec.vector(365.7165, 14.75, 3328.068, 1)
routes["Epilogue jericho"].checkpoints[13].heading = -1.889821
routes["Epilogue jericho"].checkpoints[13].roadName = "sutro_6l_east_02 AI Road 0"
routes["Epilogue jericho"].checkpoints[14] = {}
routes["Epilogue jericho"].checkpoints[14].position = vec.vector(-246.3343, 61.3227, 3283.478, 1)
routes["Epilogue jericho"].checkpoints[14].heading = -1.572725
routes["Epilogue jericho"].checkpoints[14].roadName = "sutro_8l_east_01 AI Road 3"
routes["Epilogue jericho"].checkpoints[15] = {}
routes["Epilogue jericho"].checkpoints[15].position = vec.vector(-269.3717, 84.52009, 3403.883, 1)
routes["Epilogue jericho"].checkpoints[15].heading = 1.440069
routes["Epilogue jericho"].checkpoints[15].roadName = "sutro_6l_se_01 AI Road 5"
routes["Epilogue jericho"].checkpoints[16] = {}
routes["Epilogue jericho"].checkpoints[16].position = vec.vector(366.0107, 14.29487, 3530.701, 1)
routes["Epilogue jericho"].checkpoints[16].heading = 1.57076
routes["Epilogue jericho"].checkpoints[16].roadName = "sutro_10l_se_01_01 AI Road 2"
routes["Epilogue jericho"].checkpoints[17] = {}
routes["Epilogue jericho"].checkpoints[17].position = vec.vector(615.1251, 8.25, 3610, 1)
routes["Epilogue jericho"].checkpoints[17].heading = 1.570796
routes["Epilogue jericho"].checkpoints[17].roadName = "r219_helper_01 AI Road 0"
routes["Epilogue jericho"].checkpoints[18] = {}
routes["Epilogue jericho"].checkpoints[18].position = vec.vector(863.3121, 8.25, 3610, 1)
routes["Epilogue jericho"].checkpoints[18].heading = 1.570796
routes["Epilogue jericho"].checkpoints[18].roadName = "r219_helper_01 AI Road 0"
routes["Epilogue jericho"].checkpoints[19] = {}
routes["Epilogue jericho"].checkpoints[19].position = vec.vector(898.7365, 8.249998, 3731.639, 1)
routes["Epilogue jericho"].checkpoints[19].heading = -0.7346231
routes["Epilogue jericho"].checkpoints[19].roadName = "sutro_6l_south_01b AI Road 3"
routes["Epilogue jericho"].checkpoints[20] = {}
routes["Epilogue jericho"].checkpoints[20].position = vec.vector(608.3951, 8.249998, 3885.198, 1)
routes["Epilogue jericho"].checkpoints[20].heading = -1.570748
routes["Epilogue jericho"].checkpoints[20].roadName = "sutro_6l_south_01b AI Road 1"
routes["Epilogue jericho"].arrows = {}
routes["Epilogue jericho"].roads = {}
routes["Epilogue jericho"].roads[1] = {}
routes["Epilogue jericho"].roads[1].road = "mt_6l_e_02 AI Road 3"
routes["Epilogue jericho"].roads[1].direction = "with"
routes["Epilogue jericho"].roads[2] = {}
routes["Epilogue jericho"].roads[2].road = "mt_6l_e_02 AI Road 4"
routes["Epilogue jericho"].roads[2].direction = "with"
routes["Epilogue jericho"].roads[3] = {}
routes["Epilogue jericho"].roads[3].road = "mt_6l_e_02 AI Road 5"
routes["Epilogue jericho"].roads[3].direction = "with"
routes["Epilogue jericho"].roads[4] = {}
routes["Epilogue jericho"].roads[4].road = "mt_10l_south_01 AI Road 1"
routes["Epilogue jericho"].roads[4].direction = "against"
routes["Epilogue jericho"].roads[5] = {}
routes["Epilogue jericho"].roads[5].road = "mt_10l_south_01 AI Road 0"
routes["Epilogue jericho"].roads[5].direction = "against"
routes["Epilogue jericho"].roads[6] = {}
routes["Epilogue jericho"].roads[6].road = "sutro_10l_se_01_01 AI Road 10"
routes["Epilogue jericho"].roads[6].direction = "against"
routes["Epilogue jericho"].roads[7] = {}
routes["Epilogue jericho"].roads[7].road = "sutro_shortcut_07 AI Road 3"
routes["Epilogue jericho"].roads[7].direction = "against"
routes["Epilogue jericho"].roads[8] = {}
routes["Epilogue jericho"].roads[8].road = "sutro_shortcut_07 AI Road 2"
routes["Epilogue jericho"].roads[8].direction = "against"
routes["Epilogue jericho"].roads[9] = {}
routes["Epilogue jericho"].roads[9].road = "sutro_shortcut_07 AI Road 1"
routes["Epilogue jericho"].roads[9].direction = "against"
routes["Epilogue jericho"].roads[10] = {}
routes["Epilogue jericho"].roads[10].road = "sutro_shortcut_07 AI Road 0"
routes["Epilogue jericho"].roads[10].direction = "against"
routes["Epilogue jericho"].roads[11] = {}
routes["Epilogue jericho"].roads[11].road = "sutro_6l_east_02 AI Road 3"
routes["Epilogue jericho"].roads[11].direction = "against"
routes["Epilogue jericho"].roads[12] = {}
routes["Epilogue jericho"].roads[12].road = "sutro_6l_east_02 AI Road 2"
routes["Epilogue jericho"].roads[12].direction = "against"
routes["Epilogue jericho"].roads[13] = {}
routes["Epilogue jericho"].roads[13].road = "sutro_6l_east_02 AI Road 1"
routes["Epilogue jericho"].roads[13].direction = "against"
routes["Epilogue jericho"].roads[14] = {}
routes["Epilogue jericho"].roads[14].road = "sutro_6l_east_02 AI Road 0"
routes["Epilogue jericho"].roads[14].direction = "against"
routes["Epilogue jericho"].roads[15] = {}
routes["Epilogue jericho"].roads[15].road = "sutro_shortcut_02 AI Road 0"
routes["Epilogue jericho"].roads[15].direction = "against"
routes["Epilogue jericho"].roads[16] = {}
routes["Epilogue jericho"].roads[16].road = "sutro_8l_east_01 AI Road 3"
routes["Epilogue jericho"].roads[16].direction = "against"
routes["Epilogue jericho"].roads[17] = {}
routes["Epilogue jericho"].roads[17].road = "sutro_6l_se_01 AI Road 5"
routes["Epilogue jericho"].roads[17].direction = "against"
routes["Epilogue jericho"].roads[18] = {}
routes["Epilogue jericho"].roads[18].road = "ai_helper_r217_01 AI Road 0"
routes["Epilogue jericho"].roads[18].direction = "with"
routes["Epilogue jericho"].roads[19] = {}
routes["Epilogue jericho"].roads[19].road = "sutro_10l_se_01_01 AI Road 1"
routes["Epilogue jericho"].roads[19].direction = "with"
routes["Epilogue jericho"].roads[20] = {}
routes["Epilogue jericho"].roads[20].road = "sutro_10l_se_01_01 AI Road 2"
routes["Epilogue jericho"].roads[20].direction = "with"
routes["Epilogue jericho"].roads[21] = {}
routes["Epilogue jericho"].roads[21].road = "sutro_10l_se_01_01 AI Road 3"
routes["Epilogue jericho"].roads[21].direction = "with"
routes["Epilogue jericho"].roads[22] = {}
routes["Epilogue jericho"].roads[22].road = "sutro_6l_east_04 AI Road 0"
routes["Epilogue jericho"].roads[22].direction = "with"
routes["Epilogue jericho"].roads[23] = {}
routes["Epilogue jericho"].roads[23].road = "r219_helper_01 AI Road 0"
routes["Epilogue jericho"].roads[23].direction = "against"
routes["Epilogue jericho"].roads[24] = {}
routes["Epilogue jericho"].roads[24].road = "sutro_6l_south_01b AI Road 4"
routes["Epilogue jericho"].roads[24].direction = "against"
routes["Epilogue jericho"].roads[25] = {}
routes["Epilogue jericho"].roads[25].road = "sutro_6l_south_01b AI Road 3"
routes["Epilogue jericho"].roads[25].direction = "against"
routes["Epilogue jericho"].roads[26] = {}
routes["Epilogue jericho"].roads[26].road = "sutro_6l_south_01b AI Road 2"
routes["Epilogue jericho"].roads[26].direction = "against"
routes["Epilogue jericho"].roads[27] = {}
routes["Epilogue jericho"].roads[27].road = "sutro_6l_south_01b AI Road 1"
routes["Epilogue jericho"].roads[27].direction = "against"
routes["Epilogue Emergency Route"] = {}
routes["Epilogue Emergency Route"].checkpoints = {}
routes["Epilogue Emergency Route"].checkpoints[1] = {}
routes["Epilogue Emergency Route"].checkpoints[1].position = vec.vector(1202.566, 8.401021, 3164.326, 1)
routes["Epilogue Emergency Route"].checkpoints[1].heading = 1.571307
routes["Epilogue Emergency Route"].checkpoints[1].roadName = "sutro_8l_east_03e AI Road 1"
routes["Epilogue Emergency Route"].checkpoints[2] = {}
routes["Epilogue Emergency Route"].checkpoints[2].position = vec.vector(1371.778, 8.25, 3363.669, 1)
routes["Epilogue Emergency Route"].checkpoints[2].heading = -0.4624547
routes["Epilogue Emergency Route"].checkpoints[2].roadName = "sutro_10l_se_01_01 AI Road 7"
routes["Epilogue Emergency Route"].checkpoints[3] = {}
routes["Epilogue Emergency Route"].checkpoints[3].position = vec.vector(-532.3583, 73.54951, 3286.199, 1)
routes["Epilogue Emergency Route"].checkpoints[3].heading = -1.639276
routes["Epilogue Emergency Route"].checkpoints[3].roadName = "sutro_8l_east_01 AI Road 2"
routes["Epilogue Emergency Route"].arrows = {}
routes["Epilogue Emergency Route"].roads = {}
routes["Epilogue Emergency Route"].roads[1] = {}
routes["Epilogue Emergency Route"].roads[1].road = "sutro_8l_east_03e AI Road 1"
routes["Epilogue Emergency Route"].roads[1].direction = "against"
routes["Epilogue Emergency Route"].roads[2] = {}
routes["Epilogue Emergency Route"].roads[2].road = "sutro_8l_east_03e AI Road 0"
routes["Epilogue Emergency Route"].roads[2].direction = "against"
routes["Epilogue Emergency Route"].roads[3] = {}
routes["Epilogue Emergency Route"].roads[3].road = "sutro_10l_se_01_01 AI Road 8"
routes["Epilogue Emergency Route"].roads[3].direction = "against"
routes["Epilogue Emergency Route"].roads[4] = {}
routes["Epilogue Emergency Route"].roads[4].road = "sutro_10l_se_01_01 AI Road 7"
routes["Epilogue Emergency Route"].roads[4].direction = "against"
routes["Epilogue Emergency Route"].roads[5] = {}
routes["Epilogue Emergency Route"].roads[5].road = "sutro_10l_se_01_01 AI Road 6"
routes["Epilogue Emergency Route"].roads[5].direction = "against"
routes["Epilogue Emergency Route"].roads[6] = {}
routes["Epilogue Emergency Route"].roads[6].road = "sutro_10l_se_01_01 AI Road 5"
routes["Epilogue Emergency Route"].roads[6].direction = "against"
routes["Epilogue Emergency Route"].roads[7] = {}
routes["Epilogue Emergency Route"].roads[7].road = "sutro_10l_se_01_01 AI Road 4"
routes["Epilogue Emergency Route"].roads[7].direction = "against"
routes["Epilogue Emergency Route"].roads[8] = {}
routes["Epilogue Emergency Route"].roads[8].road = "sutro_10l_se_01_01 AI Road 3"
routes["Epilogue Emergency Route"].roads[8].direction = "against"
routes["Epilogue Emergency Route"].roads[9] = {}
routes["Epilogue Emergency Route"].roads[9].road = "sutro_10l_se_01_01 AI Road 2"
routes["Epilogue Emergency Route"].roads[9].direction = "against"
routes["Epilogue Emergency Route"].roads[10] = {}
routes["Epilogue Emergency Route"].roads[10].road = "sutro_6l_east_03 AI Road 4"
routes["Epilogue Emergency Route"].roads[10].direction = "against"
routes["Epilogue Emergency Route"].roads[11] = {}
routes["Epilogue Emergency Route"].roads[11].road = "sutro_shortcut_02 AI Road 0"
routes["Epilogue Emergency Route"].roads[11].direction = "against"
routes["Epilogue Emergency Route"].roads[12] = {}
routes["Epilogue Emergency Route"].roads[12].road = "sutro_8l_east_01 AI Road 3"
routes["Epilogue Emergency Route"].roads[12].direction = "against"
routes["Epilogue Emergency Route"].roads[13] = {}
routes["Epilogue Emergency Route"].roads[13].road = "sutro_8l_east_01 AI Road 2"
routes["Epilogue Emergency Route"].roads[13].direction = "against"
routes["Epilogue jericho loop"] = {}
routes["Epilogue jericho loop"].checkpoints = {}
routes["Epilogue jericho loop"].checkpoints[1] = {}
routes["Epilogue jericho loop"].checkpoints[1].position = vec.vector(464.2076, 8.249997, 3885, 1)
routes["Epilogue jericho loop"].checkpoints[1].heading = -1.571223
routes["Epilogue jericho loop"].checkpoints[1].roadName = "sutro_6l_south_01b AI Road 0"
routes["Epilogue jericho loop"].checkpoints[2] = {}
routes["Epilogue jericho loop"].checkpoints[2].position = vec.vector(321.4016, 16.83885, 3883.804, 1)
routes["Epilogue jericho loop"].checkpoints[2].heading = -1.653577
routes["Epilogue jericho loop"].checkpoints[2].roadName = "sutro_6l_south_01b AI Road 0"
routes["Epilogue jericho loop"].checkpoints[3] = {}
routes["Epilogue jericho loop"].checkpoints[3].position = vec.vector(268.0374, 20, 3794.206, 1)
routes["Epilogue jericho loop"].checkpoints[3].heading = 2.495334
routes["Epilogue jericho loop"].checkpoints[3].roadName = "sutro_6l_east_07 AI Road 8"
routes["Epilogue jericho loop"].checkpoints[4] = {}
routes["Epilogue jericho loop"].checkpoints[4].position = vec.vector(421.4333, 8.598372, 3699.917, 1)
routes["Epilogue jericho loop"].checkpoints[4].heading = 1.417055
routes["Epilogue jericho loop"].checkpoints[4].roadName = "sutro_shortcut_e_01 AI Road 2"
routes["Epilogue jericho loop"].checkpoints[5] = {}
routes["Epilogue jericho loop"].checkpoints[5].position = vec.vector(603.0123, 8.249998, 3699.965, 1)
routes["Epilogue jericho loop"].checkpoints[5].heading = 1.563757
routes["Epilogue jericho loop"].checkpoints[5].roadName = "sutro_4l_east_03 AI Road 0"
routes["Epilogue jericho loop"].checkpoints[6] = {}
routes["Epilogue jericho loop"].checkpoints[6].position = vec.vector(725.3881, 8.249998, 3750.818, 1)
routes["Epilogue jericho loop"].checkpoints[6].heading = 0.9116055
routes["Epilogue jericho loop"].checkpoints[6].roadName = "sutro_4l_east_03 AI Road 0"
routes["Epilogue jericho loop"].checkpoints[7] = {}
routes["Epilogue jericho loop"].checkpoints[7].position = vec.vector(675.4178, 8.249998, 3885.162, 1)
routes["Epilogue jericho loop"].checkpoints[7].heading = -1.569842
routes["Epilogue jericho loop"].checkpoints[7].roadName = "sutro_6l_south_01b AI Road 1"
routes["Epilogue jericho loop"].arrows = {}
routes["Epilogue jericho loop"].roads = {}
routes["Epilogue jericho loop"].roads[1] = {}
routes["Epilogue jericho loop"].roads[1].road = "sutro_6l_south_01b AI Road 0"
routes["Epilogue jericho loop"].roads[1].direction = "against"
routes["Epilogue jericho loop"].roads[2] = {}
routes["Epilogue jericho loop"].roads[2].road = "sutro_6l_east_07 AI Road 8"
routes["Epilogue jericho loop"].roads[2].direction = "with"
routes["Epilogue jericho loop"].roads[3] = {}
routes["Epilogue jericho loop"].roads[3].road = "sutro_shortcut_e_01 AI Road 2"
routes["Epilogue jericho loop"].roads[3].direction = "with"
routes["Epilogue jericho loop"].roads[4] = {}
routes["Epilogue jericho loop"].roads[4].road = "sutro_4l_east_03 AI Road 0"
routes["Epilogue jericho loop"].roads[4].direction = "with"
routes["Epilogue jericho loop"].roads[5] = {}
routes["Epilogue jericho loop"].roads[5].road = "sutro_6l_south_01b AI Road 1"
routes["Epilogue jericho loop"].roads[5].direction = "against"
routes["Epilogue jericho end"] = {}
routes["Epilogue jericho end"].checkpoints = {}
routes["Epilogue jericho end"].checkpoints[1] = {}
routes["Epilogue jericho end"].checkpoints[1].position = vec.vector(756.339, 8.249998, 4135.318, 1)
routes["Epilogue jericho end"].checkpoints[1].heading = 0.6473097
routes["Epilogue jericho end"].checkpoints[1].roadName = "sutro_4l_east_04 AI Road 3"
routes["Epilogue jericho end"].checkpoints[2] = {}
routes["Epilogue jericho end"].checkpoints[2].position = vec.vector(994.5111, 8.249999, 3971.133, 1)
routes["Epilogue jericho end"].checkpoints[2].heading = 2.283846
routes["Epilogue jericho end"].checkpoints[2].roadName = "sutro_shortcut_e_02 AI Road 0"
routes["Epilogue jericho end"].arrows = {}
routes["Epilogue jericho end"].roads = {}
routes["Epilogue jericho end"].roads[1] = {}
routes["Epilogue jericho end"].roads[1].road = "sutro_4l_east_04 AI Road 3"
routes["Epilogue jericho end"].roads[1].direction = "against"
routes["Epilogue jericho end"].roads[2] = {}
routes["Epilogue jericho end"].roads[2].road = "sutro_shortcut_e_02 AI Road 1"
routes["Epilogue jericho end"].roads[2].direction = "against"
routes["Epilogue jericho end"].roads[3] = {}
routes["Epilogue jericho end"].roads[3].road = "sutro_shortcut_e_02 AI Road 0"
routes["Epilogue jericho end"].roads[3].direction = "against"
