routes = routes or {}
routes.ChaseActivityRoute1 = {}
routes.ChaseActivityRoute1.checkpoints = {}
routes.ChaseActivityRoute1.checkpoints[1] = {}
routes.ChaseActivityRoute1.checkpoints[1].position = vec.vector(-521.069, 56.24334, 1747.208, 1)
routes.ChaseActivityRoute1.checkpoints[1].heading = 1.849925
routes.ChaseActivityRoute1.checkpoints[1].roadName = "dt_10l_south_02b AI Road 8"
routes.ChaseActivityRoute1.checkpoints[2] = {}
routes.ChaseActivityRoute1.checkpoints[2].position = vec.vector(75.2738, 30.86808, 1546.362, 1)
routes.ChaseActivityRoute1.checkpoints[2].heading = 2.083392
routes.ChaseActivityRoute1.checkpoints[2].roadName = "dt_10l_south_03 AI Road 5"
routes.ChaseActivityRoute1.checkpoints[3] = {}
routes.ChaseActivityRoute1.checkpoints[3].position = vec.vector(642.8434, 5.974995, 1072.744, 1)
routes.ChaseActivityRoute1.checkpoints[3].heading = 2.294983
routes.ChaseActivityRoute1.checkpoints[3].roadName = "dt_10l_south_03 AI Road 1"
routes.ChaseActivityRoute1.checkpoints[4] = {}
routes.ChaseActivityRoute1.checkpoints[4].position = vec.vector(492.6028, 17.27485, 957.967, 1)
routes.ChaseActivityRoute1.checkpoints[4].heading = -1.441185
routes.ChaseActivityRoute1.checkpoints[4].roadName = "dt_10l_south_01 AI Road 1"
routes.ChaseActivityRoute1.checkpoints[5] = {}
routes.ChaseActivityRoute1.checkpoints[5].position = vec.vector(-228.0959, 18, 977.3645, 1)
routes.ChaseActivityRoute1.checkpoints[5].heading = -2.351581
routes.ChaseActivityRoute1.checkpoints[5].roadName = "dt_10l_centre_01 AI Road 7"
routes.ChaseActivityRoute1.checkpoints[6] = {}
routes.ChaseActivityRoute1.checkpoints[6].position = vec.vector(-1038.549, 15.16112, 174.4491, 1)
routes.ChaseActivityRoute1.checkpoints[6].heading = -2.35151
routes.ChaseActivityRoute1.checkpoints[6].roadName = "dt_10l_centre_01 AI Road 1"
routes.ChaseActivityRoute1.checkpoints[7] = {}
routes.ChaseActivityRoute1.checkpoints[7].position = vec.vector(-1665.627, 5.169228, -105.3093, 1)
routes.ChaseActivityRoute1.checkpoints[7].heading = -0.4884478
routes.ChaseActivityRoute1.checkpoints[7].roadName = "dt_8l_north_04 AI Road 0"
routes.ChaseActivityRoute1.checkpoints[8] = {}
routes.ChaseActivityRoute1.checkpoints[8].position = vec.vector(-1690.129, 47.25, 625.4692, 1)
routes.ChaseActivityRoute1.checkpoints[8].heading = 0.009216221
routes.ChaseActivityRoute1.checkpoints[8].roadName = "dt__8l_west_01 AI Road 6"
routes.ChaseActivityRoute1.checkpoints[9] = {}
routes.ChaseActivityRoute1.checkpoints[9].position = vec.vector(-1443.482, 42.52863, 699.0472, 1)
routes.ChaseActivityRoute1.checkpoints[9].heading = 1.777543
routes.ChaseActivityRoute1.checkpoints[9].roadName = "dt_4l_centre_08 AI Road 1"
routes.ChaseActivityRoute1.checkpoints[10] = {}
routes.ChaseActivityRoute1.checkpoints[10].position = vec.vector(-1278.13, 46.35823, 1107.571, 1)
routes.ChaseActivityRoute1.checkpoints[10].heading = 0.114653
routes.ChaseActivityRoute1.checkpoints[10].roadName = "dt_8l_centre_01ab AI Road 7"
routes.ChaseActivityRoute1.checkpoints[11] = {}
routes.ChaseActivityRoute1.checkpoints[11].position = vec.vector(-1217.001, 56.48792, 1521.484, 1)
routes.ChaseActivityRoute1.checkpoints[11].heading = 0.1414329
routes.ChaseActivityRoute1.checkpoints[11].roadName = "dt_shortcut_39 AI Road 1"
routes.ChaseActivityRoute1.checkpoints[12] = {}
routes.ChaseActivityRoute1.checkpoints[12].position = vec.vector(-559.1558, 48.80503, 1481.014, 1)
routes.ChaseActivityRoute1.checkpoints[12].heading = 1.721818
routes.ChaseActivityRoute1.checkpoints[12].roadName = "mt_10l_north_01a AI Road 5"
routes.ChaseActivityRoute1.checkpoints[13] = {}
routes.ChaseActivityRoute1.checkpoints[13].position = vec.vector(363.3681, 8.187839, 1221.169, 1)
routes.ChaseActivityRoute1.checkpoints[13].heading = 1.525799
routes.ChaseActivityRoute1.checkpoints[13].roadName = "mt_10l_north_01b AI Road 2"
routes.ChaseActivityRoute1.arrows = {}
routes.ChaseActivityRoute1.roads = {}
routes.ChaseActivityRoute1.roads[1] = {}
routes.ChaseActivityRoute1.roads[1].road = "dt_10l_south_02b AI Road 8"
routes.ChaseActivityRoute1.roads[1].direction = "with"
routes.ChaseActivityRoute1.roads[2] = {}
routes.ChaseActivityRoute1.roads[2].road = "dt_10l_south_02b AI Road 9"
routes.ChaseActivityRoute1.roads[2].direction = "with"
routes.ChaseActivityRoute1.roads[3] = {}
routes.ChaseActivityRoute1.roads[3].road = "dt_10l_south_03 AI Road 7"
routes.ChaseActivityRoute1.roads[3].direction = "against"
routes.ChaseActivityRoute1.roads[4] = {}
routes.ChaseActivityRoute1.roads[4].road = "dt_10l_south_03 AI Road 6"
routes.ChaseActivityRoute1.roads[4].direction = "against"
routes.ChaseActivityRoute1.roads[5] = {}
routes.ChaseActivityRoute1.roads[5].road = "dt_10l_south_03 AI Road 5"
routes.ChaseActivityRoute1.roads[5].direction = "against"
routes.ChaseActivityRoute1.roads[6] = {}
routes.ChaseActivityRoute1.roads[6].road = "dt_10l_south_03 AI Road 4"
routes.ChaseActivityRoute1.roads[6].direction = "against"
routes.ChaseActivityRoute1.roads[7] = {}
routes.ChaseActivityRoute1.roads[7].road = "dt_10l_south_03 AI Road 3"
routes.ChaseActivityRoute1.roads[7].direction = "against"
routes.ChaseActivityRoute1.roads[8] = {}
routes.ChaseActivityRoute1.roads[8].road = "dt_10l_south_03 AI Road 2"
routes.ChaseActivityRoute1.roads[8].direction = "against"
routes.ChaseActivityRoute1.roads[9] = {}
routes.ChaseActivityRoute1.roads[9].road = "dt_10l_south_03 AI Road 1"
routes.ChaseActivityRoute1.roads[9].direction = "against"
routes.ChaseActivityRoute1.roads[10] = {}
routes.ChaseActivityRoute1.roads[10].road = "dt_10l_south_03 AI Road 0"
routes.ChaseActivityRoute1.roads[10].direction = "against"
routes.ChaseActivityRoute1.roads[11] = {}
routes.ChaseActivityRoute1.roads[11].road = "dt_10l_south_01 AI Road 0"
routes.ChaseActivityRoute1.roads[11].direction = "with"
routes.ChaseActivityRoute1.roads[12] = {}
routes.ChaseActivityRoute1.roads[12].road = "dt_10l_south_01 AI Road 1"
routes.ChaseActivityRoute1.roads[12].direction = "with"
routes.ChaseActivityRoute1.roads[13] = {}
routes.ChaseActivityRoute1.roads[13].road = "dt_10l_south_01 AI Road 2"
routes.ChaseActivityRoute1.roads[13].direction = "with"
routes.ChaseActivityRoute1.roads[14] = {}
routes.ChaseActivityRoute1.roads[14].road = "dt_10l_south_01 AI Road 3"
routes.ChaseActivityRoute1.roads[14].direction = "with"
routes.ChaseActivityRoute1.roads[15] = {}
routes.ChaseActivityRoute1.roads[15].road = "dt_10l_south_01 AI Road 4"
routes.ChaseActivityRoute1.roads[15].direction = "with"
routes.ChaseActivityRoute1.roads[16] = {}
routes.ChaseActivityRoute1.roads[16].road = "dt_10l_centre_01 AI Road 7"
routes.ChaseActivityRoute1.roads[16].direction = "against"
routes.ChaseActivityRoute1.roads[17] = {}
routes.ChaseActivityRoute1.roads[17].road = "dt_10l_centre_01 AI Road 6"
routes.ChaseActivityRoute1.roads[17].direction = "against"
routes.ChaseActivityRoute1.roads[18] = {}
routes.ChaseActivityRoute1.roads[18].road = "dt_10l_centre_01 AI Road 5"
routes.ChaseActivityRoute1.roads[18].direction = "against"
routes.ChaseActivityRoute1.roads[19] = {}
routes.ChaseActivityRoute1.roads[19].road = "dt_10l_centre_01 AI Road 4"
routes.ChaseActivityRoute1.roads[19].direction = "against"
routes.ChaseActivityRoute1.roads[20] = {}
routes.ChaseActivityRoute1.roads[20].road = "dt_10l_centre_01 AI Road 3"
routes.ChaseActivityRoute1.roads[20].direction = "against"
routes.ChaseActivityRoute1.roads[21] = {}
routes.ChaseActivityRoute1.roads[21].road = "dt_10l_centre_01 AI Road 2"
routes.ChaseActivityRoute1.roads[21].direction = "against"
routes.ChaseActivityRoute1.roads[22] = {}
routes.ChaseActivityRoute1.roads[22].road = "dt_10l_centre_01 AI Road 1"
routes.ChaseActivityRoute1.roads[22].direction = "against"
routes.ChaseActivityRoute1.roads[23] = {}
routes.ChaseActivityRoute1.roads[23].road = "dt_10l_centre_01 AI Road 0"
routes.ChaseActivityRoute1.roads[23].direction = "against"
routes.ChaseActivityRoute1.roads[24] = {}
routes.ChaseActivityRoute1.roads[24].road = "dt_8l_north_04 AI Road 2"
routes.ChaseActivityRoute1.roads[24].direction = "against"
routes.ChaseActivityRoute1.roads[25] = {}
routes.ChaseActivityRoute1.roads[25].road = "dt_8l_north_04 AI Road 1"
routes.ChaseActivityRoute1.roads[25].direction = "against"
routes.ChaseActivityRoute1.roads[26] = {}
routes.ChaseActivityRoute1.roads[26].road = "dt_8l_north_04 AI Road 0"
routes.ChaseActivityRoute1.roads[26].direction = "against"
routes.ChaseActivityRoute1.roads[27] = {}
routes.ChaseActivityRoute1.roads[27].road = "dt__8l_west_01 AI Road 0"
routes.ChaseActivityRoute1.roads[27].direction = "with"
routes.ChaseActivityRoute1.roads[28] = {}
routes.ChaseActivityRoute1.roads[28].road = "dt__8l_west_01 AI Road 1"
routes.ChaseActivityRoute1.roads[28].direction = "with"
routes.ChaseActivityRoute1.roads[29] = {}
routes.ChaseActivityRoute1.roads[29].road = "dt__8l_west_01 AI Road 2"
routes.ChaseActivityRoute1.roads[29].direction = "with"
routes.ChaseActivityRoute1.roads[30] = {}
routes.ChaseActivityRoute1.roads[30].road = "dt__8l_west_01 AI Road 3"
routes.ChaseActivityRoute1.roads[30].direction = "with"
routes.ChaseActivityRoute1.roads[31] = {}
routes.ChaseActivityRoute1.roads[31].road = "dt__8l_west_01 AI Road 4"
routes.ChaseActivityRoute1.roads[31].direction = "with"
routes.ChaseActivityRoute1.roads[32] = {}
routes.ChaseActivityRoute1.roads[32].road = "dt__8l_west_01 AI Road 5"
routes.ChaseActivityRoute1.roads[32].direction = "with"
routes.ChaseActivityRoute1.roads[33] = {}
routes.ChaseActivityRoute1.roads[33].road = "dt__8l_west_01 AI Road 6"
routes.ChaseActivityRoute1.roads[33].direction = "with"
routes.ChaseActivityRoute1.roads[34] = {}
routes.ChaseActivityRoute1.roads[34].road = "dt_4l_centre_08 AI Road 0"
routes.ChaseActivityRoute1.roads[34].direction = "with"
routes.ChaseActivityRoute1.roads[35] = {}
routes.ChaseActivityRoute1.roads[35].road = "dt_4l_centre_08 AI Road 1"
routes.ChaseActivityRoute1.roads[35].direction = "with"
routes.ChaseActivityRoute1.roads[36] = {}
routes.ChaseActivityRoute1.roads[36].road = "dt_4l_centre_08 AI Road 2"
routes.ChaseActivityRoute1.roads[36].direction = "with"
routes.ChaseActivityRoute1.roads[37] = {}
routes.ChaseActivityRoute1.roads[37].road = "dt_8l_centre_01ab AI Road 5"
routes.ChaseActivityRoute1.roads[37].direction = "with"
routes.ChaseActivityRoute1.roads[38] = {}
routes.ChaseActivityRoute1.roads[38].road = "dt_8l_centre_01ab AI Road 6"
routes.ChaseActivityRoute1.roads[38].direction = "with"
routes.ChaseActivityRoute1.roads[39] = {}
routes.ChaseActivityRoute1.roads[39].road = "dt_8l_centre_01ab AI Road 7"
routes.ChaseActivityRoute1.roads[39].direction = "with"
routes.ChaseActivityRoute1.roads[40] = {}
routes.ChaseActivityRoute1.roads[40].road = "dt_shortcut_42 AI Road 0"
routes.ChaseActivityRoute1.roads[40].direction = "against"
routes.ChaseActivityRoute1.roads[41] = {}
routes.ChaseActivityRoute1.roads[41].road = "dt_shortcut_39 AI Road 0"
routes.ChaseActivityRoute1.roads[41].direction = "with"
routes.ChaseActivityRoute1.roads[42] = {}
routes.ChaseActivityRoute1.roads[42].road = "dt_shortcut_39 AI Road 1"
routes.ChaseActivityRoute1.roads[42].direction = "with"
routes.ChaseActivityRoute1.roads[43] = {}
routes.ChaseActivityRoute1.roads[43].road = "mt_10l_north_01a AI Road 2"
routes.ChaseActivityRoute1.roads[43].direction = "with"
routes.ChaseActivityRoute1.roads[44] = {}
routes.ChaseActivityRoute1.roads[44].road = "mt_10l_north_01a AI Road 3"
routes.ChaseActivityRoute1.roads[44].direction = "with"
routes.ChaseActivityRoute1.roads[45] = {}
routes.ChaseActivityRoute1.roads[45].road = "mt_10l_north_01a AI Road 4"
routes.ChaseActivityRoute1.roads[45].direction = "with"
routes.ChaseActivityRoute1.roads[46] = {}
routes.ChaseActivityRoute1.roads[46].road = "mt_10l_north_01a AI Road 5"
routes.ChaseActivityRoute1.roads[46].direction = "with"
routes.ChaseActivityRoute1.roads[47] = {}
routes.ChaseActivityRoute1.roads[47].road = "mt_10l_north_01b AI Road 0"
routes.ChaseActivityRoute1.roads[47].direction = "with"
routes.ChaseActivityRoute1.roads[48] = {}
routes.ChaseActivityRoute1.roads[48].road = "mt_10l_north_01b AI Road 1"
routes.ChaseActivityRoute1.roads[48].direction = "with"
routes.ChaseActivityRoute1.roads[49] = {}
routes.ChaseActivityRoute1.roads[49].road = "mt_10l_north_01b AI Road 2"
routes.ChaseActivityRoute1.roads[49].direction = "with"
routes.ChaseActivityRoute1Loop = {}
routes.ChaseActivityRoute1Loop.checkpoints = {}
routes.ChaseActivityRoute1Loop.checkpoints[1] = {}
routes.ChaseActivityRoute1Loop.checkpoints[1].position = vec.vector(456.0361, 7.999999, 1241.065, 1)
routes.ChaseActivityRoute1Loop.checkpoints[1].heading = 2.287745
routes.ChaseActivityRoute1Loop.checkpoints[1].roadName = "dt_10l_south_03 AI Road 3"
routes.ChaseActivityRoute1Loop.checkpoints[2] = {}
routes.ChaseActivityRoute1Loop.checkpoints[2].position = vec.vector(616.1007, 10.36363, 941.8713, 1)
routes.ChaseActivityRoute1Loop.checkpoints[2].heading = -1.441182
routes.ChaseActivityRoute1Loop.checkpoints[2].roadName = "dt_10l_south_01 AI Road 0"
routes.ChaseActivityRoute1Loop.checkpoints[3] = {}
routes.ChaseActivityRoute1Loop.checkpoints[3].position = vec.vector(-88.75479, 18, 1025.559, 1)
routes.ChaseActivityRoute1Loop.checkpoints[3].heading = -1.466313
routes.ChaseActivityRoute1Loop.checkpoints[3].roadName = "dt_10l_south_01 AI Road 4"
routes.ChaseActivityRoute1Loop.checkpoints[4] = {}
routes.ChaseActivityRoute1Loop.checkpoints[4].position = vec.vector(-877.6805, 17.98234, 334.3514, 1)
routes.ChaseActivityRoute1Loop.checkpoints[4].heading = -2.342984
routes.ChaseActivityRoute1Loop.checkpoints[4].roadName = "dt_10l_centre_01 AI Road 2"
routes.ChaseActivityRoute1Loop.checkpoints[5] = {}
routes.ChaseActivityRoute1Loop.checkpoints[5].position = vec.vector(-1475.593, 4.999999, -161.1558, 1)
routes.ChaseActivityRoute1Loop.checkpoints[5].heading = -1.672212
routes.ChaseActivityRoute1Loop.checkpoints[5].roadName = "dt_8l_north_04 AI Road 1"
routes.ChaseActivityRoute1Loop.checkpoints[6] = {}
routes.ChaseActivityRoute1Loop.checkpoints[6].position = vec.vector(-1691.43, 40.21906, 501.7473, 1)
routes.ChaseActivityRoute1Loop.checkpoints[6].heading = 0.007091673
routes.ChaseActivityRoute1Loop.checkpoints[6].roadName = "dt__8l_west_01 AI Road 4"
routes.ChaseActivityRoute1Loop.checkpoints[7] = {}
routes.ChaseActivityRoute1Loop.checkpoints[7].position = vec.vector(-1326.617, 42.375, 761.7837, 1)
routes.ChaseActivityRoute1Loop.checkpoints[7].heading = 0.2089025
routes.ChaseActivityRoute1Loop.checkpoints[7].roadName = "dt_8l_centre_01ab AI Road 5"
routes.ChaseActivityRoute1Loop.checkpoints[8] = {}
routes.ChaseActivityRoute1Loop.checkpoints[8].position = vec.vector(-1230.863, 51.848, 1419.732, 1)
routes.ChaseActivityRoute1Loop.checkpoints[8].heading = 0.154719
routes.ChaseActivityRoute1Loop.checkpoints[8].roadName = "dt_shortcut_39 AI Road 0"
routes.ChaseActivityRoute1Loop.checkpoints[9] = {}
routes.ChaseActivityRoute1Loop.checkpoints[9].position = vec.vector(-1137.474, 55.80722, 1568.368, 1)
routes.ChaseActivityRoute1Loop.checkpoints[9].heading = 1.69289
routes.ChaseActivityRoute1Loop.checkpoints[9].roadName = "mt_10l_north_01a AI Road 2"
routes.ChaseActivityRoute1Loop.checkpoints[10] = {}
routes.ChaseActivityRoute1Loop.checkpoints[10].position = vec.vector(-287.2097, 37.2869, 1354.439, 1)
routes.ChaseActivityRoute1Loop.checkpoints[10].heading = 2.145899
routes.ChaseActivityRoute1Loop.checkpoints[10].roadName = "mt_10l_north_01b AI Road 0"
routes.ChaseActivityRoute1Loop.checkpoints[11] = {}
routes.ChaseActivityRoute1Loop.checkpoints[11].position = vec.vector(298.5295, 13.89917, 1206.541, 1)
routes.ChaseActivityRoute1Loop.checkpoints[11].heading = 1.6401
routes.ChaseActivityRoute1Loop.checkpoints[11].roadName = "mt_10l_north_01b AI Road 2"
routes.ChaseActivityRoute1Loop.arrows = {}
routes.ChaseActivityRoute1Loop.roads = {}
routes.ChaseActivityRoute1Loop.roads[1] = {}
routes.ChaseActivityRoute1Loop.roads[1].road = "dt_10l_south_03 AI Road 3"
routes.ChaseActivityRoute1Loop.roads[1].direction = "against"
routes.ChaseActivityRoute1Loop.roads[2] = {}
routes.ChaseActivityRoute1Loop.roads[2].road = "dt_10l_south_03 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[2].direction = "against"
routes.ChaseActivityRoute1Loop.roads[3] = {}
routes.ChaseActivityRoute1Loop.roads[3].road = "dt_10l_south_03 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[3].direction = "against"
routes.ChaseActivityRoute1Loop.roads[4] = {}
routes.ChaseActivityRoute1Loop.roads[4].road = "dt_10l_south_03 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[4].direction = "against"
routes.ChaseActivityRoute1Loop.roads[5] = {}
routes.ChaseActivityRoute1Loop.roads[5].road = "dt_10l_south_01 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[5].direction = "with"
routes.ChaseActivityRoute1Loop.roads[6] = {}
routes.ChaseActivityRoute1Loop.roads[6].road = "dt_10l_south_01 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[6].direction = "with"
routes.ChaseActivityRoute1Loop.roads[7] = {}
routes.ChaseActivityRoute1Loop.roads[7].road = "dt_10l_south_01 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[7].direction = "with"
routes.ChaseActivityRoute1Loop.roads[8] = {}
routes.ChaseActivityRoute1Loop.roads[8].road = "dt_10l_south_01 AI Road 3"
routes.ChaseActivityRoute1Loop.roads[8].direction = "with"
routes.ChaseActivityRoute1Loop.roads[9] = {}
routes.ChaseActivityRoute1Loop.roads[9].road = "dt_10l_south_01 AI Road 4"
routes.ChaseActivityRoute1Loop.roads[9].direction = "with"
routes.ChaseActivityRoute1Loop.roads[10] = {}
routes.ChaseActivityRoute1Loop.roads[10].road = "dt_10l_centre_01 AI Road 7"
routes.ChaseActivityRoute1Loop.roads[10].direction = "against"
routes.ChaseActivityRoute1Loop.roads[11] = {}
routes.ChaseActivityRoute1Loop.roads[11].road = "dt_10l_centre_01 AI Road 6"
routes.ChaseActivityRoute1Loop.roads[11].direction = "against"
routes.ChaseActivityRoute1Loop.roads[12] = {}
routes.ChaseActivityRoute1Loop.roads[12].road = "dt_10l_centre_01 AI Road 5"
routes.ChaseActivityRoute1Loop.roads[12].direction = "against"
routes.ChaseActivityRoute1Loop.roads[13] = {}
routes.ChaseActivityRoute1Loop.roads[13].road = "dt_10l_centre_01 AI Road 4"
routes.ChaseActivityRoute1Loop.roads[13].direction = "against"
routes.ChaseActivityRoute1Loop.roads[14] = {}
routes.ChaseActivityRoute1Loop.roads[14].road = "dt_10l_centre_01 AI Road 3"
routes.ChaseActivityRoute1Loop.roads[14].direction = "against"
routes.ChaseActivityRoute1Loop.roads[15] = {}
routes.ChaseActivityRoute1Loop.roads[15].road = "dt_10l_centre_01 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[15].direction = "against"
routes.ChaseActivityRoute1Loop.roads[16] = {}
routes.ChaseActivityRoute1Loop.roads[16].road = "dt_10l_centre_01 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[16].direction = "against"
routes.ChaseActivityRoute1Loop.roads[17] = {}
routes.ChaseActivityRoute1Loop.roads[17].road = "dt_10l_centre_01 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[17].direction = "against"
routes.ChaseActivityRoute1Loop.roads[18] = {}
routes.ChaseActivityRoute1Loop.roads[18].road = "dt_8l_north_04 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[18].direction = "against"
routes.ChaseActivityRoute1Loop.roads[19] = {}
routes.ChaseActivityRoute1Loop.roads[19].road = "dt_8l_north_04 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[19].direction = "against"
routes.ChaseActivityRoute1Loop.roads[20] = {}
routes.ChaseActivityRoute1Loop.roads[20].road = "dt_8l_north_04 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[20].direction = "against"
routes.ChaseActivityRoute1Loop.roads[21] = {}
routes.ChaseActivityRoute1Loop.roads[21].road = "dt__8l_west_01 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[21].direction = "with"
routes.ChaseActivityRoute1Loop.roads[22] = {}
routes.ChaseActivityRoute1Loop.roads[22].road = "dt__8l_west_01 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[22].direction = "with"
routes.ChaseActivityRoute1Loop.roads[23] = {}
routes.ChaseActivityRoute1Loop.roads[23].road = "dt__8l_west_01 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[23].direction = "with"
routes.ChaseActivityRoute1Loop.roads[24] = {}
routes.ChaseActivityRoute1Loop.roads[24].road = "dt__8l_west_01 AI Road 3"
routes.ChaseActivityRoute1Loop.roads[24].direction = "with"
routes.ChaseActivityRoute1Loop.roads[25] = {}
routes.ChaseActivityRoute1Loop.roads[25].road = "dt__8l_west_01 AI Road 4"
routes.ChaseActivityRoute1Loop.roads[25].direction = "with"
routes.ChaseActivityRoute1Loop.roads[26] = {}
routes.ChaseActivityRoute1Loop.roads[26].road = "dt__8l_west_01 AI Road 5"
routes.ChaseActivityRoute1Loop.roads[26].direction = "with"
routes.ChaseActivityRoute1Loop.roads[27] = {}
routes.ChaseActivityRoute1Loop.roads[27].road = "dt__8l_west_01 AI Road 6"
routes.ChaseActivityRoute1Loop.roads[27].direction = "with"
routes.ChaseActivityRoute1Loop.roads[28] = {}
routes.ChaseActivityRoute1Loop.roads[28].road = "dt_4l_centre_08 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[28].direction = "with"
routes.ChaseActivityRoute1Loop.roads[29] = {}
routes.ChaseActivityRoute1Loop.roads[29].road = "dt_4l_centre_08 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[29].direction = "with"
routes.ChaseActivityRoute1Loop.roads[30] = {}
routes.ChaseActivityRoute1Loop.roads[30].road = "dt_4l_centre_08 AI Road 2"
routes.ChaseActivityRoute1Loop.roads[30].direction = "with"
routes.ChaseActivityRoute1Loop.roads[31] = {}
routes.ChaseActivityRoute1Loop.roads[31].road = "dt_8l_centre_01ab AI Road 5"
routes.ChaseActivityRoute1Loop.roads[31].direction = "with"
routes.ChaseActivityRoute1Loop.roads[32] = {}
routes.ChaseActivityRoute1Loop.roads[32].road = "dt_8l_centre_01ab AI Road 6"
routes.ChaseActivityRoute1Loop.roads[32].direction = "with"
routes.ChaseActivityRoute1Loop.roads[33] = {}
routes.ChaseActivityRoute1Loop.roads[33].road = "dt_8l_centre_01ab AI Road 7"
routes.ChaseActivityRoute1Loop.roads[33].direction = "with"
routes.ChaseActivityRoute1Loop.roads[34] = {}
routes.ChaseActivityRoute1Loop.roads[34].road = "dt_shortcut_42 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[34].direction = "against"
routes.ChaseActivityRoute1Loop.roads[35] = {}
routes.ChaseActivityRoute1Loop.roads[35].road = "dt_shortcut_39 AI Road 0"
routes.ChaseActivityRoute1Loop.roads[35].direction = "with"
routes.ChaseActivityRoute1Loop.roads[36] = {}
routes.ChaseActivityRoute1Loop.roads[36].road = "dt_shortcut_39 AI Road 1"
routes.ChaseActivityRoute1Loop.roads[36].direction = "with"
routes.ChaseActivityRoute1Loop.roads[37] = {}
routes.ChaseActivityRoute1Loop.roads[37].road = "mt_10l_north_01a AI Road 2"
routes.ChaseActivityRoute1Loop.roads[37].direction = "with"
routes.ChaseActivityRoute1Loop.roads[38] = {}
routes.ChaseActivityRoute1Loop.roads[38].road = "mt_10l_north_01a AI Road 3"
routes.ChaseActivityRoute1Loop.roads[38].direction = "with"
routes.ChaseActivityRoute1Loop.roads[39] = {}
routes.ChaseActivityRoute1Loop.roads[39].road = "mt_10l_north_01a AI Road 4"
routes.ChaseActivityRoute1Loop.roads[39].direction = "with"
routes.ChaseActivityRoute1Loop.roads[40] = {}
routes.ChaseActivityRoute1Loop.roads[40].road = "mt_10l_north_01a AI Road 5"
routes.ChaseActivityRoute1Loop.roads[40].direction = "with"
routes.ChaseActivityRoute1Loop.roads[41] = {}
routes.ChaseActivityRoute1Loop.roads[41].road = "mt_10l_north_01b AI Road 0"
routes.ChaseActivityRoute1Loop.roads[41].direction = "with"
routes.ChaseActivityRoute1Loop.roads[42] = {}
routes.ChaseActivityRoute1Loop.roads[42].road = "mt_10l_north_01b AI Road 1"
routes.ChaseActivityRoute1Loop.roads[42].direction = "with"
routes.ChaseActivityRoute1Loop.roads[43] = {}
routes.ChaseActivityRoute1Loop.roads[43].road = "mt_10l_north_01b AI Road 2"
routes.ChaseActivityRoute1Loop.roads[43].direction = "with"
