routes = routes or {}
routes.ChaseActivityRoute4 = {}
routes.ChaseActivityRoute4.checkpoints = {}
routes.ChaseActivityRoute4.checkpoints[1] = {}
routes.ChaseActivityRoute4.checkpoints[1].position = vec.vector(-3122.281, 139.7786, -3628.141, 1)
routes.ChaseActivityRoute4.checkpoints[1].heading = 1.966067
routes.ChaseActivityRoute4.checkpoints[1].roadName = "marin_10l_west_01 AI Road 5"
routes.ChaseActivityRoute4.checkpoints[2] = {}
routes.ChaseActivityRoute4.checkpoints[2].position = vec.vector(-1839.32, 140.4184, -3636.888, 1)
routes.ChaseActivityRoute4.checkpoints[2].heading = 1.570796
routes.ChaseActivityRoute4.checkpoints[2].roadName = "highway02_03 AI Road 0"
routes.ChaseActivityRoute4.checkpoints[3] = {}
routes.ChaseActivityRoute4.checkpoints[3].position = vec.vector(-544.8698, 28.29574, -2691.854, 1)
routes.ChaseActivityRoute4.checkpoints[3].heading = 1.158847
routes.ChaseActivityRoute4.checkpoints[3].roadName = "highway02_03 AI Road 11"
routes.ChaseActivityRoute4.checkpoints[4] = {}
routes.ChaseActivityRoute4.checkpoints[4].position = vec.vector(-177.2866, 18, -2453.813, 1)
routes.ChaseActivityRoute4.checkpoints[4].heading = -0.2072395
routes.ChaseActivityRoute4.checkpoints[4].roadName = "mountain_6l_east_01 AI Road 19"
routes.ChaseActivityRoute4.checkpoints[5] = {}
routes.ChaseActivityRoute4.checkpoints[5].position = vec.vector(641.0831, 5.195877, -2171.833, 1)
routes.ChaseActivityRoute4.checkpoints[5].heading = 1.574386
routes.ChaseActivityRoute4.checkpoints[5].roadName = "mountain_6l_east_01 AI Road 15"
routes.ChaseActivityRoute4.checkpoints[6] = {}
routes.ChaseActivityRoute4.checkpoints[6].position = vec.vector(1097.893, 20.85323, -3108.375, 1)
routes.ChaseActivityRoute4.checkpoints[6].heading = 2.057728
routes.ChaseActivityRoute4.checkpoints[6].roadName = "mountain_6l_east_01 AI Road 10"
routes.ChaseActivityRoute4.checkpoints[7] = {}
routes.ChaseActivityRoute4.checkpoints[7].position = vec.vector(826.3334, 40, -3862.631, 1)
routes.ChaseActivityRoute4.checkpoints[7].heading = -2.619896
routes.ChaseActivityRoute4.checkpoints[7].roadName = "mountain_10l_w_01a AI Road 3"
routes.ChaseActivityRoute4.checkpoints[8] = {}
routes.ChaseActivityRoute4.checkpoints[8].position = vec.vector(424.6913, 53.75, -4403.206, 1)
routes.ChaseActivityRoute4.checkpoints[8].heading = -1.040373
routes.ChaseActivityRoute4.checkpoints[8].roadName = "mountain_10l_w_01b AI Road 17"
routes.ChaseActivityRoute4.checkpoints[9] = {}
routes.ChaseActivityRoute4.checkpoints[9].position = vec.vector(-52.30215, 53.75, -3972.202, 1)
routes.ChaseActivityRoute4.checkpoints[9].heading = -0.7939281
routes.ChaseActivityRoute4.checkpoints[9].roadName = "mountain_10l_w_01b AI Road 21"
routes.ChaseActivityRoute4.checkpoints[10] = {}
routes.ChaseActivityRoute4.checkpoints[10].position = vec.vector(-578.4243, 48.55961, -3433.153, 1)
routes.ChaseActivityRoute4.checkpoints[10].heading = -0.8055574
routes.ChaseActivityRoute4.checkpoints[10].roadName = "mountain_10l_w_01b AI Road 25"
routes.ChaseActivityRoute4.checkpoints[11] = {}
routes.ChaseActivityRoute4.checkpoints[11].position = vec.vector(-991.0457, 27.76058, -3036.789, 1)
routes.ChaseActivityRoute4.checkpoints[11].heading = -0.816122
routes.ChaseActivityRoute4.checkpoints[11].roadName = "mountain_10l_w_01b AI Road 27"
routes.ChaseActivityRoute4.checkpoints[12] = {}
routes.ChaseActivityRoute4.checkpoints[12].position = vec.vector(-1047.924, 24.5, -2876.442, 1)
routes.ChaseActivityRoute4.checkpoints[12].heading = 0.7840587
routes.ChaseActivityRoute4.checkpoints[12].roadName = "mountain_6l_east_08 AI Road 0"
routes.ChaseActivityRoute4.checkpoints[13] = {}
routes.ChaseActivityRoute4.checkpoints[13].position = vec.vector(-822.1868, 30.07582, -2772.15, 1)
routes.ChaseActivityRoute4.checkpoints[13].heading = 1.374053
routes.ChaseActivityRoute4.checkpoints[13].roadName = "marin_shortcut_40 AI Road 0"
routes.ChaseActivityRoute4.arrows = {}
routes.ChaseActivityRoute4.roads = {}
routes.ChaseActivityRoute4.roads[1] = {}
routes.ChaseActivityRoute4.roads[1].road = "marin_10l_west_01 AI Road 5"
routes.ChaseActivityRoute4.roads[1].direction = "with"
routes.ChaseActivityRoute4.roads[2] = {}
routes.ChaseActivityRoute4.roads[2].road = "marin_10l_west_01 AI Road 6"
routes.ChaseActivityRoute4.roads[2].direction = "with"
routes.ChaseActivityRoute4.roads[3] = {}
routes.ChaseActivityRoute4.roads[3].road = "marin_highway_split_04 AI Road 0"
routes.ChaseActivityRoute4.roads[3].direction = "with"
routes.ChaseActivityRoute4.roads[4] = {}
routes.ChaseActivityRoute4.roads[4].road = "marin_highway_split_04 AI Road 1"
routes.ChaseActivityRoute4.roads[4].direction = "with"
routes.ChaseActivityRoute4.roads[5] = {}
routes.ChaseActivityRoute4.roads[5].road = "marin_highway_split_04 AI Road 2"
routes.ChaseActivityRoute4.roads[5].direction = "with"
routes.ChaseActivityRoute4.roads[6] = {}
routes.ChaseActivityRoute4.roads[6].road = "marin_highway_split_04 AI Road 3"
routes.ChaseActivityRoute4.roads[6].direction = "with"
routes.ChaseActivityRoute4.roads[7] = {}
routes.ChaseActivityRoute4.roads[7].road = "highway02_03 AI Road 0"
routes.ChaseActivityRoute4.roads[7].direction = "with"
routes.ChaseActivityRoute4.roads[8] = {}
routes.ChaseActivityRoute4.roads[8].road = "highway02_03 AI Road 1"
routes.ChaseActivityRoute4.roads[8].direction = "with"
routes.ChaseActivityRoute4.roads[9] = {}
routes.ChaseActivityRoute4.roads[9].road = "highway02_03 AI Road 2"
routes.ChaseActivityRoute4.roads[9].direction = "with"
routes.ChaseActivityRoute4.roads[10] = {}
routes.ChaseActivityRoute4.roads[10].road = "highway02_03 AI Road 3"
routes.ChaseActivityRoute4.roads[10].direction = "with"
routes.ChaseActivityRoute4.roads[11] = {}
routes.ChaseActivityRoute4.roads[11].road = "highway02_03 AI Road 4"
routes.ChaseActivityRoute4.roads[11].direction = "with"
routes.ChaseActivityRoute4.roads[12] = {}
routes.ChaseActivityRoute4.roads[12].road = "highway02_03 AI Road 5"
routes.ChaseActivityRoute4.roads[12].direction = "with"
routes.ChaseActivityRoute4.roads[13] = {}
routes.ChaseActivityRoute4.roads[13].road = "highway02_03 AI Road 6"
routes.ChaseActivityRoute4.roads[13].direction = "with"
routes.ChaseActivityRoute4.roads[14] = {}
routes.ChaseActivityRoute4.roads[14].road = "highway02_03 AI Road 7"
routes.ChaseActivityRoute4.roads[14].direction = "with"
routes.ChaseActivityRoute4.roads[15] = {}
routes.ChaseActivityRoute4.roads[15].road = "highway02_03 AI Road 8"
routes.ChaseActivityRoute4.roads[15].direction = "with"
routes.ChaseActivityRoute4.roads[16] = {}
routes.ChaseActivityRoute4.roads[16].road = "highway02_03 AI Road 9"
routes.ChaseActivityRoute4.roads[16].direction = "with"
routes.ChaseActivityRoute4.roads[17] = {}
routes.ChaseActivityRoute4.roads[17].road = "highway02_03 AI Road 10"
routes.ChaseActivityRoute4.roads[17].direction = "with"
routes.ChaseActivityRoute4.roads[18] = {}
routes.ChaseActivityRoute4.roads[18].road = "highway02_03 AI Road 11"
routes.ChaseActivityRoute4.roads[18].direction = "with"
routes.ChaseActivityRoute4.roads[19] = {}
routes.ChaseActivityRoute4.roads[19].road = "highway02_03 AI Road 12"
routes.ChaseActivityRoute4.roads[19].direction = "with"
routes.ChaseActivityRoute4.roads[20] = {}
routes.ChaseActivityRoute4.roads[20].road = "highway02_03 AI Road 13"
routes.ChaseActivityRoute4.roads[20].direction = "with"
routes.ChaseActivityRoute4.roads[21] = {}
routes.ChaseActivityRoute4.roads[21].road = "mountain_6l_east_01 AI Road 19"
routes.ChaseActivityRoute4.roads[21].direction = "against"
routes.ChaseActivityRoute4.roads[22] = {}
routes.ChaseActivityRoute4.roads[22].road = "mountain_6l_east_01 AI Road 18"
routes.ChaseActivityRoute4.roads[22].direction = "against"
routes.ChaseActivityRoute4.roads[23] = {}
routes.ChaseActivityRoute4.roads[23].road = "mountain_6l_east_01 AI Road 17"
routes.ChaseActivityRoute4.roads[23].direction = "against"
routes.ChaseActivityRoute4.roads[24] = {}
routes.ChaseActivityRoute4.roads[24].road = "mountain_6l_east_01 AI Road 16"
routes.ChaseActivityRoute4.roads[24].direction = "against"
routes.ChaseActivityRoute4.roads[25] = {}
routes.ChaseActivityRoute4.roads[25].road = "mountain_6l_east_01 AI Road 15"
routes.ChaseActivityRoute4.roads[25].direction = "against"
routes.ChaseActivityRoute4.roads[26] = {}
routes.ChaseActivityRoute4.roads[26].road = "mountain_6l_east_01 AI Road 14"
routes.ChaseActivityRoute4.roads[26].direction = "against"
routes.ChaseActivityRoute4.roads[27] = {}
routes.ChaseActivityRoute4.roads[27].road = "mountain_6l_east_01 AI Road 13"
routes.ChaseActivityRoute4.roads[27].direction = "against"
routes.ChaseActivityRoute4.roads[28] = {}
routes.ChaseActivityRoute4.roads[28].road = "mountain_6l_east_01 AI Road 12"
routes.ChaseActivityRoute4.roads[28].direction = "against"
routes.ChaseActivityRoute4.roads[29] = {}
routes.ChaseActivityRoute4.roads[29].road = "mountain_6l_east_01 AI Road 11"
routes.ChaseActivityRoute4.roads[29].direction = "against"
routes.ChaseActivityRoute4.roads[30] = {}
routes.ChaseActivityRoute4.roads[30].road = "mountain_6l_east_01 AI Road 10"
routes.ChaseActivityRoute4.roads[30].direction = "against"
routes.ChaseActivityRoute4.roads[31] = {}
routes.ChaseActivityRoute4.roads[31].road = "mountain_6l_east_01 AI Road 9"
routes.ChaseActivityRoute4.roads[31].direction = "against"
routes.ChaseActivityRoute4.roads[32] = {}
routes.ChaseActivityRoute4.roads[32].road = "mountain_10l_w_01a AI Road 9"
routes.ChaseActivityRoute4.roads[32].direction = "against"
routes.ChaseActivityRoute4.roads[33] = {}
routes.ChaseActivityRoute4.roads[33].road = "mountain_10l_w_01a AI Road 8"
routes.ChaseActivityRoute4.roads[33].direction = "against"
routes.ChaseActivityRoute4.roads[34] = {}
routes.ChaseActivityRoute4.roads[34].road = "mountain_10l_w_01a AI Road 7"
routes.ChaseActivityRoute4.roads[34].direction = "against"
routes.ChaseActivityRoute4.roads[35] = {}
routes.ChaseActivityRoute4.roads[35].road = "mountain_10l_w_01a AI Road 6"
routes.ChaseActivityRoute4.roads[35].direction = "against"
routes.ChaseActivityRoute4.roads[36] = {}
routes.ChaseActivityRoute4.roads[36].road = "mountain_10l_w_01a AI Road 5"
routes.ChaseActivityRoute4.roads[36].direction = "against"
routes.ChaseActivityRoute4.roads[37] = {}
routes.ChaseActivityRoute4.roads[37].road = "mountain_10l_w_01a AI Road 4"
routes.ChaseActivityRoute4.roads[37].direction = "against"
routes.ChaseActivityRoute4.roads[38] = {}
routes.ChaseActivityRoute4.roads[38].road = "mountain_10l_w_01a AI Road 3"
routes.ChaseActivityRoute4.roads[38].direction = "against"
routes.ChaseActivityRoute4.roads[39] = {}
routes.ChaseActivityRoute4.roads[39].road = "mountain_10l_w_01a AI Road 2"
routes.ChaseActivityRoute4.roads[39].direction = "against"
routes.ChaseActivityRoute4.roads[40] = {}
routes.ChaseActivityRoute4.roads[40].road = "mountain_10l_w_01a AI Road 1"
routes.ChaseActivityRoute4.roads[40].direction = "against"
routes.ChaseActivityRoute4.roads[41] = {}
routes.ChaseActivityRoute4.roads[41].road = "mountain_10l_w_01a AI Road 0"
routes.ChaseActivityRoute4.roads[41].direction = "against"
routes.ChaseActivityRoute4.roads[42] = {}
routes.ChaseActivityRoute4.roads[42].road = "marin_6l_west_01a AI Road 38"
routes.ChaseActivityRoute4.roads[42].direction = "against"
routes.ChaseActivityRoute4.roads[43] = {}
routes.ChaseActivityRoute4.roads[43].road = "marin_6l_west_01a AI Road 37"
routes.ChaseActivityRoute4.roads[43].direction = "against"
routes.ChaseActivityRoute4.roads[44] = {}
routes.ChaseActivityRoute4.roads[44].road = "marin_6l_west_01a AI Road 36"
routes.ChaseActivityRoute4.roads[44].direction = "against"
routes.ChaseActivityRoute4.roads[45] = {}
routes.ChaseActivityRoute4.roads[45].road = "mountain_10l_w_01b AI Road 17"
routes.ChaseActivityRoute4.roads[45].direction = "with"
routes.ChaseActivityRoute4.roads[46] = {}
routes.ChaseActivityRoute4.roads[46].road = "mountain_10l_w_01b AI Road 18"
routes.ChaseActivityRoute4.roads[46].direction = "with"
routes.ChaseActivityRoute4.roads[47] = {}
routes.ChaseActivityRoute4.roads[47].road = "mountain_10l_w_01b AI Road 19"
routes.ChaseActivityRoute4.roads[47].direction = "with"
routes.ChaseActivityRoute4.roads[48] = {}
routes.ChaseActivityRoute4.roads[48].road = "mountain_10l_w_01b AI Road 20"
routes.ChaseActivityRoute4.roads[48].direction = "with"
routes.ChaseActivityRoute4.roads[49] = {}
routes.ChaseActivityRoute4.roads[49].road = "mountain_10l_w_01b AI Road 21"
routes.ChaseActivityRoute4.roads[49].direction = "with"
routes.ChaseActivityRoute4.roads[50] = {}
routes.ChaseActivityRoute4.roads[50].road = "mountain_10l_w_01b AI Road 22"
routes.ChaseActivityRoute4.roads[50].direction = "with"
routes.ChaseActivityRoute4.roads[51] = {}
routes.ChaseActivityRoute4.roads[51].road = "mountain_10l_w_01b AI Road 23"
routes.ChaseActivityRoute4.roads[51].direction = "with"
routes.ChaseActivityRoute4.roads[52] = {}
routes.ChaseActivityRoute4.roads[52].road = "mountain_10l_w_01b AI Road 24"
routes.ChaseActivityRoute4.roads[52].direction = "with"
routes.ChaseActivityRoute4.roads[53] = {}
routes.ChaseActivityRoute4.roads[53].road = "mountain_10l_w_01b AI Road 25"
routes.ChaseActivityRoute4.roads[53].direction = "with"
routes.ChaseActivityRoute4.roads[54] = {}
routes.ChaseActivityRoute4.roads[54].road = "mountain_10l_w_01b AI Road 26"
routes.ChaseActivityRoute4.roads[54].direction = "with"
routes.ChaseActivityRoute4.roads[55] = {}
routes.ChaseActivityRoute4.roads[55].road = "mountain_10l_w_01b AI Road 27"
routes.ChaseActivityRoute4.roads[55].direction = "with"
routes.ChaseActivityRoute4.roads[56] = {}
routes.ChaseActivityRoute4.roads[56].road = "mountain_10l_w_01b AI Road 28"
routes.ChaseActivityRoute4.roads[56].direction = "with"
routes.ChaseActivityRoute4.roads[57] = {}
routes.ChaseActivityRoute4.roads[57].road = "mountain_10l_w_01b AI Road 29"
routes.ChaseActivityRoute4.roads[57].direction = "with"
routes.ChaseActivityRoute4.roads[58] = {}
routes.ChaseActivityRoute4.roads[58].road = "mountain_6l_east_08 AI Road 0"
routes.ChaseActivityRoute4.roads[58].direction = "with"
routes.ChaseActivityRoute4.roads[59] = {}
routes.ChaseActivityRoute4.roads[59].road = "marin_shortcut_40 AI Road 0"
routes.ChaseActivityRoute4.roads[59].direction = "with"
routes.ChaseActivityRoute4Loop = {}
routes.ChaseActivityRoute4Loop.checkpoints = {}
routes.ChaseActivityRoute4Loop.checkpoints[1] = {}
routes.ChaseActivityRoute4Loop.checkpoints[1].position = vec.vector(-477.8689, 28.29595, -2662.578, 1)
routes.ChaseActivityRoute4Loop.checkpoints[1].heading = 1.158854
routes.ChaseActivityRoute4Loop.checkpoints[1].roadName = "highway02_03 AI Road 11"
routes.ChaseActivityRoute4Loop.checkpoints[2] = {}
routes.ChaseActivityRoute4Loop.checkpoints[2].position = vec.vector(384.7132, 5, -2171.753, 1)
routes.ChaseActivityRoute4Loop.checkpoints[2].heading = 1.560825
routes.ChaseActivityRoute4Loop.checkpoints[2].roadName = "mountain_6l_east_01 AI Road 16"
routes.ChaseActivityRoute4Loop.checkpoints[3] = {}
routes.ChaseActivityRoute4Loop.checkpoints[3].position = vec.vector(1007.307, 5, -2603.303, 1)
routes.ChaseActivityRoute4Loop.checkpoints[3].heading = 2.968323
routes.ChaseActivityRoute4Loop.checkpoints[3].roadName = "mountain_6l_east_01 AI Road 12"
routes.ChaseActivityRoute4Loop.checkpoints[4] = {}
routes.ChaseActivityRoute4Loop.checkpoints[4].position = vec.vector(1136.094, 25, -3319.595, 1)
routes.ChaseActivityRoute4Loop.checkpoints[4].heading = -2.62082
routes.ChaseActivityRoute4Loop.checkpoints[4].roadName = "mountain_10l_w_01a AI Road 9"
routes.ChaseActivityRoute4Loop.checkpoints[5] = {}
routes.ChaseActivityRoute4Loop.checkpoints[5].position = vec.vector(633.7255, 45, -4195.593, 1)
routes.ChaseActivityRoute4Loop.checkpoints[5].heading = -2.610269
routes.ChaseActivityRoute4Loop.checkpoints[5].roadName = "marin_6l_west_01a AI Road 38"
routes.ChaseActivityRoute4Loop.checkpoints[6] = {}
routes.ChaseActivityRoute4Loop.checkpoints[6].position = vec.vector(84.3819, 53.75, -4106.576, 1)
routes.ChaseActivityRoute4Loop.checkpoints[6].heading = -0.7939164
routes.ChaseActivityRoute4Loop.checkpoints[6].roadName = "mountain_10l_w_01b AI Road 19"
routes.ChaseActivityRoute4Loop.checkpoints[7] = {}
routes.ChaseActivityRoute4Loop.checkpoints[7].position = vec.vector(-883.9086, 33.53559, -3139.233, 1)
routes.ChaseActivityRoute4Loop.checkpoints[7].heading = -0.8019206
routes.ChaseActivityRoute4Loop.checkpoints[7].roadName = "mountain_10l_w_01b AI Road 27"
routes.ChaseActivityRoute4Loop.checkpoints[8] = {}
routes.ChaseActivityRoute4Loop.checkpoints[8].position = vec.vector(-914.0324, 26.45565, -2799.475, 1)
routes.ChaseActivityRoute4Loop.checkpoints[8].heading = 1.088467
routes.ChaseActivityRoute4Loop.checkpoints[8].roadName = "marin_shortcut_40 AI Road 0"
routes.ChaseActivityRoute4Loop.arrows = {}
routes.ChaseActivityRoute4Loop.roads = {}
routes.ChaseActivityRoute4Loop.roads[1] = {}
routes.ChaseActivityRoute4Loop.roads[1].road = "highway02_03 AI Road 11"
routes.ChaseActivityRoute4Loop.roads[1].direction = "with"
routes.ChaseActivityRoute4Loop.roads[2] = {}
routes.ChaseActivityRoute4Loop.roads[2].road = "highway02_03 AI Road 12"
routes.ChaseActivityRoute4Loop.roads[2].direction = "with"
routes.ChaseActivityRoute4Loop.roads[3] = {}
routes.ChaseActivityRoute4Loop.roads[3].road = "highway02_03 AI Road 13"
routes.ChaseActivityRoute4Loop.roads[3].direction = "with"
routes.ChaseActivityRoute4Loop.roads[4] = {}
routes.ChaseActivityRoute4Loop.roads[4].road = "mountain_6l_east_01 AI Road 19"
routes.ChaseActivityRoute4Loop.roads[4].direction = "against"
routes.ChaseActivityRoute4Loop.roads[5] = {}
routes.ChaseActivityRoute4Loop.roads[5].road = "mountain_6l_east_01 AI Road 18"
routes.ChaseActivityRoute4Loop.roads[5].direction = "against"
routes.ChaseActivityRoute4Loop.roads[6] = {}
routes.ChaseActivityRoute4Loop.roads[6].road = "mountain_6l_east_01 AI Road 17"
routes.ChaseActivityRoute4Loop.roads[6].direction = "against"
routes.ChaseActivityRoute4Loop.roads[7] = {}
routes.ChaseActivityRoute4Loop.roads[7].road = "mountain_6l_east_01 AI Road 16"
routes.ChaseActivityRoute4Loop.roads[7].direction = "against"
routes.ChaseActivityRoute4Loop.roads[8] = {}
routes.ChaseActivityRoute4Loop.roads[8].road = "mountain_6l_east_01 AI Road 15"
routes.ChaseActivityRoute4Loop.roads[8].direction = "against"
routes.ChaseActivityRoute4Loop.roads[9] = {}
routes.ChaseActivityRoute4Loop.roads[9].road = "mountain_6l_east_01 AI Road 14"
routes.ChaseActivityRoute4Loop.roads[9].direction = "against"
routes.ChaseActivityRoute4Loop.roads[10] = {}
routes.ChaseActivityRoute4Loop.roads[10].road = "mountain_6l_east_01 AI Road 13"
routes.ChaseActivityRoute4Loop.roads[10].direction = "against"
routes.ChaseActivityRoute4Loop.roads[11] = {}
routes.ChaseActivityRoute4Loop.roads[11].road = "mountain_6l_east_01 AI Road 12"
routes.ChaseActivityRoute4Loop.roads[11].direction = "against"
routes.ChaseActivityRoute4Loop.roads[12] = {}
routes.ChaseActivityRoute4Loop.roads[12].road = "mountain_6l_east_01 AI Road 11"
routes.ChaseActivityRoute4Loop.roads[12].direction = "against"
routes.ChaseActivityRoute4Loop.roads[13] = {}
routes.ChaseActivityRoute4Loop.roads[13].road = "mountain_6l_east_01 AI Road 10"
routes.ChaseActivityRoute4Loop.roads[13].direction = "against"
routes.ChaseActivityRoute4Loop.roads[14] = {}
routes.ChaseActivityRoute4Loop.roads[14].road = "mountain_6l_east_01 AI Road 9"
routes.ChaseActivityRoute4Loop.roads[14].direction = "against"
routes.ChaseActivityRoute4Loop.roads[15] = {}
routes.ChaseActivityRoute4Loop.roads[15].road = "mountain_10l_w_01a AI Road 9"
routes.ChaseActivityRoute4Loop.roads[15].direction = "against"
routes.ChaseActivityRoute4Loop.roads[16] = {}
routes.ChaseActivityRoute4Loop.roads[16].road = "mountain_10l_w_01a AI Road 8"
routes.ChaseActivityRoute4Loop.roads[16].direction = "against"
routes.ChaseActivityRoute4Loop.roads[17] = {}
routes.ChaseActivityRoute4Loop.roads[17].road = "mountain_10l_w_01a AI Road 7"
routes.ChaseActivityRoute4Loop.roads[17].direction = "against"
routes.ChaseActivityRoute4Loop.roads[18] = {}
routes.ChaseActivityRoute4Loop.roads[18].road = "mountain_10l_w_01a AI Road 6"
routes.ChaseActivityRoute4Loop.roads[18].direction = "against"
routes.ChaseActivityRoute4Loop.roads[19] = {}
routes.ChaseActivityRoute4Loop.roads[19].road = "mountain_10l_w_01a AI Road 5"
routes.ChaseActivityRoute4Loop.roads[19].direction = "against"
routes.ChaseActivityRoute4Loop.roads[20] = {}
routes.ChaseActivityRoute4Loop.roads[20].road = "mountain_10l_w_01a AI Road 4"
routes.ChaseActivityRoute4Loop.roads[20].direction = "against"
routes.ChaseActivityRoute4Loop.roads[21] = {}
routes.ChaseActivityRoute4Loop.roads[21].road = "mountain_10l_w_01a AI Road 3"
routes.ChaseActivityRoute4Loop.roads[21].direction = "against"
routes.ChaseActivityRoute4Loop.roads[22] = {}
routes.ChaseActivityRoute4Loop.roads[22].road = "mountain_10l_w_01a AI Road 2"
routes.ChaseActivityRoute4Loop.roads[22].direction = "against"
routes.ChaseActivityRoute4Loop.roads[23] = {}
routes.ChaseActivityRoute4Loop.roads[23].road = "mountain_10l_w_01a AI Road 1"
routes.ChaseActivityRoute4Loop.roads[23].direction = "against"
routes.ChaseActivityRoute4Loop.roads[24] = {}
routes.ChaseActivityRoute4Loop.roads[24].road = "mountain_10l_w_01a AI Road 0"
routes.ChaseActivityRoute4Loop.roads[24].direction = "against"
routes.ChaseActivityRoute4Loop.roads[25] = {}
routes.ChaseActivityRoute4Loop.roads[25].road = "marin_6l_west_01a AI Road 38"
routes.ChaseActivityRoute4Loop.roads[25].direction = "against"
routes.ChaseActivityRoute4Loop.roads[26] = {}
routes.ChaseActivityRoute4Loop.roads[26].road = "marin_6l_west_01a AI Road 37"
routes.ChaseActivityRoute4Loop.roads[26].direction = "against"
routes.ChaseActivityRoute4Loop.roads[27] = {}
routes.ChaseActivityRoute4Loop.roads[27].road = "marin_6l_west_01a AI Road 36"
routes.ChaseActivityRoute4Loop.roads[27].direction = "against"
routes.ChaseActivityRoute4Loop.roads[28] = {}
routes.ChaseActivityRoute4Loop.roads[28].road = "mountain_10l_w_01b AI Road 17"
routes.ChaseActivityRoute4Loop.roads[28].direction = "with"
routes.ChaseActivityRoute4Loop.roads[29] = {}
routes.ChaseActivityRoute4Loop.roads[29].road = "mountain_10l_w_01b AI Road 18"
routes.ChaseActivityRoute4Loop.roads[29].direction = "with"
routes.ChaseActivityRoute4Loop.roads[30] = {}
routes.ChaseActivityRoute4Loop.roads[30].road = "mountain_10l_w_01b AI Road 19"
routes.ChaseActivityRoute4Loop.roads[30].direction = "with"
routes.ChaseActivityRoute4Loop.roads[31] = {}
routes.ChaseActivityRoute4Loop.roads[31].road = "mountain_10l_w_01b AI Road 20"
routes.ChaseActivityRoute4Loop.roads[31].direction = "with"
routes.ChaseActivityRoute4Loop.roads[32] = {}
routes.ChaseActivityRoute4Loop.roads[32].road = "mountain_10l_w_01b AI Road 21"
routes.ChaseActivityRoute4Loop.roads[32].direction = "with"
routes.ChaseActivityRoute4Loop.roads[33] = {}
routes.ChaseActivityRoute4Loop.roads[33].road = "mountain_10l_w_01b AI Road 22"
routes.ChaseActivityRoute4Loop.roads[33].direction = "with"
routes.ChaseActivityRoute4Loop.roads[34] = {}
routes.ChaseActivityRoute4Loop.roads[34].road = "mountain_10l_w_01b AI Road 23"
routes.ChaseActivityRoute4Loop.roads[34].direction = "with"
routes.ChaseActivityRoute4Loop.roads[35] = {}
routes.ChaseActivityRoute4Loop.roads[35].road = "mountain_10l_w_01b AI Road 24"
routes.ChaseActivityRoute4Loop.roads[35].direction = "with"
routes.ChaseActivityRoute4Loop.roads[36] = {}
routes.ChaseActivityRoute4Loop.roads[36].road = "mountain_10l_w_01b AI Road 25"
routes.ChaseActivityRoute4Loop.roads[36].direction = "with"
routes.ChaseActivityRoute4Loop.roads[37] = {}
routes.ChaseActivityRoute4Loop.roads[37].road = "mountain_10l_w_01b AI Road 26"
routes.ChaseActivityRoute4Loop.roads[37].direction = "with"
routes.ChaseActivityRoute4Loop.roads[38] = {}
routes.ChaseActivityRoute4Loop.roads[38].road = "mountain_10l_w_01b AI Road 27"
routes.ChaseActivityRoute4Loop.roads[38].direction = "with"
routes.ChaseActivityRoute4Loop.roads[39] = {}
routes.ChaseActivityRoute4Loop.roads[39].road = "mountain_10l_w_01b AI Road 28"
routes.ChaseActivityRoute4Loop.roads[39].direction = "with"
routes.ChaseActivityRoute4Loop.roads[40] = {}
routes.ChaseActivityRoute4Loop.roads[40].road = "mountain_10l_w_01b AI Road 29"
routes.ChaseActivityRoute4Loop.roads[40].direction = "with"
routes.ChaseActivityRoute4Loop.roads[41] = {}
routes.ChaseActivityRoute4Loop.roads[41].road = "mountain_6l_east_08 AI Road 0"
routes.ChaseActivityRoute4Loop.roads[41].direction = "with"
routes.ChaseActivityRoute4Loop.roads[42] = {}
routes.ChaseActivityRoute4Loop.roads[42].road = "marin_shortcut_40 AI Road 0"
routes.ChaseActivityRoute4Loop.roads[42].direction = "with"
