routes = routes or {}
routes.StreetraceTakedownActivity1 = {}
routes.StreetraceTakedownActivity1.checkpoints = {}
routes.StreetraceTakedownActivity1.checkpoints[1] = {}
routes.StreetraceTakedownActivity1.checkpoints[1].position = vec.vector(-3982.673, 43.70337, 1294.766, 1)
routes.StreetraceTakedownActivity1.checkpoints[1].heading = 1.444492
routes.StreetraceTakedownActivity1.checkpoints[1].roadName = "ggp_10l_centre_01 AI Road 1"
routes.StreetraceTakedownActivity1.checkpoints[2] = {}
routes.StreetraceTakedownActivity1.checkpoints[2].position = vec.vector(-3491.085, 54.38559, 1327.765, 1)
routes.StreetraceTakedownActivity1.checkpoints[2].heading = 1.527779
routes.StreetraceTakedownActivity1.checkpoints[2].roadName = "ggp_10l_centre_01 AI Road 3"
routes.StreetraceTakedownActivity1.checkpoints[3] = {}
routes.StreetraceTakedownActivity1.checkpoints[3].position = vec.vector(-2951.969, 57.24722, 1357.801, 1)
routes.StreetraceTakedownActivity1.checkpoints[3].heading = 1.522934
routes.StreetraceTakedownActivity1.checkpoints[3].roadName = "ggp_10l_centre_01 AI Road 5"
routes.StreetraceTakedownActivity1.checkpoints[4] = {}
routes.StreetraceTakedownActivity1.checkpoints[4].position = vec.vector(-2530.093, 66.88484, 1366.804, 1)
routes.StreetraceTakedownActivity1.checkpoints[4].heading = 1.605292
routes.StreetraceTakedownActivity1.checkpoints[4].roadName = "ggp_10l_centre_01 AI Road 7"
routes.StreetraceTakedownActivity1.checkpoints[5] = {}
routes.StreetraceTakedownActivity1.checkpoints[5].position = vec.vector(-2019.375, 55.79103, 1293.706, 1)
routes.StreetraceTakedownActivity1.checkpoints[5].heading = 1.735518
routes.StreetraceTakedownActivity1.checkpoints[5].roadName = "dt_10l_south_01 AI Road 17"
routes.StreetraceTakedownActivity1.checkpoints[6] = {}
routes.StreetraceTakedownActivity1.checkpoints[6].position = vec.vector(-1469.504, 48.23041, 1199.731, 1)
routes.StreetraceTakedownActivity1.checkpoints[6].heading = 1.739892
routes.StreetraceTakedownActivity1.checkpoints[6].roadName = "dt_10l_south_01 AI Road 14"
routes.StreetraceTakedownActivity1.checkpoints[7] = {}
routes.StreetraceTakedownActivity1.checkpoints[7].position = vec.vector(-949.6014, 40.75, 1127.588, 1)
routes.StreetraceTakedownActivity1.checkpoints[7].heading = 1.692095
routes.StreetraceTakedownActivity1.checkpoints[7].roadName = "dt_10l_south_01 AI Road 11"
routes.StreetraceTakedownActivity1.checkpoints[8] = {}
routes.StreetraceTakedownActivity1.checkpoints[8].position = vec.vector(-594.6671, 24.38378, 1087.931, 1)
routes.StreetraceTakedownActivity1.checkpoints[8].heading = 1.679749
routes.StreetraceTakedownActivity1.checkpoints[8].roadName = "dt_10l_south_01 AI Road 8"
routes.StreetraceTakedownActivity1.checkpoints[9] = {}
routes.StreetraceTakedownActivity1.checkpoints[9].position = vec.vector(-121.6345, 18, 1029.232, 1)
routes.StreetraceTakedownActivity1.checkpoints[9].heading = 1.67562
routes.StreetraceTakedownActivity1.checkpoints[9].roadName = "dt_10l_south_01 AI Road 4"
routes.StreetraceTakedownActivity1.checkpoints[10] = {}
routes.StreetraceTakedownActivity1.checkpoints[10].position = vec.vector(303.3199, 17.80668, 979.5806, 1)
routes.StreetraceTakedownActivity1.checkpoints[10].heading = 1.688909
routes.StreetraceTakedownActivity1.checkpoints[10].roadName = "dt_10l_south_01 AI Road 2"
routes.StreetraceTakedownActivity1.arrows = {}
routes.StreetraceTakedownActivity1.roads = {}
routes.StreetraceTakedownActivity1.roads[1] = {}
routes.StreetraceTakedownActivity1.roads[1].road = "_unnamed road 0x26d4aca8 : 0xfe901200 AI Road 0"
routes.StreetraceTakedownActivity1.roads[1].direction = "against"
routes.StreetraceTakedownActivity1.roads[2] = {}
routes.StreetraceTakedownActivity1.roads[2].road = "ggp_10l_centre_01 AI Road 1"
routes.StreetraceTakedownActivity1.roads[2].direction = "with"
routes.StreetraceTakedownActivity1.roads[3] = {}
routes.StreetraceTakedownActivity1.roads[3].road = "ggp_10l_centre_01 AI Road 2"
routes.StreetraceTakedownActivity1.roads[3].direction = "with"
routes.StreetraceTakedownActivity1.roads[4] = {}
routes.StreetraceTakedownActivity1.roads[4].road = "ggp_10l_centre_01 AI Road 3"
routes.StreetraceTakedownActivity1.roads[4].direction = "with"
routes.StreetraceTakedownActivity1.roads[5] = {}
routes.StreetraceTakedownActivity1.roads[5].road = "ggp_10l_centre_01 AI Road 4"
routes.StreetraceTakedownActivity1.roads[5].direction = "with"
routes.StreetraceTakedownActivity1.roads[6] = {}
routes.StreetraceTakedownActivity1.roads[6].road = "ggp_10l_centre_01 AI Road 5"
routes.StreetraceTakedownActivity1.roads[6].direction = "with"
routes.StreetraceTakedownActivity1.roads[7] = {}
routes.StreetraceTakedownActivity1.roads[7].road = "ggp_10l_centre_01 AI Road 6"
routes.StreetraceTakedownActivity1.roads[7].direction = "with"
routes.StreetraceTakedownActivity1.roads[8] = {}
routes.StreetraceTakedownActivity1.roads[8].road = "ggp_10l_centre_01 AI Road 7"
routes.StreetraceTakedownActivity1.roads[8].direction = "with"
routes.StreetraceTakedownActivity1.roads[9] = {}
routes.StreetraceTakedownActivity1.roads[9].road = "ggp_10l_centre_01 AI Road 8"
routes.StreetraceTakedownActivity1.roads[9].direction = "with"
routes.StreetraceTakedownActivity1.roads[10] = {}
routes.StreetraceTakedownActivity1.roads[10].road = "dt_10l_south_01 AI Road 18"
routes.StreetraceTakedownActivity1.roads[10].direction = "against"
routes.StreetraceTakedownActivity1.roads[11] = {}
routes.StreetraceTakedownActivity1.roads[11].road = "dt_10l_south_01 AI Road 17"
routes.StreetraceTakedownActivity1.roads[11].direction = "against"
routes.StreetraceTakedownActivity1.roads[12] = {}
routes.StreetraceTakedownActivity1.roads[12].road = "dt_10l_south_01 AI Road 16"
routes.StreetraceTakedownActivity1.roads[12].direction = "against"
routes.StreetraceTakedownActivity1.roads[13] = {}
routes.StreetraceTakedownActivity1.roads[13].road = "dt_10l_south_01 AI Road 15"
routes.StreetraceTakedownActivity1.roads[13].direction = "against"
routes.StreetraceTakedownActivity1.roads[14] = {}
routes.StreetraceTakedownActivity1.roads[14].road = "dt_10l_south_01 AI Road 14"
routes.StreetraceTakedownActivity1.roads[14].direction = "against"
routes.StreetraceTakedownActivity1.roads[15] = {}
routes.StreetraceTakedownActivity1.roads[15].road = "dt_10l_south_01 AI Road 13"
routes.StreetraceTakedownActivity1.roads[15].direction = "against"
routes.StreetraceTakedownActivity1.roads[16] = {}
routes.StreetraceTakedownActivity1.roads[16].road = "dt_10l_south_01 AI Road 12"
routes.StreetraceTakedownActivity1.roads[16].direction = "against"
routes.StreetraceTakedownActivity1.roads[17] = {}
routes.StreetraceTakedownActivity1.roads[17].road = "dt_10l_south_01 AI Road 11"
routes.StreetraceTakedownActivity1.roads[17].direction = "against"
routes.StreetraceTakedownActivity1.roads[18] = {}
routes.StreetraceTakedownActivity1.roads[18].road = "dt_10l_south_01 AI Road 10"
routes.StreetraceTakedownActivity1.roads[18].direction = "against"
routes.StreetraceTakedownActivity1.roads[19] = {}
routes.StreetraceTakedownActivity1.roads[19].road = "dt_10l_south_01 AI Road 9"
routes.StreetraceTakedownActivity1.roads[19].direction = "against"
routes.StreetraceTakedownActivity1.roads[20] = {}
routes.StreetraceTakedownActivity1.roads[20].road = "dt_10l_south_01 AI Road 8"
routes.StreetraceTakedownActivity1.roads[20].direction = "against"
routes.StreetraceTakedownActivity1.roads[21] = {}
routes.StreetraceTakedownActivity1.roads[21].road = "dt_10l_south_01 AI Road 7"
routes.StreetraceTakedownActivity1.roads[21].direction = "against"
routes.StreetraceTakedownActivity1.roads[22] = {}
routes.StreetraceTakedownActivity1.roads[22].road = "dt_10l_south_01 AI Road 6"
routes.StreetraceTakedownActivity1.roads[22].direction = "against"
routes.StreetraceTakedownActivity1.roads[23] = {}
routes.StreetraceTakedownActivity1.roads[23].road = "dt_10l_south_01 AI Road 5"
routes.StreetraceTakedownActivity1.roads[23].direction = "against"
routes.StreetraceTakedownActivity1.roads[24] = {}
routes.StreetraceTakedownActivity1.roads[24].road = "dt_10l_south_01 AI Road 4"
routes.StreetraceTakedownActivity1.roads[24].direction = "against"
routes.StreetraceTakedownActivity1.roads[25] = {}
routes.StreetraceTakedownActivity1.roads[25].road = "dt_10l_south_01 AI Road 3"
routes.StreetraceTakedownActivity1.roads[25].direction = "against"
routes.StreetraceTakedownActivity1.roads[26] = {}
routes.StreetraceTakedownActivity1.roads[26].road = "dt_10l_south_01 AI Road 2"
routes.StreetraceTakedownActivity1.roads[26].direction = "against"
