routes = routes or {}
routes.StreetraceTakedownActivity4Route = {}
routes.StreetraceTakedownActivity4Route.checkpoints = {}
routes.StreetraceTakedownActivity4Route.checkpoints[1] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[1].position = vec.vector(449.3809, 17.84307, -2990.815, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[1].heading = -0.8793246
routes.StreetraceTakedownActivity4Route.checkpoints[1].roadName = "marin_4l_east_02 AI Road 2"
routes.StreetraceTakedownActivity4Route.checkpoints[2] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[2].position = vec.vector(142.6344, 18.49568, -2839.912, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[2].heading = -1.200637
routes.StreetraceTakedownActivity4Route.checkpoints[2].roadName = "marin_4l_east_02 AI Road 0"
routes.StreetraceTakedownActivity4Route.checkpoints[3] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[3].position = vec.vector(-177.1134, 18, -2454.333, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[3].heading = -0.2097854
routes.StreetraceTakedownActivity4Route.checkpoints[3].roadName = "mountain_6l_east_01 AI Road 19"
routes.StreetraceTakedownActivity4Route.checkpoints[4] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[4].position = vec.vector(79.73547, 5, -2202.307, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[4].heading = 1.395082
routes.StreetraceTakedownActivity4Route.checkpoints[4].roadName = "mountain_6l_east_01 AI Road 17"
routes.StreetraceTakedownActivity4Route.checkpoints[5] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[5].position = vec.vector(581.0565, 5.148751, -2171.616, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[5].heading = 1.57442
routes.StreetraceTakedownActivity4Route.checkpoints[5].roadName = "mountain_6l_east_01 AI Road 15"
routes.StreetraceTakedownActivity4Route.checkpoints[6] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[6].position = vec.vector(959.4649, 5, -2423.64, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[6].heading = 2.87666
routes.StreetraceTakedownActivity4Route.checkpoints[6].roadName = "mountain_6l_east_01 AI Road 12"
routes.StreetraceTakedownActivity4Route.checkpoints[7] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[7].position = vec.vector(1015, 11.52989, -2785.755, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[7].heading = 3.141593
routes.StreetraceTakedownActivity4Route.checkpoints[7].roadName = "mountain_6l_east_01 AI Road 11"
routes.StreetraceTakedownActivity4Route.checkpoints[8] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[8].position = vec.vector(1085.871, 20.3374, -3101.981, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[8].heading = 2.058028
routes.StreetraceTakedownActivity4Route.checkpoints[8].roadName = "mountain_6l_east_01 AI Road 10"
routes.StreetraceTakedownActivity4Route.checkpoints[9] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[9].position = vec.vector(1519.692, 26.03026, -3241.441, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[9].heading = 1.570802
routes.StreetraceTakedownActivity4Route.checkpoints[9].roadName = "mountain_6l_east_01 AI Road 6"
routes.StreetraceTakedownActivity4Route.checkpoints[10] = {}
routes.StreetraceTakedownActivity4Route.checkpoints[10].position = vec.vector(1820, 27.75, -3648.614, 1)
routes.StreetraceTakedownActivity4Route.checkpoints[10].heading = 3.141593
routes.StreetraceTakedownActivity4Route.checkpoints[10].roadName = "mountain_6l_east_01 AI Road 3"
routes.StreetraceTakedownActivity4Route.arrows = {}
routes.StreetraceTakedownActivity4Route.roads = {}
routes.StreetraceTakedownActivity4Route.roads[1] = {}
routes.StreetraceTakedownActivity4Route.roads[1].road = "marin_4l_east_02 AI Road 2"
routes.StreetraceTakedownActivity4Route.roads[1].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[2] = {}
routes.StreetraceTakedownActivity4Route.roads[2].road = "marin_4l_east_02 AI Road 1"
routes.StreetraceTakedownActivity4Route.roads[2].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[3] = {}
routes.StreetraceTakedownActivity4Route.roads[3].road = "marin_4l_east_02 AI Road 0"
routes.StreetraceTakedownActivity4Route.roads[3].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[4] = {}
routes.StreetraceTakedownActivity4Route.roads[4].road = "mountain_6l_east_01 AI Road 21"
routes.StreetraceTakedownActivity4Route.roads[4].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[5] = {}
routes.StreetraceTakedownActivity4Route.roads[5].road = "mountain_6l_east_01 AI Road 20"
routes.StreetraceTakedownActivity4Route.roads[5].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[6] = {}
routes.StreetraceTakedownActivity4Route.roads[6].road = "mountain_6l_east_01 AI Road 19"
routes.StreetraceTakedownActivity4Route.roads[6].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[7] = {}
routes.StreetraceTakedownActivity4Route.roads[7].road = "mountain_6l_east_01 AI Road 18"
routes.StreetraceTakedownActivity4Route.roads[7].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[8] = {}
routes.StreetraceTakedownActivity4Route.roads[8].road = "mountain_6l_east_01 AI Road 17"
routes.StreetraceTakedownActivity4Route.roads[8].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[9] = {}
routes.StreetraceTakedownActivity4Route.roads[9].road = "mountain_6l_east_01 AI Road 16"
routes.StreetraceTakedownActivity4Route.roads[9].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[10] = {}
routes.StreetraceTakedownActivity4Route.roads[10].road = "mountain_6l_east_01 AI Road 15"
routes.StreetraceTakedownActivity4Route.roads[10].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[11] = {}
routes.StreetraceTakedownActivity4Route.roads[11].road = "mountain_6l_east_01 AI Road 14"
routes.StreetraceTakedownActivity4Route.roads[11].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[12] = {}
routes.StreetraceTakedownActivity4Route.roads[12].road = "mountain_6l_east_01 AI Road 13"
routes.StreetraceTakedownActivity4Route.roads[12].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[13] = {}
routes.StreetraceTakedownActivity4Route.roads[13].road = "mountain_6l_east_01 AI Road 12"
routes.StreetraceTakedownActivity4Route.roads[13].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[14] = {}
routes.StreetraceTakedownActivity4Route.roads[14].road = "mountain_6l_east_01 AI Road 11"
routes.StreetraceTakedownActivity4Route.roads[14].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[15] = {}
routes.StreetraceTakedownActivity4Route.roads[15].road = "mountain_6l_east_01 AI Road 10"
routes.StreetraceTakedownActivity4Route.roads[15].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[16] = {}
routes.StreetraceTakedownActivity4Route.roads[16].road = "mountain_6l_east_01 AI Road 9"
routes.StreetraceTakedownActivity4Route.roads[16].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[17] = {}
routes.StreetraceTakedownActivity4Route.roads[17].road = "mountain_6l_east_01 AI Road 8"
routes.StreetraceTakedownActivity4Route.roads[17].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[18] = {}
routes.StreetraceTakedownActivity4Route.roads[18].road = "mountain_6l_east_01 AI Road 7"
routes.StreetraceTakedownActivity4Route.roads[18].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[19] = {}
routes.StreetraceTakedownActivity4Route.roads[19].road = "mountain_6l_east_01 AI Road 6"
routes.StreetraceTakedownActivity4Route.roads[19].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[20] = {}
routes.StreetraceTakedownActivity4Route.roads[20].road = "mountain_6l_east_01 AI Road 5"
routes.StreetraceTakedownActivity4Route.roads[20].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[21] = {}
routes.StreetraceTakedownActivity4Route.roads[21].road = "mountain_6l_east_01 AI Road 4"
routes.StreetraceTakedownActivity4Route.roads[21].direction = "against"
routes.StreetraceTakedownActivity4Route.roads[22] = {}
routes.StreetraceTakedownActivity4Route.roads[22].road = "mountain_6l_east_01 AI Road 3"
routes.StreetraceTakedownActivity4Route.roads[22].direction = "against"
