routes = routes or {}
routes.StreetraceTakedownActivity2Route = {}
routes.StreetraceTakedownActivity2Route.checkpoints = {}
routes.StreetraceTakedownActivity2Route.checkpoints[1] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[1].position = vec.vector(-2236.03, 47.25614, 389.1216, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[1].heading = 1.258401
routes.StreetraceTakedownActivity2Route.checkpoints[1].roadName = "highway_split_sanfran_02 AI Road 5"
routes.StreetraceTakedownActivity2Route.checkpoints[2] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[2].position = vec.vector(-1630.451, 60.23287, 793.4427, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[2].heading = 1.129795
routes.StreetraceTakedownActivity2Route.checkpoints[2].roadName = "highway_split_sanfran_02 AI Road 3"
routes.StreetraceTakedownActivity2Route.checkpoints[3] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[3].position = vec.vector(-1048.384, 57, 1075.562, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[3].heading = 0.4360615
routes.StreetraceTakedownActivity2Route.checkpoints[3].roadName = "highway01_16b AI Road 0"
routes.StreetraceTakedownActivity2Route.checkpoints[4] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[4].position = vec.vector(-941.3136, 63.46992, 1477.504, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[4].heading = 0.2734391
routes.StreetraceTakedownActivity2Route.checkpoints[4].roadName = "highway01_16b AI Road 2"
routes.StreetraceTakedownActivity2Route.checkpoints[5] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[5].position = vec.vector(-740.7358, 76.5, 2026.059, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[5].heading = 0.3753742
routes.StreetraceTakedownActivity2Route.checkpoints[5].roadName = "highway01_16b AI Road 5"
routes.StreetraceTakedownActivity2Route.checkpoints[6] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[6].position = vec.vector(-503.8903, 76.5, 2565.067, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[6].heading = 0.4680883
routes.StreetraceTakedownActivity2Route.checkpoints[6].roadName = "highway01_16b AI Road 8"
routes.StreetraceTakedownActivity2Route.checkpoints[7] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[7].position = vec.vector(50.50998, 53.50954, 2721.171, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[7].heading = 2.004365
routes.StreetraceTakedownActivity2Route.checkpoints[7].roadName = "highway01_16b AI Road 14"
routes.StreetraceTakedownActivity2Route.checkpoints[8] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[8].position = vec.vector(490.7661, 46.91515, 2458.072, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[8].heading = 2.192818
routes.StreetraceTakedownActivity2Route.checkpoints[8].roadName = "highway01_16b AI Road 17"
routes.StreetraceTakedownActivity2Route.checkpoints[9] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[9].position = vec.vector(944.6294, 28.4784, 2112.629, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[9].heading = 2.151888
routes.StreetraceTakedownActivity2Route.checkpoints[9].roadName = "bb_sliproad_04 AI Road 0"
routes.StreetraceTakedownActivity2Route.checkpoints[10] = {}
routes.StreetraceTakedownActivity2Route.checkpoints[10].position = vec.vector(1345.31, 8.519661, 2315.327, 1)
routes.StreetraceTakedownActivity2Route.checkpoints[10].heading = 0.7330491
routes.StreetraceTakedownActivity2Route.checkpoints[10].roadName = "mt_10l_centre_03b AI Road 5"
routes.StreetraceTakedownActivity2Route.arrows = {}
routes.StreetraceTakedownActivity2Route.roads = {}
routes.StreetraceTakedownActivity2Route.roads[1] = {}
routes.StreetraceTakedownActivity2Route.roads[1].road = "ggp_sliproad_03 AI Road 0"
routes.StreetraceTakedownActivity2Route.roads[1].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[2] = {}
routes.StreetraceTakedownActivity2Route.roads[2].road = "highway01_15 AI Road 3"
routes.StreetraceTakedownActivity2Route.roads[2].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[3] = {}
routes.StreetraceTakedownActivity2Route.roads[3].road = "highway01_15 AI Road 2"
routes.StreetraceTakedownActivity2Route.roads[3].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[4] = {}
routes.StreetraceTakedownActivity2Route.roads[4].road = "highway01_15 AI Road 1"
routes.StreetraceTakedownActivity2Route.roads[4].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[5] = {}
routes.StreetraceTakedownActivity2Route.roads[5].road = "highway01_15 AI Road 0"
routes.StreetraceTakedownActivity2Route.roads[5].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[6] = {}
routes.StreetraceTakedownActivity2Route.roads[6].road = "highway_split_sanfran_02 AI Road 5"
routes.StreetraceTakedownActivity2Route.roads[6].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[7] = {}
routes.StreetraceTakedownActivity2Route.roads[7].road = "highway_split_sanfran_02 AI Road 4"
routes.StreetraceTakedownActivity2Route.roads[7].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[8] = {}
routes.StreetraceTakedownActivity2Route.roads[8].road = "highway_split_sanfran_02 AI Road 3"
routes.StreetraceTakedownActivity2Route.roads[8].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[9] = {}
routes.StreetraceTakedownActivity2Route.roads[9].road = "highway_split_sanfran_02 AI Road 2"
routes.StreetraceTakedownActivity2Route.roads[9].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[10] = {}
routes.StreetraceTakedownActivity2Route.roads[10].road = "highway_split_sanfran_02 AI Road 1"
routes.StreetraceTakedownActivity2Route.roads[10].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[11] = {}
routes.StreetraceTakedownActivity2Route.roads[11].road = "highway_split_sanfran_02 AI Road 0"
routes.StreetraceTakedownActivity2Route.roads[11].direction = "against"
routes.StreetraceTakedownActivity2Route.roads[12] = {}
routes.StreetraceTakedownActivity2Route.roads[12].road = "highway01_16b AI Road 0"
routes.StreetraceTakedownActivity2Route.roads[12].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[13] = {}
routes.StreetraceTakedownActivity2Route.roads[13].road = "highway01_16b AI Road 1"
routes.StreetraceTakedownActivity2Route.roads[13].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[14] = {}
routes.StreetraceTakedownActivity2Route.roads[14].road = "highway01_16b AI Road 2"
routes.StreetraceTakedownActivity2Route.roads[14].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[15] = {}
routes.StreetraceTakedownActivity2Route.roads[15].road = "highway01_16b AI Road 3"
routes.StreetraceTakedownActivity2Route.roads[15].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[16] = {}
routes.StreetraceTakedownActivity2Route.roads[16].road = "highway01_16b AI Road 4"
routes.StreetraceTakedownActivity2Route.roads[16].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[17] = {}
routes.StreetraceTakedownActivity2Route.roads[17].road = "highway01_16b AI Road 5"
routes.StreetraceTakedownActivity2Route.roads[17].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[18] = {}
routes.StreetraceTakedownActivity2Route.roads[18].road = "highway01_16b AI Road 6"
routes.StreetraceTakedownActivity2Route.roads[18].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[19] = {}
routes.StreetraceTakedownActivity2Route.roads[19].road = "highway01_16b AI Road 7"
routes.StreetraceTakedownActivity2Route.roads[19].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[20] = {}
routes.StreetraceTakedownActivity2Route.roads[20].road = "highway01_16b AI Road 8"
routes.StreetraceTakedownActivity2Route.roads[20].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[21] = {}
routes.StreetraceTakedownActivity2Route.roads[21].road = "highway01_16b AI Road 9"
routes.StreetraceTakedownActivity2Route.roads[21].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[22] = {}
routes.StreetraceTakedownActivity2Route.roads[22].road = "highway01_16b AI Road 10"
routes.StreetraceTakedownActivity2Route.roads[22].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[23] = {}
routes.StreetraceTakedownActivity2Route.roads[23].road = "highway01_16b AI Road 11"
routes.StreetraceTakedownActivity2Route.roads[23].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[24] = {}
routes.StreetraceTakedownActivity2Route.roads[24].road = "highway01_16b AI Road 12"
routes.StreetraceTakedownActivity2Route.roads[24].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[25] = {}
routes.StreetraceTakedownActivity2Route.roads[25].road = "highway01_16b AI Road 13"
routes.StreetraceTakedownActivity2Route.roads[25].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[26] = {}
routes.StreetraceTakedownActivity2Route.roads[26].road = "highway01_16b AI Road 14"
routes.StreetraceTakedownActivity2Route.roads[26].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[27] = {}
routes.StreetraceTakedownActivity2Route.roads[27].road = "highway01_16b AI Road 15"
routes.StreetraceTakedownActivity2Route.roads[27].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[28] = {}
routes.StreetraceTakedownActivity2Route.roads[28].road = "highway01_16b AI Road 16"
routes.StreetraceTakedownActivity2Route.roads[28].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[29] = {}
routes.StreetraceTakedownActivity2Route.roads[29].road = "highway01_16b AI Road 17"
routes.StreetraceTakedownActivity2Route.roads[29].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[30] = {}
routes.StreetraceTakedownActivity2Route.roads[30].road = "highway01_16b AI Road 18"
routes.StreetraceTakedownActivity2Route.roads[30].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[31] = {}
routes.StreetraceTakedownActivity2Route.roads[31].road = "bb_sliproad_04 AI Road 0"
routes.StreetraceTakedownActivity2Route.roads[31].direction = "with"
routes.StreetraceTakedownActivity2Route.roads[32] = {}
routes.StreetraceTakedownActivity2Route.roads[32].road = "mt_10l_centre_03b AI Road 5"
routes.StreetraceTakedownActivity2Route.roads[32].direction = "with"
