routes = routes or {}
routes["All clubbed out warmup"] = {}
routes["All clubbed out warmup"].checkpoints = {}
routes["All clubbed out warmup"].checkpoints[1] = {}
routes["All clubbed out warmup"].checkpoints[1].position = vec.vector(-1457.388, 4.999999, -157.5894, 1)
routes["All clubbed out warmup"].checkpoints[1].heading = 1.412005
routes["All clubbed out warmup"].checkpoints[1].roadName = "dt_8l_north_04 AI Road 1"
routes["All clubbed out warmup"].checkpoints[2] = {}
routes["All clubbed out warmup"].checkpoints[2].position = vec.vector(-1255.381, 4.999999, -40.3601, 1)
routes["All clubbed out warmup"].checkpoints[2].heading = 0.7906863
routes["All clubbed out warmup"].checkpoints[2].roadName = "dt_10l_centre_01 AI Road 0"
routes["All clubbed out warmup"].checkpoints[3] = {}
routes["All clubbed out warmup"].checkpoints[3].position = vec.vector(-1177.007, 15.63424, 149.5085, 1)
routes["All clubbed out warmup"].checkpoints[3].heading = -1.408586
routes["All clubbed out warmup"].checkpoints[3].roadName = "dt_8l_centre_01ab AI Road 0"
routes["All clubbed out warmup"].checkpoints[4] = {}
routes["All clubbed out warmup"].checkpoints[4].position = vec.vector(-1385.157, 24.80458, 168.162, 1)
routes["All clubbed out warmup"].checkpoints[4].heading = -2.441682
routes["All clubbed out warmup"].checkpoints[4].roadName = "dt_6l_west_02 AI Road 0"
routes["All clubbed out warmup"].checkpoints[5] = {}
routes["All clubbed out warmup"].checkpoints[5].position = vec.vector(-1689.996, 14.37018, -37.0301, 1)
routes["All clubbed out warmup"].checkpoints[5].heading = 3.045166
routes["All clubbed out warmup"].checkpoints[5].roadName = "dt_8l_north_04 AI Road 0"
routes["All clubbed out warmup"].arrows = {}
routes["All clubbed out warmup"].roads = {}
routes["All clubbed out warmup"].roads[1] = {}
routes["All clubbed out warmup"].roads[1].road = "dt_8l_north_04 AI Road 1"
routes["All clubbed out warmup"].roads[1].direction = "with"
routes["All clubbed out warmup"].roads[2] = {}
routes["All clubbed out warmup"].roads[2].road = "dt_8l_north_04 AI Road 2"
routes["All clubbed out warmup"].roads[2].direction = "with"
routes["All clubbed out warmup"].roads[3] = {}
routes["All clubbed out warmup"].roads[3].road = "dt_10l_centre_01 AI Road 0"
routes["All clubbed out warmup"].roads[3].direction = "with"
routes["All clubbed out warmup"].roads[4] = {}
routes["All clubbed out warmup"].roads[4].road = "dt_8l_centre_01ab AI Road 0"
routes["All clubbed out warmup"].roads[4].direction = "with"
routes["All clubbed out warmup"].roads[5] = {}
routes["All clubbed out warmup"].roads[5].road = "dt_6l_west_02 AI Road 0"
routes["All clubbed out warmup"].roads[5].direction = "with"
routes["All clubbed out warmup"].roads[6] = {}
routes["All clubbed out warmup"].roads[6].road = "dt_8l_north_04 AI Road 0"
routes["All clubbed out warmup"].roads[6].direction = "with"
