routes = routes or {}
routes["Heat from above ambulance"] = {}
routes["Heat from above ambulance"].checkpoints = {}
routes["Heat from above ambulance"].checkpoints[1] = {}
routes["Heat from above ambulance"].checkpoints[1].position = vec.vector(-145.9934, 19.10469, 983.2249, 1)
routes["Heat from above ambulance"].checkpoints[1].heading = -0.8252894
routes["Heat from above ambulance"].checkpoints[1].roadName = "dt_shortcut_08 AI Road 0"
routes["Heat from above ambulance"].arrows = {}
routes["Heat from above ambulance"].roads = {}
routes["Heat from above ambulance"].roads[1] = {}
routes["Heat from above ambulance"].roads[1].road = "dt_6l_centre_03 AI Road 0"
routes["Heat from above ambulance"].roads[1].direction = "with"
routes["Heat from above ambulance"].roads[2] = {}
routes["Heat from above ambulance"].roads[2].road = "dt_shortcut_08 AI Road 0"
routes["Heat from above ambulance"].roads[2].direction = "with"
routes["Heat from above racer"] = {}
routes["Heat from above racer"].checkpoints = {}
routes["Heat from above racer"].checkpoints[1] = {}
routes["Heat from above racer"].checkpoints[1].position = vec.vector(-767.6436, 66.74999, 1811.548, 1)
routes["Heat from above racer"].checkpoints[1].heading = -1.347867
routes["Heat from above racer"].checkpoints[1].roadName = "dt_10l_south_02b AI Road 6"
routes["Heat from above racer"].checkpoints[2] = {}
routes["Heat from above racer"].checkpoints[2].position = vec.vector(-1222.326, 66.75, 1886.835, 1)
routes["Heat from above racer"].checkpoints[2].heading = -1.436274
routes["Heat from above racer"].checkpoints[2].roadName = "dt_10l_south_02b AI Road 3"
routes["Heat from above racer"].arrows = {}
routes["Heat from above racer"].roads = {}
routes["Heat from above racer"].roads[1] = {}
routes["Heat from above racer"].roads[1].road = "dt_10l_south_02b AI Road 8"
routes["Heat from above racer"].roads[1].direction = "against"
routes["Heat from above racer"].roads[2] = {}
routes["Heat from above racer"].roads[2].road = "dt_10l_south_02b AI Road 7"
routes["Heat from above racer"].roads[2].direction = "against"
routes["Heat from above racer"].roads[3] = {}
routes["Heat from above racer"].roads[3].road = "dt_10l_south_02b AI Road 6"
routes["Heat from above racer"].roads[3].direction = "against"
routes["Heat from above racer"].roads[4] = {}
routes["Heat from above racer"].roads[4].road = "dt_10l_south_02b AI Road 5"
routes["Heat from above racer"].roads[4].direction = "against"
routes["Heat from above racer"].roads[5] = {}
routes["Heat from above racer"].roads[5].road = "dt_10l_south_02b AI Road 4"
routes["Heat from above racer"].roads[5].direction = "against"
routes["Heat from above racer"].roads[6] = {}
routes["Heat from above racer"].roads[6].road = "dt_10l_south_02b AI Road 3"
routes["Heat from above racer"].roads[6].direction = "against"
routes["Heat from above firetruck"] = {}
routes["Heat from above firetruck"].checkpoints = {}
routes["Heat from above firetruck"].checkpoints[1] = {}
routes["Heat from above firetruck"].checkpoints[1].position = vec.vector(-68.71109, 37.52234, 1503.078, 1)
routes["Heat from above firetruck"].checkpoints[1].heading = -2.918097
routes["Heat from above firetruck"].checkpoints[1].roadName = "dt_10l_centre_02 AI Road 2"
routes["Heat from above firetruck"].checkpoints[2] = {}
routes["Heat from above firetruck"].checkpoints[2].position = vec.vector(-159.6492, 18, 1102.679, 1)
routes["Heat from above firetruck"].checkpoints[2].heading = -2.918251
routes["Heat from above firetruck"].checkpoints[2].roadName = "dt_10l_centre_02 AI Road 0"
routes["Heat from above firetruck"].arrows = {}
routes["Heat from above firetruck"].roads = {}
routes["Heat from above firetruck"].roads[1] = {}
routes["Heat from above firetruck"].roads[1].road = "dt_10l_centre_02 AI Road 2"
routes["Heat from above firetruck"].roads[1].direction = "against"
routes["Heat from above firetruck"].roads[2] = {}
routes["Heat from above firetruck"].roads[2].road = "dt_10l_centre_02 AI Road 1"
routes["Heat from above firetruck"].roads[2].direction = "against"
routes["Heat from above firetruck"].roads[3] = {}
routes["Heat from above firetruck"].roads[3].road = "dt_10l_centre_02 AI Road 0"
routes["Heat from above firetruck"].roads[3].direction = "against"
routes["Heat from above red car 1"] = {}
routes["Heat from above red car 1"].checkpoints = {}
routes["Heat from above red car 1"].checkpoints[1] = {}
routes["Heat from above red car 1"].checkpoints[1].position = vec.vector(-298.1292, 40.74996, 2284.335, 1)
routes["Heat from above red car 1"].checkpoints[1].heading = 0.5938851
routes["Heat from above red car 1"].checkpoints[1].roadName = "mt_6l_w_02a AI Road 1"
routes["Heat from above red car 1"].checkpoints[2] = {}
routes["Heat from above red car 1"].checkpoints[2].position = vec.vector(-124.4103, 44, 2580.083, 1)
routes["Heat from above red car 1"].checkpoints[2].heading = 0.491243
routes["Heat from above red car 1"].checkpoints[2].roadName = "mt_shortcut_07 AI Road 0"
routes["Heat from above red car 1"].arrows = {}
routes["Heat from above red car 1"].roads = {}
routes["Heat from above red car 1"].roads[1] = {}
routes["Heat from above red car 1"].roads[1].road = "mt_6l_w_02a AI Road 1"
routes["Heat from above red car 1"].roads[1].direction = "with"
routes["Heat from above red car 1"].roads[2] = {}
routes["Heat from above red car 1"].roads[2].road = "mt_6l_w_02b AI Road 0"
routes["Heat from above red car 1"].roads[2].direction = "with"
routes["Heat from above red car 1"].roads[3] = {}
routes["Heat from above red car 1"].roads[3].road = "mt_shortcut_07 AI Road 0"
routes["Heat from above red car 1"].roads[3].direction = "with"
routes["Heat from above warmup"] = {}
routes["Heat from above warmup"].checkpoints = {}
routes["Heat from above warmup"].checkpoints[1] = {}
routes["Heat from above warmup"].checkpoints[1].position = vec.vector(75.46871, 35.55564, 103.8259, 1)
routes["Heat from above warmup"].checkpoints[1].heading = -1.390135
routes["Heat from above warmup"].checkpoints[1].roadName = "dt_4l_east_04 AI Road 2"
routes["Heat from above warmup"].checkpoints[2] = {}
routes["Heat from above warmup"].checkpoints[2].position = vec.vector(-21.27215, 21.11816, -4.873393, 1)
routes["Heat from above warmup"].checkpoints[2].heading = -3.007528
routes["Heat from above warmup"].checkpoints[2].roadName = "dt_8l_centre_02 AI Road 1"
routes["Heat from above warmup"].checkpoints[3] = {}
routes["Heat from above warmup"].checkpoints[3].position = vec.vector(-50.0257, 4.445169, -179.5801, 1)
routes["Heat from above warmup"].checkpoints[3].heading = -2.987823
routes["Heat from above warmup"].checkpoints[3].roadName = "dt_8l_centre_02 AI Road 0"
routes["Heat from above warmup"].checkpoints[4] = {}
routes["Heat from above warmup"].checkpoints[4].position = vec.vector(15.46741, 4.445144, -287.9583, 1)
routes["Heat from above warmup"].checkpoints[4].heading = 1.687964
routes["Heat from above warmup"].checkpoints[4].roadName = "dt_10l_east_01 AI Road 5"
routes["Heat from above warmup"].checkpoints[5] = {}
routes["Heat from above warmup"].checkpoints[5].position = vec.vector(265.866, 4.999999, -297.8768, 1)
routes["Heat from above warmup"].checkpoints[5].heading = 1.451901
routes["Heat from above warmup"].checkpoints[5].roadName = "dt_10l_east_01 AI Road 6"
routes["Heat from above warmup"].checkpoints[6] = {}
routes["Heat from above warmup"].checkpoints[6].position = vec.vector(621.0717, 6.080364, -177.9078, 1)
routes["Heat from above warmup"].checkpoints[6].heading = 1.067256
routes["Heat from above warmup"].checkpoints[6].roadName = "dt_10l_east_01 AI Road 7"
routes["Heat from above warmup"].checkpoints[7] = {}
routes["Heat from above warmup"].checkpoints[7].position = vec.vector(726.7973, 7.033201, -36.1104, 1)
routes["Heat from above warmup"].checkpoints[7].heading = -0.3793799
routes["Heat from above warmup"].checkpoints[7].roadName = "dt_6l_east_01 AI Road 0"
routes["Heat from above warmup"].checkpoints[8] = {}
routes["Heat from above warmup"].checkpoints[8].position = vec.vector(488.6665, 33.66143, 24.33493, 1)
routes["Heat from above warmup"].checkpoints[8].heading = -0.8379871
routes["Heat from above warmup"].checkpoints[8].roadName = "dt_4l_east_02 AI Road 1"
routes["Heat from above warmup"].checkpoints[9] = {}
routes["Heat from above warmup"].checkpoints[9].position = vec.vector(470.3257, 55.01775, 326.1289, 1)
routes["Heat from above warmup"].checkpoints[9].heading = 0.408631
routes["Heat from above warmup"].checkpoints[9].roadName = "dt_4l_east_02 AI Road 0"
routes["Heat from above warmup"].checkpoints[10] = {}
routes["Heat from above warmup"].checkpoints[10].position = vec.vector(292.2273, 70.91219, 395.3962, 1)
routes["Heat from above warmup"].checkpoints[10].heading = -2.304922
routes["Heat from above warmup"].checkpoints[10].roadName = "dt_4l_east_04 AI Road 3"
routes["Heat from above warmup"].checkpoints[11] = {}
routes["Heat from above warmup"].checkpoints[11].position = vec.vector(285.5664, 74.86486, 165.9875, 1)
routes["Heat from above warmup"].checkpoints[11].heading = -2.64173
routes["Heat from above warmup"].checkpoints[11].roadName = "dt_4l_east_04 AI Road 2"
routes["Heat from above warmup"].arrows = {}
routes["Heat from above warmup"].roads = {}
routes["Heat from above warmup"].roads[1] = {}
routes["Heat from above warmup"].roads[1].road = "dt_4l_east_04 AI Road 2"
routes["Heat from above warmup"].roads[1].direction = "against"
routes["Heat from above warmup"].roads[2] = {}
routes["Heat from above warmup"].roads[2].road = "dt_8l_centre_02 AI Road 1"
routes["Heat from above warmup"].roads[2].direction = "against"
routes["Heat from above warmup"].roads[3] = {}
routes["Heat from above warmup"].roads[3].road = "dt_8l_centre_02 AI Road 0"
routes["Heat from above warmup"].roads[3].direction = "against"
routes["Heat from above warmup"].roads[4] = {}
routes["Heat from above warmup"].roads[4].road = "dt_10l_east_01 AI Road 5"
routes["Heat from above warmup"].roads[4].direction = "with"
routes["Heat from above warmup"].roads[5] = {}
routes["Heat from above warmup"].roads[5].road = "dt_10l_east_01 AI Road 6"
routes["Heat from above warmup"].roads[5].direction = "with"
routes["Heat from above warmup"].roads[6] = {}
routes["Heat from above warmup"].roads[6].road = "dt_10l_east_01 AI Road 7"
routes["Heat from above warmup"].roads[6].direction = "with"
routes["Heat from above warmup"].roads[7] = {}
routes["Heat from above warmup"].roads[7].road = "dt_6l_east_01 AI Road 0"
routes["Heat from above warmup"].roads[7].direction = "with"
routes["Heat from above warmup"].roads[8] = {}
routes["Heat from above warmup"].roads[8].road = "dt_4l_east_02 AI Road 2"
routes["Heat from above warmup"].roads[8].direction = "against"
routes["Heat from above warmup"].roads[9] = {}
routes["Heat from above warmup"].roads[9].road = "dt_4l_east_02 AI Road 1"
routes["Heat from above warmup"].roads[9].direction = "against"
routes["Heat from above warmup"].roads[10] = {}
routes["Heat from above warmup"].roads[10].road = "dt_4l_east_02 AI Road 0"
routes["Heat from above warmup"].roads[10].direction = "against"
routes["Heat from above warmup"].roads[11] = {}
routes["Heat from above warmup"].roads[11].road = "dt_4l_east_04 AI Road 3"
routes["Heat from above warmup"].roads[11].direction = "against"
routes["Heat from above streetrace"] = {}
routes["Heat from above streetrace"].checkpoints = {}
routes["Heat from above streetrace"].checkpoints[1] = {}
routes["Heat from above streetrace"].checkpoints[1].position = vec.vector(-242.808, 61.90662, 28.09844, 1)
routes["Heat from above streetrace"].checkpoints[1].heading = 2.643916
routes["Heat from above streetrace"].checkpoints[1].roadName = "lombard_street AI Road 0"
routes["Heat from above streetrace"].checkpoints[2] = {}
routes["Heat from above streetrace"].checkpoints[2].position = vec.vector(50.09572, 18.99892, -56.5079, 1)
routes["Heat from above streetrace"].checkpoints[2].heading = 1.643912
routes["Heat from above streetrace"].checkpoints[2].roadName = "dt_8l_centre_01aa AI Road 0"
routes["Heat from above streetrace"].checkpoints[3] = {}
routes["Heat from above streetrace"].checkpoints[3].position = vec.vector(554.3956, 5.147204, -213.1728, 1)
routes["Heat from above streetrace"].checkpoints[3].heading = 1.159918
routes["Heat from above streetrace"].checkpoints[3].roadName = "dt_10l_east_01 AI Road 7"
routes["Heat from above streetrace"].checkpoints[4] = {}
routes["Heat from above streetrace"].checkpoints[4].position = vec.vector(881.8072, 5.993133, 27.88613, 1)
routes["Heat from above streetrace"].checkpoints[4].heading = 0.806626
routes["Heat from above streetrace"].checkpoints[4].roadName = "dt_10l_east_01 AI Road 8"
routes["Heat from above streetrace"].arrows = {}
routes["Heat from above streetrace"].roads = {}
routes["Heat from above streetrace"].roads[1] = {}
routes["Heat from above streetrace"].roads[1].road = "lombard_street AI Road 0"
routes["Heat from above streetrace"].roads[1].direction = "with"
routes["Heat from above streetrace"].roads[2] = {}
routes["Heat from above streetrace"].roads[2].road = "dt_8l_centre_01aa AI Road 0"
routes["Heat from above streetrace"].roads[2].direction = "against"
routes["Heat from above streetrace"].roads[3] = {}
routes["Heat from above streetrace"].roads[3].road = "dt_10l_east_01 AI Road 7"
routes["Heat from above streetrace"].roads[3].direction = "with"
routes["Heat from above streetrace"].roads[4] = {}
routes["Heat from above streetrace"].roads[4].road = "dt_10l_east_01 AI Road 8"
routes["Heat from above streetrace"].roads[4].direction = "with"
routes["Heat From Above Truck Route"] = {}
routes["Heat From Above Truck Route"].checkpoints = {}
routes["Heat From Above Truck Route"].checkpoints[1] = {}
routes["Heat From Above Truck Route"].checkpoints[1].position = vec.vector(-3917.921, 48.01374, 2874.571, 1)
routes["Heat From Above Truck Route"].checkpoints[1].heading = -1.882695
routes["Heat From Above Truck Route"].checkpoints[1].roadName = "sutro_4l_west_02 AI Road 1"
routes["Heat From Above Truck Route"].checkpoints[2] = {}
routes["Heat From Above Truck Route"].checkpoints[2].position = vec.vector(-4159.723, 21.25, 2600.125, 1)
routes["Heat From Above Truck Route"].checkpoints[2].heading = 2.881453
routes["Heat From Above Truck Route"].checkpoints[2].roadName = "sutro_6l_west_02 AI Road 2"
routes["Heat From Above Truck Route"].checkpoints[3] = {}
routes["Heat From Above Truck Route"].checkpoints[3].position = vec.vector(-3464.911, 43.60422, 2149.507, 1)
routes["Heat From Above Truck Route"].checkpoints[3].heading = 1.690876
routes["Heat From Above Truck Route"].checkpoints[3].roadName = "ggp_10l_south_05 AI Road 9"
routes["Heat From Above Truck Route"].checkpoints[4] = {}
routes["Heat From Above Truck Route"].checkpoints[4].position = vec.vector(-3314.781, 46.09932, 1497.133, 1)
routes["Heat From Above Truck Route"].checkpoints[4].heading = 1.826136
routes["Heat From Above Truck Route"].checkpoints[4].roadName = "ggp_8l_centre_02 AI Road 1"
routes["Heat From Above Truck Route"].checkpoints[5] = {}
routes["Heat From Above Truck Route"].checkpoints[5].position = vec.vector(-3061.296, 66.25, 952.3926, 1)
routes["Heat From Above Truck Route"].checkpoints[5].heading = -1.695977
routes["Heat From Above Truck Route"].checkpoints[5].roadName = "ggp_shortcut_07 AI Road 1"
routes["Heat From Above Truck Route"].arrows = {}
routes["Heat From Above Truck Route"].roads = {}
routes["Heat From Above Truck Route"].roads[1] = {}
routes["Heat From Above Truck Route"].roads[1].road = "sutro_4l_west_02 AI Road 0"
routes["Heat From Above Truck Route"].roads[1].direction = "with"
routes["Heat From Above Truck Route"].roads[2] = {}
routes["Heat From Above Truck Route"].roads[2].road = "sutro_4l_west_02 AI Road 1"
routes["Heat From Above Truck Route"].roads[2].direction = "with"
routes["Heat From Above Truck Route"].roads[3] = {}
routes["Heat From Above Truck Route"].roads[3].road = "sutro_8l_north_01 AI Road 2"
routes["Heat From Above Truck Route"].roads[3].direction = "with"
routes["Heat From Above Truck Route"].roads[4] = {}
routes["Heat From Above Truck Route"].roads[4].road = "sutro_shortcut_01 AI Road 1"
routes["Heat From Above Truck Route"].roads[4].direction = "against"
routes["Heat From Above Truck Route"].roads[5] = {}
routes["Heat From Above Truck Route"].roads[5].road = "sutro_shortcut_01 AI Road 0"
routes["Heat From Above Truck Route"].roads[5].direction = "against"
routes["Heat From Above Truck Route"].roads[6] = {}
routes["Heat From Above Truck Route"].roads[6].road = "sutro_6l_west_02 AI Road 2"
routes["Heat From Above Truck Route"].roads[6].direction = "against"
routes["Heat From Above Truck Route"].roads[7] = {}
routes["Heat From Above Truck Route"].roads[7].road = "sutro_6l_west_02 AI Road 1"
routes["Heat From Above Truck Route"].roads[7].direction = "against"
routes["Heat From Above Truck Route"].roads[8] = {}
routes["Heat From Above Truck Route"].roads[8].road = "sutro_6l_west_02 AI Road 0"
routes["Heat From Above Truck Route"].roads[8].direction = "against"
routes["Heat From Above Truck Route"].roads[9] = {}
routes["Heat From Above Truck Route"].roads[9].road = "ggp_10l_south_05 AI Road 10"
routes["Heat From Above Truck Route"].roads[9].direction = "against"
routes["Heat From Above Truck Route"].roads[10] = {}
routes["Heat From Above Truck Route"].roads[10].road = "ggp_10l_south_05 AI Road 9"
routes["Heat From Above Truck Route"].roads[10].direction = "against"
routes["Heat From Above Truck Route"].roads[11] = {}
routes["Heat From Above Truck Route"].roads[11].road = "ggp_8l_centre_02 AI Road 5"
routes["Heat From Above Truck Route"].roads[11].direction = "against"
routes["Heat From Above Truck Route"].roads[12] = {}
routes["Heat From Above Truck Route"].roads[12].road = "ggp_8l_centre_02 AI Road 4"
routes["Heat From Above Truck Route"].roads[12].direction = "against"
routes["Heat From Above Truck Route"].roads[13] = {}
routes["Heat From Above Truck Route"].roads[13].road = "ggp_8l_centre_02 AI Road 3"
routes["Heat From Above Truck Route"].roads[13].direction = "against"
routes["Heat From Above Truck Route"].roads[14] = {}
routes["Heat From Above Truck Route"].roads[14].road = "ggp_8l_centre_02 AI Road 2"
routes["Heat From Above Truck Route"].roads[14].direction = "against"
routes["Heat From Above Truck Route"].roads[15] = {}
routes["Heat From Above Truck Route"].roads[15].road = "ggp_8l_centre_02 AI Road 1"
routes["Heat From Above Truck Route"].roads[15].direction = "against"
routes["Heat From Above Truck Route"].roads[16] = {}
routes["Heat From Above Truck Route"].roads[16].road = "ggp_8l_centre_02 AI Road 0"
routes["Heat From Above Truck Route"].roads[16].direction = "against"
routes["Heat From Above Truck Route"].roads[17] = {}
routes["Heat From Above Truck Route"].roads[17].road = "ggp_8l_centre_03 AI Road 2"
routes["Heat From Above Truck Route"].roads[17].direction = "against"
routes["Heat From Above Truck Route"].roads[18] = {}
routes["Heat From Above Truck Route"].roads[18].road = "ggp_shortcut_07 AI Road 2"
routes["Heat From Above Truck Route"].roads[18].direction = "against"
routes["Heat From Above Truck Route"].roads[19] = {}
routes["Heat From Above Truck Route"].roads[19].road = "ggp_shortcut_07 AI Road 1"
routes["Heat From Above Truck Route"].roads[19].direction = "against"
