routes = routes or {}
routes["Streetrace takedown"] = {}
routes["Streetrace takedown"].checkpoints = {}
routes["Streetrace takedown"].checkpoints[1] = {}
routes["Streetrace takedown"].checkpoints[1].position = vec.vector(-4445, 14.75, 2055.967, 1)
routes["Streetrace takedown"].checkpoints[1].heading = 3.141593
routes["Streetrace takedown"].checkpoints[1].roadName = "ggp_10l_west_01 AI Road 4"
routes["Streetrace takedown"].checkpoints[2] = {}
routes["Streetrace takedown"].checkpoints[2].position = vec.vector(-4445, 14.75, 1781.239, 1)
routes["Streetrace takedown"].checkpoints[2].heading = 3.141564
routes["Streetrace takedown"].checkpoints[2].roadName = "ggp_10l_west_01 AI Road 5"
routes["Streetrace takedown"].checkpoints[3] = {}
routes["Streetrace takedown"].checkpoints[3].position = vec.vector(-4453.56, 21.6554, 1527.523, 1)
routes["Streetrace takedown"].checkpoints[3].heading = -2.702015
routes["Streetrace takedown"].checkpoints[3].roadName = "ggp_10l_west_01 AI Road 6"
routes["Streetrace takedown"].checkpoints[4] = {}
routes["Streetrace takedown"].checkpoints[4].position = vec.vector(-4602.66, 27.74999, 1302.187, 1)
routes["Streetrace takedown"].checkpoints[4].heading = -3.049136
routes["Streetrace takedown"].checkpoints[4].roadName = "ggp_10l_west_01 AI Road 7"
routes["Streetrace takedown"].checkpoints[5] = {}
routes["Streetrace takedown"].checkpoints[5].position = vec.vector(-4365.92, 27.75007, 996.7167, 1)
routes["Streetrace takedown"].checkpoints[5].heading = 2.478986
routes["Streetrace takedown"].checkpoints[5].roadName = "ggp_8l_west_01 AI Road 0"
routes["Streetrace takedown"].checkpoints[6] = {}
routes["Streetrace takedown"].checkpoints[6].position = vec.vector(-4069.192, 26.89688, 799.3868, 1)
routes["Streetrace takedown"].checkpoints[6].heading = 1.903482
routes["Streetrace takedown"].checkpoints[6].roadName = "ggp_8l_west_01 AI Road 1"
routes["Streetrace takedown"].checkpoints[7] = {}
routes["Streetrace takedown"].checkpoints[7].position = vec.vector(-3735.318, 21.06663, 636.9819, 1)
routes["Streetrace takedown"].checkpoints[7].heading = 2.331934
routes["Streetrace takedown"].checkpoints[7].roadName = "ggp_8l_west_01 AI Road 3"
routes["Streetrace takedown"].checkpoints[8] = {}
routes["Streetrace takedown"].checkpoints[8].position = vec.vector(-3576.387, 15.97289, 342.1776, 1)
routes["Streetrace takedown"].checkpoints[8].heading = 2.664322
routes["Streetrace takedown"].checkpoints[8].roadName = "ggp_8l_west_01 AI Road 4"
routes["Streetrace takedown"].checkpoints[9] = {}
routes["Streetrace takedown"].checkpoints[9].position = vec.vector(-3365.672, 8.815489, -83.13847, 1)
routes["Streetrace takedown"].checkpoints[9].heading = 2.824772
routes["Streetrace takedown"].checkpoints[9].roadName = "ggp_8l_west_01 AI Road 6"
routes["Streetrace takedown"].checkpoints[10] = {}
routes["Streetrace takedown"].checkpoints[10].position = vec.vector(-2993.494, 2.075, -294.5266, 1)
routes["Streetrace takedown"].checkpoints[10].heading = 1.345974
routes["Streetrace takedown"].checkpoints[10].roadName = "ggp_8l_west_01 AI Road 8"
routes["Streetrace takedown"].checkpoints[11] = {}
routes["Streetrace takedown"].checkpoints[11].position = vec.vector(-2698.785, 2.075, -285.8979, 1)
routes["Streetrace takedown"].checkpoints[11].heading = 1.570763
routes["Streetrace takedown"].checkpoints[11].roadName = "ggp_8l_west_01 AI Road 9"
routes["Streetrace takedown"].checkpoints[12] = {}
routes["Streetrace takedown"].checkpoints[12].position = vec.vector(-2290.971, 2.442076, -284.5303, 1)
routes["Streetrace takedown"].checkpoints[12].heading = 1.472909
routes["Streetrace takedown"].checkpoints[12].roadName = "ggp_8l_north_03 AI Road 0"
routes["Streetrace takedown"].checkpoints[13] = {}
routes["Streetrace takedown"].checkpoints[13].position = vec.vector(-1832.016, 4.999999, -209.8334, 1)
routes["Streetrace takedown"].checkpoints[13].heading = 1.426615
routes["Streetrace takedown"].checkpoints[13].roadName = "ggp_8l_north_03 AI Road 1"
routes["Streetrace takedown"].checkpoints[14] = {}
routes["Streetrace takedown"].checkpoints[14].position = vec.vector(-1487.564, 4.999999, -162.5694, 1)
routes["Streetrace takedown"].checkpoints[14].heading = 1.507599
routes["Streetrace takedown"].checkpoints[14].roadName = "dt_8l_north_04 AI Road 1"
routes["Streetrace takedown"].checkpoints[15] = {}
routes["Streetrace takedown"].checkpoints[15].position = vec.vector(-1250.953, 4.999999, -111, 1)
routes["Streetrace takedown"].checkpoints[15].heading = 1.570796
routes["Streetrace takedown"].checkpoints[15].roadName = "dt_10l_east_01 AI Road 0"
routes["Streetrace takedown"].checkpoints[16] = {}
routes["Streetrace takedown"].checkpoints[16].position = vec.vector(-765.0049, 4.999999, -158.3636, 1)
routes["Streetrace takedown"].checkpoints[16].heading = 1.740329
routes["Streetrace takedown"].checkpoints[16].roadName = "dt_10l_east_01 AI Road 2"
routes["Streetrace takedown"].checkpoints[17] = {}
routes["Streetrace takedown"].checkpoints[17].position = vec.vector(6.570417, 4.445157, -286.8495, 1)
routes["Streetrace takedown"].checkpoints[17].heading = 1.685239
routes["Streetrace takedown"].checkpoints[17].roadName = "dt_10l_east_01 AI Road 5"
routes["Streetrace takedown"].checkpoints[18] = {}
routes["Streetrace takedown"].checkpoints[18].position = vec.vector(424.4107, 4.783431, -265.6565, 1)
routes["Streetrace takedown"].checkpoints[18].heading = 1.244036
routes["Streetrace takedown"].checkpoints[18].roadName = "dt_10l_east_01 AI Road 7"
routes["Streetrace takedown"].checkpoints[19] = {}
routes["Streetrace takedown"].checkpoints[19].position = vec.vector(795.9921, 6.590937, -56.28732, 1)
routes["Streetrace takedown"].checkpoints[19].heading = 0.8419597
routes["Streetrace takedown"].checkpoints[19].roadName = "dt_10l_east_01 AI Road 8"
routes["Streetrace takedown"].checkpoints[20] = {}
routes["Streetrace takedown"].checkpoints[20].position = vec.vector(1003.965, 5.974999, 243.932, 1)
routes["Streetrace takedown"].checkpoints[20].heading = 0.4011032
routes["Streetrace takedown"].checkpoints[20].roadName = "dt_10l_east_01 AI Road 9"
routes["Streetrace takedown"].checkpoints[21] = {}
routes["Streetrace takedown"].checkpoints[21].position = vec.vector(1187.93, 5.974995, 696.0797, 1)
routes["Streetrace takedown"].checkpoints[21].heading = 0.3941578
routes["Streetrace takedown"].checkpoints[21].roadName = "dt_mt_join_01 AI Road 0"
routes["Streetrace takedown"].checkpoints[22] = {}
routes["Streetrace takedown"].checkpoints[22].position = vec.vector(1317.707, 5.974996, 990.6639, 1)
routes["Streetrace takedown"].checkpoints[22].heading = 0.4320022
routes["Streetrace takedown"].checkpoints[22].roadName = "mt_10l_south_01 AI Road 7"
routes["Streetrace takedown"].checkpoints[23] = {}
routes["Streetrace takedown"].checkpoints[23].position = vec.vector(1447.774, 5.974996, 1290.384, 1)
routes["Streetrace takedown"].checkpoints[23].heading = 0.2305056
routes["Streetrace takedown"].checkpoints[23].roadName = "mt_10l_south_01 AI Road 5"
routes["Streetrace takedown"].checkpoints[24] = {}
routes["Streetrace takedown"].checkpoints[24].position = vec.vector(1467.797, 5.974996, 1610.108, 1)
routes["Streetrace takedown"].checkpoints[24].heading = 0.02016536
routes["Streetrace takedown"].checkpoints[24].roadName = "mt_10l_south_01 AI Road 3"
routes["Streetrace takedown"].arrows = {}
routes["Streetrace takedown"].roads = {}
routes["Streetrace takedown"].roads[1] = {}
routes["Streetrace takedown"].roads[1].road = "ggp_10l_west_01 AI Road 4"
routes["Streetrace takedown"].roads[1].direction = "with"
routes["Streetrace takedown"].roads[2] = {}
routes["Streetrace takedown"].roads[2].road = "ggp_10l_west_01 AI Road 5"
routes["Streetrace takedown"].roads[2].direction = "with"
routes["Streetrace takedown"].roads[3] = {}
routes["Streetrace takedown"].roads[3].road = "ggp_10l_west_01 AI Road 6"
routes["Streetrace takedown"].roads[3].direction = "with"
routes["Streetrace takedown"].roads[4] = {}
routes["Streetrace takedown"].roads[4].road = "ggp_10l_west_01 AI Road 7"
routes["Streetrace takedown"].roads[4].direction = "with"
routes["Streetrace takedown"].roads[5] = {}
routes["Streetrace takedown"].roads[5].road = "ggp_8l_west_01 AI Road 0"
routes["Streetrace takedown"].roads[5].direction = "with"
routes["Streetrace takedown"].roads[6] = {}
routes["Streetrace takedown"].roads[6].road = "ggp_8l_west_01 AI Road 1"
routes["Streetrace takedown"].roads[6].direction = "with"
routes["Streetrace takedown"].roads[7] = {}
routes["Streetrace takedown"].roads[7].road = "ggp_8l_west_01 AI Road 2"
routes["Streetrace takedown"].roads[7].direction = "with"
routes["Streetrace takedown"].roads[8] = {}
routes["Streetrace takedown"].roads[8].road = "ggp_8l_west_01 AI Road 3"
routes["Streetrace takedown"].roads[8].direction = "with"
routes["Streetrace takedown"].roads[9] = {}
routes["Streetrace takedown"].roads[9].road = "ggp_8l_west_01 AI Road 4"
routes["Streetrace takedown"].roads[9].direction = "with"
routes["Streetrace takedown"].roads[10] = {}
routes["Streetrace takedown"].roads[10].road = "ggp_8l_west_01 AI Road 5"
routes["Streetrace takedown"].roads[10].direction = "with"
routes["Streetrace takedown"].roads[11] = {}
routes["Streetrace takedown"].roads[11].road = "ggp_8l_west_01 AI Road 6"
routes["Streetrace takedown"].roads[11].direction = "with"
routes["Streetrace takedown"].roads[12] = {}
routes["Streetrace takedown"].roads[12].road = "ggp_8l_west_01 AI Road 7"
routes["Streetrace takedown"].roads[12].direction = "with"
routes["Streetrace takedown"].roads[13] = {}
routes["Streetrace takedown"].roads[13].road = "ggp_8l_west_01 AI Road 8"
routes["Streetrace takedown"].roads[13].direction = "with"
routes["Streetrace takedown"].roads[14] = {}
routes["Streetrace takedown"].roads[14].road = "ggp_8l_west_01 AI Road 9"
routes["Streetrace takedown"].roads[14].direction = "with"
routes["Streetrace takedown"].roads[15] = {}
routes["Streetrace takedown"].roads[15].road = "ggp_8l_west_01 AI Road 10"
routes["Streetrace takedown"].roads[15].direction = "with"
routes["Streetrace takedown"].roads[16] = {}
routes["Streetrace takedown"].roads[16].road = "ggp_8l_north_03 AI Road 0"
routes["Streetrace takedown"].roads[16].direction = "with"
routes["Streetrace takedown"].roads[17] = {}
routes["Streetrace takedown"].roads[17].road = "ggp_8l_north_03 AI Road 1"
routes["Streetrace takedown"].roads[17].direction = "with"
routes["Streetrace takedown"].roads[18] = {}
routes["Streetrace takedown"].roads[18].road = "dt_8l_north_04 AI Road 1"
routes["Streetrace takedown"].roads[18].direction = "with"
routes["Streetrace takedown"].roads[19] = {}
routes["Streetrace takedown"].roads[19].road = "dt_8l_north_04 AI Road 2"
routes["Streetrace takedown"].roads[19].direction = "with"
routes["Streetrace takedown"].roads[20] = {}
routes["Streetrace takedown"].roads[20].road = "dt_10l_east_01 AI Road 0"
routes["Streetrace takedown"].roads[20].direction = "with"
routes["Streetrace takedown"].roads[21] = {}
routes["Streetrace takedown"].roads[21].road = "dt_10l_east_01 AI Road 1"
routes["Streetrace takedown"].roads[21].direction = "with"
routes["Streetrace takedown"].roads[22] = {}
routes["Streetrace takedown"].roads[22].road = "dt_10l_east_01 AI Road 2"
routes["Streetrace takedown"].roads[22].direction = "with"
routes["Streetrace takedown"].roads[23] = {}
routes["Streetrace takedown"].roads[23].road = "dt_10l_east_01 AI Road 3"
routes["Streetrace takedown"].roads[23].direction = "with"
routes["Streetrace takedown"].roads[24] = {}
routes["Streetrace takedown"].roads[24].road = "dt_10l_east_01 AI Road 4"
routes["Streetrace takedown"].roads[24].direction = "with"
routes["Streetrace takedown"].roads[25] = {}
routes["Streetrace takedown"].roads[25].road = "dt_10l_east_01 AI Road 5"
routes["Streetrace takedown"].roads[25].direction = "with"
routes["Streetrace takedown"].roads[26] = {}
routes["Streetrace takedown"].roads[26].road = "dt_10l_east_01 AI Road 6"
routes["Streetrace takedown"].roads[26].direction = "with"
routes["Streetrace takedown"].roads[27] = {}
routes["Streetrace takedown"].roads[27].road = "dt_10l_east_01 AI Road 7"
routes["Streetrace takedown"].roads[27].direction = "with"
routes["Streetrace takedown"].roads[28] = {}
routes["Streetrace takedown"].roads[28].road = "dt_10l_east_01 AI Road 8"
routes["Streetrace takedown"].roads[28].direction = "with"
routes["Streetrace takedown"].roads[29] = {}
routes["Streetrace takedown"].roads[29].road = "dt_10l_east_01 AI Road 9"
routes["Streetrace takedown"].roads[29].direction = "with"
routes["Streetrace takedown"].roads[30] = {}
routes["Streetrace takedown"].roads[30].road = "dt_10l_east_01 AI Road 10"
routes["Streetrace takedown"].roads[30].direction = "with"
routes["Streetrace takedown"].roads[31] = {}
routes["Streetrace takedown"].roads[31].road = "dt_mt_join_01 AI Road 0"
routes["Streetrace takedown"].roads[31].direction = "with"
routes["Streetrace takedown"].roads[32] = {}
routes["Streetrace takedown"].roads[32].road = "dt_mt_join_01 AI Road 1"
routes["Streetrace takedown"].roads[32].direction = "with"
routes["Streetrace takedown"].roads[33] = {}
routes["Streetrace takedown"].roads[33].road = "mt_10l_south_01 AI Road 8"
routes["Streetrace takedown"].roads[33].direction = "against"
routes["Streetrace takedown"].roads[34] = {}
routes["Streetrace takedown"].roads[34].road = "mt_10l_south_01 AI Road 7"
routes["Streetrace takedown"].roads[34].direction = "against"
routes["Streetrace takedown"].roads[35] = {}
routes["Streetrace takedown"].roads[35].road = "mt_10l_south_01 AI Road 6"
routes["Streetrace takedown"].roads[35].direction = "against"
routes["Streetrace takedown"].roads[36] = {}
routes["Streetrace takedown"].roads[36].road = "mt_10l_south_01 AI Road 5"
routes["Streetrace takedown"].roads[36].direction = "against"
routes["Streetrace takedown"].roads[37] = {}
routes["Streetrace takedown"].roads[37].road = "mt_10l_south_01 AI Road 4"
routes["Streetrace takedown"].roads[37].direction = "against"
routes["Streetrace takedown"].roads[38] = {}
routes["Streetrace takedown"].roads[38].road = "mt_10l_south_01 AI Road 3"
routes["Streetrace takedown"].roads[38].direction = "against"
