routes = routes or {}
routes["Streetrace takedown warmup"] = {}
routes["Streetrace takedown warmup"].checkpoints = {}
routes["Streetrace takedown warmup"].checkpoints[1] = {}
routes["Streetrace takedown warmup"].checkpoints[1].position = vec.vector(-4445, 14.75, 2036.13, 1)
routes["Streetrace takedown warmup"].checkpoints[1].heading = 3.141593
routes["Streetrace takedown warmup"].checkpoints[1].roadName = "ggp_10l_west_01 AI Road 4"
routes["Streetrace takedown warmup"].checkpoints[2] = {}
routes["Streetrace takedown warmup"].checkpoints[2].position = vec.vector(-4217.884, 18.94197, 1842.346, 1)
routes["Streetrace takedown warmup"].checkpoints[2].heading = 1.930274
routes["Streetrace takedown warmup"].checkpoints[2].roadName = "ggp_4l_sw_01 AI Road 1"
routes["Streetrace takedown warmup"].checkpoints[3] = {}
routes["Streetrace takedown warmup"].checkpoints[3].position = vec.vector(-3942.326, 27.74308, 1902.56, 1)
routes["Streetrace takedown warmup"].checkpoints[3].heading = 1.137435
routes["Streetrace takedown warmup"].checkpoints[3].roadName = "ggp_4l_sw_02 AI Road 0"
routes["Streetrace takedown warmup"].checkpoints[4] = {}
routes["Streetrace takedown warmup"].checkpoints[4].position = vec.vector(-3755.64, 37.49999, 2058.866, 1)
routes["Streetrace takedown warmup"].checkpoints[4].heading = 0.02842465
routes["Streetrace takedown warmup"].checkpoints[4].roadName = "ggp_6l_west_01 AI Road 2"
routes["Streetrace takedown warmup"].checkpoints[5] = {}
routes["Streetrace takedown warmup"].checkpoints[5].position = vec.vector(-4018.005, 29.32887, 2150, 1)
routes["Streetrace takedown warmup"].checkpoints[5].heading = -1.57079
routes["Streetrace takedown warmup"].checkpoints[5].roadName = "ggp_10l_south_05 AI Road 11"
routes["Streetrace takedown warmup"].checkpoints[6] = {}
routes["Streetrace takedown warmup"].checkpoints[6].position = vec.vector(-4387.958, 14.75, 2150, 1)
routes["Streetrace takedown warmup"].checkpoints[6].heading = -1.570775
routes["Streetrace takedown warmup"].checkpoints[6].roadName = "ggp_10l_south_05 AI Road 13"
routes["Streetrace takedown warmup"].arrows = {}
routes["Streetrace takedown warmup"].roads = {}
routes["Streetrace takedown warmup"].roads[1] = {}
routes["Streetrace takedown warmup"].roads[1].road = "ggp_10l_west_01 AI Road 4"
routes["Streetrace takedown warmup"].roads[1].direction = "with"
routes["Streetrace takedown warmup"].roads[2] = {}
routes["Streetrace takedown warmup"].roads[2].road = "ggp_4l_sw_01 AI Road 0"
routes["Streetrace takedown warmup"].roads[2].direction = "with"
routes["Streetrace takedown warmup"].roads[3] = {}
routes["Streetrace takedown warmup"].roads[3].road = "ggp_4l_sw_01 AI Road 1"
routes["Streetrace takedown warmup"].roads[3].direction = "with"
routes["Streetrace takedown warmup"].roads[4] = {}
routes["Streetrace takedown warmup"].roads[4].road = "ggp_4l_sw_02 AI Road 0"
routes["Streetrace takedown warmup"].roads[4].direction = "with"
routes["Streetrace takedown warmup"].roads[5] = {}
routes["Streetrace takedown warmup"].roads[5].road = "ggp_6l_west_01 AI Road 2"
routes["Streetrace takedown warmup"].roads[5].direction = "with"
routes["Streetrace takedown warmup"].roads[6] = {}
routes["Streetrace takedown warmup"].roads[6].road = "ggp_10l_south_05 AI Road 11"
routes["Streetrace takedown warmup"].roads[6].direction = "with"
routes["Streetrace takedown warmup"].roads[7] = {}
routes["Streetrace takedown warmup"].roads[7].road = "ggp_10l_south_05 AI Road 12"
routes["Streetrace takedown warmup"].roads[7].direction = "with"
routes["Streetrace takedown warmup"].roads[8] = {}
routes["Streetrace takedown warmup"].roads[8].road = "ggp_10l_south_05 AI Road 13"
routes["Streetrace takedown warmup"].roads[8].direction = "with"
