routes = routes or {}
routes["Takedown the getaway evader route"] = {}
routes["Takedown the getaway evader route"].checkpoints = {}
routes["Takedown the getaway evader route"].checkpoints[1] = {}
routes["Takedown the getaway evader route"].checkpoints[1].position = vec.vector(-524.1681, 21.24999, 684.1072, 1)
routes["Takedown the getaway evader route"].checkpoints[1].heading = 0.7877848
routes["Takedown the getaway evader route"].checkpoints[1].roadName = "dt_10l_centre_01 AI Road 4"
routes["Takedown the getaway evader route"].checkpoints[2] = {}
routes["Takedown the getaway evader route"].checkpoints[2].position = vec.vector(-237.065, 18, 968.4789, 1)
routes["Takedown the getaway evader route"].checkpoints[2].heading = 0.7900223
routes["Takedown the getaway evader route"].checkpoints[2].roadName = "dt_10l_centre_01 AI Road 7"
routes["Takedown the getaway evader route"].checkpoints[3] = {}
routes["Takedown the getaway evader route"].checkpoints[3].position = vec.vector(-63.6188, 39.75473, 1525.468, 1)
routes["Takedown the getaway evader route"].checkpoints[3].heading = 0.2237162
routes["Takedown the getaway evader route"].checkpoints[3].roadName = "dt_10l_centre_02 AI Road 2"
routes["Takedown the getaway evader route"].checkpoints[4] = {}
routes["Takedown the getaway evader route"].checkpoints[4].position = vec.vector(-523.312, 56.39008, 1747.847, 1)
routes["Takedown the getaway evader route"].checkpoints[4].heading = -1.291674
routes["Takedown the getaway evader route"].checkpoints[4].roadName = "dt_10l_south_02b AI Road 8"
routes["Takedown the getaway evader route"].checkpoints[5] = {}
routes["Takedown the getaway evader route"].checkpoints[5].position = vec.vector(-1222.326, 66.75, 1886.835, 1)
routes["Takedown the getaway evader route"].checkpoints[5].heading = -1.436274
routes["Takedown the getaway evader route"].checkpoints[5].roadName = "dt_10l_south_02b AI Road 3"
routes["Takedown the getaway evader route"].checkpoints[6] = {}
routes["Takedown the getaway evader route"].checkpoints[6].position = vec.vector(-1564.818, 63.49998, 1674.347, 1)
routes["Takedown the getaway evader route"].checkpoints[6].heading = -2.935254
routes["Takedown the getaway evader route"].checkpoints[6].roadName = "dt__8l_west_01 AI Road 12"
routes["Takedown the getaway evader route"].checkpoints[7] = {}
routes["Takedown the getaway evader route"].checkpoints[7].position = vec.vector(-1652.648, 40.1929, 1164.561, 1)
routes["Takedown the getaway evader route"].checkpoints[7].heading = -2.979261
routes["Takedown the getaway evader route"].checkpoints[7].roadName = "dt__8l_west_01 AI Road 10"
routes["Takedown the getaway evader route"].checkpoints[8] = {}
routes["Takedown the getaway evader route"].checkpoints[8].position = vec.vector(-1691.134, 41.8488, 532.6135, 1)
routes["Takedown the getaway evader route"].checkpoints[8].heading = -3.131258
routes["Takedown the getaway evader route"].checkpoints[8].roadName = "dt__8l_west_01 AI Road 4"
routes["Takedown the getaway evader route"].checkpoints[9] = {}
routes["Takedown the getaway evader route"].checkpoints[9].position = vec.vector(-1682.783, 9.282166, -76.44586, 1)
routes["Takedown the getaway evader route"].checkpoints[9].heading = 2.931675
routes["Takedown the getaway evader route"].checkpoints[9].roadName = "dt_8l_north_04 AI Road 0"
routes["Takedown the getaway evader route"].checkpoints[10] = {}
routes["Takedown the getaway evader route"].checkpoints[10].position = vec.vector(-1154.474, 14.05753, 59.60286, 1)
routes["Takedown the getaway evader route"].checkpoints[10].heading = 0.7900764
routes["Takedown the getaway evader route"].checkpoints[10].roadName = "dt_10l_centre_01 AI Road 0"
routes["Takedown the getaway evader route"].checkpoints[11] = {}
routes["Takedown the getaway evader route"].checkpoints[11].position = vec.vector(-731.1206, 27.31978, 478.9763, 1)
routes["Takedown the getaway evader route"].checkpoints[11].heading = 0.7904801
routes["Takedown the getaway evader route"].checkpoints[11].roadName = "dt_10l_centre_01 AI Road 3"
routes["Takedown the getaway evader route"].arrows = {}
routes["Takedown the getaway evader route"].roads = {}
routes["Takedown the getaway evader route"].roads[1] = {}
routes["Takedown the getaway evader route"].roads[1].road = "dt_10l_centre_01 AI Road 4"
routes["Takedown the getaway evader route"].roads[1].direction = "with"
routes["Takedown the getaway evader route"].roads[2] = {}
routes["Takedown the getaway evader route"].roads[2].road = "dt_10l_centre_01 AI Road 5"
routes["Takedown the getaway evader route"].roads[2].direction = "with"
routes["Takedown the getaway evader route"].roads[3] = {}
routes["Takedown the getaway evader route"].roads[3].road = "dt_10l_centre_01 AI Road 6"
routes["Takedown the getaway evader route"].roads[3].direction = "with"
routes["Takedown the getaway evader route"].roads[4] = {}
routes["Takedown the getaway evader route"].roads[4].road = "dt_10l_centre_01 AI Road 7"
routes["Takedown the getaway evader route"].roads[4].direction = "with"
routes["Takedown the getaway evader route"].roads[5] = {}
routes["Takedown the getaway evader route"].roads[5].road = "dt_10l_centre_02 AI Road 0"
routes["Takedown the getaway evader route"].roads[5].direction = "with"
routes["Takedown the getaway evader route"].roads[6] = {}
routes["Takedown the getaway evader route"].roads[6].road = "dt_10l_centre_02 AI Road 1"
routes["Takedown the getaway evader route"].roads[6].direction = "with"
routes["Takedown the getaway evader route"].roads[7] = {}
routes["Takedown the getaway evader route"].roads[7].road = "dt_10l_centre_02 AI Road 2"
routes["Takedown the getaway evader route"].roads[7].direction = "with"
routes["Takedown the getaway evader route"].roads[8] = {}
routes["Takedown the getaway evader route"].roads[8].road = "dt_10l_south_03 AI Road 6"
routes["Takedown the getaway evader route"].roads[8].direction = "with"
routes["Takedown the getaway evader route"].roads[9] = {}
routes["Takedown the getaway evader route"].roads[9].road = "dt_10l_south_03 AI Road 7"
routes["Takedown the getaway evader route"].roads[9].direction = "with"
routes["Takedown the getaway evader route"].roads[10] = {}
routes["Takedown the getaway evader route"].roads[10].road = "dt_10l_south_02b AI Road 9"
routes["Takedown the getaway evader route"].roads[10].direction = "against"
routes["Takedown the getaway evader route"].roads[11] = {}
routes["Takedown the getaway evader route"].roads[11].road = "dt_10l_south_02b AI Road 8"
routes["Takedown the getaway evader route"].roads[11].direction = "against"
routes["Takedown the getaway evader route"].roads[12] = {}
routes["Takedown the getaway evader route"].roads[12].road = "dt_10l_south_02b AI Road 7"
routes["Takedown the getaway evader route"].roads[12].direction = "against"
routes["Takedown the getaway evader route"].roads[13] = {}
routes["Takedown the getaway evader route"].roads[13].road = "dt_10l_south_02b AI Road 6"
routes["Takedown the getaway evader route"].roads[13].direction = "against"
routes["Takedown the getaway evader route"].roads[14] = {}
routes["Takedown the getaway evader route"].roads[14].road = "dt_10l_south_02b AI Road 5"
routes["Takedown the getaway evader route"].roads[14].direction = "against"
routes["Takedown the getaway evader route"].roads[15] = {}
routes["Takedown the getaway evader route"].roads[15].road = "dt_10l_south_02b AI Road 4"
routes["Takedown the getaway evader route"].roads[15].direction = "against"
routes["Takedown the getaway evader route"].roads[16] = {}
routes["Takedown the getaway evader route"].roads[16].road = "dt_10l_south_02b AI Road 3"
routes["Takedown the getaway evader route"].roads[16].direction = "against"
routes["Takedown the getaway evader route"].roads[17] = {}
routes["Takedown the getaway evader route"].roads[17].road = "dt_10l_south_02b AI Road 2"
routes["Takedown the getaway evader route"].roads[17].direction = "against"
routes["Takedown the getaway evader route"].roads[18] = {}
routes["Takedown the getaway evader route"].roads[18].road = "dt__8l_west_01 AI Road 14"
routes["Takedown the getaway evader route"].roads[18].direction = "against"
routes["Takedown the getaway evader route"].roads[19] = {}
routes["Takedown the getaway evader route"].roads[19].road = "dt__8l_west_01 AI Road 13"
routes["Takedown the getaway evader route"].roads[19].direction = "against"
routes["Takedown the getaway evader route"].roads[20] = {}
routes["Takedown the getaway evader route"].roads[20].road = "dt__8l_west_01 AI Road 12"
routes["Takedown the getaway evader route"].roads[20].direction = "against"
routes["Takedown the getaway evader route"].roads[21] = {}
routes["Takedown the getaway evader route"].roads[21].road = "dt__8l_west_01 AI Road 11"
routes["Takedown the getaway evader route"].roads[21].direction = "against"
routes["Takedown the getaway evader route"].roads[22] = {}
routes["Takedown the getaway evader route"].roads[22].road = "dt__8l_west_01 AI Road 10"
routes["Takedown the getaway evader route"].roads[22].direction = "against"
routes["Takedown the getaway evader route"].roads[23] = {}
routes["Takedown the getaway evader route"].roads[23].road = "dt__8l_west_01 AI Road 9"
routes["Takedown the getaway evader route"].roads[23].direction = "against"
routes["Takedown the getaway evader route"].roads[24] = {}
routes["Takedown the getaway evader route"].roads[24].road = "dt__8l_west_01 AI Road 8"
routes["Takedown the getaway evader route"].roads[24].direction = "against"
routes["Takedown the getaway evader route"].roads[25] = {}
routes["Takedown the getaway evader route"].roads[25].road = "dt__8l_west_01 AI Road 7"
routes["Takedown the getaway evader route"].roads[25].direction = "against"
routes["Takedown the getaway evader route"].roads[26] = {}
routes["Takedown the getaway evader route"].roads[26].road = "dt__8l_west_01 AI Road 6"
routes["Takedown the getaway evader route"].roads[26].direction = "against"
routes["Takedown the getaway evader route"].roads[27] = {}
routes["Takedown the getaway evader route"].roads[27].road = "dt__8l_west_01 AI Road 5"
routes["Takedown the getaway evader route"].roads[27].direction = "against"
routes["Takedown the getaway evader route"].roads[28] = {}
routes["Takedown the getaway evader route"].roads[28].road = "dt__8l_west_01 AI Road 4"
routes["Takedown the getaway evader route"].roads[28].direction = "against"
routes["Takedown the getaway evader route"].roads[29] = {}
routes["Takedown the getaway evader route"].roads[29].road = "dt__8l_west_01 AI Road 3"
routes["Takedown the getaway evader route"].roads[29].direction = "against"
routes["Takedown the getaway evader route"].roads[30] = {}
routes["Takedown the getaway evader route"].roads[30].road = "dt__8l_west_01 AI Road 2"
routes["Takedown the getaway evader route"].roads[30].direction = "against"
routes["Takedown the getaway evader route"].roads[31] = {}
routes["Takedown the getaway evader route"].roads[31].road = "dt__8l_west_01 AI Road 1"
routes["Takedown the getaway evader route"].roads[31].direction = "against"
routes["Takedown the getaway evader route"].roads[32] = {}
routes["Takedown the getaway evader route"].roads[32].road = "dt__8l_west_01 AI Road 0"
routes["Takedown the getaway evader route"].roads[32].direction = "against"
routes["Takedown the getaway evader route"].roads[33] = {}
routes["Takedown the getaway evader route"].roads[33].road = "dt_8l_north_04 AI Road 0"
routes["Takedown the getaway evader route"].roads[33].direction = "with"
routes["Takedown the getaway evader route"].roads[34] = {}
routes["Takedown the getaway evader route"].roads[34].road = "dt_8l_north_04 AI Road 1"
routes["Takedown the getaway evader route"].roads[34].direction = "with"
routes["Takedown the getaway evader route"].roads[35] = {}
routes["Takedown the getaway evader route"].roads[35].road = "dt_8l_north_04 AI Road 2"
routes["Takedown the getaway evader route"].roads[35].direction = "with"
routes["Takedown the getaway evader route"].roads[36] = {}
routes["Takedown the getaway evader route"].roads[36].road = "dt_10l_centre_01 AI Road 0"
routes["Takedown the getaway evader route"].roads[36].direction = "with"
routes["Takedown the getaway evader route"].roads[37] = {}
routes["Takedown the getaway evader route"].roads[37].road = "dt_10l_centre_01 AI Road 1"
routes["Takedown the getaway evader route"].roads[37].direction = "with"
routes["Takedown the getaway evader route"].roads[38] = {}
routes["Takedown the getaway evader route"].roads[38].road = "dt_10l_centre_01 AI Road 2"
routes["Takedown the getaway evader route"].roads[38].direction = "with"
routes["Takedown the getaway evader route"].roads[39] = {}
routes["Takedown the getaway evader route"].roads[39].road = "dt_10l_centre_01 AI Road 3"
routes["Takedown the getaway evader route"].roads[39].direction = "with"
routes["Takedown the getaway warmup route"] = {}
routes["Takedown the getaway warmup route"].checkpoints = {}
routes["Takedown the getaway warmup route"].checkpoints[1] = {}
routes["Takedown the getaway warmup route"].checkpoints[1].position = vec.vector(-488.3831, 21.73211, 1075.971, 1)
routes["Takedown the getaway warmup route"].checkpoints[1].heading = -1.459184
routes["Takedown the getaway warmup route"].checkpoints[1].roadName = "dt_10l_south_01 AI Road 7"
routes["Takedown the getaway warmup route"].checkpoints[2] = {}
routes["Takedown the getaway warmup route"].checkpoints[2].position = vec.vector(-912.9568, 39.3106, 1043.525, 1)
routes["Takedown the getaway warmup route"].checkpoints[2].heading = -2.831915
routes["Takedown the getaway warmup route"].checkpoints[2].roadName = "dt_shortcut_12a AI Road 0"
routes["Takedown the getaway warmup route"].checkpoints[3] = {}
routes["Takedown the getaway warmup route"].checkpoints[3].position = vec.vector(-899.8317, 36.98987, 928.6095, 1)
routes["Takedown the getaway warmup route"].checkpoints[3].heading = 1.786493
routes["Takedown the getaway warmup route"].checkpoints[3].roadName = "dt_6l_centre_02 AI Road 0"
routes["Takedown the getaway warmup route"].checkpoints[4] = {}
routes["Takedown the getaway warmup route"].checkpoints[4].position = vec.vector(-271.5461, 18, 934.3187, 1)
routes["Takedown the getaway warmup route"].checkpoints[4].heading = 0.790095
routes["Takedown the getaway warmup route"].checkpoints[4].roadName = "dt_10l_centre_01 AI Road 6"
routes["Takedown the getaway warmup route"].checkpoints[5] = {}
routes["Takedown the getaway warmup route"].checkpoints[5].position = vec.vector(-238.8801, 18.11256, 1045.593, 1)
routes["Takedown the getaway warmup route"].checkpoints[5].heading = -1.45243
routes["Takedown the getaway warmup route"].checkpoints[5].roadName = "dt_10l_south_01 AI Road 5"
routes["Takedown the getaway warmup route"].checkpoints[6] = {}
routes["Takedown the getaway warmup route"].checkpoints[6].position = vec.vector(-349.5666, 19.93667, 1059.218, 1)
routes["Takedown the getaway warmup route"].checkpoints[6].heading = -1.446322
routes["Takedown the getaway warmup route"].checkpoints[6].roadName = "dt_10l_south_01 AI Road 6"
routes["Takedown the getaway warmup route"].arrows = {}
routes["Takedown the getaway warmup route"].roads = {}
routes["Takedown the getaway warmup route"].roads[1] = {}
routes["Takedown the getaway warmup route"].roads[1].road = "dt_10l_south_01 AI Road 7"
routes["Takedown the getaway warmup route"].roads[1].direction = "with"
routes["Takedown the getaway warmup route"].roads[2] = {}
routes["Takedown the getaway warmup route"].roads[2].road = "dt_10l_south_01 AI Road 8"
routes["Takedown the getaway warmup route"].roads[2].direction = "with"
routes["Takedown the getaway warmup route"].roads[3] = {}
routes["Takedown the getaway warmup route"].roads[3].road = "dt_10l_south_01 AI Road 9"
routes["Takedown the getaway warmup route"].roads[3].direction = "with"
routes["Takedown the getaway warmup route"].roads[4] = {}
routes["Takedown the getaway warmup route"].roads[4].road = "dt_10l_south_01 AI Road 10"
routes["Takedown the getaway warmup route"].roads[4].direction = "with"
routes["Takedown the getaway warmup route"].roads[5] = {}
routes["Takedown the getaway warmup route"].roads[5].road = "dt_shortcut_12a AI Road 0"
routes["Takedown the getaway warmup route"].roads[5].direction = "against"
routes["Takedown the getaway warmup route"].roads[6] = {}
routes["Takedown the getaway warmup route"].roads[6].road = "dt_6l_centre_02 AI Road 0"
routes["Takedown the getaway warmup route"].roads[6].direction = "with"
routes["Takedown the getaway warmup route"].roads[7] = {}
routes["Takedown the getaway warmup route"].roads[7].road = "dt_6l_centre_02 AI Road 1"
routes["Takedown the getaway warmup route"].roads[7].direction = "with"
routes["Takedown the getaway warmup route"].roads[8] = {}
routes["Takedown the getaway warmup route"].roads[8].road = "dt_6l_centre_02 AI Road 2"
routes["Takedown the getaway warmup route"].roads[8].direction = "with"
routes["Takedown the getaway warmup route"].roads[9] = {}
routes["Takedown the getaway warmup route"].roads[9].road = "dt_6l_centre_02 AI Road 3"
routes["Takedown the getaway warmup route"].roads[9].direction = "with"
routes["Takedown the getaway warmup route"].roads[10] = {}
routes["Takedown the getaway warmup route"].roads[10].road = "dt_10l_centre_01 AI Road 6"
routes["Takedown the getaway warmup route"].roads[10].direction = "with"
routes["Takedown the getaway warmup route"].roads[11] = {}
routes["Takedown the getaway warmup route"].roads[11].road = "dt_10l_centre_01 AI Road 7"
routes["Takedown the getaway warmup route"].roads[11].direction = "with"
routes["Takedown the getaway warmup route"].roads[12] = {}
routes["Takedown the getaway warmup route"].roads[12].road = "dt_10l_south_01 AI Road 5"
routes["Takedown the getaway warmup route"].roads[12].direction = "with"
routes["Takedown the getaway warmup route"].roads[13] = {}
routes["Takedown the getaway warmup route"].roads[13].road = "dt_10l_south_01 AI Road 6"
routes["Takedown the getaway warmup route"].roads[13].direction = "with"
