routes = routes or {}
routes["Checkpoint activity 2 route"] = {}
routes["Checkpoint activity 2 route"].checkpoints = {}
routes["Checkpoint activity 2 route"].checkpoints[1] = {}
routes["Checkpoint activity 2 route"].checkpoints[1].position = vec.vector(1092.26, 5.974996, 686.8823, 1)
routes["Checkpoint activity 2 route"].checkpoints[1].heading = 2.245519
routes["Checkpoint activity 2 route"].checkpoints[1].roadName = "dt_10l_east_01 AI Road 11"
routes["Checkpoint activity 2 route"].checkpoints[2] = {}
routes["Checkpoint activity 2 route"].checkpoints[2].position = vec.vector(1223.818, 5.974996, 782.0232, 1)
routes["Checkpoint activity 2 route"].checkpoints[2].heading = 0.3962373
routes["Checkpoint activity 2 route"].checkpoints[2].roadName = "dt_mt_join_01 AI Road 0"
routes["Checkpoint activity 2 route"].checkpoints[2].roadWidth = 50
routes["Checkpoint activity 2 route"].checkpoints[2].displayWidth = 50
routes["Checkpoint activity 2 route"].checkpoints[3] = {}
routes["Checkpoint activity 2 route"].checkpoints[3].position = vec.vector(1122.671, 5.974995, 1027.794, 1)
routes["Checkpoint activity 2 route"].checkpoints[3].heading = -0.8530585
routes["Checkpoint activity 2 route"].checkpoints[3].roadName = "mt_10l_south_02 AI Road 3"
routes["Checkpoint activity 2 route"].checkpoints[4] = {}
routes["Checkpoint activity 2 route"].checkpoints[4].position = vec.vector(1079.651, 5.974996, 1198.647, 1)
routes["Checkpoint activity 2 route"].checkpoints[4].heading = 0.8257887
routes["Checkpoint activity 2 route"].checkpoints[4].roadName = "mt_6l_e_01 AI Road 0"
routes["Checkpoint activity 2 route"].checkpoints[5] = {}
routes["Checkpoint activity 2 route"].checkpoints[5].position = vec.vector(1297.513, 5.974996, 1167.168, 1)
routes["Checkpoint activity 2 route"].checkpoints[5].heading = 2.292323
routes["Checkpoint activity 2 route"].checkpoints[5].roadName = "dt_4l_east_06 AI Road 1"
routes["Checkpoint activity 2 route"].checkpoints[5].roadWidth = 29
routes["Checkpoint activity 2 route"].checkpoints[5].displayWidth = 27
routes["Checkpoint activity 2 route"].checkpoints[6] = {}
routes["Checkpoint activity 2 route"].checkpoints[6].position = vec.vector(1406.461, 5.974996, 1175.414, 1)
routes["Checkpoint activity 2 route"].checkpoints[6].heading = 0.4115683
routes["Checkpoint activity 2 route"].checkpoints[6].roadName = "mt_10l_south_01 AI Road 6"
routes["Checkpoint activity 2 route"].checkpoints[6].roadWidth = 60
routes["Checkpoint activity 2 route"].checkpoints[6].displayWidth = 60
routes["Checkpoint activity 2 route"].checkpoints[7] = {}
routes["Checkpoint activity 2 route"].checkpoints[7].position = vec.vector(1358.999, 5.974995, 1456.468, 1)
routes["Checkpoint activity 2 route"].checkpoints[7].heading = -2.311936
routes["Checkpoint activity 2 route"].checkpoints[7].roadName = "mt_6l_e_01 AI Road 2"
routes["Checkpoint activity 2 route"].checkpoints[8] = {}
routes["Checkpoint activity 2 route"].checkpoints[8].position = vec.vector(1190.797, 5.974995, 1513.647, 1)
routes["Checkpoint activity 2 route"].checkpoints[8].heading = -0.8505442
routes["Checkpoint activity 2 route"].checkpoints[8].roadName = "dt_4l_east_05 AI Road 0"
routes["Checkpoint activity 2 route"].checkpoints[9] = {}
routes["Checkpoint activity 2 route"].checkpoints[9].position = vec.vector(1027.597, 5.974995, 1537.168, 1)
routes["Checkpoint activity 2 route"].checkpoints[9].heading = -2.333077
routes["Checkpoint activity 2 route"].checkpoints[9].roadName = "mt_6l_e_02 AI Road 2"
routes["Checkpoint activity 2 route"].checkpoints[10] = {}
routes["Checkpoint activity 2 route"].checkpoints[10].position = vec.vector(768.103, 5.975001, 1630.795, 1)
routes["Checkpoint activity 2 route"].checkpoints[10].heading = -0.8545823
routes["Checkpoint activity 2 route"].checkpoints[10].roadName = "mt_6l_centre_01 AI Road 8"
routes["Checkpoint activity 2 route"].checkpoints[11] = {}
routes["Checkpoint activity 2 route"].checkpoints[11].position = vec.vector(477.8387, 18.00904, 1774.077, 1)
routes["Checkpoint activity 2 route"].checkpoints[11].heading = -2.387719
routes["Checkpoint activity 2 route"].checkpoints[11].roadName = "mt_6l_centre_04 AI Road 5"
routes["Checkpoint activity 2 route"].checkpoints[12] = {}
routes["Checkpoint activity 2 route"].checkpoints[12].position = vec.vector(474.1834, 11.9358, 1578.56, 1)
routes["Checkpoint activity 2 route"].checkpoints[12].heading = 2.295975
routes["Checkpoint activity 2 route"].checkpoints[12].roadName = "mt_shortcuts_01ab AI Road 0"
routes["Checkpoint activity 2 route"].checkpoints[13] = {}
routes["Checkpoint activity 2 route"].checkpoints[13].position = vec.vector(626.1141, 6.198164, 1307.561, 1)
routes["Checkpoint activity 2 route"].checkpoints[13].heading = 2.290076
routes["Checkpoint activity 2 route"].checkpoints[13].roadName = "embargedero_shortcut_02 AI Road 0"
routes["Checkpoint activity 2 route"].checkpoints[14] = {}
routes["Checkpoint activity 2 route"].checkpoints[14].position = vec.vector(864.9498, 5.975001, 1099.946, 1)
routes["Checkpoint activity 2 route"].checkpoints[14].heading = 2.276676
routes["Checkpoint activity 2 route"].checkpoints[14].roadName = "embargedero_shortcut_02 AI Road 2"
routes["Checkpoint activity 2 route"].checkpoints[14].roadWidth = 30
routes["Checkpoint activity 2 route"].checkpoints[14].displayWidth = 30
routes["Checkpoint activity 2 route"].arrows = {}
routes["Checkpoint activity 2 route"].arrows[1] = {}
routes["Checkpoint activity 2 route"].arrows[1].position = vec.vector(1274.296, 3, 918.7369, 1)
routes["Checkpoint activity 2 route"].arrows[1].heading = -0.7610274
routes["Checkpoint activity 2 route"].arrows[1].modelId = 78
routes["Checkpoint activity 2 route"].arrows[2] = {}
routes["Checkpoint activity 2 route"].arrows[2].position = vec.vector(995.695, 3, 1143.249, 1)
routes["Checkpoint activity 2 route"].arrows[2].heading = 0.8233396
routes["Checkpoint activity 2 route"].arrows[2].modelId = 219
routes["Checkpoint activity 2 route"].arrows[3] = {}
routes["Checkpoint activity 2 route"].arrows[3].position = vec.vector(1181.229, 3, 1291.067, 1)
routes["Checkpoint activity 2 route"].arrows[3].heading = 2.330559
routes["Checkpoint activity 2 route"].arrows[3].modelId = 219
routes["Checkpoint activity 2 route"].arrows[4] = {}
routes["Checkpoint activity 2 route"].arrows[4].position = vec.vector(1390.456, 3, 1091.088, 1)
routes["Checkpoint activity 2 route"].arrows[4].heading = 0.4236685
routes["Checkpoint activity 2 route"].arrows[4].modelId = 219
routes["Checkpoint activity 2 route"].arrows[5] = {}
routes["Checkpoint activity 2 route"].arrows[5].position = vec.vector(1451.704, 3, 1544.739, 1)
routes["Checkpoint activity 2 route"].arrows[5].heading = -1.943195
routes["Checkpoint activity 2 route"].arrows[5].modelId = 219
routes["Checkpoint activity 2 route"].arrows[6] = {}
routes["Checkpoint activity 2 route"].arrows[6].position = vec.vector(1298.342, 3, 1400.909, 1)
routes["Checkpoint activity 2 route"].arrows[6].heading = -0.8458653
routes["Checkpoint activity 2 route"].arrows[6].modelId = 78
routes["Checkpoint activity 2 route"].arrows[7] = {}
routes["Checkpoint activity 2 route"].arrows[7].position = vec.vector(1084.954, 3, 1611.644, 1)
routes["Checkpoint activity 2 route"].arrows[7].heading = -2.261348
routes["Checkpoint activity 2 route"].arrows[7].modelId = 78
routes["Checkpoint activity 2 route"].arrows[8] = {}
routes["Checkpoint activity 2 route"].arrows[8].position = vec.vector(944.1788, 3, 1454.51, 1)
routes["Checkpoint activity 2 route"].arrows[8].heading = -0.8833182
routes["Checkpoint activity 2 route"].arrows[8].modelId = 219
routes["Checkpoint activity 2 route"].arrows[9] = {}
routes["Checkpoint activity 2 route"].arrows[9].position = vec.vector(520.2878, 15, 1843.007, 1)
routes["Checkpoint activity 2 route"].arrows[9].heading = -2.42132
routes["Checkpoint activity 2 route"].arrows[9].modelId = 219
routes["Checkpoint activity 2 route"].arrows[10] = {}
routes["Checkpoint activity 2 route"].arrows[10].position = vec.vector(366.2408, 15, 1649.196, 1)
routes["Checkpoint activity 2 route"].arrows[10].heading = 2.334673
routes["Checkpoint activity 2 route"].arrows[10].modelId = 78
routes["Checkpoint activity 2 route"].arrows[11] = {}
routes["Checkpoint activity 2 route"].arrows[11].position = vec.vector(602.163, 3, 1475.533, 1)
routes["Checkpoint activity 2 route"].arrows[11].heading = -2.447357
routes["Checkpoint activity 2 route"].arrows[11].modelId = 219
routes["Checkpoint activity 2 route"].arrows[12] = {}
routes["Checkpoint activity 2 route"].arrows[12].position = vec.vector(509.8267, 3, 1385.645, 1)
routes["Checkpoint activity 2 route"].arrows[12].heading = 2.239839
routes["Checkpoint activity 2 route"].arrows[12].modelId = 78
routes["Checkpoint activity 2 route"].arrows[13] = {}
routes["Checkpoint activity 2 route"].arrows[13].position = vec.vector(697.6865, 2.5, 1217.591, 1)
routes["Checkpoint activity 2 route"].arrows[13].heading = 2.312744
routes["Checkpoint activity 2 route"].arrows[13].modelId = 78
routes["Checkpoint activity 2 route"].arrows[14] = {}
routes["Checkpoint activity 2 route"].arrows[14].position = vec.vector(1192.103, 3, 643.3764, 1)
routes["Checkpoint activity 2 route"].arrows[14].heading = 0.3775307
routes["Checkpoint activity 2 route"].arrows[14].modelId = 219
routes["Checkpoint activity 2 route"].arrows[15] = {}
routes["Checkpoint activity 2 route"].arrows[15].position = vec.vector(727.4168, 2.5, 1244.959, 1)
routes["Checkpoint activity 2 route"].arrows[15].heading = 2.334921
routes["Checkpoint activity 2 route"].arrows[15].modelId = 78
routes["Checkpoint activity 2 route"].roads = {}
routes["Checkpoint activity 2 route"].roads[1] = {}
routes["Checkpoint activity 2 route"].roads[1].road = "dt_shortcut_11 AI Road 0"
routes["Checkpoint activity 2 route"].roads[1].direction = "with"
routes["Checkpoint activity 2 route"].roads[2] = {}
routes["Checkpoint activity 2 route"].roads[2].road = "dt_10l_east_01 AI Road 11"
routes["Checkpoint activity 2 route"].roads[2].direction = "against"
routes["Checkpoint activity 2 route"].roads[3] = {}
routes["Checkpoint activity 2 route"].roads[3].road = "dt_mt_join_01 AI Road 0"
routes["Checkpoint activity 2 route"].roads[3].direction = "with"
routes["Checkpoint activity 2 route"].roads[4] = {}
routes["Checkpoint activity 2 route"].roads[4].road = "dt_mt_join_01 AI Road 1"
routes["Checkpoint activity 2 route"].roads[4].direction = "with"
routes["Checkpoint activity 2 route"].roads[5] = {}
routes["Checkpoint activity 2 route"].roads[5].road = "mt_10l_south_02 AI Road 3"
routes["Checkpoint activity 2 route"].roads[5].direction = "against"
routes["Checkpoint activity 2 route"].roads[6] = {}
routes["Checkpoint activity 2 route"].roads[6].road = "mt_10l_south_02 AI Road 2"
routes["Checkpoint activity 2 route"].roads[6].direction = "against"
routes["Checkpoint activity 2 route"].roads[7] = {}
routes["Checkpoint activity 2 route"].roads[7].road = "mt_6l_e_01 AI Road 0"
routes["Checkpoint activity 2 route"].roads[7].direction = "with"
routes["Checkpoint activity 2 route"].roads[8] = {}
routes["Checkpoint activity 2 route"].roads[8].road = "dt_4l_east_06 AI Road 0"
routes["Checkpoint activity 2 route"].roads[8].direction = "with"
routes["Checkpoint activity 2 route"].roads[9] = {}
routes["Checkpoint activity 2 route"].roads[9].road = "dt_4l_east_06 AI Road 1"
routes["Checkpoint activity 2 route"].roads[9].direction = "with"
routes["Checkpoint activity 2 route"].roads[10] = {}
routes["Checkpoint activity 2 route"].roads[10].road = "mt_10l_south_01 AI Road 6"
routes["Checkpoint activity 2 route"].roads[10].direction = "against"
routes["Checkpoint activity 2 route"].roads[11] = {}
routes["Checkpoint activity 2 route"].roads[11].road = "mt_10l_south_01 AI Road 5"
routes["Checkpoint activity 2 route"].roads[11].direction = "against"
routes["Checkpoint activity 2 route"].roads[12] = {}
routes["Checkpoint activity 2 route"].roads[12].road = "r336_aihelper_02 AI Road 0"
routes["Checkpoint activity 2 route"].roads[12].direction = "against"
routes["Checkpoint activity 2 route"].roads[13] = {}
routes["Checkpoint activity 2 route"].roads[13].road = "mt_6l_e_01 AI Road 2"
routes["Checkpoint activity 2 route"].roads[13].direction = "against"
routes["Checkpoint activity 2 route"].roads[14] = {}
routes["Checkpoint activity 2 route"].roads[14].road = "dt_4l_east_05 AI Road 0"
routes["Checkpoint activity 2 route"].roads[14].direction = "against"
routes["Checkpoint activity 2 route"].roads[15] = {}
routes["Checkpoint activity 2 route"].roads[15].road = "mt_6l_e_02 AI Road 2"
routes["Checkpoint activity 2 route"].roads[15].direction = "against"
routes["Checkpoint activity 2 route"].roads[16] = {}
routes["Checkpoint activity 2 route"].roads[16].road = "mt_6l_e_02 AI Road 1"
routes["Checkpoint activity 2 route"].roads[16].direction = "against"
routes["Checkpoint activity 2 route"].roads[17] = {}
routes["Checkpoint activity 2 route"].roads[17].road = "mt_6l_centre_01 AI Road 9"
routes["Checkpoint activity 2 route"].roads[17].direction = "against"
routes["Checkpoint activity 2 route"].roads[18] = {}
routes["Checkpoint activity 2 route"].roads[18].road = "mt_6l_centre_01 AI Road 8"
routes["Checkpoint activity 2 route"].roads[18].direction = "against"
routes["Checkpoint activity 2 route"].roads[19] = {}
routes["Checkpoint activity 2 route"].roads[19].road = "mt_6l_centre_01 AI Road 7"
routes["Checkpoint activity 2 route"].roads[19].direction = "against"
routes["Checkpoint activity 2 route"].roads[20] = {}
routes["Checkpoint activity 2 route"].roads[20].road = "mt_6l_centre_04 AI Road 5"
routes["Checkpoint activity 2 route"].roads[20].direction = "against"
routes["Checkpoint activity 2 route"].roads[21] = {}
routes["Checkpoint activity 2 route"].roads[21].road = "mt_6l_centre_04 AI Road 4"
routes["Checkpoint activity 2 route"].roads[21].direction = "against"
routes["Checkpoint activity 2 route"].roads[22] = {}
routes["Checkpoint activity 2 route"].roads[22].road = "mt_shortcuts_01ab AI Road 0"
routes["Checkpoint activity 2 route"].roads[22].direction = "with"
routes["Checkpoint activity 2 route"].roads[23] = {}
routes["Checkpoint activity 2 route"].roads[23].road = "barcelero_alleyway_01 AI Road 1"
routes["Checkpoint activity 2 route"].roads[23].direction = "against"
routes["Checkpoint activity 2 route"].roads[24] = {}
routes["Checkpoint activity 2 route"].roads[24].road = "embargedero_shortcut_02 AI Road 0"
routes["Checkpoint activity 2 route"].roads[24].direction = "with"
routes["Checkpoint activity 2 route"].roads[25] = {}
routes["Checkpoint activity 2 route"].roads[25].road = "embargedero_shortcut_02 AI Road 1"
routes["Checkpoint activity 2 route"].roads[25].direction = "with"
routes["Checkpoint activity 2 route"].roads[26] = {}
routes["Checkpoint activity 2 route"].roads[26].road = "embargedero_shortcut_02 AI Road 2"
routes["Checkpoint activity 2 route"].roads[26].direction = "with"
