routes = routes or {}
routes.HeartometerActivity3 = {}
routes.HeartometerActivity3.checkpoints = {}
routes.HeartometerActivity3.checkpoints[1] = {}
routes.HeartometerActivity3.checkpoints[1].position = vec.vector(-3069.402, 66.25255, 951.3442, 1)
routes.HeartometerActivity3.checkpoints[1].heading = -1.711074
routes.HeartometerActivity3.checkpoints[1].roadName = "ggp_shortcut_07 AI Road 1"
routes.HeartometerActivity3.arrows = {}
routes.HeartometerActivity3.roads = {}
routes.HeartometerActivity3.roads[1] = {}
routes.HeartometerActivity3.roads[1].road = "mountain_10l_w_01b AI Road 35"
routes.HeartometerActivity3.roads[1].direction = "with"
routes.HeartometerActivity3.roads[2] = {}
routes.HeartometerActivity3.roads[2].road = "mountain_10l_w_01b AI Road 36"
routes.HeartometerActivity3.roads[2].direction = "with"
routes.HeartometerActivity3.roads[3] = {}
routes.HeartometerActivity3.roads[3].road = "mountain_10l_w_01b AI Road 37"
routes.HeartometerActivity3.roads[3].direction = "with"
routes.HeartometerActivity3.roads[4] = {}
routes.HeartometerActivity3.roads[4].road = "mountain_10l_w_06 AI Road 15"
routes.HeartometerActivity3.roads[4].direction = "against"
routes.HeartometerActivity3.roads[5] = {}
routes.HeartometerActivity3.roads[5].road = "mountain_10l_w_06 AI Road 14"
routes.HeartometerActivity3.roads[5].direction = "against"
routes.HeartometerActivity3.roads[6] = {}
routes.HeartometerActivity3.roads[6].road = "mountain_6l_west_02 AI Road 0"
routes.HeartometerActivity3.roads[6].direction = "with"
routes.HeartometerActivity3.roads[7] = {}
routes.HeartometerActivity3.roads[7].road = "ggb_marin_sliproad_02 AI Road 0"
routes.HeartometerActivity3.roads[7].direction = "against"
routes.HeartometerActivity3.roads[8] = {}
routes.HeartometerActivity3.roads[8].road = "highway01_15 AI Road 12"
routes.HeartometerActivity3.roads[8].direction = "against"
routes.HeartometerActivity3.roads[9] = {}
routes.HeartometerActivity3.roads[9].road = "highway01_15 AI Road 11"
routes.HeartometerActivity3.roads[9].direction = "against"
routes.HeartometerActivity3.roads[10] = {}
routes.HeartometerActivity3.roads[10].road = "highway01_15 AI Road 10"
routes.HeartometerActivity3.roads[10].direction = "against"
routes.HeartometerActivity3.roads[11] = {}
routes.HeartometerActivity3.roads[11].road = "highway01_15 AI Road 9"
routes.HeartometerActivity3.roads[11].direction = "against"
routes.HeartometerActivity3.roads[12] = {}
routes.HeartometerActivity3.roads[12].road = "highway01_15 AI Road 8"
routes.HeartometerActivity3.roads[12].direction = "against"
routes.HeartometerActivity3.roads[13] = {}
routes.HeartometerActivity3.roads[13].road = "highway01_15 AI Road 7"
routes.HeartometerActivity3.roads[13].direction = "against"
routes.HeartometerActivity3.roads[14] = {}
routes.HeartometerActivity3.roads[14].road = "highway01_15 AI Road 6"
routes.HeartometerActivity3.roads[14].direction = "against"
routes.HeartometerActivity3.roads[15] = {}
routes.HeartometerActivity3.roads[15].road = "highway01_15 AI Road 5"
routes.HeartometerActivity3.roads[15].direction = "against"
routes.HeartometerActivity3.roads[16] = {}
routes.HeartometerActivity3.roads[16].road = "ggp_sliproad_04 AI Road 0"
routes.HeartometerActivity3.roads[16].direction = "with"
routes.HeartometerActivity3.roads[17] = {}
routes.HeartometerActivity3.roads[17].road = "ggp_4l_nw_17 AI Road 2"
routes.HeartometerActivity3.roads[17].direction = "against"
routes.HeartometerActivity3.roads[18] = {}
routes.HeartometerActivity3.roads[18].road = "ggp_4l_nw_17 AI Road 1"
routes.HeartometerActivity3.roads[18].direction = "against"
routes.HeartometerActivity3.roads[19] = {}
routes.HeartometerActivity3.roads[19].road = "ggp_4l_nw_17 AI Road 0"
routes.HeartometerActivity3.roads[19].direction = "against"
routes.HeartometerActivity3.roads[20] = {}
routes.HeartometerActivity3.roads[20].road = "ggp_8l_centre_03 AI Road 0"
routes.HeartometerActivity3.roads[20].direction = "with"
routes.HeartometerActivity3.roads[21] = {}
routes.HeartometerActivity3.roads[21].road = "ggp_8l_centre_03 AI Road 1"
routes.HeartometerActivity3.roads[21].direction = "with"
routes.HeartometerActivity3.roads[22] = {}
routes.HeartometerActivity3.roads[22].road = "ggp_shortcut_07 AI Road 2"
routes.HeartometerActivity3.roads[22].direction = "against"
routes.HeartometerActivity3.roads[23] = {}
routes.HeartometerActivity3.roads[23].road = "ggp_shortcut_07 AI Road 1"
routes.HeartometerActivity3.roads[23].direction = "against"
