routes = routes or {}
routes.HeartometerActivity4 = {}
routes.HeartometerActivity4.checkpoints = {}
routes.HeartometerActivity4.checkpoints[1] = {}
routes.HeartometerActivity4.checkpoints[1].position = vec.vector(1211.726, 5.974995, 1242.639, 1)
routes.HeartometerActivity4.checkpoints[1].heading = 2.292285
routes.HeartometerActivity4.checkpoints[1].roadName = "dt_4l_east_06 AI Road 0"
routes.HeartometerActivity4.arrows = {}
routes.HeartometerActivity4.roads = {}
routes.HeartometerActivity4.roads[1] = {}
routes.HeartometerActivity4.roads[1].road = "sutro_ggp_join_03 AI Road 0"
routes.HeartometerActivity4.roads[1].direction = "with"
routes.HeartometerActivity4.roads[2] = {}
routes.HeartometerActivity4.roads[2].road = "sutro_6l_west_01 AI Road 0"
routes.HeartometerActivity4.roads[2].direction = "against"
routes.HeartometerActivity4.roads[3] = {}
routes.HeartometerActivity4.roads[3].road = "sutro_8l_north_01 AI Road 10"
routes.HeartometerActivity4.roads[3].direction = "with"
routes.HeartometerActivity4.roads[4] = {}
routes.HeartometerActivity4.roads[4].road = "dt_10l_south_02b AI Road 0"
routes.HeartometerActivity4.roads[4].direction = "with"
routes.HeartometerActivity4.roads[5] = {}
routes.HeartometerActivity4.roads[5].road = "dt_10l_south_02b AI Road 1"
routes.HeartometerActivity4.roads[5].direction = "with"
routes.HeartometerActivity4.roads[6] = {}
routes.HeartometerActivity4.roads[6].road = "dt_10l_south_02b AI Road 2"
routes.HeartometerActivity4.roads[6].direction = "with"
routes.HeartometerActivity4.roads[7] = {}
routes.HeartometerActivity4.roads[7].road = "dt_10l_south_02b AI Road 3"
routes.HeartometerActivity4.roads[7].direction = "with"
routes.HeartometerActivity4.roads[8] = {}
routes.HeartometerActivity4.roads[8].road = "dt_10l_south_02b AI Road 4"
routes.HeartometerActivity4.roads[8].direction = "with"
routes.HeartometerActivity4.roads[9] = {}
routes.HeartometerActivity4.roads[9].road = "dt_10l_south_02b AI Road 5"
routes.HeartometerActivity4.roads[9].direction = "with"
routes.HeartometerActivity4.roads[10] = {}
routes.HeartometerActivity4.roads[10].road = "dt_10l_south_02b AI Road 6"
routes.HeartometerActivity4.roads[10].direction = "with"
routes.HeartometerActivity4.roads[11] = {}
routes.HeartometerActivity4.roads[11].road = "dt_10l_south_02b AI Road 7"
routes.HeartometerActivity4.roads[11].direction = "with"
routes.HeartometerActivity4.roads[12] = {}
routes.HeartometerActivity4.roads[12].road = "dt_10l_south_02b AI Road 8"
routes.HeartometerActivity4.roads[12].direction = "with"
routes.HeartometerActivity4.roads[13] = {}
routes.HeartometerActivity4.roads[13].road = "dt_10l_south_02b AI Road 9"
routes.HeartometerActivity4.roads[13].direction = "with"
routes.HeartometerActivity4.roads[14] = {}
routes.HeartometerActivity4.roads[14].road = "dt_10l_south_03 AI Road 7"
routes.HeartometerActivity4.roads[14].direction = "against"
routes.HeartometerActivity4.roads[15] = {}
routes.HeartometerActivity4.roads[15].road = "dt_10l_south_03 AI Road 6"
routes.HeartometerActivity4.roads[15].direction = "against"
routes.HeartometerActivity4.roads[16] = {}
routes.HeartometerActivity4.roads[16].road = "dt_10l_south_03 AI Road 5"
routes.HeartometerActivity4.roads[16].direction = "against"
routes.HeartometerActivity4.roads[17] = {}
routes.HeartometerActivity4.roads[17].road = "dt_10l_south_03 AI Road 4"
routes.HeartometerActivity4.roads[17].direction = "against"
routes.HeartometerActivity4.roads[18] = {}
routes.HeartometerActivity4.roads[18].road = "dt_10l_south_03 AI Road 3"
routes.HeartometerActivity4.roads[18].direction = "against"
routes.HeartometerActivity4.roads[19] = {}
routes.HeartometerActivity4.roads[19].road = "dt_10l_south_03 AI Road 2"
routes.HeartometerActivity4.roads[19].direction = "against"
routes.HeartometerActivity4.roads[20] = {}
routes.HeartometerActivity4.roads[20].road = "sanfran_shortcut_06 AI Road 0"
routes.HeartometerActivity4.roads[20].direction = "with"
routes.HeartometerActivity4.roads[21] = {}
routes.HeartometerActivity4.roads[21].road = "sanfran_shortcut_06 AI Road 1"
routes.HeartometerActivity4.roads[21].direction = "with"
routes.HeartometerActivity4.roads[22] = {}
routes.HeartometerActivity4.roads[22].road = "mt_10l_south_02 AI Road 1"
routes.HeartometerActivity4.roads[22].direction = "with"
routes.HeartometerActivity4.roads[23] = {}
routes.HeartometerActivity4.roads[23].road = "mt_6l_e_01 AI Road 0"
routes.HeartometerActivity4.roads[23].direction = "with"
routes.HeartometerActivity4.roads[24] = {}
routes.HeartometerActivity4.roads[24].road = "dt_4l_east_06 AI Road 0"
routes.HeartometerActivity4.roads[24].direction = "with"
