routes = routes or {}
routes["Smash activity 1 route"] = {}
routes["Smash activity 1 route"].checkpoints = {}
routes["Smash activity 1 route"].checkpoints[1] = {}
routes["Smash activity 1 route"].checkpoints[1].position = vec.vector(-774.5339, 61.52943, 2416.841, 1)
routes["Smash activity 1 route"].checkpoints[1].heading = 2.148486
routes["Smash activity 1 route"].checkpoints[1].roadName = "mt_shortcut_09 AI Road 0"
routes["Smash activity 1 route"].arrows = {}
routes["Smash activity 1 route"].arrows[1] = {}
routes["Smash activity 1 route"].arrows[1].position = vec.vector(152.007, 19.5, 1373.747, 1)
routes["Smash activity 1 route"].arrows[1].heading = -2.829424
routes["Smash activity 1 route"].arrows[1].modelId = 78
routes["Smash activity 1 route"].arrows[2] = {}
routes["Smash activity 1 route"].arrows[2].position = vec.vector(104.102, 27.5, 1212.073, 1)
routes["Smash activity 1 route"].arrows[2].heading = -1.387534
routes["Smash activity 1 route"].arrows[2].modelId = 78
routes["Smash activity 1 route"].arrows[3] = {}
routes["Smash activity 1 route"].arrows[3].position = vec.vector(-425.3523, 44.5, 1475.005, 1)
routes["Smash activity 1 route"].arrows[3].heading = -1.268085
routes["Smash activity 1 route"].arrows[3].modelId = 78
routes["Smash activity 1 route"].arrows[4] = {}
routes["Smash activity 1 route"].arrows[4].position = vec.vector(-1036.235, 66.5, 2213.387, 1)
routes["Smash activity 1 route"].arrows[4].heading = 2.046588
routes["Smash activity 1 route"].arrows[4].modelId = 78
routes["Smash activity 1 route"].arrows[5] = {}
routes["Smash activity 1 route"].arrows[5].position = vec.vector(-867.6661, 63.5, 2119.851, 1)
routes["Smash activity 1 route"].arrows[5].heading = 0.5015947
routes["Smash activity 1 route"].arrows[5].modelId = 78
routes["Smash activity 1 route"].arrows[6] = {}
routes["Smash activity 1 route"].arrows[6].position = vec.vector(-813.8749, 65.5, 2244.187, 1)
routes["Smash activity 1 route"].arrows[6].heading = 2.092771
routes["Smash activity 1 route"].arrows[6].modelId = 78
routes["Smash activity 1 route"].arrows[7] = {}
routes["Smash activity 1 route"].arrows[7].position = vec.vector(-589.9799, 43.5, 2095.335, 1)
routes["Smash activity 1 route"].arrows[7].heading = 0.5895416
routes["Smash activity 1 route"].arrows[7].modelId = 78
routes["Smash activity 1 route"].arrows[8] = {}
routes["Smash activity 1 route"].arrows[8].position = vec.vector(-381.4222, 55.5, 2417.019, 1)
routes["Smash activity 1 route"].arrows[8].heading = -0.9997295
routes["Smash activity 1 route"].arrows[8].modelId = 219
routes["Smash activity 1 route"].arrows[9] = {}
routes["Smash activity 1 route"].arrows[9].position = vec.vector(-850.6773, 76.5, 2677.218, 1)
routes["Smash activity 1 route"].arrows[9].heading = -2.540519
routes["Smash activity 1 route"].arrows[9].modelId = 78
routes["Smash activity 1 route"].arrows[10] = {}
routes["Smash activity 1 route"].arrows[10].position = vec.vector(-973.2488, 76.5, 2536.167, 1)
routes["Smash activity 1 route"].arrows[10].heading = 2.418613
routes["Smash activity 1 route"].arrows[10].modelId = 219
routes["Smash activity 1 route"].arrows[11] = {}
routes["Smash activity 1 route"].arrows[11].position = vec.vector(-605.2237, 46.5, 1851.384, 1)
routes["Smash activity 1 route"].arrows[11].heading = -1.079378
routes["Smash activity 1 route"].arrows[11].modelId = 78
routes["Smash activity 1 route"].arrows[12] = {}
routes["Smash activity 1 route"].arrows[12].position = vec.vector(-1115.923, 63.5, 2094.168, 1)
routes["Smash activity 1 route"].arrows[12].heading = 0.4636478
routes["Smash activity 1 route"].arrows[12].modelId = 78
routes["Smash activity 1 route"].arrows[13] = {}
routes["Smash activity 1 route"].arrows[13].position = vec.vector(-827.4069, 50.5, 1523.096, 1)
routes["Smash activity 1 route"].arrows[13].heading = 0.2449786
routes["Smash activity 1 route"].arrows[13].modelId = 78
routes["Smash activity 1 route"].roads = {}
routes["Smash activity 1 route"].roads[1] = {}
routes["Smash activity 1 route"].roads[1].road = "dt_trans_fakeroad_01 AI Road 0"
routes["Smash activity 1 route"].roads[1].direction = "with"
routes["Smash activity 1 route"].roads[2] = {}
routes["Smash activity 1 route"].roads[2].road = "mt_6l_centre_04 AI Road 0"
routes["Smash activity 1 route"].roads[2].direction = "against"
routes["Smash activity 1 route"].roads[3] = {}
routes["Smash activity 1 route"].roads[3].road = "mt_10l_north_01b AI Road 1"
routes["Smash activity 1 route"].roads[3].direction = "against"
routes["Smash activity 1 route"].roads[4] = {}
routes["Smash activity 1 route"].roads[4].road = "mt_10l_north_01b AI Road 0"
routes["Smash activity 1 route"].roads[4].direction = "against"
routes["Smash activity 1 route"].roads[5] = {}
routes["Smash activity 1 route"].roads[5].road = "mt_10l_north_01a AI Road 5"
routes["Smash activity 1 route"].roads[5].direction = "against"
routes["Smash activity 1 route"].roads[6] = {}
routes["Smash activity 1 route"].roads[6].road = "mt_10l_north_01a AI Road 4"
routes["Smash activity 1 route"].roads[6].direction = "against"
routes["Smash activity 1 route"].roads[7] = {}
routes["Smash activity 1 route"].roads[7].road = "mt_6l_w_04 AI Road 0"
routes["Smash activity 1 route"].roads[7].direction = "with"
routes["Smash activity 1 route"].roads[8] = {}
routes["Smash activity 1 route"].roads[8].road = "mt_6l_w_04 AI Road 1"
routes["Smash activity 1 route"].roads[8].direction = "with"
routes["Smash activity 1 route"].roads[9] = {}
routes["Smash activity 1 route"].roads[9].road = "mt_6l_w_04 AI Road 2"
routes["Smash activity 1 route"].roads[9].direction = "with"
routes["Smash activity 1 route"].roads[10] = {}
routes["Smash activity 1 route"].roads[10].road = "dt_shortcut_25 AI Road 0"
routes["Smash activity 1 route"].roads[10].direction = "against"
routes["Smash activity 1 route"].roads[11] = {}
routes["Smash activity 1 route"].roads[11].road = "dt_4l_south_05ba AI Road 1"
routes["Smash activity 1 route"].roads[11].direction = "against"
routes["Smash activity 1 route"].roads[12] = {}
routes["Smash activity 1 route"].roads[12].road = "dt_4l_west_10 AI Road 0"
routes["Smash activity 1 route"].roads[12].direction = "with"
routes["Smash activity 1 route"].roads[13] = {}
routes["Smash activity 1 route"].roads[13].road = "r302_helper_01 AI Road 0"
routes["Smash activity 1 route"].roads[13].direction = "with"
routes["Smash activity 1 route"].roads[14] = {}
routes["Smash activity 1 route"].roads[14].road = "dt_4l_west_06 AI Road 1"
routes["Smash activity 1 route"].roads[14].direction = "with"
routes["Smash activity 1 route"].roads[15] = {}
routes["Smash activity 1 route"].roads[15].road = "mt_4l_west_01 AI Road 2"
routes["Smash activity 1 route"].roads[15].direction = "against"
routes["Smash activity 1 route"].roads[16] = {}
routes["Smash activity 1 route"].roads[16].road = "exposition_access_road AI Road 0"
routes["Smash activity 1 route"].roads[16].direction = "with"
routes["Smash activity 1 route"].roads[17] = {}
routes["Smash activity 1 route"].roads[17].road = "mt_6l_centre_01 AI Road 2"
routes["Smash activity 1 route"].roads[17].direction = "against"
routes["Smash activity 1 route"].roads[18] = {}
routes["Smash activity 1 route"].roads[18].road = "mt_6l_centre_01 AI Road 1"
routes["Smash activity 1 route"].roads[18].direction = "against"
routes["Smash activity 1 route"].roads[19] = {}
routes["Smash activity 1 route"].roads[19].road = "mt_6l_centre_01 AI Road 0"
routes["Smash activity 1 route"].roads[19].direction = "against"
routes["Smash activity 1 route"].roads[20] = {}
routes["Smash activity 1 route"].roads[20].road = "dt_8l_centre_01b AI Road 3"
routes["Smash activity 1 route"].roads[20].direction = "against"
routes["Smash activity 1 route"].roads[21] = {}
routes["Smash activity 1 route"].roads[21].road = "mt_shortcut_09 AI Road 0"
routes["Smash activity 1 route"].roads[21].direction = "with"
