routes = routes or {}
routes["Smash activity 4 route"] = {}
routes["Smash activity 4 route"].checkpoints = {}
routes["Smash activity 4 route"].checkpoints[1] = {}
routes["Smash activity 4 route"].checkpoints[1].position = vec.vector(1388.092, 29.99999, -4056.271, 1)
routes["Smash activity 4 route"].checkpoints[1].heading = 0.5694496
routes["Smash activity 4 route"].checkpoints[1].roadName = "marin_6l_east_02a AI Road 0"
routes["Smash activity 4 route"].arrows = {}
routes["Smash activity 4 route"].arrows[1] = {}
routes["Smash activity 4 route"].arrows[1].position = vec.vector(2010.092, 25.5, -3762.972, 1)
routes["Smash activity 4 route"].arrows[1].heading = -0.6921383
routes["Smash activity 4 route"].arrows[1].modelId = 78
routes["Smash activity 4 route"].arrows[2] = {}
routes["Smash activity 4 route"].arrows[2].position = vec.vector(1803.956, 24.5, -3685.356, 1)
routes["Smash activity 4 route"].arrows[2].heading = -0.01249942
routes["Smash activity 4 route"].arrows[2].modelId = 78
routes["Smash activity 4 route"].arrows[3] = {}
routes["Smash activity 4 route"].arrows[3].position = vec.vector(1820.829, 24.5, -3551.814, 1)
routes["Smash activity 4 route"].arrows[3].heading = -1.570813
routes["Smash activity 4 route"].arrows[3].modelId = 78
routes["Smash activity 4 route"].arrows[4] = {}
routes["Smash activity 4 route"].arrows[4].position = vec.vector(1217.867, 36.5, -3555.64, 1)
routes["Smash activity 4 route"].arrows[4].heading = -2.17996
routes["Smash activity 4 route"].arrows[4].modelId = 219
routes["Smash activity 4 route"].arrows[5] = {}
routes["Smash activity 4 route"].arrows[5].position = vec.vector(1016.762, 21.5, -3508.536, 1)
routes["Smash activity 4 route"].arrows[5].heading = -2.598403
routes["Smash activity 4 route"].arrows[5].modelId = 78
routes["Smash activity 4 route"].arrows[6] = {}
routes["Smash activity 4 route"].arrows[6].position = vec.vector(966.0469, 31.5, -3618.11, 1)
routes["Smash activity 4 route"].arrows[6].heading = -1.655698
routes["Smash activity 4 route"].arrows[6].modelId = 219
routes["Smash activity 4 route"].arrows[7] = {}
routes["Smash activity 4 route"].arrows[7].position = vec.vector(681.4818, 27, -3569.075, 1)
routes["Smash activity 4 route"].arrows[7].heading = -2.602487
routes["Smash activity 4 route"].arrows[7].modelId = 78
routes["Smash activity 4 route"].arrows[8] = {}
routes["Smash activity 4 route"].arrows[8].position = vec.vector(386.0835, 40, -4097.327, 1)
routes["Smash activity 4 route"].arrows[8].heading = 2.119294
routes["Smash activity 4 route"].arrows[8].modelId = 78
routes["Smash activity 4 route"].arrows[9] = {}
routes["Smash activity 4 route"].arrows[9].position = vec.vector(631.6279, 41.5, -4231.323, 1)
routes["Smash activity 4 route"].arrows[9].heading = -2.600907
routes["Smash activity 4 route"].arrows[9].modelId = 78
routes["Smash activity 4 route"].arrows[10] = {}
routes["Smash activity 4 route"].arrows[10].position = vec.vector(478.5101, 50.5, -4460.958, 1)
routes["Smash activity 4 route"].arrows[10].heading = 2.077949
routes["Smash activity 4 route"].arrows[10].modelId = 219
routes["Smash activity 4 route"].arrows[11] = {}
routes["Smash activity 4 route"].arrows[11].position = vec.vector(795.4349, 50, -4612.579, 1)
routes["Smash activity 4 route"].arrows[11].heading = 0.5277616
routes["Smash activity 4 route"].arrows[11].modelId = 219
routes["Smash activity 4 route"].arrows[12] = {}
routes["Smash activity 4 route"].arrows[12].position = vec.vector(924.5468, 26.5, -4385.009, 1)
routes["Smash activity 4 route"].arrows[12].heading = 2.087106
routes["Smash activity 4 route"].arrows[12].modelId = 78
routes["Smash activity 4 route"].arrows[13] = {}
routes["Smash activity 4 route"].arrows[13].position = vec.vector(1011.647, 26.5, -4446.678, 1)
routes["Smash activity 4 route"].arrows[13].heading = 0.5250677
routes["Smash activity 4 route"].arrows[13].modelId = 78
routes["Smash activity 4 route"].arrows[14] = {}
routes["Smash activity 4 route"].arrows[14].position = vec.vector(1082.3, 26.5, -4321.877, 1)
routes["Smash activity 4 route"].arrows[14].heading = 2.096645
routes["Smash activity 4 route"].arrows[14].modelId = 78
routes["Smash activity 4 route"].arrows[15] = {}
routes["Smash activity 4 route"].arrows[15].position = vec.vector(1179.906, 26.5, -4393.572, 1)
routes["Smash activity 4 route"].arrows[15].heading = 0.5811846
routes["Smash activity 4 route"].arrows[15].modelId = 78
routes["Smash activity 4 route"].roads = {}
routes["Smash activity 4 route"].roads[1] = {}
routes["Smash activity 4 route"].roads[1].road = "marin_4l_east_07 AI Road 0"
routes["Smash activity 4 route"].roads[1].direction = "with"
routes["Smash activity 4 route"].roads[2] = {}
routes["Smash activity 4 route"].roads[2].road = "marin_shortcut_17 AI Road 3"
routes["Smash activity 4 route"].roads[2].direction = "against"
routes["Smash activity 4 route"].roads[3] = {}
routes["Smash activity 4 route"].roads[3].road = "mountain_6l_east_01 AI Road 3"
routes["Smash activity 4 route"].roads[3].direction = "with"
routes["Smash activity 4 route"].roads[4] = {}
routes["Smash activity 4 route"].roads[4].road = "marin_sliproad_18 AI Road 0"
routes["Smash activity 4 route"].roads[4].direction = "against"
routes["Smash activity 4 route"].roads[5] = {}
routes["Smash activity 4 route"].roads[5].road = "mountain_10l_w_01b AI Road 2"
routes["Smash activity 4 route"].roads[5].direction = "against"
routes["Smash activity 4 route"].roads[6] = {}
routes["Smash activity 4 route"].roads[6].road = "marin_sliproad_08 AI Road 0"
routes["Smash activity 4 route"].roads[6].direction = "with"
routes["Smash activity 4 route"].roads[7] = {}
routes["Smash activity 4 route"].roads[7].road = "mountain_10l_w_01a AI Road 7"
routes["Smash activity 4 route"].roads[7].direction = "against"
routes["Smash activity 4 route"].roads[8] = {}
routes["Smash activity 4 route"].roads[8].road = "r625_shortcut_01 AI Road 0"
routes["Smash activity 4 route"].roads[8].direction = "against"
routes["Smash activity 4 route"].roads[9] = {}
routes["Smash activity 4 route"].roads[9].road = "marin_east_10 AI Road 3"
routes["Smash activity 4 route"].roads[9].direction = "against"
routes["Smash activity 4 route"].roads[10] = {}
routes["Smash activity 4 route"].roads[10].road = "marin_shortcut_47 AI Road 1"
routes["Smash activity 4 route"].roads[10].direction = "against"
routes["Smash activity 4 route"].roads[11] = {}
routes["Smash activity 4 route"].roads[11].road = "marin_shortcut_47 AI Road 0"
routes["Smash activity 4 route"].roads[11].direction = "against"
routes["Smash activity 4 route"].roads[12] = {}
routes["Smash activity 4 route"].roads[12].road = "marin_shortcut_12a AI Road 2"
routes["Smash activity 4 route"].roads[12].direction = "against"
routes["Smash activity 4 route"].roads[13] = {}
routes["Smash activity 4 route"].roads[13].road = "marin_4l_east_12 AI Road 0"
routes["Smash activity 4 route"].roads[13].direction = "against"
routes["Smash activity 4 route"].roads[14] = {}
routes["Smash activity 4 route"].roads[14].road = "marin_6l_west_01a AI Road 37"
routes["Smash activity 4 route"].roads[14].direction = "against"
routes["Smash activity 4 route"].roads[15] = {}
routes["Smash activity 4 route"].roads[15].road = "marin_6l_west_01a AI Road 36"
routes["Smash activity 4 route"].roads[15].direction = "against"
routes["Smash activity 4 route"].roads[16] = {}
routes["Smash activity 4 route"].roads[16].road = "mountain_10l_w_01b AI Road 16"
routes["Smash activity 4 route"].roads[16].direction = "against"
routes["Smash activity 4 route"].roads[17] = {}
routes["Smash activity 4 route"].roads[17].road = "marin_shortcut_27 AI Road 0"
routes["Smash activity 4 route"].roads[17].direction = "with"
routes["Smash activity 4 route"].roads[18] = {}
routes["Smash activity 4 route"].roads[18].road = "marin_shortcut_15a AI Road 1"
routes["Smash activity 4 route"].roads[18].direction = "with"
routes["Smash activity 4 route"].roads[19] = {}
routes["Smash activity 4 route"].roads[19].road = "marin_shortcut_29 AI Road 0"
routes["Smash activity 4 route"].roads[19].direction = "with"
routes["Smash activity 4 route"].roads[20] = {}
routes["Smash activity 4 route"].roads[20].road = "marin_6l_east_01 AI Road 5"
routes["Smash activity 4 route"].roads[20].direction = "with"
routes["Smash activity 4 route"].roads[21] = {}
routes["Smash activity 4 route"].roads[21].road = "marin_4l_east_10 AI Road 0"
routes["Smash activity 4 route"].roads[21].direction = "with"
routes["Smash activity 4 route"].roads[22] = {}
routes["Smash activity 4 route"].roads[22].road = "marin_4l_east_10 AI Road 1"
routes["Smash activity 4 route"].roads[22].direction = "with"
routes["Smash activity 4 route"].roads[23] = {}
routes["Smash activity 4 route"].roads[23].road = "marin_4l_east_10 AI Road 2"
routes["Smash activity 4 route"].roads[23].direction = "with"
routes["Smash activity 4 route"].roads[24] = {}
routes["Smash activity 4 route"].roads[24].road = "marin_6l_east_02a AI Road 0"
routes["Smash activity 4 route"].roads[24].direction = "with"
