routes = routes or {}
routes["Smash activity 3 route"] = {}
routes["Smash activity 3 route"].checkpoints = {}
routes["Smash activity 3 route"].checkpoints[1] = {}
routes["Smash activity 3 route"].checkpoints[1].position = vec.vector(-129.0249, 80.14911, 3613.343, 1)
routes["Smash activity 3 route"].checkpoints[1].heading = 1.31846
routes["Smash activity 3 route"].checkpoints[1].roadName = "sutro_shortcut_04 AI Road 0"
routes["Smash activity 3 route"].arrows = {}
routes["Smash activity 3 route"].arrows[1] = {}
routes["Smash activity 3 route"].arrows[1].position = vec.vector(-1742.87, 180.5, 4410.244, 1)
routes["Smash activity 3 route"].arrows[1].heading = 0.8169667
routes["Smash activity 3 route"].arrows[1].modelId = 78
routes["Smash activity 3 route"].arrows[2] = {}
routes["Smash activity 3 route"].arrows[2].position = vec.vector(-1582.569, 183.5, 4317.691, 1)
routes["Smash activity 3 route"].arrows[2].heading = 1.518214
routes["Smash activity 3 route"].arrows[2].modelId = 78
routes["Smash activity 3 route"].arrows[3] = {}
routes["Smash activity 3 route"].arrows[3].position = vec.vector(-1345.305, 176.5, 4280.395, 1)
routes["Smash activity 3 route"].arrows[3].heading = -2.650429
routes["Smash activity 3 route"].arrows[3].modelId = 78
routes["Smash activity 3 route"].arrows[4] = {}
routes["Smash activity 3 route"].arrows[4].position = vec.vector(-1414.782, 176.5, 4134.551, 1)
routes["Smash activity 3 route"].arrows[4].heading = 1.523683
routes["Smash activity 3 route"].arrows[4].modelId = 78
routes["Smash activity 3 route"].arrows[5] = {}
routes["Smash activity 3 route"].arrows[5].position = vec.vector(-1096.606, 172, 4251.618, 1)
routes["Smash activity 3 route"].arrows[5].heading = 1.313473
routes["Smash activity 3 route"].arrows[5].modelId = 78
routes["Smash activity 3 route"].arrows[6] = {}
routes["Smash activity 3 route"].arrows[6].position = vec.vector(-702.32, 138, 3862.456, 1)
routes["Smash activity 3 route"].arrows[6].heading = 1.552941
routes["Smash activity 3 route"].arrows[6].modelId = 78
routes["Smash activity 3 route"].arrows[7] = {}
routes["Smash activity 3 route"].arrows[7].position = vec.vector(-524.1479, 115.5, 3511.08, 1)
routes["Smash activity 3 route"].arrows[7].heading = 1.61159
routes["Smash activity 3 route"].arrows[7].modelId = 78
routes["Smash activity 3 route"].arrows[8] = {}
routes["Smash activity 3 route"].arrows[8].position = vec.vector(-291.9233, 95.5, 3556.198, 1)
routes["Smash activity 3 route"].arrows[8].heading = 1.116077
routes["Smash activity 3 route"].arrows[8].modelId = 219
routes["Smash activity 3 route"].arrows[9] = {}
routes["Smash activity 3 route"].arrows[9].position = vec.vector(-465.22, 122.5, 3772.686, 1)
routes["Smash activity 3 route"].arrows[9].heading = 3.141593
routes["Smash activity 3 route"].arrows[9].modelId = 219
routes["Smash activity 3 route"].arrows[10] = {}
routes["Smash activity 3 route"].arrows[10].position = vec.vector(-1157.477, 171.5, 4100.112, 1)
routes["Smash activity 3 route"].arrows[10].heading = 0.4072556
routes["Smash activity 3 route"].arrows[10].modelId = 219
routes["Smash activity 3 route"].roads = {}
routes["Smash activity 3 route"].roads[1] = {}
routes["Smash activity 3 route"].roads[1].road = "sutro_quarry_01 AI Road 1"
routes["Smash activity 3 route"].roads[1].direction = "with"
routes["Smash activity 3 route"].roads[2] = {}
routes["Smash activity 3 route"].roads[2].road = "sutro_shortcut_32 AI Road 1"
routes["Smash activity 3 route"].roads[2].direction = "with"
routes["Smash activity 3 route"].roads[3] = {}
routes["Smash activity 3 route"].roads[3].road = "sutro_shortcut_23 AI Road 2"
routes["Smash activity 3 route"].roads[3].direction = "against"
routes["Smash activity 3 route"].roads[4] = {}
routes["Smash activity 3 route"].roads[4].road = "sutro_shortcut_33 AI Road 0"
routes["Smash activity 3 route"].roads[4].direction = "with"
routes["Smash activity 3 route"].roads[5] = {}
routes["Smash activity 3 route"].roads[5].road = "sanfran_shortcut_27 AI Road 5"
routes["Smash activity 3 route"].roads[5].direction = "with"
routes["Smash activity 3 route"].roads[6] = {}
routes["Smash activity 3 route"].roads[6].road = "sutro_south_main AI Road 23"
routes["Smash activity 3 route"].roads[6].direction = "with"
routes["Smash activity 3 route"].roads[7] = {}
routes["Smash activity 3 route"].roads[7].road = "sutro_shortcut_22 AI Road 0"
routes["Smash activity 3 route"].roads[7].direction = "with"
routes["Smash activity 3 route"].roads[8] = {}
routes["Smash activity 3 route"].roads[8].road = "sutro_shortcut_22 AI Road 1"
routes["Smash activity 3 route"].roads[8].direction = "with"
routes["Smash activity 3 route"].roads[9] = {}
routes["Smash activity 3 route"].roads[9].road = "marin_shortcut_24 AI Road 0"
routes["Smash activity 3 route"].roads[9].direction = "with"
routes["Smash activity 3 route"].roads[10] = {}
routes["Smash activity 3 route"].roads[10].road = "marin_shortcut_24 AI Road 1"
routes["Smash activity 3 route"].roads[10].direction = "with"
routes["Smash activity 3 route"].roads[11] = {}
routes["Smash activity 3 route"].roads[11].road = "sutro_4l_south_2 AI Road 4"
routes["Smash activity 3 route"].roads[11].direction = "against"
routes["Smash activity 3 route"].roads[12] = {}
routes["Smash activity 3 route"].roads[12].road = "sutro_4l_south_2 AI Road 3"
routes["Smash activity 3 route"].roads[12].direction = "against"
routes["Smash activity 3 route"].roads[13] = {}
routes["Smash activity 3 route"].roads[13].road = "sutro_6l_se_01 AI Road 3"
routes["Smash activity 3 route"].roads[13].direction = "with"
routes["Smash activity 3 route"].roads[14] = {}
routes["Smash activity 3 route"].roads[14].road = "sutro_shortcut_04 AI Road 0"
routes["Smash activity 3 route"].roads[14].direction = "with"
