routes = routes or {}
routes["Tanker 1 Route"] = {}
routes["Tanker 1 Route"].checkpoints = {}
routes["Tanker 1 Route"].checkpoints[1] = {}
routes["Tanker 1 Route"].checkpoints[1].position = vec.vector(-1328.974, 170.1053, 3808.499, 1)
routes["Tanker 1 Route"].checkpoints[1].heading = -0.921708
routes["Tanker 1 Route"].checkpoints[1].roadName = "sutro_6l_south_01a AI Road 7"
routes["Tanker 1 Route"].checkpoints[2] = {}
routes["Tanker 1 Route"].checkpoints[2].position = vec.vector(-1507.076, 177.25, 3957.411, 1)
routes["Tanker 1 Route"].checkpoints[2].heading = 0.271774
routes["Tanker 1 Route"].checkpoints[2].roadName = "sutro_1l_south_01 AI Road 0"
routes["Tanker 1 Route"].checkpoints[3] = {}
routes["Tanker 1 Route"].checkpoints[3].position = vec.vector(-1333.807, 171.3103, 3950.066, 1)
routes["Tanker 1 Route"].checkpoints[3].heading = 2.274757
routes["Tanker 1 Route"].checkpoints[3].roadName = "marin_shortcut_23 AI Road 1"
routes["Tanker 1 Route"].checkpoints[4] = {}
routes["Tanker 1 Route"].checkpoints[4].position = vec.vector(-1248.93, 169.125, 3810.586, 1)
routes["Tanker 1 Route"].checkpoints[4].heading = -3.085247
routes["Tanker 1 Route"].checkpoints[4].roadName = "sutro_4l_south_03 AI Road 1"
routes["Tanker 1 Route"].arrows = {}
routes["Tanker 1 Route"].roads = {}
routes["Tanker 1 Route"].roads[1] = {}
routes["Tanker 1 Route"].roads[1].road = "sutro_6l_south_01a AI Road 7"
routes["Tanker 1 Route"].roads[1].direction = "against"
routes["Tanker 1 Route"].roads[2] = {}
routes["Tanker 1 Route"].roads[2].road = "sutro_4l_south_01 AI Road 2"
routes["Tanker 1 Route"].roads[2].direction = "against"
routes["Tanker 1 Route"].roads[3] = {}
routes["Tanker 1 Route"].roads[3].road = "sutro_1l_south_01 AI Road 0"
routes["Tanker 1 Route"].roads[3].direction = "with"
routes["Tanker 1 Route"].roads[4] = {}
routes["Tanker 1 Route"].roads[4].road = "marin_shortcut_23 AI Road 1"
routes["Tanker 1 Route"].roads[4].direction = "with"
routes["Tanker 1 Route"].roads[5] = {}
routes["Tanker 1 Route"].roads[5].road = "sutro_4l_south_03 AI Road 1"
routes["Tanker 1 Route"].roads[5].direction = "against"
routes["Tanker on fire activity 1 tanker"] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[1] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[1].position = vec.vector(-4445, 15.51315, 2244.491, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[1].heading = 3.141593
routes["Tanker on fire activity 1 tanker"].checkpoints[1].roadName = "ggp_10l_west_01 AI Road 3"
routes["Tanker on fire activity 1 tanker"].checkpoints[2] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[2].position = vec.vector(-4453.56, 21.6554, 1527.523, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[2].heading = -2.702015
routes["Tanker on fire activity 1 tanker"].checkpoints[2].roadName = "ggp_10l_west_01 AI Road 6"
routes["Tanker on fire activity 1 tanker"].checkpoints[3] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[3].position = vec.vector(-4049.308, 26.73572, 792.3104, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[3].heading = 1.904669
routes["Tanker on fire activity 1 tanker"].checkpoints[3].roadName = "ggp_8l_west_01 AI Road 1"
routes["Tanker on fire activity 1 tanker"].checkpoints[4] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[4].position = vec.vector(-3497.945, 10.59338, 189.926, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[4].heading = 2.666423
routes["Tanker on fire activity 1 tanker"].checkpoints[4].roadName = "ggp_8l_west_01 AI Road 4"
routes["Tanker on fire activity 1 tanker"].checkpoints[5] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[5].position = vec.vector(-3025.479, 2.075, -302.1033, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[5].heading = 1.273092
routes["Tanker on fire activity 1 tanker"].checkpoints[5].roadName = "ggp_8l_west_01 AI Road 8"
routes["Tanker on fire activity 1 tanker"].checkpoints[6] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[6].position = vec.vector(-2269.347, 2.769991, -281.6086, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[6].heading = 1.436978
routes["Tanker on fire activity 1 tanker"].checkpoints[6].roadName = "ggp_8l_north_03 AI Road 0"
routes["Tanker on fire activity 1 tanker"].checkpoints[7] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[7].position = vec.vector(-1481.12, 4.999999, -161.9167, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[7].heading = 1.488716
routes["Tanker on fire activity 1 tanker"].checkpoints[7].roadName = "dt_8l_north_04 AI Road 1"
routes["Tanker on fire activity 1 tanker"].checkpoints[8] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[8].position = vec.vector(-623.236, 4.999999, -182.6287, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[8].heading = 1.74031
routes["Tanker on fire activity 1 tanker"].checkpoints[8].roadName = "dt_10l_east_01 AI Road 3"
routes["Tanker on fire activity 1 tanker"].checkpoints[9] = {}
routes["Tanker on fire activity 1 tanker"].checkpoints[9].position = vec.vector(15.46741, 4.445144, -287.9583, 1)
routes["Tanker on fire activity 1 tanker"].checkpoints[9].heading = 1.687964
routes["Tanker on fire activity 1 tanker"].checkpoints[9].roadName = "dt_10l_east_01 AI Road 5"
routes["Tanker on fire activity 1 tanker"].arrows = {}
routes["Tanker on fire activity 1 tanker"].roads = {}
routes["Tanker on fire activity 1 tanker"].roads[1] = {}
routes["Tanker on fire activity 1 tanker"].roads[1].road = "ggp_10l_west_01 AI Road 3"
routes["Tanker on fire activity 1 tanker"].roads[1].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[2] = {}
routes["Tanker on fire activity 1 tanker"].roads[2].road = "ggp_10l_west_01 AI Road 4"
routes["Tanker on fire activity 1 tanker"].roads[2].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[3] = {}
routes["Tanker on fire activity 1 tanker"].roads[3].road = "ggp_10l_west_01 AI Road 5"
routes["Tanker on fire activity 1 tanker"].roads[3].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[4] = {}
routes["Tanker on fire activity 1 tanker"].roads[4].road = "ggp_10l_west_01 AI Road 6"
routes["Tanker on fire activity 1 tanker"].roads[4].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[5] = {}
routes["Tanker on fire activity 1 tanker"].roads[5].road = "ggp_10l_west_01 AI Road 7"
routes["Tanker on fire activity 1 tanker"].roads[5].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[6] = {}
routes["Tanker on fire activity 1 tanker"].roads[6].road = "ggp_8l_west_01 AI Road 0"
routes["Tanker on fire activity 1 tanker"].roads[6].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[7] = {}
routes["Tanker on fire activity 1 tanker"].roads[7].road = "ggp_8l_west_01 AI Road 1"
routes["Tanker on fire activity 1 tanker"].roads[7].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[8] = {}
routes["Tanker on fire activity 1 tanker"].roads[8].road = "ggp_8l_west_01 AI Road 2"
routes["Tanker on fire activity 1 tanker"].roads[8].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[9] = {}
routes["Tanker on fire activity 1 tanker"].roads[9].road = "ggp_8l_west_01 AI Road 3"
routes["Tanker on fire activity 1 tanker"].roads[9].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[10] = {}
routes["Tanker on fire activity 1 tanker"].roads[10].road = "ggp_8l_west_01 AI Road 4"
routes["Tanker on fire activity 1 tanker"].roads[10].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[11] = {}
routes["Tanker on fire activity 1 tanker"].roads[11].road = "ggp_8l_west_01 AI Road 5"
routes["Tanker on fire activity 1 tanker"].roads[11].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[12] = {}
routes["Tanker on fire activity 1 tanker"].roads[12].road = "ggp_8l_west_01 AI Road 6"
routes["Tanker on fire activity 1 tanker"].roads[12].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[13] = {}
routes["Tanker on fire activity 1 tanker"].roads[13].road = "ggp_8l_west_01 AI Road 7"
routes["Tanker on fire activity 1 tanker"].roads[13].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[14] = {}
routes["Tanker on fire activity 1 tanker"].roads[14].road = "ggp_8l_west_01 AI Road 8"
routes["Tanker on fire activity 1 tanker"].roads[14].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[15] = {}
routes["Tanker on fire activity 1 tanker"].roads[15].road = "ggp_8l_west_01 AI Road 9"
routes["Tanker on fire activity 1 tanker"].roads[15].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[16] = {}
routes["Tanker on fire activity 1 tanker"].roads[16].road = "ggp_8l_west_01 AI Road 10"
routes["Tanker on fire activity 1 tanker"].roads[16].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[17] = {}
routes["Tanker on fire activity 1 tanker"].roads[17].road = "ggp_8l_north_03 AI Road 0"
routes["Tanker on fire activity 1 tanker"].roads[17].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[18] = {}
routes["Tanker on fire activity 1 tanker"].roads[18].road = "ggp_8l_north_03 AI Road 1"
routes["Tanker on fire activity 1 tanker"].roads[18].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[19] = {}
routes["Tanker on fire activity 1 tanker"].roads[19].road = "dt_8l_north_04 AI Road 1"
routes["Tanker on fire activity 1 tanker"].roads[19].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[20] = {}
routes["Tanker on fire activity 1 tanker"].roads[20].road = "dt_8l_north_04 AI Road 2"
routes["Tanker on fire activity 1 tanker"].roads[20].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[21] = {}
routes["Tanker on fire activity 1 tanker"].roads[21].road = "dt_10l_east_01 AI Road 0"
routes["Tanker on fire activity 1 tanker"].roads[21].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[22] = {}
routes["Tanker on fire activity 1 tanker"].roads[22].road = "dt_10l_east_01 AI Road 1"
routes["Tanker on fire activity 1 tanker"].roads[22].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[23] = {}
routes["Tanker on fire activity 1 tanker"].roads[23].road = "dt_10l_east_01 AI Road 2"
routes["Tanker on fire activity 1 tanker"].roads[23].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[24] = {}
routes["Tanker on fire activity 1 tanker"].roads[24].road = "dt_10l_east_01 AI Road 3"
routes["Tanker on fire activity 1 tanker"].roads[24].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[25] = {}
routes["Tanker on fire activity 1 tanker"].roads[25].road = "dt_10l_east_01 AI Road 4"
routes["Tanker on fire activity 1 tanker"].roads[25].direction = "with"
routes["Tanker on fire activity 1 tanker"].roads[26] = {}
routes["Tanker on fire activity 1 tanker"].roads[26].road = "dt_10l_east_01 AI Road 5"
routes["Tanker on fire activity 1 tanker"].roads[26].direction = "with"
routes["Tanker on fire activity 1 tanker 1"] = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints[1] = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints[1].position = vec.vector(-869.2761, 66.74999, 1834.621, 1)
routes["Tanker on fire activity 1 tanker 1"].checkpoints[1].heading = 1.794058
routes["Tanker on fire activity 1 tanker 1"].checkpoints[1].roadName = "dt_10l_south_02b AI Road 6"
routes["Tanker on fire activity 1 tanker 1"].checkpoints[2] = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints[2].position = vec.vector(-89.7192, 42.01543, 1613.667, 1)
routes["Tanker on fire activity 1 tanker 1"].checkpoints[2].heading = 1.87375
routes["Tanker on fire activity 1 tanker 1"].checkpoints[2].roadName = "dt_10l_south_03 AI Road 6"
routes["Tanker on fire activity 1 tanker 1"].checkpoints[3] = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints[3].position = vec.vector(375.0961, 7.999999, 1315.755, 1)
routes["Tanker on fire activity 1 tanker 1"].checkpoints[3].heading = 2.348701
routes["Tanker on fire activity 1 tanker 1"].checkpoints[3].roadName = "dt_10l_south_03 AI Road 4"
routes["Tanker on fire activity 1 tanker 1"].checkpoints[4] = {}
routes["Tanker on fire activity 1 tanker 1"].checkpoints[4].position = vec.vector(861.0548, 5.974996, 876.4137, 1)
routes["Tanker on fire activity 1 tanker 1"].checkpoints[4].heading = 2.257906
routes["Tanker on fire activity 1 tanker 1"].checkpoints[4].roadName = "dt_10l_east_01 AI Road 14"
routes["Tanker on fire activity 1 tanker 1"].arrows = {}
routes["Tanker on fire activity 1 tanker 1"].roads = {}
routes["Tanker on fire activity 1 tanker 1"].roads[1] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[1].road = "dt_10l_south_02b AI Road 6"
routes["Tanker on fire activity 1 tanker 1"].roads[1].direction = "with"
routes["Tanker on fire activity 1 tanker 1"].roads[2] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[2].road = "dt_10l_south_02b AI Road 7"
routes["Tanker on fire activity 1 tanker 1"].roads[2].direction = "with"
routes["Tanker on fire activity 1 tanker 1"].roads[3] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[3].road = "dt_10l_south_02b AI Road 8"
routes["Tanker on fire activity 1 tanker 1"].roads[3].direction = "with"
routes["Tanker on fire activity 1 tanker 1"].roads[4] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[4].road = "dt_10l_south_02b AI Road 9"
routes["Tanker on fire activity 1 tanker 1"].roads[4].direction = "with"
routes["Tanker on fire activity 1 tanker 1"].roads[5] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[5].road = "dt_10l_south_03 AI Road 7"
routes["Tanker on fire activity 1 tanker 1"].roads[5].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[6] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[6].road = "dt_10l_south_03 AI Road 6"
routes["Tanker on fire activity 1 tanker 1"].roads[6].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[7] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[7].road = "dt_10l_south_03 AI Road 5"
routes["Tanker on fire activity 1 tanker 1"].roads[7].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[8] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[8].road = "dt_10l_south_03 AI Road 4"
routes["Tanker on fire activity 1 tanker 1"].roads[8].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[9] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[9].road = "dt_10l_south_03 AI Road 3"
routes["Tanker on fire activity 1 tanker 1"].roads[9].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[10] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[10].road = "dt_10l_south_03 AI Road 2"
routes["Tanker on fire activity 1 tanker 1"].roads[10].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[11] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[11].road = "dt_10l_south_03 AI Road 1"
routes["Tanker on fire activity 1 tanker 1"].roads[11].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[12] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[12].road = "dt_10l_south_03 AI Road 0"
routes["Tanker on fire activity 1 tanker 1"].roads[12].direction = "against"
routes["Tanker on fire activity 1 tanker 1"].roads[13] = {}
routes["Tanker on fire activity 1 tanker 1"].roads[13].road = "dt_10l_east_01 AI Road 14"
routes["Tanker on fire activity 1 tanker 1"].roads[13].direction = "against"
