routes = routes or {}
routes["Tanker on fire activity 2 tanker 1"] = {}
routes["Tanker on fire activity 2 tanker 1"].checkpoints = {}
routes["Tanker on fire activity 2 tanker 1"].checkpoints[1] = {}
routes["Tanker on fire activity 2 tanker 1"].checkpoints[1].position = vec.vector(-2765.009, 66.00936, -2509.254, 1)
routes["Tanker on fire activity 2 tanker 1"].checkpoints[1].heading = 3.024577
routes["Tanker on fire activity 2 tanker 1"].checkpoints[1].roadName = "highway01_15 AI Road 17"
routes["Tanker on fire activity 2 tanker 1"].checkpoints[2] = {}
routes["Tanker on fire activity 2 tanker 1"].checkpoints[2].position = vec.vector(29.16791, 34.25006, -2832.254, 1)
routes["Tanker on fire activity 2 tanker 1"].checkpoints[2].heading = 0.9466686
routes["Tanker on fire activity 2 tanker 1"].checkpoints[2].roadName = "highway01_15 AI Road 45"
routes["Tanker on fire activity 2 tanker 1"].arrows = {}
routes["Tanker on fire activity 2 tanker 1"].roads = {}
routes["Tanker on fire activity 2 tanker 1"].roads[1] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[1].road = "highway01_15 AI Road 17"
routes["Tanker on fire activity 2 tanker 1"].roads[1].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[2] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[2].road = "highway01_15 AI Road 18"
routes["Tanker on fire activity 2 tanker 1"].roads[2].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[3] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[3].road = "highway01_15 AI Road 19"
routes["Tanker on fire activity 2 tanker 1"].roads[3].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[4] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[4].road = "highway01_15 AI Road 20"
routes["Tanker on fire activity 2 tanker 1"].roads[4].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[5] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[5].road = "highway01_15 AI Road 21"
routes["Tanker on fire activity 2 tanker 1"].roads[5].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[6] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[6].road = "highway01_15 AI Road 22"
routes["Tanker on fire activity 2 tanker 1"].roads[6].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[7] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[7].road = "highway01_15 AI Road 23"
routes["Tanker on fire activity 2 tanker 1"].roads[7].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[8] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[8].road = "highway01_15 AI Road 24"
routes["Tanker on fire activity 2 tanker 1"].roads[8].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[9] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[9].road = "highway01_15 AI Road 25"
routes["Tanker on fire activity 2 tanker 1"].roads[9].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[10] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[10].road = "highway01_15 AI Road 26"
routes["Tanker on fire activity 2 tanker 1"].roads[10].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[11] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[11].road = "highway01_15 AI Road 27"
routes["Tanker on fire activity 2 tanker 1"].roads[11].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[12] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[12].road = "highway01_15 AI Road 28"
routes["Tanker on fire activity 2 tanker 1"].roads[12].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[13] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[13].road = "highway01_15 AI Road 29"
routes["Tanker on fire activity 2 tanker 1"].roads[13].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[14] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[14].road = "highway01_15 AI Road 30"
routes["Tanker on fire activity 2 tanker 1"].roads[14].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[15] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[15].road = "highway01_15 AI Road 31"
routes["Tanker on fire activity 2 tanker 1"].roads[15].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[16] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[16].road = "highway01_15 AI Road 32"
routes["Tanker on fire activity 2 tanker 1"].roads[16].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[17] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[17].road = "highway01_15 AI Road 33"
routes["Tanker on fire activity 2 tanker 1"].roads[17].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[18] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[18].road = "highway01_15 AI Road 34"
routes["Tanker on fire activity 2 tanker 1"].roads[18].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[19] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[19].road = "highway01_15 AI Road 35"
routes["Tanker on fire activity 2 tanker 1"].roads[19].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[20] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[20].road = "highway01_15 AI Road 36"
routes["Tanker on fire activity 2 tanker 1"].roads[20].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[21] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[21].road = "highway01_15 AI Road 37"
routes["Tanker on fire activity 2 tanker 1"].roads[21].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[22] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[22].road = "highway01_15 AI Road 38"
routes["Tanker on fire activity 2 tanker 1"].roads[22].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[23] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[23].road = "highway01_15 AI Road 39"
routes["Tanker on fire activity 2 tanker 1"].roads[23].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[24] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[24].road = "highway01_15 AI Road 40"
routes["Tanker on fire activity 2 tanker 1"].roads[24].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[25] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[25].road = "highway01_15 AI Road 41"
routes["Tanker on fire activity 2 tanker 1"].roads[25].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[26] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[26].road = "highway01_15 AI Road 42"
routes["Tanker on fire activity 2 tanker 1"].roads[26].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[27] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[27].road = "highway01_15 AI Road 43"
routes["Tanker on fire activity 2 tanker 1"].roads[27].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[28] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[28].road = "highway01_15 AI Road 44"
routes["Tanker on fire activity 2 tanker 1"].roads[28].direction = "with"
routes["Tanker on fire activity 2 tanker 1"].roads[29] = {}
routes["Tanker on fire activity 2 tanker 1"].roads[29].road = "highway01_15 AI Road 45"
routes["Tanker on fire activity 2 tanker 1"].roads[29].direction = "with"
routes["Tanker on fire activity 2 tanker 3"] = {}
routes["Tanker on fire activity 2 tanker 3"].checkpoints = {}
routes["Tanker on fire activity 2 tanker 3"].checkpoints[1] = {}
routes["Tanker on fire activity 2 tanker 3"].checkpoints[1].position = vec.vector(1376.174, 47.33827, -2467.332, 1)
routes["Tanker on fire activity 2 tanker 3"].checkpoints[1].heading = 1.418818
routes["Tanker on fire activity 2 tanker 3"].checkpoints[1].roadName = "highway01_15 AI Road 51"
routes["Tanker on fire activity 2 tanker 3"].checkpoints[2] = {}
routes["Tanker on fire activity 2 tanker 3"].checkpoints[2].position = vec.vector(2816.725, 38.45646, -203.4536, 1)
routes["Tanker on fire activity 2 tanker 3"].checkpoints[2].heading = 0.529833
routes["Tanker on fire activity 2 tanker 3"].checkpoints[2].roadName = "superhighway_road_01 AI Road 4"
routes["Tanker on fire activity 2 tanker 3"].arrows = {}
routes["Tanker on fire activity 2 tanker 3"].roads = {}
routes["Tanker on fire activity 2 tanker 3"].roads[1] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[1].road = "highway01_15 AI Road 51"
routes["Tanker on fire activity 2 tanker 3"].roads[1].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[2] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[2].road = "highway01_15 AI Road 52"
routes["Tanker on fire activity 2 tanker 3"].roads[2].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[3] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[3].road = "highway01_15 AI Road 53"
routes["Tanker on fire activity 2 tanker 3"].roads[3].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[4] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[4].road = "highway01_15 AI Road 54"
routes["Tanker on fire activity 2 tanker 3"].roads[4].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[5] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[5].road = "highway01_15 AI Road 55"
routes["Tanker on fire activity 2 tanker 3"].roads[5].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[6] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[6].road = "highway01_15 AI Road 56"
routes["Tanker on fire activity 2 tanker 3"].roads[6].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[7] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[7].road = "highway01_15 AI Road 57"
routes["Tanker on fire activity 2 tanker 3"].roads[7].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[8] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[8].road = "highway01_15 AI Road 58"
routes["Tanker on fire activity 2 tanker 3"].roads[8].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[9] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[9].road = "highway01_15 AI Road 59"
routes["Tanker on fire activity 2 tanker 3"].roads[9].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[10] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[10].road = "highway01_15 AI Road 60"
routes["Tanker on fire activity 2 tanker 3"].roads[10].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[11] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[11].road = "highway01_15 AI Road 61"
routes["Tanker on fire activity 2 tanker 3"].roads[11].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[12] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[12].road = "highway01_15 AI Road 62"
routes["Tanker on fire activity 2 tanker 3"].roads[12].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[13] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[13].road = "superhighway_split_03 AI Road 6"
routes["Tanker on fire activity 2 tanker 3"].roads[13].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[14] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[14].road = "superhighway_split_03 AI Road 5"
routes["Tanker on fire activity 2 tanker 3"].roads[14].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[15] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[15].road = "superhighway_split_03 AI Road 4"
routes["Tanker on fire activity 2 tanker 3"].roads[15].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[16] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[16].road = "superhighway_split_03 AI Road 3"
routes["Tanker on fire activity 2 tanker 3"].roads[16].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[17] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[17].road = "superhighway_split_03 AI Road 2"
routes["Tanker on fire activity 2 tanker 3"].roads[17].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[18] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[18].road = "superhighway_split_03 AI Road 1"
routes["Tanker on fire activity 2 tanker 3"].roads[18].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[19] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[19].road = "superhighway_split_03 AI Road 0"
routes["Tanker on fire activity 2 tanker 3"].roads[19].direction = "against"
routes["Tanker on fire activity 2 tanker 3"].roads[20] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[20].road = "superhighway_road_01 AI Road 0"
routes["Tanker on fire activity 2 tanker 3"].roads[20].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[21] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[21].road = "superhighway_road_01 AI Road 1"
routes["Tanker on fire activity 2 tanker 3"].roads[21].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[22] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[22].road = "superhighway_road_01 AI Road 2"
routes["Tanker on fire activity 2 tanker 3"].roads[22].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[23] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[23].road = "superhighway_road_01 AI Road 3"
routes["Tanker on fire activity 2 tanker 3"].roads[23].direction = "with"
routes["Tanker on fire activity 2 tanker 3"].roads[24] = {}
routes["Tanker on fire activity 2 tanker 3"].roads[24].road = "superhighway_road_01 AI Road 4"
routes["Tanker on fire activity 2 tanker 3"].roads[24].direction = "with"
routes["Tanker on fire activity 2 tanker 2"] = {}
routes["Tanker on fire activity 2 tanker 2"].checkpoints = {}
routes["Tanker on fire activity 2 tanker 2"].checkpoints[1] = {}
routes["Tanker on fire activity 2 tanker 2"].checkpoints[1].position = vec.vector(-58.85194, 53.75, -3965.763, 1)
routes["Tanker on fire activity 2 tanker 2"].checkpoints[1].heading = 2.347667
routes["Tanker on fire activity 2 tanker 2"].checkpoints[1].roadName = "mountain_10l_w_01b AI Road 21"
routes["Tanker on fire activity 2 tanker 2"].checkpoints[2] = {}
routes["Tanker on fire activity 2 tanker 2"].checkpoints[2].position = vec.vector(2254.511, 40.94889, -4180.771, 1)
routes["Tanker on fire activity 2 tanker 2"].checkpoints[2].heading = 0.3742007
routes["Tanker on fire activity 2 tanker 2"].checkpoints[2].roadName = "mountain_10l_w_01b AI Road 10"
routes["Tanker on fire activity 2 tanker 2"].arrows = {}
routes["Tanker on fire activity 2 tanker 2"].roads = {}
routes["Tanker on fire activity 2 tanker 2"].roads[1] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[1].road = "mountain_10l_w_01b AI Road 21"
routes["Tanker on fire activity 2 tanker 2"].roads[1].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[2] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[2].road = "mountain_10l_w_01b AI Road 20"
routes["Tanker on fire activity 2 tanker 2"].roads[2].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[3] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[3].road = "mountain_10l_w_01b AI Road 19"
routes["Tanker on fire activity 2 tanker 2"].roads[3].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[4] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[4].road = "mountain_10l_w_01b AI Road 18"
routes["Tanker on fire activity 2 tanker 2"].roads[4].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[5] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[5].road = "mountain_10l_w_01b AI Road 17"
routes["Tanker on fire activity 2 tanker 2"].roads[5].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[6] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[6].road = "mountain_10l_w_01b AI Road 16"
routes["Tanker on fire activity 2 tanker 2"].roads[6].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[7] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[7].road = "mountain_10l_w_01b AI Road 15"
routes["Tanker on fire activity 2 tanker 2"].roads[7].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[8] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[8].road = "mountain_10l_w_01b AI Road 14"
routes["Tanker on fire activity 2 tanker 2"].roads[8].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[9] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[9].road = "mountain_10l_w_01b AI Road 13"
routes["Tanker on fire activity 2 tanker 2"].roads[9].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[10] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[10].road = "mountain_10l_w_01b AI Road 12"
routes["Tanker on fire activity 2 tanker 2"].roads[10].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[11] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[11].road = "mountain_10l_w_01b AI Road 11"
routes["Tanker on fire activity 2 tanker 2"].roads[11].direction = "against"
routes["Tanker on fire activity 2 tanker 2"].roads[12] = {}
routes["Tanker on fire activity 2 tanker 2"].roads[12].road = "mountain_10l_w_01b AI Road 10"
routes["Tanker on fire activity 2 tanker 2"].roads[12].direction = "against"
routes["Tanker on fire activity 2 truck 2a"] = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints[1] = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints[1].position = vec.vector(1820, 27.83765, -3997.816, 1)
routes["Tanker on fire activity 2 truck 2a"].checkpoints[1].heading = 0
routes["Tanker on fire activity 2 truck 2a"].checkpoints[1].roadName = "mountain_6l_east_01 AI Road 0"
routes["Tanker on fire activity 2 truck 2a"].checkpoints[2] = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints[2].position = vec.vector(2039.457, 27.75, -3950, 1)
routes["Tanker on fire activity 2 truck 2a"].checkpoints[2].heading = 1.570796
routes["Tanker on fire activity 2 truck 2a"].checkpoints[2].roadName = "marin_shortcut_44a AI Road 0"
routes["Tanker on fire activity 2 truck 2a"].checkpoints[3] = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints[3].position = vec.vector(2115, 30.03532, -4124.642, 1)
routes["Tanker on fire activity 2 truck 2a"].checkpoints[3].heading = 3.141593
routes["Tanker on fire activity 2 truck 2a"].checkpoints[3].roadName = "marin_shortcut_15b AI Road 2"
routes["Tanker on fire activity 2 truck 2a"].checkpoints[4] = {}
routes["Tanker on fire activity 2 truck 2a"].checkpoints[4].position = vec.vector(1883.595, 30, -4200, 1)
routes["Tanker on fire activity 2 truck 2a"].checkpoints[4].heading = -1.570796
routes["Tanker on fire activity 2 truck 2a"].checkpoints[4].roadName = "marin_east_10 AI Road 10"
routes["Tanker on fire activity 2 truck 2a"].arrows = {}
routes["Tanker on fire activity 2 truck 2a"].roads = {}
routes["Tanker on fire activity 2 truck 2a"].roads[1] = {}
routes["Tanker on fire activity 2 truck 2a"].roads[1].road = "mountain_6l_east_01 AI Road 0"
routes["Tanker on fire activity 2 truck 2a"].roads[1].direction = "with"
routes["Tanker on fire activity 2 truck 2a"].roads[2] = {}
routes["Tanker on fire activity 2 truck 2a"].roads[2].road = "marin_shortcut_44a AI Road 0"
routes["Tanker on fire activity 2 truck 2a"].roads[2].direction = "with"
routes["Tanker on fire activity 2 truck 2a"].roads[3] = {}
routes["Tanker on fire activity 2 truck 2a"].roads[3].road = "marin_shortcut_15b AI Road 3"
routes["Tanker on fire activity 2 truck 2a"].roads[3].direction = "against"
routes["Tanker on fire activity 2 truck 2a"].roads[4] = {}
routes["Tanker on fire activity 2 truck 2a"].roads[4].road = "marin_shortcut_15b AI Road 2"
routes["Tanker on fire activity 2 truck 2a"].roads[4].direction = "against"
routes["Tanker on fire activity 2 truck 2a"].roads[5] = {}
routes["Tanker on fire activity 2 truck 2a"].roads[5].road = "marin_east_10 AI Road 10"
routes["Tanker on fire activity 2 truck 2a"].roads[5].direction = "against"
routes["Tanker on fire actibity 2 tanker 2b"] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[1] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[1].position = vec.vector(-96.81384, 90.05944, -4692.753, 1)
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[1].heading = -0.5131468
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[1].roadName = "r681_shortcut_01 AI Road 0"
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[2] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[2].position = vec.vector(-394.6721, 95.77988, -4591.292, 1)
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[2].heading = -1.179875
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[2].roadName = "marin_4l_centre_03 AI Road 2"
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[3] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[3].position = vec.vector(-608.4865, 97.33636, -4603.758, 1)
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[3].heading = -2.493665
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[3].roadName = "marin_shortcut_35 AI Road 0"
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[4] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[4].position = vec.vector(-463.2664, 129, -4772.528, 1)
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[4].heading = 0.9784252
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[4].roadName = "marin_shortcut_35 AI Road 0"
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[5] = {}
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[5].position = vec.vector(-145.0465, 111.4256, -4903.916, 1)
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[5].heading = 2.582673
routes["Tanker on fire actibity 2 tanker 2b"].checkpoints[5].roadName = "marin_6l_west_01a AI Road 31"
routes["Tanker on fire actibity 2 tanker 2b"].arrows = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[1] = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[1].road = "r681_shortcut_01 AI Road 0"
routes["Tanker on fire actibity 2 tanker 2b"].roads[1].direction = "against"
routes["Tanker on fire actibity 2 tanker 2b"].roads[2] = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[2].road = "marin_4l_centre_03 AI Road 3"
routes["Tanker on fire actibity 2 tanker 2b"].roads[2].direction = "against"
routes["Tanker on fire actibity 2 tanker 2b"].roads[3] = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[3].road = "marin_4l_centre_03 AI Road 2"
routes["Tanker on fire actibity 2 tanker 2b"].roads[3].direction = "against"
routes["Tanker on fire actibity 2 tanker 2b"].roads[4] = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[4].road = "marin_shortcut_35 AI Road 0"
routes["Tanker on fire actibity 2 tanker 2b"].roads[4].direction = "against"
routes["Tanker on fire actibity 2 tanker 2b"].roads[5] = {}
routes["Tanker on fire actibity 2 tanker 2b"].roads[5].road = "marin_6l_west_01a AI Road 31"
routes["Tanker on fire actibity 2 tanker 2b"].roads[5].direction = "with"
