routes = routes or {}
routes["Bad medicine warmup route"] = {}
routes["Bad medicine warmup route"].checkpoints = {}
routes["Bad medicine warmup route"].checkpoints[1] = {}
routes["Bad medicine warmup route"].checkpoints[1].position = vec.vector(1781.42, 30, -4632.992, 1)
routes["Bad medicine warmup route"].checkpoints[1].heading = 0.566369
routes["Bad medicine warmup route"].checkpoints[1].roadName = "marin_4l_east_11 AI Road 3"
routes["Bad medicine warmup route"].checkpoints[2] = {}
routes["Bad medicine warmup route"].checkpoints[2].position = vec.vector(1584.659, 29.99999, -4401.283, 1)
routes["Bad medicine warmup route"].checkpoints[2].heading = -1.03889
routes["Bad medicine warmup route"].checkpoints[2].roadName = "marin_4l_centre_01 AI Road 19"
routes["Bad medicine warmup route"].checkpoints[3] = {}
routes["Bad medicine warmup route"].checkpoints[3].position = vec.vector(1365.306, 30, -4375.404, 1)
routes["Bad medicine warmup route"].checkpoints[3].heading = -2.600941
routes["Bad medicine warmup route"].checkpoints[3].roadName = "marin_4l_east_13 AI Road 0"
routes["Bad medicine warmup route"].checkpoints[4] = {}
routes["Bad medicine warmup route"].checkpoints[4].position = vec.vector(1596.763, 29.99999, -4648.847, 1)
routes["Bad medicine warmup route"].checkpoints[4].heading = 2.141113
routes["Bad medicine warmup route"].checkpoints[4].roadName = "marin_4l_east_11 AI Road 2"
routes["Bad medicine warmup route"].arrows = {}
routes["Bad medicine warmup route"].roads = {}
routes["Bad medicine warmup route"].roads[1] = {}
routes["Bad medicine warmup route"].roads[1].road = "marin_4l_east_11 AI Road 3"
routes["Bad medicine warmup route"].roads[1].direction = "with"
routes["Bad medicine warmup route"].roads[2] = {}
routes["Bad medicine warmup route"].roads[2].road = "marin_4l_centre_01 AI Road 20"
routes["Bad medicine warmup route"].roads[2].direction = "against"
routes["Bad medicine warmup route"].roads[3] = {}
routes["Bad medicine warmup route"].roads[3].road = "marin_4l_centre_01 AI Road 19"
routes["Bad medicine warmup route"].roads[3].direction = "against"
routes["Bad medicine warmup route"].roads[4] = {}
routes["Bad medicine warmup route"].roads[4].road = "marin_4l_centre_01 AI Road 18"
routes["Bad medicine warmup route"].roads[4].direction = "against"
routes["Bad medicine warmup route"].roads[5] = {}
routes["Bad medicine warmup route"].roads[5].road = "marin_4l_east_13 AI Road 0"
routes["Bad medicine warmup route"].roads[5].direction = "against"
routes["Bad medicine warmup route"].roads[6] = {}
routes["Bad medicine warmup route"].roads[6].road = "marin_4l_east_11 AI Road 1"
routes["Bad medicine warmup route"].roads[6].direction = "with"
routes["Bad medicine warmup route"].roads[7] = {}
routes["Bad medicine warmup route"].roads[7].road = "marin_4l_east_11 AI Road 2"
routes["Bad medicine warmup route"].roads[7].direction = "with"
