routes = routes or {}
routes.CrankedWarmupRoute = {}
routes.CrankedWarmupRoute.checkpoints = {}
routes.CrankedWarmupRoute.checkpoints[1] = {}
routes.CrankedWarmupRoute.checkpoints[1].position = vec.vector(-2530.991, 163.9188, 3595.072, 1)
routes.CrankedWarmupRoute.checkpoints[1].heading = -1.55872
routes.CrankedWarmupRoute.checkpoints[1].roadName = "sutro_6l_south_01a AI Road 2"
routes.CrankedWarmupRoute.checkpoints[2] = {}
routes.CrankedWarmupRoute.checkpoints[2].position = vec.vector(-2873.071, 106.8907, 3213.914, 1)
routes.CrankedWarmupRoute.checkpoints[2].heading = 2.012152
routes.CrankedWarmupRoute.checkpoints[2].roadName = "sutro_6l_south_01a AI Road 0"
routes.CrankedWarmupRoute.checkpoints[3] = {}
routes.CrankedWarmupRoute.checkpoints[3].position = vec.vector(-2257.187, 146.4116, 3367.583, 1)
routes.CrankedWarmupRoute.checkpoints[3].heading = 1.534797
routes.CrankedWarmupRoute.checkpoints[3].roadName = "sutro_6l_centre_06b AI Road 1"
routes.CrankedWarmupRoute.checkpoints[4] = {}
routes.CrankedWarmupRoute.checkpoints[4].position = vec.vector(-2246.89, 176.6076, 3541.319, 1)
routes.CrankedWarmupRoute.checkpoints[4].heading = -1.118717
routes.CrankedWarmupRoute.checkpoints[4].roadName = "sutro_4l_centre_04 AI Road 2"
routes.CrankedWarmupRoute.arrows = {}
routes.CrankedWarmupRoute.roads = {}
routes.CrankedWarmupRoute.roads[1] = {}
routes.CrankedWarmupRoute.roads[1].road = "sutro_6l_south_01a AI Road 2"
routes.CrankedWarmupRoute.roads[1].direction = "against"
routes.CrankedWarmupRoute.roads[2] = {}
routes.CrankedWarmupRoute.roads[2].road = "sutro_6l_south_01a AI Road 1"
routes.CrankedWarmupRoute.roads[2].direction = "against"
routes.CrankedWarmupRoute.roads[3] = {}
routes.CrankedWarmupRoute.roads[3].road = "sutro_6l_south_01a AI Road 0"
routes.CrankedWarmupRoute.roads[3].direction = "against"
routes.CrankedWarmupRoute.roads[4] = {}
routes.CrankedWarmupRoute.roads[4].road = "sutro_6l_centre_06b AI Road 0"
routes.CrankedWarmupRoute.roads[4].direction = "with"
routes.CrankedWarmupRoute.roads[5] = {}
routes.CrankedWarmupRoute.roads[5].road = "sutro_6l_centre_06b AI Road 1"
routes.CrankedWarmupRoute.roads[5].direction = "with"
routes.CrankedWarmupRoute.roads[6] = {}
routes.CrankedWarmupRoute.roads[6].road = "sutro_6l_centre_06b AI Road 2"
routes.CrankedWarmupRoute.roads[6].direction = "with"
routes.CrankedWarmupRoute.roads[7] = {}
routes.CrankedWarmupRoute.roads[7].road = "sutro_4l_centre_04 AI Road 0"
routes.CrankedWarmupRoute.roads[7].direction = "with"
routes.CrankedWarmupRoute.roads[8] = {}
routes.CrankedWarmupRoute.roads[8].road = "sutro_4l_centre_04 AI Road 1"
routes.CrankedWarmupRoute.roads[8].direction = "with"
routes.CrankedWarmupRoute.roads[9] = {}
routes.CrankedWarmupRoute.roads[9].road = "sutro_4l_centre_04 AI Road 2"
routes.CrankedWarmupRoute.roads[9].direction = "with"
