routes = routes or {}
routes["DeactivatingBUTs Warmup"] = {}
routes["DeactivatingBUTs Warmup"].checkpoints = {}
routes["DeactivatingBUTs Warmup"].checkpoints[1] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[1].position = vec.vector(-2810.51, 43.59215, -2252.131, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[1].heading = 2.959709
routes["DeactivatingBUTs Warmup"].checkpoints[1].roadName = "highway01_15 AI Road 16"
routes["DeactivatingBUTs Warmup"].checkpoints[2] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[2].position = vec.vector(-2943.202, 80.75379, -2798.083, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[2].heading = -2.29244
routes["DeactivatingBUTs Warmup"].checkpoints[2].roadName = "highway01_15 AI Road 20"
routes["DeactivatingBUTs Warmup"].checkpoints[3] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[3].position = vec.vector(-2658.439, 138.3696, -3468.19, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[3].heading = 2.31479
routes["DeactivatingBUTs Warmup"].checkpoints[3].roadName = "highway01_15 AI Road 28"
routes["DeactivatingBUTs Warmup"].checkpoints[4] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[4].position = vec.vector(-1581.258, 137.6392, -3763.764, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[4].heading = 1.444123
routes["DeactivatingBUTs Warmup"].checkpoints[4].roadName = "highway01_15 AI Road 36"
routes["DeactivatingBUTs Warmup"].checkpoints[5] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[5].position = vec.vector(-665.6219, 60.25, -3403.506, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[5].heading = 0.5791871
routes["DeactivatingBUTs Warmup"].checkpoints[5].roadName = "highway01_15 AI Road 41"
routes["DeactivatingBUTs Warmup"].checkpoints[6] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[6].position = vec.vector(-262.4418, 56.17608, -3042.254, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[6].heading = 0.9466831
routes["DeactivatingBUTs Warmup"].checkpoints[6].roadName = "highway01_15 AI Road 43"
routes["DeactivatingBUTs Warmup"].checkpoints[7] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[7].position = vec.vector(893.8393, 24.49979, -2542.704, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[7].heading = 1.409491
routes["DeactivatingBUTs Warmup"].checkpoints[7].roadName = "highway01_15 AI Road 50"
routes["DeactivatingBUTs Warmup"].checkpoints[8] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[8].position = vec.vector(2158.506, 52.66274, -2480.916, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[8].heading = 1.479391
routes["DeactivatingBUTs Warmup"].checkpoints[8].roadName = "highway01_15 AI Road 56"
routes["DeactivatingBUTs Warmup"].checkpoints[9] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[9].position = vec.vector(2861.191, 6.120214, -1915.78, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[9].heading = 0.6959798
routes["DeactivatingBUTs Warmup"].checkpoints[9].roadName = "highway01_15 AI Road 62"
routes["DeactivatingBUTs Warmup"].checkpoints[10] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[10].position = vec.vector(2766.193, 35.72624, -289.7023, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[10].heading = 0.5298623
routes["DeactivatingBUTs Warmup"].checkpoints[10].roadName = "superhighway_road_01 AI Road 4"
routes["DeactivatingBUTs Warmup"].checkpoints[11] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[11].position = vec.vector(1899.258, 47.00214, 1443.88, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[11].heading = -1.141876
routes["DeactivatingBUTs Warmup"].checkpoints[11].roadName = "highway01_16b AI Road 23"
routes["DeactivatingBUTs Warmup"].checkpoints[12] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[12].position = vec.vector(491.4086, 46.90316, 2457.604, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[12].heading = -0.9485821
routes["DeactivatingBUTs Warmup"].checkpoints[12].roadName = "highway01_16b AI Road 17"
routes["DeactivatingBUTs Warmup"].checkpoints[13] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[13].position = vec.vector(-175.7467, 69.59872, 2764.517, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[13].heading = -1.649444
routes["DeactivatingBUTs Warmup"].checkpoints[13].roadName = "highway01_16b AI Road 13"
routes["DeactivatingBUTs Warmup"].checkpoints[14] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[14].position = vec.vector(-1007.411, 57, 1215.178, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[14].heading = -2.932211
routes["DeactivatingBUTs Warmup"].checkpoints[14].roadName = "highway01_16b AI Road 1"
routes["DeactivatingBUTs Warmup"].checkpoints[15] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[15].position = vec.vector(-2355.654, 47.25, 344.7676, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[15].heading = -1.819214
routes["DeactivatingBUTs Warmup"].checkpoints[15].roadName = "highway01_15 AI Road 1"
routes["DeactivatingBUTs Warmup"].checkpoints[16] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[16].position = vec.vector(-3123.272, 66.53858, -504.7299, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[16].heading = 2.966542
routes["DeactivatingBUTs Warmup"].checkpoints[16].roadName = "highway01_15 AI Road 7"
routes["DeactivatingBUTs Warmup"].checkpoints[17] = {}
routes["DeactivatingBUTs Warmup"].checkpoints[17].position = vec.vector(-2848.903, 40.74999, -2048.806, 1)
routes["DeactivatingBUTs Warmup"].checkpoints[17].heading = 2.951815
routes["DeactivatingBUTs Warmup"].checkpoints[17].roadName = "highway01_15 AI Road 15"
routes["DeactivatingBUTs Warmup"].arrows = {}
routes["DeactivatingBUTs Warmup"].roads = {}
routes["DeactivatingBUTs Warmup"].roads[1] = {}
routes["DeactivatingBUTs Warmup"].roads[1].road = "highway01_15 AI Road 16"
routes["DeactivatingBUTs Warmup"].roads[1].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[2] = {}
routes["DeactivatingBUTs Warmup"].roads[2].road = "highway01_15 AI Road 17"
routes["DeactivatingBUTs Warmup"].roads[2].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[3] = {}
routes["DeactivatingBUTs Warmup"].roads[3].road = "highway01_15 AI Road 18"
routes["DeactivatingBUTs Warmup"].roads[3].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[4] = {}
routes["DeactivatingBUTs Warmup"].roads[4].road = "highway01_15 AI Road 19"
routes["DeactivatingBUTs Warmup"].roads[4].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[5] = {}
routes["DeactivatingBUTs Warmup"].roads[5].road = "highway01_15 AI Road 20"
routes["DeactivatingBUTs Warmup"].roads[5].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[6] = {}
routes["DeactivatingBUTs Warmup"].roads[6].road = "highway01_15 AI Road 21"
routes["DeactivatingBUTs Warmup"].roads[6].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[7] = {}
routes["DeactivatingBUTs Warmup"].roads[7].road = "highway01_15 AI Road 22"
routes["DeactivatingBUTs Warmup"].roads[7].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[8] = {}
routes["DeactivatingBUTs Warmup"].roads[8].road = "highway01_15 AI Road 23"
routes["DeactivatingBUTs Warmup"].roads[8].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[9] = {}
routes["DeactivatingBUTs Warmup"].roads[9].road = "highway01_15 AI Road 24"
routes["DeactivatingBUTs Warmup"].roads[9].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[10] = {}
routes["DeactivatingBUTs Warmup"].roads[10].road = "highway01_15 AI Road 25"
routes["DeactivatingBUTs Warmup"].roads[10].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[11] = {}
routes["DeactivatingBUTs Warmup"].roads[11].road = "highway01_15 AI Road 26"
routes["DeactivatingBUTs Warmup"].roads[11].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[12] = {}
routes["DeactivatingBUTs Warmup"].roads[12].road = "highway01_15 AI Road 27"
routes["DeactivatingBUTs Warmup"].roads[12].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[13] = {}
routes["DeactivatingBUTs Warmup"].roads[13].road = "highway01_15 AI Road 28"
routes["DeactivatingBUTs Warmup"].roads[13].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[14] = {}
routes["DeactivatingBUTs Warmup"].roads[14].road = "highway01_15 AI Road 29"
routes["DeactivatingBUTs Warmup"].roads[14].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[15] = {}
routes["DeactivatingBUTs Warmup"].roads[15].road = "highway01_15 AI Road 30"
routes["DeactivatingBUTs Warmup"].roads[15].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[16] = {}
routes["DeactivatingBUTs Warmup"].roads[16].road = "highway01_15 AI Road 31"
routes["DeactivatingBUTs Warmup"].roads[16].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[17] = {}
routes["DeactivatingBUTs Warmup"].roads[17].road = "highway01_15 AI Road 32"
routes["DeactivatingBUTs Warmup"].roads[17].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[18] = {}
routes["DeactivatingBUTs Warmup"].roads[18].road = "highway01_15 AI Road 33"
routes["DeactivatingBUTs Warmup"].roads[18].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[19] = {}
routes["DeactivatingBUTs Warmup"].roads[19].road = "highway01_15 AI Road 34"
routes["DeactivatingBUTs Warmup"].roads[19].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[20] = {}
routes["DeactivatingBUTs Warmup"].roads[20].road = "highway01_15 AI Road 35"
routes["DeactivatingBUTs Warmup"].roads[20].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[21] = {}
routes["DeactivatingBUTs Warmup"].roads[21].road = "highway01_15 AI Road 36"
routes["DeactivatingBUTs Warmup"].roads[21].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[22] = {}
routes["DeactivatingBUTs Warmup"].roads[22].road = "highway01_15 AI Road 37"
routes["DeactivatingBUTs Warmup"].roads[22].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[23] = {}
routes["DeactivatingBUTs Warmup"].roads[23].road = "highway01_15 AI Road 38"
routes["DeactivatingBUTs Warmup"].roads[23].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[24] = {}
routes["DeactivatingBUTs Warmup"].roads[24].road = "highway01_15 AI Road 39"
routes["DeactivatingBUTs Warmup"].roads[24].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[25] = {}
routes["DeactivatingBUTs Warmup"].roads[25].road = "highway01_15 AI Road 40"
routes["DeactivatingBUTs Warmup"].roads[25].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[26] = {}
routes["DeactivatingBUTs Warmup"].roads[26].road = "highway01_15 AI Road 41"
routes["DeactivatingBUTs Warmup"].roads[26].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[27] = {}
routes["DeactivatingBUTs Warmup"].roads[27].road = "highway01_15 AI Road 42"
routes["DeactivatingBUTs Warmup"].roads[27].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[28] = {}
routes["DeactivatingBUTs Warmup"].roads[28].road = "highway01_15 AI Road 43"
routes["DeactivatingBUTs Warmup"].roads[28].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[29] = {}
routes["DeactivatingBUTs Warmup"].roads[29].road = "highway01_15 AI Road 44"
routes["DeactivatingBUTs Warmup"].roads[29].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[30] = {}
routes["DeactivatingBUTs Warmup"].roads[30].road = "highway01_15 AI Road 45"
routes["DeactivatingBUTs Warmup"].roads[30].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[31] = {}
routes["DeactivatingBUTs Warmup"].roads[31].road = "highway01_15 AI Road 46"
routes["DeactivatingBUTs Warmup"].roads[31].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[32] = {}
routes["DeactivatingBUTs Warmup"].roads[32].road = "highway01_15 AI Road 47"
routes["DeactivatingBUTs Warmup"].roads[32].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[33] = {}
routes["DeactivatingBUTs Warmup"].roads[33].road = "highway01_15 AI Road 48"
routes["DeactivatingBUTs Warmup"].roads[33].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[34] = {}
routes["DeactivatingBUTs Warmup"].roads[34].road = "highway01_15 AI Road 49"
routes["DeactivatingBUTs Warmup"].roads[34].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[35] = {}
routes["DeactivatingBUTs Warmup"].roads[35].road = "highway01_15 AI Road 50"
routes["DeactivatingBUTs Warmup"].roads[35].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[36] = {}
routes["DeactivatingBUTs Warmup"].roads[36].road = "highway01_15 AI Road 51"
routes["DeactivatingBUTs Warmup"].roads[36].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[37] = {}
routes["DeactivatingBUTs Warmup"].roads[37].road = "highway01_15 AI Road 52"
routes["DeactivatingBUTs Warmup"].roads[37].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[38] = {}
routes["DeactivatingBUTs Warmup"].roads[38].road = "highway01_15 AI Road 53"
routes["DeactivatingBUTs Warmup"].roads[38].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[39] = {}
routes["DeactivatingBUTs Warmup"].roads[39].road = "highway01_15 AI Road 54"
routes["DeactivatingBUTs Warmup"].roads[39].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[40] = {}
routes["DeactivatingBUTs Warmup"].roads[40].road = "highway01_15 AI Road 55"
routes["DeactivatingBUTs Warmup"].roads[40].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[41] = {}
routes["DeactivatingBUTs Warmup"].roads[41].road = "highway01_15 AI Road 56"
routes["DeactivatingBUTs Warmup"].roads[41].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[42] = {}
routes["DeactivatingBUTs Warmup"].roads[42].road = "highway01_15 AI Road 57"
routes["DeactivatingBUTs Warmup"].roads[42].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[43] = {}
routes["DeactivatingBUTs Warmup"].roads[43].road = "highway01_15 AI Road 58"
routes["DeactivatingBUTs Warmup"].roads[43].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[44] = {}
routes["DeactivatingBUTs Warmup"].roads[44].road = "highway01_15 AI Road 59"
routes["DeactivatingBUTs Warmup"].roads[44].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[45] = {}
routes["DeactivatingBUTs Warmup"].roads[45].road = "highway01_15 AI Road 60"
routes["DeactivatingBUTs Warmup"].roads[45].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[46] = {}
routes["DeactivatingBUTs Warmup"].roads[46].road = "highway01_15 AI Road 61"
routes["DeactivatingBUTs Warmup"].roads[46].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[47] = {}
routes["DeactivatingBUTs Warmup"].roads[47].road = "highway01_15 AI Road 62"
routes["DeactivatingBUTs Warmup"].roads[47].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[48] = {}
routes["DeactivatingBUTs Warmup"].roads[48].road = "superhighway_split_03 AI Road 6"
routes["DeactivatingBUTs Warmup"].roads[48].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[49] = {}
routes["DeactivatingBUTs Warmup"].roads[49].road = "superhighway_split_03 AI Road 5"
routes["DeactivatingBUTs Warmup"].roads[49].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[50] = {}
routes["DeactivatingBUTs Warmup"].roads[50].road = "superhighway_split_03 AI Road 4"
routes["DeactivatingBUTs Warmup"].roads[50].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[51] = {}
routes["DeactivatingBUTs Warmup"].roads[51].road = "superhighway_split_03 AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[51].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[52] = {}
routes["DeactivatingBUTs Warmup"].roads[52].road = "superhighway_split_03 AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[52].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[53] = {}
routes["DeactivatingBUTs Warmup"].roads[53].road = "superhighway_split_03 AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[53].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[54] = {}
routes["DeactivatingBUTs Warmup"].roads[54].road = "superhighway_split_03 AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[54].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[55] = {}
routes["DeactivatingBUTs Warmup"].roads[55].road = "superhighway_road_01 AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[55].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[56] = {}
routes["DeactivatingBUTs Warmup"].roads[56].road = "superhighway_road_01 AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[56].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[57] = {}
routes["DeactivatingBUTs Warmup"].roads[57].road = "superhighway_road_01 AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[57].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[58] = {}
routes["DeactivatingBUTs Warmup"].roads[58].road = "superhighway_road_01 AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[58].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[59] = {}
routes["DeactivatingBUTs Warmup"].roads[59].road = "superhighway_road_01 AI Road 4"
routes["DeactivatingBUTs Warmup"].roads[59].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[60] = {}
routes["DeactivatingBUTs Warmup"].roads[60].road = "superhighway_road_01 AI Road 5"
routes["DeactivatingBUTs Warmup"].roads[60].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[61] = {}
routes["DeactivatingBUTs Warmup"].roads[61].road = "superhighway_road_01 AI Road 6"
routes["DeactivatingBUTs Warmup"].roads[61].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[62] = {}
routes["DeactivatingBUTs Warmup"].roads[62].road = "superhighway_split_01 AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[62].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[63] = {}
routes["DeactivatingBUTs Warmup"].roads[63].road = "superhighway_split_01 AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[63].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[64] = {}
routes["DeactivatingBUTs Warmup"].roads[64].road = "superhighway_split_01 AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[64].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[65] = {}
routes["DeactivatingBUTs Warmup"].roads[65].road = "superhighway_split_01 AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[65].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[66] = {}
routes["DeactivatingBUTs Warmup"].roads[66].road = "highway01_16b AI Road 29"
routes["DeactivatingBUTs Warmup"].roads[66].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[67] = {}
routes["DeactivatingBUTs Warmup"].roads[67].road = "highway01_16b AI Road 28"
routes["DeactivatingBUTs Warmup"].roads[67].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[68] = {}
routes["DeactivatingBUTs Warmup"].roads[68].road = "highway01_16b AI Road 27"
routes["DeactivatingBUTs Warmup"].roads[68].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[69] = {}
routes["DeactivatingBUTs Warmup"].roads[69].road = "highway01_16b AI Road 26"
routes["DeactivatingBUTs Warmup"].roads[69].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[70] = {}
routes["DeactivatingBUTs Warmup"].roads[70].road = "highway01_16b AI Road 25"
routes["DeactivatingBUTs Warmup"].roads[70].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[71] = {}
routes["DeactivatingBUTs Warmup"].roads[71].road = "highway01_16b AI Road 24"
routes["DeactivatingBUTs Warmup"].roads[71].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[72] = {}
routes["DeactivatingBUTs Warmup"].roads[72].road = "highway01_16b AI Road 23"
routes["DeactivatingBUTs Warmup"].roads[72].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[73] = {}
routes["DeactivatingBUTs Warmup"].roads[73].road = "highway01_16b AI Road 22"
routes["DeactivatingBUTs Warmup"].roads[73].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[74] = {}
routes["DeactivatingBUTs Warmup"].roads[74].road = "highway01_16b AI Road 21"
routes["DeactivatingBUTs Warmup"].roads[74].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[75] = {}
routes["DeactivatingBUTs Warmup"].roads[75].road = "highway01_16b AI Road 20"
routes["DeactivatingBUTs Warmup"].roads[75].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[76] = {}
routes["DeactivatingBUTs Warmup"].roads[76].road = "highway01_16b AI Road 19"
routes["DeactivatingBUTs Warmup"].roads[76].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[77] = {}
routes["DeactivatingBUTs Warmup"].roads[77].road = "highway01_16b AI Road 18"
routes["DeactivatingBUTs Warmup"].roads[77].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[78] = {}
routes["DeactivatingBUTs Warmup"].roads[78].road = "highway01_16b AI Road 17"
routes["DeactivatingBUTs Warmup"].roads[78].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[79] = {}
routes["DeactivatingBUTs Warmup"].roads[79].road = "highway01_16b AI Road 16"
routes["DeactivatingBUTs Warmup"].roads[79].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[80] = {}
routes["DeactivatingBUTs Warmup"].roads[80].road = "highway01_16b AI Road 15"
routes["DeactivatingBUTs Warmup"].roads[80].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[81] = {}
routes["DeactivatingBUTs Warmup"].roads[81].road = "highway01_16b AI Road 14"
routes["DeactivatingBUTs Warmup"].roads[81].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[82] = {}
routes["DeactivatingBUTs Warmup"].roads[82].road = "highway01_16b AI Road 13"
routes["DeactivatingBUTs Warmup"].roads[82].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[83] = {}
routes["DeactivatingBUTs Warmup"].roads[83].road = "highway01_16b AI Road 12"
routes["DeactivatingBUTs Warmup"].roads[83].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[84] = {}
routes["DeactivatingBUTs Warmup"].roads[84].road = "highway01_16b AI Road 11"
routes["DeactivatingBUTs Warmup"].roads[84].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[85] = {}
routes["DeactivatingBUTs Warmup"].roads[85].road = "highway01_16b AI Road 10"
routes["DeactivatingBUTs Warmup"].roads[85].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[86] = {}
routes["DeactivatingBUTs Warmup"].roads[86].road = "highway01_16b AI Road 9"
routes["DeactivatingBUTs Warmup"].roads[86].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[87] = {}
routes["DeactivatingBUTs Warmup"].roads[87].road = "highway01_16b AI Road 8"
routes["DeactivatingBUTs Warmup"].roads[87].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[88] = {}
routes["DeactivatingBUTs Warmup"].roads[88].road = "highway01_16b AI Road 7"
routes["DeactivatingBUTs Warmup"].roads[88].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[89] = {}
routes["DeactivatingBUTs Warmup"].roads[89].road = "highway01_16b AI Road 6"
routes["DeactivatingBUTs Warmup"].roads[89].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[90] = {}
routes["DeactivatingBUTs Warmup"].roads[90].road = "highway01_16b AI Road 5"
routes["DeactivatingBUTs Warmup"].roads[90].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[91] = {}
routes["DeactivatingBUTs Warmup"].roads[91].road = "highway01_16b AI Road 4"
routes["DeactivatingBUTs Warmup"].roads[91].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[92] = {}
routes["DeactivatingBUTs Warmup"].roads[92].road = "highway01_16b AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[92].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[93] = {}
routes["DeactivatingBUTs Warmup"].roads[93].road = "highway01_16b AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[93].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[94] = {}
routes["DeactivatingBUTs Warmup"].roads[94].road = "highway01_16b AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[94].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[95] = {}
routes["DeactivatingBUTs Warmup"].roads[95].road = "highway01_16b AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[95].direction = "against"
routes["DeactivatingBUTs Warmup"].roads[96] = {}
routes["DeactivatingBUTs Warmup"].roads[96].road = "highway_split_sanfran_01 AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[96].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[97] = {}
routes["DeactivatingBUTs Warmup"].roads[97].road = "highway_split_sanfran_01 AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[97].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[98] = {}
routes["DeactivatingBUTs Warmup"].roads[98].road = "highway_split_sanfran_01 AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[98].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[99] = {}
routes["DeactivatingBUTs Warmup"].roads[99].road = "highway_split_sanfran_01 AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[99].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[100] = {}
routes["DeactivatingBUTs Warmup"].roads[100].road = "highway_split_sanfran_01 AI Road 4"
routes["DeactivatingBUTs Warmup"].roads[100].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[101] = {}
routes["DeactivatingBUTs Warmup"].roads[101].road = "highway_split_sanfran_01 AI Road 5"
routes["DeactivatingBUTs Warmup"].roads[101].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[102] = {}
routes["DeactivatingBUTs Warmup"].roads[102].road = "highway01_15 AI Road 0"
routes["DeactivatingBUTs Warmup"].roads[102].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[103] = {}
routes["DeactivatingBUTs Warmup"].roads[103].road = "highway01_15 AI Road 1"
routes["DeactivatingBUTs Warmup"].roads[103].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[104] = {}
routes["DeactivatingBUTs Warmup"].roads[104].road = "highway01_15 AI Road 2"
routes["DeactivatingBUTs Warmup"].roads[104].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[105] = {}
routes["DeactivatingBUTs Warmup"].roads[105].road = "highway01_15 AI Road 3"
routes["DeactivatingBUTs Warmup"].roads[105].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[106] = {}
routes["DeactivatingBUTs Warmup"].roads[106].road = "highway01_15 AI Road 4"
routes["DeactivatingBUTs Warmup"].roads[106].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[107] = {}
routes["DeactivatingBUTs Warmup"].roads[107].road = "highway01_15 AI Road 5"
routes["DeactivatingBUTs Warmup"].roads[107].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[108] = {}
routes["DeactivatingBUTs Warmup"].roads[108].road = "highway01_15 AI Road 6"
routes["DeactivatingBUTs Warmup"].roads[108].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[109] = {}
routes["DeactivatingBUTs Warmup"].roads[109].road = "highway01_15 AI Road 7"
routes["DeactivatingBUTs Warmup"].roads[109].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[110] = {}
routes["DeactivatingBUTs Warmup"].roads[110].road = "highway01_15 AI Road 8"
routes["DeactivatingBUTs Warmup"].roads[110].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[111] = {}
routes["DeactivatingBUTs Warmup"].roads[111].road = "highway01_15 AI Road 9"
routes["DeactivatingBUTs Warmup"].roads[111].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[112] = {}
routes["DeactivatingBUTs Warmup"].roads[112].road = "highway01_15 AI Road 10"
routes["DeactivatingBUTs Warmup"].roads[112].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[113] = {}
routes["DeactivatingBUTs Warmup"].roads[113].road = "highway01_15 AI Road 11"
routes["DeactivatingBUTs Warmup"].roads[113].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[114] = {}
routes["DeactivatingBUTs Warmup"].roads[114].road = "highway01_15 AI Road 12"
routes["DeactivatingBUTs Warmup"].roads[114].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[115] = {}
routes["DeactivatingBUTs Warmup"].roads[115].road = "highway01_15 AI Road 13"
routes["DeactivatingBUTs Warmup"].roads[115].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[116] = {}
routes["DeactivatingBUTs Warmup"].roads[116].road = "highway01_15 AI Road 14"
routes["DeactivatingBUTs Warmup"].roads[116].direction = "with"
routes["DeactivatingBUTs Warmup"].roads[117] = {}
routes["DeactivatingBUTs Warmup"].roads[117].road = "highway01_15 AI Road 15"
routes["DeactivatingBUTs Warmup"].roads[117].direction = "with"
