routes = routes or {}
routes["Something weird ambulance 2"] = {}
routes["Something weird ambulance 2"].checkpoints = {}
routes["Something weird ambulance 2"].checkpoints[1] = {}
routes["Something weird ambulance 2"].checkpoints[1].position = vec.vector(699.6967, 10.51714, 112.3999, 1)
routes["Something weird ambulance 2"].checkpoints[1].heading = -3.121707
routes["Something weird ambulance 2"].checkpoints[1].roadName = "dt_6l_east_01 AI Road 1"
routes["Something weird ambulance 2"].checkpoints[2] = {}
routes["Something weird ambulance 2"].checkpoints[2].position = vec.vector(594.7241, 10.44529, 10.08117, 1)
routes["Something weird ambulance 2"].checkpoints[2].heading = -1.811527
routes["Something weird ambulance 2"].checkpoints[2].roadName = "dt_4l_east_02 AI Road 2"
routes["Something weird ambulance 2"].checkpoints[3] = {}
routes["Something weird ambulance 2"].checkpoints[3].position = vec.vector(459.3506, 54.88418, 300.7628, 1)
routes["Something weird ambulance 2"].checkpoints[3].heading = 0.3962645
routes["Something weird ambulance 2"].checkpoints[3].roadName = "dt_4l_east_02 AI Road 0"
routes["Something weird ambulance 2"].checkpoints[4] = {}
routes["Something weird ambulance 2"].checkpoints[4].position = vec.vector(590.8164, 30.87439, 612.0062, 1)
routes["Something weird ambulance 2"].checkpoints[4].heading = -0.2244066
routes["Something weird ambulance 2"].checkpoints[4].roadName = "dt_shortcut_01 AI Road 0"
routes["Something weird ambulance 2"].checkpoints[5] = {}
routes["Something weird ambulance 2"].checkpoints[5].position = vec.vector(493.1945, 17.24477, 957.8899, 1)
routes["Something weird ambulance 2"].checkpoints[5].heading = -1.441156
routes["Something weird ambulance 2"].checkpoints[5].roadName = "dt_10l_south_01 AI Road 1"
routes["Something weird ambulance 2"].checkpoints[6] = {}
routes["Something weird ambulance 2"].checkpoints[6].position = vec.vector(-238.9979, 18, 966.5639, 1)
routes["Something weird ambulance 2"].checkpoints[6].heading = -2.351557
routes["Something weird ambulance 2"].checkpoints[6].roadName = "dt_10l_centre_01 AI Road 7"
routes["Something weird ambulance 2"].checkpoints[7] = {}
routes["Something weird ambulance 2"].checkpoints[7].position = vec.vector(-544.2558, 21.78391, 764.2239, 1)
routes["Something weird ambulance 2"].checkpoints[7].heading = -1.835731
routes["Something weird ambulance 2"].checkpoints[7].roadName = "dt_4l_centre_02 AI Road 0"
routes["Something weird ambulance 2"].checkpoints[8] = {}
routes["Something weird ambulance 2"].checkpoints[8].position = vec.vector(-1025.516, 38.79992, 726.2834, 1)
routes["Something weird ambulance 2"].checkpoints[8].heading = -2.798832
routes["Something weird ambulance 2"].checkpoints[8].roadName = "dt_6l_west_01 AI Road 1"
routes["Something weird ambulance 2"].checkpoints[9] = {}
routes["Something weird ambulance 2"].checkpoints[9].position = vec.vector(-1163.069, 25.3411, 264.6992, 1)
routes["Something weird ambulance 2"].checkpoints[9].heading = 2.757871
routes["Something weird ambulance 2"].checkpoints[9].roadName = "dt_shortcut_09aa AI Road 0"
routes["Something weird ambulance 2"].checkpoints[10] = {}
routes["Something weird ambulance 2"].checkpoints[10].position = vec.vector(-1030.265, 15.37659, 182.6564, 1)
routes["Something weird ambulance 2"].checkpoints[10].heading = 0.7900578
routes["Something weird ambulance 2"].checkpoints[10].roadName = "dt_10l_centre_01 AI Road 1"
routes["Something weird ambulance 2"].checkpoints[11] = {}
routes["Something weird ambulance 2"].checkpoints[11].position = vec.vector(-368.0049, 22.67673, 732.7212, 1)
routes["Something weird ambulance 2"].checkpoints[11].heading = 1.738048
routes["Something weird ambulance 2"].checkpoints[11].roadName = "dt_4l_centre_01 AI Road 0"
routes["Something weird ambulance 2"].checkpoints[12] = {}
routes["Something weird ambulance 2"].checkpoints[12].position = vec.vector(244.9545, 32.77382, 617.7994, 1)
routes["Something weird ambulance 2"].checkpoints[12].heading = 1.771001
routes["Something weird ambulance 2"].checkpoints[12].roadName = "dt_4l_centre_01 AI Road 2"
routes["Something weird ambulance 2"].checkpoints[13] = {}
routes["Something weird ambulance 2"].checkpoints[13].position = vec.vector(400.2463, 21.71985, 887.932, 1)
routes["Something weird ambulance 2"].checkpoints[13].heading = 0.2678262
routes["Something weird ambulance 2"].checkpoints[13].roadName = "dt_8l_centre_02 AI Road 6"
routes["Something weird ambulance 2"].arrows = {}
routes["Something weird ambulance 2"].roads = {}
routes["Something weird ambulance 2"].roads[1] = {}
routes["Something weird ambulance 2"].roads[1].road = "dt_6l_east_01 AI Road 1"
routes["Something weird ambulance 2"].roads[1].direction = "against"
routes["Something weird ambulance 2"].roads[2] = {}
routes["Something weird ambulance 2"].roads[2].road = "dt_4l_east_02 AI Road 2"
routes["Something weird ambulance 2"].roads[2].direction = "against"
routes["Something weird ambulance 2"].roads[3] = {}
routes["Something weird ambulance 2"].roads[3].road = "dt_4l_east_02 AI Road 1"
routes["Something weird ambulance 2"].roads[3].direction = "against"
routes["Something weird ambulance 2"].roads[4] = {}
routes["Something weird ambulance 2"].roads[4].road = "dt_4l_east_02 AI Road 0"
routes["Something weird ambulance 2"].roads[4].direction = "against"
routes["Something weird ambulance 2"].roads[5] = {}
routes["Something weird ambulance 2"].roads[5].road = "dt_4l_east_03 AI Road 0"
routes["Something weird ambulance 2"].roads[5].direction = "with"
routes["Something weird ambulance 2"].roads[6] = {}
routes["Something weird ambulance 2"].roads[6].road = "dt_shortcut_01 AI Road 0"
routes["Something weird ambulance 2"].roads[6].direction = "with"
routes["Something weird ambulance 2"].roads[7] = {}
routes["Something weird ambulance 2"].roads[7].road = "dt_shortcut_01 AI Road 1"
routes["Something weird ambulance 2"].roads[7].direction = "with"
routes["Something weird ambulance 2"].roads[8] = {}
routes["Something weird ambulance 2"].roads[8].road = "dt_10l_south_01 AI Road 1"
routes["Something weird ambulance 2"].roads[8].direction = "with"
routes["Something weird ambulance 2"].roads[9] = {}
routes["Something weird ambulance 2"].roads[9].road = "dt_10l_south_01 AI Road 2"
routes["Something weird ambulance 2"].roads[9].direction = "with"
routes["Something weird ambulance 2"].roads[10] = {}
routes["Something weird ambulance 2"].roads[10].road = "dt_10l_south_01 AI Road 3"
routes["Something weird ambulance 2"].roads[10].direction = "with"
routes["Something weird ambulance 2"].roads[11] = {}
routes["Something weird ambulance 2"].roads[11].road = "dt_10l_south_01 AI Road 4"
routes["Something weird ambulance 2"].roads[11].direction = "with"
routes["Something weird ambulance 2"].roads[12] = {}
routes["Something weird ambulance 2"].roads[12].road = "dt_10l_centre_01 AI Road 7"
routes["Something weird ambulance 2"].roads[12].direction = "against"
routes["Something weird ambulance 2"].roads[13] = {}
routes["Something weird ambulance 2"].roads[13].road = "dt_10l_centre_01 AI Road 6"
routes["Something weird ambulance 2"].roads[13].direction = "against"
routes["Something weird ambulance 2"].roads[14] = {}
routes["Something weird ambulance 2"].roads[14].road = "dt_10l_centre_01 AI Road 5"
routes["Something weird ambulance 2"].roads[14].direction = "against"
routes["Something weird ambulance 2"].roads[15] = {}
routes["Something weird ambulance 2"].roads[15].road = "dt_4l_centre_02 AI Road 0"
routes["Something weird ambulance 2"].roads[15].direction = "against"
routes["Something weird ambulance 2"].roads[16] = {}
routes["Something weird ambulance 2"].roads[16].road = "dt_4l_centre_03 AI Road 1"
routes["Something weird ambulance 2"].roads[16].direction = "against"
routes["Something weird ambulance 2"].roads[17] = {}
routes["Something weird ambulance 2"].roads[17].road = "dt_4l_centre_03 AI Road 0"
routes["Something weird ambulance 2"].roads[17].direction = "against"
routes["Something weird ambulance 2"].roads[18] = {}
routes["Something weird ambulance 2"].roads[18].road = "dt_6l_west_01 AI Road 1"
routes["Something weird ambulance 2"].roads[18].direction = "against"
routes["Something weird ambulance 2"].roads[19] = {}
routes["Something weird ambulance 2"].roads[19].road = "dt_6l_west_01 AI Road 0"
routes["Something weird ambulance 2"].roads[19].direction = "against"
routes["Something weird ambulance 2"].roads[20] = {}
routes["Something weird ambulance 2"].roads[20].road = "dt_shortcut_09aa AI Road 0"
routes["Something weird ambulance 2"].roads[20].direction = "with"
routes["Something weird ambulance 2"].roads[21] = {}
routes["Something weird ambulance 2"].roads[21].road = "dt_10l_centre_01 AI Road 1"
routes["Something weird ambulance 2"].roads[21].direction = "with"
routes["Something weird ambulance 2"].roads[22] = {}
routes["Something weird ambulance 2"].roads[22].road = "dt_10l_centre_01 AI Road 2"
routes["Something weird ambulance 2"].roads[22].direction = "with"
routes["Something weird ambulance 2"].roads[23] = {}
routes["Something weird ambulance 2"].roads[23].road = "dt_10l_centre_01 AI Road 3"
routes["Something weird ambulance 2"].roads[23].direction = "with"
routes["Something weird ambulance 2"].roads[24] = {}
routes["Something weird ambulance 2"].roads[24].road = "dt_10l_centre_01 AI Road 4"
routes["Something weird ambulance 2"].roads[24].direction = "with"
routes["Something weird ambulance 2"].roads[25] = {}
routes["Something weird ambulance 2"].roads[25].road = "dt_4l_centre_01 AI Road 0"
routes["Something weird ambulance 2"].roads[25].direction = "with"
routes["Something weird ambulance 2"].roads[26] = {}
routes["Something weird ambulance 2"].roads[26].road = "dt_4l_centre_01 AI Road 1"
routes["Something weird ambulance 2"].roads[26].direction = "with"
routes["Something weird ambulance 2"].roads[27] = {}
routes["Something weird ambulance 2"].roads[27].road = "dt_4l_centre_01 AI Road 2"
routes["Something weird ambulance 2"].roads[27].direction = "with"
routes["Something weird ambulance 2"].roads[28] = {}
routes["Something weird ambulance 2"].roads[28].road = "dt_8l_centre_02 AI Road 5"
routes["Something weird ambulance 2"].roads[28].direction = "with"
routes["Something weird ambulance 2"].roads[29] = {}
routes["Something weird ambulance 2"].roads[29].road = "dt_8l_centre_02 AI Road 6"
routes["Something weird ambulance 2"].roads[29].direction = "with"
