routes = routes or {}
routes.TestActivityRoute = {}
routes.TestActivityRoute.checkpoints = {}
routes.TestActivityRoute.checkpoints[1] = {}
routes.TestActivityRoute.checkpoints[1].position = vec.vector(-52.96608, 18, 1021.72, 1)
routes.TestActivityRoute.checkpoints[1].heading = 1.676382
routes.TestActivityRoute.checkpoints[1].roadName = "dt_10l_south_01 AI Road 4"
routes.TestActivityRoute.checkpoints[1].roadWidth = 44
routes.TestActivityRoute.checkpoints[1].distance = 88.68248
routes.TestActivityRoute.checkpoints[2] = {}
routes.TestActivityRoute.checkpoints[2].position = vec.vector(295.0692, 17.8192, 980.558, 1)
routes.TestActivityRoute.checkpoints[2].heading = 1.688793
routes.TestActivityRoute.checkpoints[2].roadName = "dt_10l_south_01 AI Road 2"
routes.TestActivityRoute.checkpoints[2].roadWidth = 44
routes.TestActivityRoute.checkpoints[2].distance = 438.0073
routes.TestActivityRoute.checkpoints[3] = {}
routes.TestActivityRoute.checkpoints[3].position = vec.vector(393.534, 27.17162, 863.1614, 1)
routes.TestActivityRoute.checkpoints[3].heading = -2.879113
routes.TestActivityRoute.checkpoints[3].roadName = "dt_8l_centre_02 AI Road 6"
routes.TestActivityRoute.checkpoints[3].roadWidth = 36
routes.TestActivityRoute.checkpoints[3].distance = 648.6918
routes.TestActivityRoute.checkpoints[4] = {}
routes.TestActivityRoute.checkpoints[4].position = vec.vector(14.1181, 40.07909, 832.175, 1)
routes.TestActivityRoute.checkpoints[4].heading = -1.388331
routes.TestActivityRoute.checkpoints[4].roadName = "dt_6l_centre_03 AI Road 1"
routes.TestActivityRoute.checkpoints[4].roadWidth = 36
routes.TestActivityRoute.checkpoints[4].distance = 1093.886
routes.TestActivityRoute.checkpoints[5] = {}
routes.TestActivityRoute.checkpoints[5].position = vec.vector(-102.9213, 28.26626, 945.0457, 1)
routes.TestActivityRoute.checkpoints[5].heading = -0.846872
routes.TestActivityRoute.checkpoints[5].roadName = "dt_shortcut_08 AI Road 0"
routes.TestActivityRoute.checkpoints[5].roadWidth = 14
routes.TestActivityRoute.checkpoints[5].distance = 1274.933
routes.TestActivityRoute.arrows = {}
routes.TestActivityRoute.roads = {}
routes.TestActivityRoute.roads[1] = {}
routes.TestActivityRoute.roads[1].road = "dt_10l_south_01 AI Road 4"
routes.TestActivityRoute.roads[1].direction = "against"
routes.TestActivityRoute.roads[2] = {}
routes.TestActivityRoute.roads[2].road = "dt_10l_south_01 AI Road 3"
routes.TestActivityRoute.roads[2].direction = "against"
routes.TestActivityRoute.roads[3] = {}
routes.TestActivityRoute.roads[3].road = "dt_10l_south_01 AI Road 2"
routes.TestActivityRoute.roads[3].direction = "against"
routes.TestActivityRoute.roads[4] = {}
routes.TestActivityRoute.roads[4].road = "dt_8l_centre_02 AI Road 6"
routes.TestActivityRoute.roads[4].direction = "against"
routes.TestActivityRoute.roads[5] = {}
routes.TestActivityRoute.roads[5].road = "dt_6l_centre_03 AI Road 2"
routes.TestActivityRoute.roads[5].direction = "against"
routes.TestActivityRoute.roads[6] = {}
routes.TestActivityRoute.roads[6].road = "dt_6l_centre_03 AI Road 1"
routes.TestActivityRoute.roads[6].direction = "against"
routes.TestActivityRoute.roads[7] = {}
routes.TestActivityRoute.roads[7].road = "dt_shortcut_08 AI Road 0"
routes.TestActivityRoute.roads[7].direction = "with"
