routes = routes or {}
routes.HotCarRoute2 = {}
routes.HotCarRoute2.checkpoints = {}
routes.HotCarRoute2.checkpoints[1] = {}
routes.HotCarRoute2.checkpoints[1].position = vec.vector(-3689.092, 32.45548, 1579.981, 1)
routes.HotCarRoute2.checkpoints[1].heading = 1.922144
routes.HotCarRoute2.checkpoints[1].roadName = "ggp_4l_sw_06 AI Road 0"
routes.HotCarRoute2.checkpoints[2] = {}
routes.HotCarRoute2.checkpoints[2].position = vec.vector(-3524.838, 54.75076, 1326.205, 1)
routes.HotCarRoute2.checkpoints[2].heading = -1.616036
routes.HotCarRoute2.checkpoints[2].roadName = "ggp_10l_centre_01 AI Road 3"
routes.HotCarRoute2.checkpoints[3] = {}
routes.HotCarRoute2.checkpoints[3].position = vec.vector(-3869.75, 40.234, 1468.937, 1)
routes.HotCarRoute2.checkpoints[3].heading = 0.5614926
routes.HotCarRoute2.checkpoints[3].roadName = "ggp_6l_west_01 AI Road 0"
routes.HotCarRoute2.arrows = {}
routes.HotCarRoute2.roads = {}
routes.HotCarRoute2.roads[1] = {}
routes.HotCarRoute2.roads[1].road = "ggp_4l_sw_06 AI Road 0"
routes.HotCarRoute2.roads[1].direction = "with"
routes.HotCarRoute2.roads[2] = {}
routes.HotCarRoute2.roads[2].road = "ggp_8l_centre_02 AI Road 1"
routes.HotCarRoute2.roads[2].direction = "against"
routes.HotCarRoute2.roads[3] = {}
routes.HotCarRoute2.roads[3].road = "gg_shortcut_10 AI Road 0"
routes.HotCarRoute2.roads[3].direction = "against"
routes.HotCarRoute2.roads[4] = {}
routes.HotCarRoute2.roads[4].road = "ggp_10l_centre_01 AI Road 3"
routes.HotCarRoute2.roads[4].direction = "against"
routes.HotCarRoute2.roads[5] = {}
routes.HotCarRoute2.roads[5].road = "ggp_10l_centre_01 AI Road 2"
routes.HotCarRoute2.roads[5].direction = "against"
routes.HotCarRoute2.roads[6] = {}
routes.HotCarRoute2.roads[6].road = "ggp_6l_west_01 AI Road 0"
routes.HotCarRoute2.roads[6].direction = "with"
routes.HotCarRoute3 = {}
routes.HotCarRoute3.checkpoints = {}
routes.HotCarRoute3.checkpoints[1] = {}
routes.HotCarRoute3.checkpoints[1].position = vec.vector(-1280.838, 45.81352, 1084.124, 1)
routes.HotCarRoute3.checkpoints[1].heading = 0.1060587
routes.HotCarRoute3.checkpoints[1].roadName = "dt_8l_centre_01ab AI Road 7"
routes.HotCarRoute3.checkpoints[2] = {}
routes.HotCarRoute3.checkpoints[2].position = vec.vector(-949.6014, 40.75, 1127.588, 1)
routes.HotCarRoute3.checkpoints[2].heading = 1.692095
routes.HotCarRoute3.checkpoints[2].roadName = "dt_10l_south_01 AI Road 11"
routes.HotCarRoute3.checkpoints[3] = {}
routes.HotCarRoute3.checkpoints[3].position = vec.vector(-1294.172, 42.375, 951.5422, 1)
routes.HotCarRoute3.checkpoints[3].heading = 0.09261003
routes.HotCarRoute3.checkpoints[3].roadName = "dt_8l_centre_01ab AI Road 6"
routes.HotCarRoute3.arrows = {}
routes.HotCarRoute3.roads = {}
routes.HotCarRoute3.roads[1] = {}
routes.HotCarRoute3.roads[1].road = "dt_8l_centre_01ab AI Road 7"
routes.HotCarRoute3.roads[1].direction = "with"
routes.HotCarRoute3.roads[2] = {}
routes.HotCarRoute3.roads[2].road = "dt_10l_south_01 AI Road 12"
routes.HotCarRoute3.roads[2].direction = "against"
routes.HotCarRoute3.roads[3] = {}
routes.HotCarRoute3.roads[3].road = "dt_10l_south_01 AI Road 11"
routes.HotCarRoute3.roads[3].direction = "against"
routes.HotCarRoute3.roads[4] = {}
routes.HotCarRoute3.roads[4].road = "dt_shortcut_12a AI Road 0"
routes.HotCarRoute3.roads[4].direction = "against"
routes.HotCarRoute3.roads[5] = {}
routes.HotCarRoute3.roads[5].road = "dt_6l_west_01 AI Road 2"
routes.HotCarRoute3.roads[5].direction = "against"
routes.HotCarRoute3.roads[6] = {}
routes.HotCarRoute3.roads[6].road = "dt_4l_west_07 AI Road 1"
routes.HotCarRoute3.roads[6].direction = "against"
routes.HotCarRoute3.roads[7] = {}
routes.HotCarRoute3.roads[7].road = "dt_4l_west_07 AI Road 0"
routes.HotCarRoute3.roads[7].direction = "against"
routes.HotCarRoute3.roads[8] = {}
routes.HotCarRoute3.roads[8].road = "dt_8l_centre_01ab AI Road 6"
routes.HotCarRoute3.roads[8].direction = "with"
routes.HotCarRoute4 = {}
routes.HotCarRoute4.checkpoints = {}
routes.HotCarRoute4.checkpoints[1] = {}
routes.HotCarRoute4.checkpoints[1].position = vec.vector(1820, 27.75, -3359.621, 1)
routes.HotCarRoute4.checkpoints[1].heading = 0
routes.HotCarRoute4.checkpoints[1].roadName = "mountain_6l_east_01 AI Road 5"
routes.HotCarRoute4.checkpoints[2] = {}
routes.HotCarRoute4.checkpoints[2].position = vec.vector(1345, 25.67848, -3304.707, 1)
routes.HotCarRoute4.checkpoints[2].heading = 3.141593
routes.HotCarRoute4.checkpoints[2].roadName = "marin_4l_east_01 AI Road 1"
routes.HotCarRoute4.checkpoints[3] = {}
routes.HotCarRoute4.checkpoints[3].position = vec.vector(1765.926, 27.75, -3455, 1)
routes.HotCarRoute4.checkpoints[3].heading = 1.570796
routes.HotCarRoute4.checkpoints[3].roadName = "marin_4l_east_06 AI Road 1"
routes.HotCarRoute4.arrows = {}
routes.HotCarRoute4.roads = {}
routes.HotCarRoute4.roads[1] = {}
routes.HotCarRoute4.roads[1].road = "mountain_6l_east_01 AI Road 5"
routes.HotCarRoute4.roads[1].direction = "with"
routes.HotCarRoute4.roads[2] = {}
routes.HotCarRoute4.roads[2].road = "mountain_6l_east_01 AI Road 6"
routes.HotCarRoute4.roads[2].direction = "with"
routes.HotCarRoute4.roads[3] = {}
routes.HotCarRoute4.roads[3].road = "marin_4l_east_01 AI Road 1"
routes.HotCarRoute4.roads[3].direction = "against"
routes.HotCarRoute4.roads[4] = {}
routes.HotCarRoute4.roads[4].road = "marin_4l_east_06 AI Road 0"
routes.HotCarRoute4.roads[4].direction = "with"
routes.HotCarRoute4.roads[5] = {}
routes.HotCarRoute4.roads[5].road = "marin_4l_east_06 AI Road 1"
routes.HotCarRoute4.roads[5].direction = "with"
routes.HotCarRoute1 = {}
routes.HotCarRoute1.checkpoints = {}
routes.HotCarRoute1.checkpoints[1] = {}
routes.HotCarRoute1.checkpoints[1].position = vec.vector(-2353.967, 171.5767, 3702.291, 1)
routes.HotCarRoute1.checkpoints[1].heading = -0.8529672
routes.HotCarRoute1.checkpoints[1].roadName = "sutro_1l_south_02 AI Road 0"
routes.HotCarRoute1.checkpoints[2] = {}
routes.HotCarRoute1.checkpoints[2].position = vec.vector(-2888.7, 125.4117, 3634.868, 1)
routes.HotCarRoute1.checkpoints[2].heading = -1.810397
routes.HotCarRoute1.checkpoints[2].roadName = "sutro_west_03 AI Road 5"
routes.HotCarRoute1.checkpoints[3] = {}
routes.HotCarRoute1.checkpoints[3].position = vec.vector(-2690.478, 145.1398, 3757.553, 1)
routes.HotCarRoute1.checkpoints[3].heading = 1.299189
routes.HotCarRoute1.checkpoints[3].roadName = "sutro_shortcut_26 AI Road 2"
routes.HotCarRoute1.checkpoints[4] = {}
routes.HotCarRoute1.checkpoints[4].position = vec.vector(-2252.385, 177.2516, 3800.961, 1)
routes.HotCarRoute1.checkpoints[4].heading = 1.760267
routes.HotCarRoute1.checkpoints[4].roadName = "sutro_shortcut_26 AI Road 3"
routes.HotCarRoute1.checkpoints[5] = {}
routes.HotCarRoute1.checkpoints[5].position = vec.vector(-2226.24, 177.25, 3670.765, 1)
routes.HotCarRoute1.checkpoints[5].heading = -2.331898
routes.HotCarRoute1.checkpoints[5].roadName = "sutro_6l_south_01a AI Road 3"
routes.HotCarRoute1.arrows = {}
routes.HotCarRoute1.roads = {}
routes.HotCarRoute1.roads[1] = {}
routes.HotCarRoute1.roads[1].road = "sutro_1l_south_02 AI Road 0"
routes.HotCarRoute1.roads[1].direction = "with"
routes.HotCarRoute1.roads[2] = {}
routes.HotCarRoute1.roads[2].road = "sutro_1l_south_02 AI Road 1"
routes.HotCarRoute1.roads[2].direction = "with"
routes.HotCarRoute1.roads[3] = {}
routes.HotCarRoute1.roads[3].road = "sutro_west_03 AI Road 5"
routes.HotCarRoute1.roads[3].direction = "with"
routes.HotCarRoute1.roads[4] = {}
routes.HotCarRoute1.roads[4].road = "sutro_shortcut_26 AI Road 2"
routes.HotCarRoute1.roads[4].direction = "with"
routes.HotCarRoute1.roads[5] = {}
routes.HotCarRoute1.roads[5].road = "sutro_shortcut_26 AI Road 3"
routes.HotCarRoute1.roads[5].direction = "with"
routes.HotCarRoute1.roads[6] = {}
routes.HotCarRoute1.roads[6].road = "sutro_6l_south_01a AI Road 3"
routes.HotCarRoute1.roads[6].direction = "against"
routes.GoneWarmupRoute = {}
routes.GoneWarmupRoute.checkpoints = {}
routes.GoneWarmupRoute.checkpoints[1] = {}
routes.GoneWarmupRoute.checkpoints[1].position = vec.vector(-1142.511, 24.5003, -2891.705, 1)
routes.GoneWarmupRoute.checkpoints[1].heading = -0.8042442
routes.GoneWarmupRoute.checkpoints[1].roadName = "mountain_10l_w_01b AI Road 30"
routes.GoneWarmupRoute.checkpoints[2] = {}
routes.GoneWarmupRoute.checkpoints[2].position = vec.vector(-2150.245, 8.301941, -2350.534, 1)
routes.GoneWarmupRoute.checkpoints[2].heading = -1.348916
routes.GoneWarmupRoute.checkpoints[2].roadName = "marin_shortcut_02 AI Road 0"
routes.GoneWarmupRoute.checkpoints[3] = {}
routes.GoneWarmupRoute.checkpoints[3].position = vec.vector(-2190.504, 68.4055, -2789.705, 1)
routes.GoneWarmupRoute.checkpoints[3].heading = 2.238328
routes.GoneWarmupRoute.checkpoints[3].roadName = "marin_4l_west_02 AI Road 17"
routes.GoneWarmupRoute.checkpoints[4] = {}
routes.GoneWarmupRoute.checkpoints[4].position = vec.vector(-1808.743, 52.51534, -3064.79, 1)
routes.GoneWarmupRoute.checkpoints[4].heading = 1.967902
routes.GoneWarmupRoute.checkpoints[4].roadName = "marin_shortcut_42 AI Road 0"
routes.GoneWarmupRoute.checkpoints[5] = {}
routes.GoneWarmupRoute.checkpoints[5].position = vec.vector(-1167.954, 26.06076, -2995.195, 1)
routes.GoneWarmupRoute.checkpoints[5].heading = 0.7915384
routes.GoneWarmupRoute.checkpoints[5].roadName = "mountain_6l_west_01 AI Road 4"
routes.GoneWarmupRoute.arrows = {}
routes.GoneWarmupRoute.roads = {}
routes.GoneWarmupRoute.roads[1] = {}
routes.GoneWarmupRoute.roads[1].road = "mountain_10l_w_01b AI Road 30"
routes.GoneWarmupRoute.roads[1].direction = "with"
routes.GoneWarmupRoute.roads[2] = {}
routes.GoneWarmupRoute.roads[2].road = "mountain_10l_w_01b AI Road 31"
routes.GoneWarmupRoute.roads[2].direction = "with"
routes.GoneWarmupRoute.roads[3] = {}
routes.GoneWarmupRoute.roads[3].road = "mountain_10l_w_01b AI Road 32"
routes.GoneWarmupRoute.roads[3].direction = "with"
routes.GoneWarmupRoute.roads[4] = {}
routes.GoneWarmupRoute.roads[4].road = "mountain_10l_w_01b AI Road 33"
routes.GoneWarmupRoute.roads[4].direction = "with"
routes.GoneWarmupRoute.roads[5] = {}
routes.GoneWarmupRoute.roads[5].road = "mountain_10l_w_01b AI Road 34"
routes.GoneWarmupRoute.roads[5].direction = "with"
routes.GoneWarmupRoute.roads[6] = {}
routes.GoneWarmupRoute.roads[6].road = "mountain_10l_w_01b AI Road 35"
routes.GoneWarmupRoute.roads[6].direction = "with"
routes.GoneWarmupRoute.roads[7] = {}
routes.GoneWarmupRoute.roads[7].road = "mountain_10l_w_01b AI Road 36"
routes.GoneWarmupRoute.roads[7].direction = "with"
routes.GoneWarmupRoute.roads[8] = {}
routes.GoneWarmupRoute.roads[8].road = "mountain_10l_w_01b AI Road 37"
routes.GoneWarmupRoute.roads[8].direction = "with"
routes.GoneWarmupRoute.roads[9] = {}
routes.GoneWarmupRoute.roads[9].road = "mountain_10l_w_06 AI Road 15"
routes.GoneWarmupRoute.roads[9].direction = "against"
routes.GoneWarmupRoute.roads[10] = {}
routes.GoneWarmupRoute.roads[10].road = "marin_shortcut_02 AI Road 0"
routes.GoneWarmupRoute.roads[10].direction = "against"
routes.GoneWarmupRoute.roads[11] = {}
routes.GoneWarmupRoute.roads[11].road = "marin_4l_west_02 AI Road 17"
routes.GoneWarmupRoute.roads[11].direction = "with"
routes.GoneWarmupRoute.roads[12] = {}
routes.GoneWarmupRoute.roads[12].road = "marin_shortcut_42 AI Road 0"
routes.GoneWarmupRoute.roads[12].direction = "with"
routes.GoneWarmupRoute.roads[13] = {}
routes.GoneWarmupRoute.roads[13].road = "mountain_6l_west_01 AI Road 3"
routes.GoneWarmupRoute.roads[13].direction = "with"
routes.GoneWarmupRoute.roads[14] = {}
routes.GoneWarmupRoute.roads[14].road = "mountain_6l_west_01 AI Road 4"
routes.GoneWarmupRoute.roads[14].direction = "with"
