routes = routes or {}
routes.KillTannerWarmupRoute = {}
routes.KillTannerWarmupRoute.checkpoints = {}
routes.KillTannerWarmupRoute.checkpoints[1] = {}
routes.KillTannerWarmupRoute.checkpoints[1].position = vec.vector(-2837.569, 32.81955, -1781.948, 1)
routes.KillTannerWarmupRoute.checkpoints[1].heading = 2.341254
routes.KillTannerWarmupRoute.checkpoints[1].roadName = "ggb_marin_sliproad_02 AI Road 0"
routes.KillTannerWarmupRoute.checkpoints[2] = {}
routes.KillTannerWarmupRoute.checkpoints[2].position = vec.vector(-2453.322, 15.76986, -1739.04, 1)
routes.KillTannerWarmupRoute.checkpoints[2].heading = -0.5230588
routes.KillTannerWarmupRoute.checkpoints[2].roadName = "mountain_10l_w_06 AI Road 12"
routes.KillTannerWarmupRoute.checkpoints[3] = {}
routes.KillTannerWarmupRoute.checkpoints[3].position = vec.vector(-2918.385, 42.31431, -1660.184, 1)
routes.KillTannerWarmupRoute.checkpoints[3].heading = 2.974224
routes.KillTannerWarmupRoute.checkpoints[3].roadName = "highway01_15 AI Road 12"
routes.KillTannerWarmupRoute.arrows = {}
routes.KillTannerWarmupRoute.roads = {}
routes.KillTannerWarmupRoute.roads[1] = {}
routes.KillTannerWarmupRoute.roads[1].road = "ggb_marin_sliproad_02 AI Road 0"
routes.KillTannerWarmupRoute.roads[1].direction = "with"
routes.KillTannerWarmupRoute.roads[2] = {}
routes.KillTannerWarmupRoute.roads[2].road = "mountain_6l_west_02 AI Road 0"
routes.KillTannerWarmupRoute.roads[2].direction = "against"
routes.KillTannerWarmupRoute.roads[3] = {}
routes.KillTannerWarmupRoute.roads[3].road = "mountain_10l_w_06 AI Road 13"
routes.KillTannerWarmupRoute.roads[3].direction = "against"
routes.KillTannerWarmupRoute.roads[4] = {}
routes.KillTannerWarmupRoute.roads[4].road = "mountain_10l_w_06 AI Road 12"
routes.KillTannerWarmupRoute.roads[4].direction = "against"
routes.KillTannerWarmupRoute.roads[5] = {}
routes.KillTannerWarmupRoute.roads[5].road = "mountain_10l_w_06 AI Road 11"
routes.KillTannerWarmupRoute.roads[5].direction = "against"
routes.KillTannerWarmupRoute.roads[6] = {}
routes.KillTannerWarmupRoute.roads[6].road = "ggb_marin_sliproad_04 AI Road 0"
routes.KillTannerWarmupRoute.roads[6].direction = "against"
routes.KillTannerWarmupRoute.roads[7] = {}
routes.KillTannerWarmupRoute.roads[7].road = "highway01_15 AI Road 12"
routes.KillTannerWarmupRoute.roads[7].direction = "with"
