routes = routes or {}
routes["Smash TV warmup"] = {}
routes["Smash TV warmup"].checkpoints = {}
routes["Smash TV warmup"].checkpoints[1] = {}
routes["Smash TV warmup"].checkpoints[1].position = vec.vector(-2962.453, 131.6415, 4129.306, 1)
routes["Smash TV warmup"].checkpoints[1].heading = 2.399892
routes["Smash TV warmup"].checkpoints[1].roadName = "sutro_south_main AI Road 14"
routes["Smash TV warmup"].checkpoints[2] = {}
routes["Smash TV warmup"].checkpoints[2].position = vec.vector(-2944.11, 112.298, 3846.038, 1)
routes["Smash TV warmup"].checkpoints[2].heading = -0.8770453
routes["Smash TV warmup"].checkpoints[2].roadName = "sutro_south_main AI Road 11"
routes["Smash TV warmup"].checkpoints[3] = {}
routes["Smash TV warmup"].checkpoints[3].position = vec.vector(-3428.808, 81.14024, 4115.693, 1)
routes["Smash TV warmup"].checkpoints[3].heading = -1.787083
routes["Smash TV warmup"].checkpoints[3].roadName = "sutro_south_main AI Road 7"
routes["Smash TV warmup"].checkpoints[4] = {}
routes["Smash TV warmup"].checkpoints[4].position = vec.vector(-3836.725, 66.00082, 3917.45, 1)
routes["Smash TV warmup"].checkpoints[4].heading = -2.480639
routes["Smash TV warmup"].checkpoints[4].roadName = "sutro_shortcut_24 AI Road 0"
routes["Smash TV warmup"].checkpoints[5] = {}
routes["Smash TV warmup"].checkpoints[5].position = vec.vector(-4011.056, 35.67612, 3457.019, 1)
routes["Smash TV warmup"].checkpoints[5].heading = 0.8538575
routes["Smash TV warmup"].checkpoints[5].roadName = "sutro_west_03 AI Road 13"
routes["Smash TV warmup"].checkpoints[6] = {}
routes["Smash TV warmup"].checkpoints[6].position = vec.vector(-3370.193, 73.37877, 3919.058, 1)
routes["Smash TV warmup"].checkpoints[6].heading = 1.458202
routes["Smash TV warmup"].checkpoints[6].roadName = "sutro_west_03 AI Road 10"
routes["Smash TV warmup"].checkpoints[7] = {}
routes["Smash TV warmup"].checkpoints[7].position = vec.vector(-3007.723, 121.4471, 3624.781, 1)
routes["Smash TV warmup"].checkpoints[7].heading = 0.4296772
routes["Smash TV warmup"].checkpoints[7].roadName = "sutro_shortcut_26 AI Road 2"
routes["Smash TV warmup"].checkpoints[8] = {}
routes["Smash TV warmup"].checkpoints[8].position = vec.vector(-2264.512, 177.25, 3892.503, 1)
routes["Smash TV warmup"].checkpoints[8].heading = 0.7964017
routes["Smash TV warmup"].checkpoints[8].roadName = "sutro_shortcut_16 AI Road 0"
routes["Smash TV warmup"].checkpoints[9] = {}
routes["Smash TV warmup"].checkpoints[9].position = vec.vector(-2291.876, 181.6188, 4146.5, 1)
routes["Smash TV warmup"].checkpoints[9].heading = -1.7849
routes["Smash TV warmup"].checkpoints[9].roadName = "sutro_south_main AI Road 18"
routes["Smash TV warmup"].checkpoints[10] = {}
routes["Smash TV warmup"].checkpoints[10].position = vec.vector(-2704.774, 163.0921, 4106.666, 1)
routes["Smash TV warmup"].checkpoints[10].heading = -0.2097007
routes["Smash TV warmup"].checkpoints[10].roadName = "sutro_south_main AI Road 16"
routes["Smash TV warmup"].arrows = {}
routes["Smash TV warmup"].roads = {}
routes["Smash TV warmup"].roads[1] = {}
routes["Smash TV warmup"].roads[1].road = "sutro_south_main AI Road 14"
routes["Smash TV warmup"].roads[1].direction = "against"
routes["Smash TV warmup"].roads[2] = {}
routes["Smash TV warmup"].roads[2].road = "sutro_south_main AI Road 13"
routes["Smash TV warmup"].roads[2].direction = "against"
routes["Smash TV warmup"].roads[3] = {}
routes["Smash TV warmup"].roads[3].road = "sutro_south_main AI Road 12"
routes["Smash TV warmup"].roads[3].direction = "against"
routes["Smash TV warmup"].roads[4] = {}
routes["Smash TV warmup"].roads[4].road = "sutro_south_main AI Road 11"
routes["Smash TV warmup"].roads[4].direction = "against"
routes["Smash TV warmup"].roads[5] = {}
routes["Smash TV warmup"].roads[5].road = "sutro_south_main AI Road 10"
routes["Smash TV warmup"].roads[5].direction = "against"
routes["Smash TV warmup"].roads[6] = {}
routes["Smash TV warmup"].roads[6].road = "sutro_south_main AI Road 9"
routes["Smash TV warmup"].roads[6].direction = "against"
routes["Smash TV warmup"].roads[7] = {}
routes["Smash TV warmup"].roads[7].road = "sutro_south_main AI Road 8"
routes["Smash TV warmup"].roads[7].direction = "against"
routes["Smash TV warmup"].roads[8] = {}
routes["Smash TV warmup"].roads[8].road = "sutro_south_main AI Road 7"
routes["Smash TV warmup"].roads[8].direction = "against"
routes["Smash TV warmup"].roads[9] = {}
routes["Smash TV warmup"].roads[9].road = "sutro_south_main AI Road 6"
routes["Smash TV warmup"].roads[9].direction = "against"
routes["Smash TV warmup"].roads[10] = {}
routes["Smash TV warmup"].roads[10].road = "sutro_shortcut_24 AI Road 0"
routes["Smash TV warmup"].roads[10].direction = "with"
routes["Smash TV warmup"].roads[11] = {}
routes["Smash TV warmup"].roads[11].road = "sutro_west_03 AI Road 14"
routes["Smash TV warmup"].roads[11].direction = "against"
routes["Smash TV warmup"].roads[12] = {}
routes["Smash TV warmup"].roads[12].road = "sutro_west_03 AI Road 13"
routes["Smash TV warmup"].roads[12].direction = "against"
routes["Smash TV warmup"].roads[13] = {}
routes["Smash TV warmup"].roads[13].road = "sutro_west_03 AI Road 12"
routes["Smash TV warmup"].roads[13].direction = "against"
routes["Smash TV warmup"].roads[14] = {}
routes["Smash TV warmup"].roads[14].road = "sutro_west_03 AI Road 11"
routes["Smash TV warmup"].roads[14].direction = "against"
routes["Smash TV warmup"].roads[15] = {}
routes["Smash TV warmup"].roads[15].road = "sutro_west_03 AI Road 10"
routes["Smash TV warmup"].roads[15].direction = "against"
routes["Smash TV warmup"].roads[16] = {}
routes["Smash TV warmup"].roads[16].road = "sutro_west_03 AI Road 9"
routes["Smash TV warmup"].roads[16].direction = "against"
routes["Smash TV warmup"].roads[17] = {}
routes["Smash TV warmup"].roads[17].road = "sutro_west_03 AI Road 8"
routes["Smash TV warmup"].roads[17].direction = "against"
routes["Smash TV warmup"].roads[18] = {}
routes["Smash TV warmup"].roads[18].road = "sutro_west_03 AI Road 7"
routes["Smash TV warmup"].roads[18].direction = "against"
routes["Smash TV warmup"].roads[19] = {}
routes["Smash TV warmup"].roads[19].road = "sutro_west_03 AI Road 6"
routes["Smash TV warmup"].roads[19].direction = "against"
routes["Smash TV warmup"].roads[20] = {}
routes["Smash TV warmup"].roads[20].road = "sutro_shortcut_26 AI Road 2"
routes["Smash TV warmup"].roads[20].direction = "with"
routes["Smash TV warmup"].roads[21] = {}
routes["Smash TV warmup"].roads[21].road = "sutro_shortcut_16 AI Road 0"
routes["Smash TV warmup"].roads[21].direction = "with"
routes["Smash TV warmup"].roads[22] = {}
routes["Smash TV warmup"].roads[22].road = "sutro_shortcut_17 AI Road 6"
routes["Smash TV warmup"].roads[22].direction = "against"
routes["Smash TV warmup"].roads[23] = {}
routes["Smash TV warmup"].roads[23].road = "sutro_south_main AI Road 18"
routes["Smash TV warmup"].roads[23].direction = "against"
routes["Smash TV warmup"].roads[24] = {}
routes["Smash TV warmup"].roads[24].road = "garage_helper_06 AI Road 1"
routes["Smash TV warmup"].roads[24].direction = "against"
routes["Smash TV warmup"].roads[25] = {}
routes["Smash TV warmup"].roads[25].road = "garage_helper_a06 AI Road 0"
routes["Smash TV warmup"].roads[25].direction = "against"
routes["Smash TV warmup"].roads[26] = {}
routes["Smash TV warmup"].roads[26].road = "sutro_south_main AI Road 16"
routes["Smash TV warmup"].roads[26].direction = "against"
