routes = routes or {}
routes["Rushdown Start 02"] = {}
routes["Rushdown Start 02"].checkpoints = {}
routes["Rushdown Start 02"].checkpoints[1] = {}
routes["Rushdown Start 02"].checkpoints[1].position = vec.vector(1233.279, 30, -4071.596, 1)
routes["Rushdown Start 02"].checkpoints[1].heading = -2.58218
routes["Rushdown Start 02"].checkpoints[1].roadName = "marin_shortcut_29 AI Road 3"
routes["Rushdown Start 02"].checkpoints[2] = {}
routes["Rushdown Start 02"].checkpoints[2].position = vec.vector(902.6253, 30.70563, -4420.165, 1)
routes["Rushdown Start 02"].checkpoints[2].heading = 0.5440328
routes["Rushdown Start 02"].checkpoints[2].roadName = "marin_shortcut_27 AI Road 0"
routes["Rushdown Start 02"].arrows = {}
routes["Rushdown Start 02"].roads = {}
routes["Rushdown Start 02"].roads[1] = {}
routes["Rushdown Start 02"].roads[1].road = "marin_shortcut_29 AI Road 3"
routes["Rushdown Start 02"].roads[1].direction = "against"
routes["Rushdown Start 02"].roads[2] = {}
routes["Rushdown Start 02"].roads[2].road = "marin_4l_centre_01 AI Road 15"
routes["Rushdown Start 02"].roads[2].direction = "against"
routes["Rushdown Start 02"].roads[3] = {}
routes["Rushdown Start 02"].roads[3].road = "marin_4l_centre_01 AI Road 14"
routes["Rushdown Start 02"].roads[3].direction = "against"
routes["Rushdown Start 02"].roads[4] = {}
routes["Rushdown Start 02"].roads[4].road = "marin_4l_centre_01 AI Road 13"
routes["Rushdown Start 02"].roads[4].direction = "against"
routes["Rushdown Start 02"].roads[5] = {}
routes["Rushdown Start 02"].roads[5].road = "r654_shortcut_01 AI Road 0"
routes["Rushdown Start 02"].roads[5].direction = "against"
routes["Rushdown Start 02"].roads[6] = {}
routes["Rushdown Start 02"].roads[6].road = "mountain_10l_w_01a AI Road 0"
routes["Rushdown Start 02"].roads[6].direction = "against"
routes["Rushdown Start 02"].roads[7] = {}
routes["Rushdown Start 02"].roads[7].road = "marin_6l_west_01a AI Road 38"
routes["Rushdown Start 02"].roads[7].direction = "against"
routes["Rushdown Start 02"].roads[8] = {}
routes["Rushdown Start 02"].roads[8].road = "marin_6l_west_01a AI Road 37"
routes["Rushdown Start 02"].roads[8].direction = "against"
routes["Rushdown Start 02"].roads[9] = {}
routes["Rushdown Start 02"].roads[9].road = "marin_6l_west_01a AI Road 36"
routes["Rushdown Start 02"].roads[9].direction = "against"
routes["Rushdown Start 02"].roads[10] = {}
routes["Rushdown Start 02"].roads[10].road = "mountain_10l_w_01b AI Road 16"
routes["Rushdown Start 02"].roads[10].direction = "against"
routes["Rushdown Start 02"].roads[11] = {}
routes["Rushdown Start 02"].roads[11].road = "marin_shortcut_27 AI Road 0"
routes["Rushdown Start 02"].roads[11].direction = "with"
