routes = routes or {}
routes["Rushdown Start 07"] = {}
routes["Rushdown Start 07"].checkpoints = {}
routes["Rushdown Start 07"].checkpoints[1] = {}
routes["Rushdown Start 07"].checkpoints[1].position = vec.vector(837.0598, 8.286572, 3224.224, 1)
routes["Rushdown Start 07"].checkpoints[1].heading = -0.002454194
routes["Rushdown Start 07"].checkpoints[1].roadName = "r248_shortcut_01 AI Road 0"
routes["Rushdown Start 07"].checkpoints[2] = {}
routes["Rushdown Start 07"].checkpoints[2].position = vec.vector(918.7252, 8.249998, 3816.5, 1)
routes["Rushdown Start 07"].checkpoints[2].heading = -2.352016
routes["Rushdown Start 07"].checkpoints[2].roadName = "sutro_shortcut_e_05 AI Road 0"
routes["Rushdown Start 07"].arrows = {}
routes["Rushdown Start 07"].roads = {}
routes["Rushdown Start 07"].roads[1] = {}
routes["Rushdown Start 07"].roads[1].road = "r248_shortcut_01 AI Road 0"
routes["Rushdown Start 07"].roads[1].direction = "with"
routes["Rushdown Start 07"].roads[2] = {}
routes["Rushdown Start 07"].roads[2].road = "sutro_6l_east_02 AI Road 3"
routes["Rushdown Start 07"].roads[2].direction = "with"
routes["Rushdown Start 07"].roads[3] = {}
routes["Rushdown Start 07"].roads[3].road = "sutro_6l_east_01b AI Road 2"
routes["Rushdown Start 07"].roads[3].direction = "with"
routes["Rushdown Start 07"].roads[4] = {}
routes["Rushdown Start 07"].roads[4].road = "sutro_6l_south_01b AI Road 5"
routes["Rushdown Start 07"].roads[4].direction = "against"
routes["Rushdown Start 07"].roads[5] = {}
routes["Rushdown Start 07"].roads[5].road = "sutro_6l_south_01b AI Road 4"
routes["Rushdown Start 07"].roads[5].direction = "against"
routes["Rushdown Start 07"].roads[6] = {}
routes["Rushdown Start 07"].roads[6].road = "sutro_4l_east_04 AI Road 0"
routes["Rushdown Start 07"].roads[6].direction = "with"
routes["Rushdown Start 07"].roads[7] = {}
routes["Rushdown Start 07"].roads[7].road = "sutro_8l_east_04 AI Road 3"
routes["Rushdown Start 07"].roads[7].direction = "with"
routes["Rushdown Start 07"].roads[8] = {}
routes["Rushdown Start 07"].roads[8].road = "sutro_shortcut_e_05 AI Road 0"
routes["Rushdown Start 07"].roads[8].direction = "against"
