routes = routes or {}
routes["Rushdown Start 01"] = {}
routes["Rushdown Start 01"].checkpoints = {}
routes["Rushdown Start 01"].checkpoints[1] = {}
routes["Rushdown Start 01"].checkpoints[1].position = vec.vector(-2557.1, 66.85155, 987.6478, 1)
routes["Rushdown Start 01"].checkpoints[1].heading = 1.674931
routes["Rushdown Start 01"].checkpoints[1].roadName = "gg_shortcut_02b AI Road 1"
routes["Rushdown Start 01"].checkpoints[2] = {}
routes["Rushdown Start 01"].checkpoints[2].position = vec.vector(-2084.059, 63.95734, 873.0659, 1)
routes["Rushdown Start 01"].checkpoints[2].heading = -0.05177752
routes["Rushdown Start 01"].checkpoints[2].roadName = "ggp_shortcut_11 AI Road 0"
routes["Rushdown Start 01"].arrows = {}
routes["Rushdown Start 01"].roads = {}
routes["Rushdown Start 01"].roads[1] = {}
routes["Rushdown Start 01"].roads[1].road = "gg_shortcut_02b AI Road 1"
routes["Rushdown Start 01"].roads[1].direction = "against"
routes["Rushdown Start 01"].roads[2] = {}
routes["Rushdown Start 01"].roads[2].road = "gg_shortcut_02b AI Road 0"
routes["Rushdown Start 01"].roads[2].direction = "against"
routes["Rushdown Start 01"].roads[3] = {}
routes["Rushdown Start 01"].roads[3].road = "gg_shortcut_02a AI Road 1"
routes["Rushdown Start 01"].roads[3].direction = "against"
routes["Rushdown Start 01"].roads[4] = {}
routes["Rushdown Start 01"].roads[4].road = "gg_shortcut_02a AI Road 0"
routes["Rushdown Start 01"].roads[4].direction = "against"
routes["Rushdown Start 01"].roads[5] = {}
routes["Rushdown Start 01"].roads[5].road = "ggp_4l_ne_04b AI Road 4"
routes["Rushdown Start 01"].roads[5].direction = "against"
routes["Rushdown Start 01"].roads[6] = {}
routes["Rushdown Start 01"].roads[6].road = "ggp_4l_ne_04b AI Road 3"
routes["Rushdown Start 01"].roads[6].direction = "against"
routes["Rushdown Start 01"].roads[7] = {}
routes["Rushdown Start 01"].roads[7].road = "ggp_4l_ne_04b AI Road 2"
routes["Rushdown Start 01"].roads[7].direction = "against"
routes["Rushdown Start 01"].roads[8] = {}
routes["Rushdown Start 01"].roads[8].road = "ggp_4l_ne_04b AI Road 1"
routes["Rushdown Start 01"].roads[8].direction = "against"
routes["Rushdown Start 01"].roads[9] = {}
routes["Rushdown Start 01"].roads[9].road = "ggp_4l_ne_04b AI Road 0"
routes["Rushdown Start 01"].roads[9].direction = "against"
routes["Rushdown Start 01"].roads[10] = {}
routes["Rushdown Start 01"].roads[10].road = "ggp_4l_ne_04a AI Road 3"
routes["Rushdown Start 01"].roads[10].direction = "against"
routes["Rushdown Start 01"].roads[11] = {}
routes["Rushdown Start 01"].roads[11].road = "ggp_shortcut_11 AI Road 0"
routes["Rushdown Start 01"].roads[11].direction = "against"
