routes = routes or {}
routes["Rushdown Start 05"] = {}
routes["Rushdown Start 05"].checkpoints = {}
routes["Rushdown Start 05"].checkpoints[1] = {}
routes["Rushdown Start 05"].checkpoints[1].position = vec.vector(-3420.287, 75.22554, 3990.737, 1)
routes["Rushdown Start 05"].checkpoints[1].heading = -1.580534
routes["Rushdown Start 05"].checkpoints[1].roadName = "sutro_shortcut_14 AI Road 0"
routes["Rushdown Start 05"].checkpoints[2] = {}
routes["Rushdown Start 05"].checkpoints[2].position = vec.vector(-3913.44, 61.28488, 3880.395, 1)
routes["Rushdown Start 05"].checkpoints[2].heading = 1.740379
routes["Rushdown Start 05"].checkpoints[2].roadName = "sutro_shortcut_24 AI Road 0"
routes["Rushdown Start 05"].arrows = {}
routes["Rushdown Start 05"].roads = {}
routes["Rushdown Start 05"].roads[1] = {}
routes["Rushdown Start 05"].roads[1].road = "sutro_shortcut_14 AI Road 0"
routes["Rushdown Start 05"].roads[1].direction = "against"
routes["Rushdown Start 05"].roads[2] = {}
routes["Rushdown Start 05"].roads[2].road = "sutro_south_main AI Road 6"
routes["Rushdown Start 05"].roads[2].direction = "against"
routes["Rushdown Start 05"].roads[3] = {}
routes["Rushdown Start 05"].roads[3].road = "sutro_south_main AI Road 5"
routes["Rushdown Start 05"].roads[3].direction = "against"
routes["Rushdown Start 05"].roads[4] = {}
routes["Rushdown Start 05"].roads[4].road = "sutro_south_main AI Road 4"
routes["Rushdown Start 05"].roads[4].direction = "against"
routes["Rushdown Start 05"].roads[5] = {}
routes["Rushdown Start 05"].roads[5].road = "sutro_south_main AI Road 3"
routes["Rushdown Start 05"].roads[5].direction = "against"
routes["Rushdown Start 05"].roads[6] = {}
routes["Rushdown Start 05"].roads[6].road = "sutro_south_main AI Road 2"
routes["Rushdown Start 05"].roads[6].direction = "against"
routes["Rushdown Start 05"].roads[7] = {}
routes["Rushdown Start 05"].roads[7].road = "sutro_south_main AI Road 1"
routes["Rushdown Start 05"].roads[7].direction = "against"
routes["Rushdown Start 05"].roads[8] = {}
routes["Rushdown Start 05"].roads[8].road = "sutro_west_03 AI Road 15"
routes["Rushdown Start 05"].roads[8].direction = "against"
routes["Rushdown Start 05"].roads[9] = {}
routes["Rushdown Start 05"].roads[9].road = "sutro_shortcut_24 AI Road 0"
routes["Rushdown Start 05"].roads[9].direction = "against"
