routes = routes or {}
routes["Rushdown Start 03"] = {}
routes["Rushdown Start 03"].checkpoints = {}
routes["Rushdown Start 03"].checkpoints[1] = {}
routes["Rushdown Start 03"].checkpoints[1].position = vec.vector(-3773.601, 47.24693, 2807.642, 1)
routes["Rushdown Start 03"].checkpoints[1].heading = -0.2555777
routes["Rushdown Start 03"].checkpoints[1].roadName = "sutro_shortcut_19 AI Road 5"
routes["Rushdown Start 03"].checkpoints[2] = {}
routes["Rushdown Start 03"].checkpoints[2].position = vec.vector(-3525.676, 79.97536, 3241.992, 1)
routes["Rushdown Start 03"].checkpoints[2].heading = -2.720442
routes["Rushdown Start 03"].checkpoints[2].roadName = "sutro_shortcut_15 AI Road 1"
routes["Rushdown Start 03"].arrows = {}
routes["Rushdown Start 03"].roads = {}
routes["Rushdown Start 03"].roads[1] = {}
routes["Rushdown Start 03"].roads[1].road = "sutro_shortcut_19 AI Road 5"
routes["Rushdown Start 03"].roads[1].direction = "against"
routes["Rushdown Start 03"].roads[2] = {}
routes["Rushdown Start 03"].roads[2].road = "sutro_4l_west_02 AI Road 1"
routes["Rushdown Start 03"].roads[2].direction = "with"
routes["Rushdown Start 03"].roads[3] = {}
routes["Rushdown Start 03"].roads[3].road = "sutro_8l_north_01 AI Road 1"
routes["Rushdown Start 03"].roads[3].direction = "against"
routes["Rushdown Start 03"].roads[4] = {}
routes["Rushdown Start 03"].roads[4].road = "sutro_shortcut_19 AI Road 3"
routes["Rushdown Start 03"].roads[4].direction = "against"
routes["Rushdown Start 03"].roads[5] = {}
routes["Rushdown Start 03"].roads[5].road = "sutro_shortcut_20 AI Road 0"
routes["Rushdown Start 03"].roads[5].direction = "with"
routes["Rushdown Start 03"].roads[6] = {}
routes["Rushdown Start 03"].roads[6].road = "sutro_6l_west_02 AI Road 5"
routes["Rushdown Start 03"].roads[6].direction = "with"
routes["Rushdown Start 03"].roads[7] = {}
routes["Rushdown Start 03"].roads[7].road = "sutro_6l_west_02 AI Road 6"
routes["Rushdown Start 03"].roads[7].direction = "with"
routes["Rushdown Start 03"].roads[8] = {}
routes["Rushdown Start 03"].roads[8].road = "sutro_south_main AI Road 0"
routes["Rushdown Start 03"].roads[8].direction = "with"
routes["Rushdown Start 03"].roads[9] = {}
routes["Rushdown Start 03"].roads[9].road = "sutro_west_03 AI Road 15"
routes["Rushdown Start 03"].roads[9].direction = "against"
routes["Rushdown Start 03"].roads[10] = {}
routes["Rushdown Start 03"].roads[10].road = "sutro_shortcut_15 AI Road 0"
routes["Rushdown Start 03"].roads[10].direction = "with"
routes["Rushdown Start 03"].roads[11] = {}
routes["Rushdown Start 03"].roads[11].road = "sutro_shortcut_15 AI Road 1"
routes["Rushdown Start 03"].roads[11].direction = "with"
