routes = routes or {}
routes["Online Test Route Start"] = {}
routes["Online Test Route Start"].checkpoints = {}
routes["Online Test Route Start"].checkpoints[1] = {}
routes["Online Test Route Start"].checkpoints[1].position = vec.vector(657.5138, 6.039532, 1280.167, 1)
routes["Online Test Route Start"].checkpoints[1].heading = 2.289345
routes["Online Test Route Start"].checkpoints[1].roadName = "embargedero_shortcut_02 AI Road 0"
routes["Online Test Route Start"].checkpoints[2] = {}
routes["Online Test Route Start"].checkpoints[2].position = vec.vector(668.4562, 6.003437, 1270.647, 1)
routes["Online Test Route Start"].checkpoints[2].heading = 2.289018
routes["Online Test Route Start"].checkpoints[2].roadName = "embargedero_shortcut_02 AI Road 0"
routes["Online Test Route Start"].arrows = {}
routes["Online Test Route Start"].roads = {}
routes["Online Test Route"] = {}
routes["Online Test Route"].checkpoints = {}
routes["Online Test Route"].checkpoints[1] = {}
routes["Online Test Route"].checkpoints[1].position = vec.vector(652.933, 5.974995, 1182.827, 1)
routes["Online Test Route"].checkpoints[1].heading = -2.320141
routes["Online Test Route"].checkpoints[1].roadName = "sanfran_shortcut_06 AI Road 0"
routes["Online Test Route"].checkpoints[2] = {}
routes["Online Test Route"].checkpoints[2].position = vec.vector(519.4567, 6.508474, 1185.444, 1)
routes["Online Test Route"].checkpoints[2].heading = -0.8502352
routes["Online Test Route"].checkpoints[2].roadName = "dt_10l_south_03 AI Road 2"
routes["Online Test Route"].checkpoints[3] = {}
routes["Online Test Route"].checkpoints[3].position = vec.vector(375.0961, 7.999999, 1315.755, 1)
routes["Online Test Route"].checkpoints[3].heading = -0.7928922
routes["Online Test Route"].checkpoints[3].roadName = "dt_10l_south_03 AI Road 4"
routes["Online Test Route"].checkpoints[4] = {}
routes["Online Test Route"].checkpoints[4].position = vec.vector(256.7017, 16.90735, 1418.176, 1)
routes["Online Test Route"].checkpoints[4].heading = -0.8591196
routes["Online Test Route"].checkpoints[4].roadName = "dt_10l_south_03 AI Road 4"
routes["Online Test Route"].checkpoints[5] = {}
routes["Online Test Route"].checkpoints[5].position = vec.vector(241.2352, 18.00904, 1520.382, 1)
routes["Online Test Route"].checkpoints[5].heading = 0.7480065
routes["Online Test Route"].checkpoints[5].roadName = "mt_6l_centre_04 AI Road 2"
routes["Online Test Route"].checkpoints[6] = {}
routes["Online Test Route"].checkpoints[6].position = vec.vector(336.9929, 18.00904, 1623.621, 1)
routes["Online Test Route"].checkpoints[6].heading = 0.7564899
routes["Online Test Route"].checkpoints[6].roadName = "mt_6l_centre_04 AI Road 3"
routes["Online Test Route"].checkpoints[7] = {}
routes["Online Test Route"].checkpoints[7].position = vec.vector(433.9012, 16.53377, 1614.21, 1)
routes["Online Test Route"].checkpoints[7].heading = 2.295812
routes["Online Test Route"].checkpoints[7].roadName = "mt_shortcuts_01ab AI Road 0"
routes["Online Test Route"].checkpoints[8] = {}
routes["Online Test Route"].checkpoints[8].position = vec.vector(540.8055, 6.084949, 1520.546, 1)
routes["Online Test Route"].checkpoints[8].heading = 2.291319
routes["Online Test Route"].checkpoints[8].roadName = "mt_shortcuts_01ab AI Road 0"
routes["Online Test Route"].checkpoints[9] = {}
routes["Online Test Route"].checkpoints[9].position = vec.vector(690.8356, 5.975, 1399.419, 1)
routes["Online Test Route"].checkpoints[9].heading = 2.277704
routes["Online Test Route"].checkpoints[9].roadName = "mt_10l_south_02 AI Road 0"
routes["Online Test Route"].checkpoints[10] = {}
routes["Online Test Route"].checkpoints[10].position = vec.vector(752.2051, 5.974995, 1275.186, 1)
routes["Online Test Route"].checkpoints[10].heading = -2.320105
routes["Online Test Route"].checkpoints[10].roadName = "sanfran_shortcut_06 AI Road 1"
routes["Online Test Route"].arrows = {}
routes["Online Test Route"].roads = {}
routes["Online Test Route"].roads[1] = {}
routes["Online Test Route"].roads[1].road = "sanfran_shortcut_06 AI Road 0"
routes["Online Test Route"].roads[1].direction = "against"
routes["Online Test Route"].roads[2] = {}
routes["Online Test Route"].roads[2].road = "dt_10l_south_03 AI Road 2"
routes["Online Test Route"].roads[2].direction = "with"
routes["Online Test Route"].roads[3] = {}
routes["Online Test Route"].roads[3].road = "dt_10l_south_03 AI Road 3"
routes["Online Test Route"].roads[3].direction = "with"
routes["Online Test Route"].roads[4] = {}
routes["Online Test Route"].roads[4].road = "dt_10l_south_03 AI Road 4"
routes["Online Test Route"].roads[4].direction = "with"
routes["Online Test Route"].roads[5] = {}
routes["Online Test Route"].roads[5].road = "mt_6l_centre_04 AI Road 2"
routes["Online Test Route"].roads[5].direction = "with"
routes["Online Test Route"].roads[6] = {}
routes["Online Test Route"].roads[6].road = "mt_6l_centre_04 AI Road 3"
routes["Online Test Route"].roads[6].direction = "with"
routes["Online Test Route"].roads[7] = {}
routes["Online Test Route"].roads[7].road = "mt_shortcuts_01ab AI Road 0"
routes["Online Test Route"].roads[7].direction = "with"
routes["Online Test Route"].roads[8] = {}
routes["Online Test Route"].roads[8].road = "mt_10l_south_02 AI Road 0"
routes["Online Test Route"].roads[8].direction = "with"
routes["Online Test Route"].roads[9] = {}
routes["Online Test Route"].roads[9].road = "sanfran_shortcut_06 AI Road 1"
routes["Online Test Route"].roads[9].direction = "against"
