routes = routes or {}
routes["Alone warmup"] = {}
routes["Alone warmup"].checkpoints = {}
routes["Alone warmup"].checkpoints[1] = {}
routes["Alone warmup"].checkpoints[1].position = vec.vector(-378.4683, 65.02898, -87.34892, 1)
routes["Alone warmup"].checkpoints[1].heading = 1.235016
routes["Alone warmup"].checkpoints[1].roadName = "dt_6l_north_01 AI Road 2"
routes["Alone warmup"].checkpoints[2] = {}
routes["Alone warmup"].checkpoints[2].position = vec.vector(-401.1534, 70.00031, 187.305, 1)
routes["Alone warmup"].checkpoints[2].heading = -1.419775
routes["Alone warmup"].checkpoints[2].roadName = "dt_twisty_road AI Road 0"
routes["Alone warmup"].checkpoints[3] = {}
routes["Alone warmup"].checkpoints[3].position = vec.vector(-576.0152, 35.3256, -5.454664, 1)
routes["Alone warmup"].checkpoints[3].heading = -2.954168
routes["Alone warmup"].checkpoints[3].roadName = "dt_4l_centre_09 AI Road 0"
routes["Alone warmup"].checkpoints[4] = {}
routes["Alone warmup"].checkpoints[4].position = vec.vector(-487.8338, 36.42179, -106.4671, 1)
routes["Alone warmup"].checkpoints[4].heading = 1.8595
routes["Alone warmup"].checkpoints[4].roadName = "dt_6l_north_01 AI Road 2"
routes["Alone warmup"].arrows = {}
routes["Alone warmup"].roads = {}
routes["Alone warmup"].roads[1] = {}
routes["Alone warmup"].roads[1].road = "dt_6l_north_01 AI Road 2"
routes["Alone warmup"].roads[1].direction = "with"
routes["Alone warmup"].roads[2] = {}
routes["Alone warmup"].roads[2].road = "dt_6l_north_01 AI Road 3"
routes["Alone warmup"].roads[2].direction = "with"
routes["Alone warmup"].roads[3] = {}
routes["Alone warmup"].roads[3].road = "dt_twisty_road AI Road 0"
routes["Alone warmup"].roads[3].direction = "against"
routes["Alone warmup"].roads[4] = {}
routes["Alone warmup"].roads[4].road = "dt_4l_centre_09 AI Road 1"
routes["Alone warmup"].roads[4].direction = "against"
routes["Alone warmup"].roads[5] = {}
routes["Alone warmup"].roads[5].road = "dt_4l_centre_09 AI Road 0"
routes["Alone warmup"].roads[5].direction = "against"
routes["Alone evader top"] = {}
routes["Alone evader top"].checkpoints = {}
routes["Alone evader top"].checkpoints[1] = {}
routes["Alone evader top"].checkpoints[1].position = vec.vector(-462.9054, 43.45934, 1407.18, 1)
routes["Alone evader top"].checkpoints[1].heading = 0.4942094
routes["Alone evader top"].checkpoints[1].roadName = "dt_shortcut_19 AI Road 1"
routes["Alone evader top"].checkpoints[2] = {}
routes["Alone evader top"].checkpoints[2].position = vec.vector(-416.7234, 47.24998, 1489.929, 1)
routes["Alone evader top"].checkpoints[2].heading = 0.5347926
routes["Alone evader top"].checkpoints[2].roadName = "mt_10l_centre_04 AI Road 0"
routes["Alone evader top"].arrows = {}
routes["Alone evader top"].roads = {}
routes["Alone evader top"].roads[1] = {}
routes["Alone evader top"].roads[1].road = "dt_shortcut_19 AI Road 1"
routes["Alone evader top"].roads[1].direction = "with"
routes["Alone evader top"].roads[2] = {}
routes["Alone evader top"].roads[2].road = "mt_10l_centre_04 AI Road 0"
routes["Alone evader top"].roads[2].direction = "with"
routes["Alone evader bottom"] = {}
routes["Alone evader bottom"].checkpoints = {}
routes["Alone evader bottom"].checkpoints[1] = {}
routes["Alone evader bottom"].checkpoints[1].position = vec.vector(-436.1009, 30.78249, 1331.209, 1)
routes["Alone evader bottom"].checkpoints[1].heading = 2.07419
routes["Alone evader bottom"].checkpoints[1].roadName = "dt_shortcut_20 AI Road 3"
routes["Alone evader bottom"].checkpoints[2] = {}
routes["Alone evader bottom"].checkpoints[2].position = vec.vector(-366.5992, 23.48611, 1211.143, 1)
routes["Alone evader bottom"].checkpoints[2].heading = -3.00439
routes["Alone evader bottom"].checkpoints[2].roadName = "chinat_shortcut_01 AI Road 0"
routes["Alone evader bottom"].arrows = {}
routes["Alone evader bottom"].roads = {}
routes["Alone evader bottom"].roads[1] = {}
routes["Alone evader bottom"].roads[1].road = "dt_shortcut_20 AI Road 3"
routes["Alone evader bottom"].roads[1].direction = "with"
routes["Alone evader bottom"].roads[2] = {}
routes["Alone evader bottom"].roads[2].road = "chinat_shortcut_01 AI Road 0"
routes["Alone evader bottom"].roads[2].direction = "against"
