routes = routes or {}
routes.ChequeredFlagRoute = {}
routes.ChequeredFlagRoute.checkpoints = {}
routes.ChequeredFlagRoute.checkpoints[1] = {}
routes.ChequeredFlagRoute.checkpoints[1].position = vec.vector(1332.033, 45.1081, -4776.311, 1)
routes.ChequeredFlagRoute.checkpoints[1].heading = -1.856834
routes.ChequeredFlagRoute.checkpoints[1].roadName = "mountain_10l_w_01b AI Road 14"
routes.ChequeredFlagRoute.checkpoints[2] = {}
routes.ChequeredFlagRoute.checkpoints[2].position = vec.vector(834.119, 53.75, -4632.417, 1)
routes.ChequeredFlagRoute.checkpoints[2].heading = -1.059944
routes.ChequeredFlagRoute.checkpoints[2].roadName = "mountain_10l_w_01b AI Road 15"
routes.ChequeredFlagRoute.checkpoints[3] = {}
routes.ChequeredFlagRoute.checkpoints[3].position = vec.vector(439.3612, 53.75, -4528.227, 1)
routes.ChequeredFlagRoute.checkpoints[3].heading = -2.58777
routes.ChequeredFlagRoute.checkpoints[3].roadName = "marin_6l_west_01a AI Road 35"
routes.ChequeredFlagRoute.checkpoints[4] = {}
routes.ChequeredFlagRoute.checkpoints[4].position = vec.vector(336.79, 65.05062, -4661.827, 1)
routes.ChequeredFlagRoute.checkpoints[4].heading = -2.211197
routes.ChequeredFlagRoute.checkpoints[4].roadName = "marin_6l_west_01a AI Road 34"
routes.ChequeredFlagRoute.checkpoints[5] = {}
routes.ChequeredFlagRoute.checkpoints[5].position = vec.vector(-195.4576, 116.597, -4853.39, 1)
routes.ChequeredFlagRoute.checkpoints[5].heading = -0.623269
routes.ChequeredFlagRoute.checkpoints[5].roadName = "marin_6l_west_01a AI Road 31"
routes.ChequeredFlagRoute.checkpoints[6] = {}
routes.ChequeredFlagRoute.checkpoints[6].position = vec.vector(-443.6166, 131.841, -4833.074, 1)
routes.ChequeredFlagRoute.checkpoints[6].heading = -2.681731
routes.ChequeredFlagRoute.checkpoints[6].roadName = "marin_6l_west_01a AI Road 29"
routes.ChequeredFlagRoute.checkpoints[7] = {}
routes.ChequeredFlagRoute.checkpoints[7].position = vec.vector(-695.0533, 120.5147, -4781.459, 1)
routes.ChequeredFlagRoute.checkpoints[7].heading = -0.9009187
routes.ChequeredFlagRoute.checkpoints[7].roadName = "marin_6l_west_01a AI Road 28"
routes.ChequeredFlagRoute.checkpoints[8] = {}
routes.ChequeredFlagRoute.checkpoints[8].position = vec.vector(-962.6525, 106.315, -4519.442, 1)
routes.ChequeredFlagRoute.checkpoints[8].heading = -0.8127705
routes.ChequeredFlagRoute.checkpoints[8].roadName = "marin_6l_west_01a AI Road 25"
routes.ChequeredFlagRoute.checkpoints[9] = {}
routes.ChequeredFlagRoute.checkpoints[9].position = vec.vector(-1497.907, 155, -4198.706, 1)
routes.ChequeredFlagRoute.checkpoints[9].heading = -1.239079
routes.ChequeredFlagRoute.checkpoints[9].roadName = "marin_6l_west_01a AI Road 21"
routes.ChequeredFlagRoute.checkpoints[10] = {}
routes.ChequeredFlagRoute.checkpoints[10].position = vec.vector(-1818.409, 155.1222, -4090.37, 1)
routes.ChequeredFlagRoute.checkpoints[10].heading = -1.232893
routes.ChequeredFlagRoute.checkpoints[10].roadName = "marin_6l_west_01a AI Road 18"
routes.ChequeredFlagRoute.checkpoints[11] = {}
routes.ChequeredFlagRoute.checkpoints[11].position = vec.vector(-2258.613, 163.1789, -3990.343, 1)
routes.ChequeredFlagRoute.checkpoints[11].heading = -2.02895
routes.ChequeredFlagRoute.checkpoints[11].roadName = "marin_6l_west_01a AI Road 16"
routes.ChequeredFlagRoute.checkpoints[12] = {}
routes.ChequeredFlagRoute.checkpoints[12].position = vec.vector(-2630.197, 165.1586, -4151.55, 1)
routes.ChequeredFlagRoute.checkpoints[12].heading = -0.9630319
routes.ChequeredFlagRoute.checkpoints[12].roadName = "marin_6l_west_01a AI Road 13"
routes.ChequeredFlagRoute.checkpoints[13] = {}
routes.ChequeredFlagRoute.checkpoints[13].position = vec.vector(-2630.383, 165.2168, -3772.333, 1)
routes.ChequeredFlagRoute.checkpoints[13].heading = -2.363665
routes.ChequeredFlagRoute.checkpoints[13].roadName = "marin_6l_west_01a AI Road 10"
routes.ChequeredFlagRoute.checkpoints[14] = {}
routes.ChequeredFlagRoute.checkpoints[14].position = vec.vector(-2920.862, 176.6025, -3932.966, 1)
routes.ChequeredFlagRoute.checkpoints[14].heading = -1.518798
routes.ChequeredFlagRoute.checkpoints[14].roadName = "marin_6l_west_01a AI Road 8"
routes.ChequeredFlagRoute.checkpoints[15] = {}
routes.ChequeredFlagRoute.checkpoints[15].position = vec.vector(-3322.466, 182.8583, -3749.902, 1)
routes.ChequeredFlagRoute.checkpoints[15].heading = -2.01895
routes.ChequeredFlagRoute.checkpoints[15].roadName = "marin_6l_west_01a AI Road 5"
routes.ChequeredFlagRoute.checkpoints[16] = {}
routes.ChequeredFlagRoute.checkpoints[16].position = vec.vector(-3631.914, 168.0126, -3563.298, 1)
routes.ChequeredFlagRoute.checkpoints[16].heading = -0.03147307
routes.ChequeredFlagRoute.checkpoints[16].roadName = "marin_6l_west_01a AI Road 2"
routes.ChequeredFlagRoute.checkpoints[17] = {}
routes.ChequeredFlagRoute.checkpoints[17].position = vec.vector(-3559.944, 123.3713, -2660.7, 1)
routes.ChequeredFlagRoute.checkpoints[17].heading = -0.2566978
routes.ChequeredFlagRoute.checkpoints[17].roadName = "marin_4l_west_02 AI Road 1"
routes.ChequeredFlagRoute.checkpoints[18] = {}
routes.ChequeredFlagRoute.checkpoints[18].position = vec.vector(-3812.058, 123.4127, -2433.118, 1)
routes.ChequeredFlagRoute.checkpoints[18].heading = -2.391187
routes.ChequeredFlagRoute.checkpoints[18].roadName = "marin_4l_west_02 AI Road 3"
routes.ChequeredFlagRoute.checkpoints[19] = {}
routes.ChequeredFlagRoute.checkpoints[19].position = vec.vector(-4034.907, 128.3857, -2729.34, 1)
routes.ChequeredFlagRoute.checkpoints[19].heading = -2.021997
routes.ChequeredFlagRoute.checkpoints[19].roadName = "marin_4l_west_02 AI Road 4"
routes.ChequeredFlagRoute.checkpoints[20] = {}
routes.ChequeredFlagRoute.checkpoints[20].position = vec.vector(-4099.408, 116.0193, -2542.076, 1)
routes.ChequeredFlagRoute.checkpoints[20].heading = 0.8929178
routes.ChequeredFlagRoute.checkpoints[20].roadName = "marin_4l_west_02 AI Road 5"
routes.ChequeredFlagRoute.checkpoints[21] = {}
routes.ChequeredFlagRoute.checkpoints[21].position = vec.vector(-3718.732, 74.51704, -2193.112, 1)
routes.ChequeredFlagRoute.checkpoints[21].heading = 0.4909956
routes.ChequeredFlagRoute.checkpoints[21].roadName = "marin_shortcut_14 AI Road 0"
routes.ChequeredFlagRoute.checkpoints[22] = {}
routes.ChequeredFlagRoute.checkpoints[22].position = vec.vector(-3711.86, 64.00933, -1793.476, 1)
routes.ChequeredFlagRoute.checkpoints[22].heading = -0.3421663
routes.ChequeredFlagRoute.checkpoints[22].roadName = "mountain_10l_w_06 AI Road 6"
routes.ChequeredFlagRoute.checkpoints[23] = {}
routes.ChequeredFlagRoute.checkpoints[23].position = vec.vector(-3321.311, 26.04716, -1543.043, 1)
routes.ChequeredFlagRoute.checkpoints[23].heading = 1.319327
routes.ChequeredFlagRoute.checkpoints[23].roadName = "mountain_10l_w_06 AI Road 8"
routes.ChequeredFlagRoute.checkpoints[24] = {}
routes.ChequeredFlagRoute.checkpoints[24].position = vec.vector(-2880.682, 20.95003, -1430.324, 1)
routes.ChequeredFlagRoute.checkpoints[24].heading = 1.327149
routes.ChequeredFlagRoute.checkpoints[24].roadName = "mountain_10l_w_06 AI Road 10"
routes.ChequeredFlagRoute.checkpoints[25] = {}
routes.ChequeredFlagRoute.checkpoints[25].position = vec.vector(-2571.54, 20.80968, -1534.039, 1)
routes.ChequeredFlagRoute.checkpoints[25].heading = 2.618752
routes.ChequeredFlagRoute.checkpoints[25].roadName = "mountain_10l_w_06 AI Road 12"
routes.ChequeredFlagRoute.checkpoints[26] = {}
routes.ChequeredFlagRoute.checkpoints[26].position = vec.vector(-2437.468, 15.25931, -1766.536, 1)
routes.ChequeredFlagRoute.checkpoints[26].heading = 2.618552
routes.ChequeredFlagRoute.checkpoints[26].roadName = "mountain_10l_w_06 AI Road 12"
routes.ChequeredFlagRoute.checkpoints[27] = {}
routes.ChequeredFlagRoute.checkpoints[27].position = vec.vector(-2187.865, 8.295304, -2205.806, 1)
routes.ChequeredFlagRoute.checkpoints[27].heading = 2.60549
routes.ChequeredFlagRoute.checkpoints[27].roadName = "mountain_10l_w_06 AI Road 14"
routes.ChequeredFlagRoute.checkpoints[28] = {}
routes.ChequeredFlagRoute.checkpoints[28].position = vec.vector(-1400.173, 8.25, -2584.854, 1)
routes.ChequeredFlagRoute.checkpoints[28].heading = 2.302126
routes.ChequeredFlagRoute.checkpoints[28].roadName = "mountain_10l_w_01b AI Road 34"
routes.ChequeredFlagRoute.arrows = {}
routes.ChequeredFlagRoute.arrows[1] = {}
routes.ChequeredFlagRoute.arrows[1].position = vec.vector(-425.0111, 125, -4755.977, 1)
routes.ChequeredFlagRoute.arrows[1].heading = -3.059808
routes.ChequeredFlagRoute.arrows[1].modelId = 78
routes.ChequeredFlagRoute.arrows[2] = {}
routes.ChequeredFlagRoute.arrows[2].position = vec.vector(-572.8466, 129.5, -4947.736, 1)
routes.ChequeredFlagRoute.arrows[2].heading = -1.304544
routes.ChequeredFlagRoute.arrows[2].modelId = 78
routes.ChequeredFlagRoute.arrows[3] = {}
routes.ChequeredFlagRoute.arrows[3].position = vec.vector(-2217.656, 158, -3943.895, 1)
routes.ChequeredFlagRoute.arrows[3].heading = -2.100043
routes.ChequeredFlagRoute.arrows[3].modelId = 78
routes.ChequeredFlagRoute.arrows[4] = {}
routes.ChequeredFlagRoute.arrows[4].position = vec.vector(-2492.569, 161, -4227.052, 1)
routes.ChequeredFlagRoute.arrows[4].heading = -1.446442
routes.ChequeredFlagRoute.arrows[4].modelId = 78
routes.ChequeredFlagRoute.arrows[5] = {}
routes.ChequeredFlagRoute.arrows[5].position = vec.vector(-3290.059, 179, -3704.539, 1)
routes.ChequeredFlagRoute.arrows[5].heading = -2.14299
routes.ChequeredFlagRoute.arrows[5].modelId = 78
routes.ChequeredFlagRoute.arrows[6] = {}
routes.ChequeredFlagRoute.arrows[6].position = vec.vector(-2450.156, 161, -3906.808, 1)
routes.ChequeredFlagRoute.arrows[6].heading = 0.2046417
routes.ChequeredFlagRoute.arrows[6].modelId = 78
routes.ChequeredFlagRoute.arrows[7] = {}
routes.ChequeredFlagRoute.arrows[7].position = vec.vector(-3640.08, 115, -2377.022, 1)
routes.ChequeredFlagRoute.arrows[7].heading = -1.312544
routes.ChequeredFlagRoute.arrows[7].modelId = 78
routes.ChequeredFlagRoute.arrows[8] = {}
routes.ChequeredFlagRoute.arrows[8].position = vec.vector(-3497.678, 182.5, -3831.409, 1)
routes.ChequeredFlagRoute.arrows[8].heading = -0.9025062
routes.ChequeredFlagRoute.arrows[8].modelId = 78
routes.ChequeredFlagRoute.arrows[9] = {}
routes.ChequeredFlagRoute.arrows[9].position = vec.vector(-3569.892, 119, -2746.762, 1)
routes.ChequeredFlagRoute.arrows[9].heading = 0.2310907
routes.ChequeredFlagRoute.arrows[9].modelId = 78
routes.ChequeredFlagRoute.arrows[10] = {}
routes.ChequeredFlagRoute.arrows[10].position = vec.vector(-3725.44, 70.5, -2261.487, 1)
routes.ChequeredFlagRoute.arrows[10].heading = 0
routes.ChequeredFlagRoute.arrows[10].modelId = 219
routes.ChequeredFlagRoute.arrows[11] = {}
routes.ChequeredFlagRoute.arrows[11].position = vec.vector(-3730.038, 49, -1694.543, 1)
routes.ChequeredFlagRoute.arrows[11].heading = 0.8065583
routes.ChequeredFlagRoute.arrows[11].modelId = 78
routes.ChequeredFlagRoute.arrows[12] = {}
routes.ChequeredFlagRoute.arrows[12].position = vec.vector(-1933.166, 5, -2440.661, 1)
routes.ChequeredFlagRoute.arrows[12].heading = 1.687905
routes.ChequeredFlagRoute.arrows[12].modelId = 78
routes.ChequeredFlagRoute.arrows[13] = {}
routes.ChequeredFlagRoute.arrows[13].position = vec.vector(-34.04941, 107, -4949.703, 1)
routes.ChequeredFlagRoute.arrows[13].heading = -1.394674
routes.ChequeredFlagRoute.arrows[13].modelId = 78
routes.ChequeredFlagRoute.arrows[14] = {}
routes.ChequeredFlagRoute.arrows[14].position = vec.vector(469.6561, 50.75, -4436.907, 1)
routes.ChequeredFlagRoute.arrows[14].heading = -2.573488
routes.ChequeredFlagRoute.arrows[14].modelId = 219
routes.ChequeredFlagRoute.arrows[15] = {}
routes.ChequeredFlagRoute.arrows[15].position = vec.vector(-874.4836, 102, -4580.106, 1)
routes.ChequeredFlagRoute.arrows[15].heading = -0.7509294
routes.ChequeredFlagRoute.arrows[15].modelId = 78
routes.ChequeredFlagRoute.arrows[16] = {}
routes.ChequeredFlagRoute.arrows[16].position = vec.vector(-927.4467, 102, -4613.877, 1)
routes.ChequeredFlagRoute.arrows[16].heading = -0.5968259
routes.ChequeredFlagRoute.arrows[16].modelId = 78
routes.ChequeredFlagRoute.arrows[17] = {}
routes.ChequeredFlagRoute.arrows[17].position = vec.vector(-1413.501, 152, -4192.926, 1)
routes.ChequeredFlagRoute.arrows[17].heading = -1.339705
routes.ChequeredFlagRoute.arrows[17].modelId = 78
routes.ChequeredFlagRoute.arrows[18] = {}
routes.ChequeredFlagRoute.arrows[18].position = vec.vector(-1696.545, 152, -4086.981, 1)
routes.ChequeredFlagRoute.arrows[18].heading = -1.24464
routes.ChequeredFlagRoute.arrows[18].modelId = 78
routes.ChequeredFlagRoute.arrows[19] = {}
routes.ChequeredFlagRoute.arrows[19].position = vec.vector(-1680.545, 152, -4181.154, 1)
routes.ChequeredFlagRoute.arrows[19].heading = -1.07145
routes.ChequeredFlagRoute.arrows[19].modelId = 78
routes.ChequeredFlagRoute.arrows[20] = {}
routes.ChequeredFlagRoute.arrows[20].position = vec.vector(-3488.963, 122, -2970.424, 1)
routes.ChequeredFlagRoute.arrows[20].heading = -0.1894804
routes.ChequeredFlagRoute.arrows[20].modelId = 220
routes.ChequeredFlagRoute.arrows[21] = {}
routes.ChequeredFlagRoute.arrows[21].position = vec.vector(-4188.78, 119.89, -2662.86, 1)
routes.ChequeredFlagRoute.arrows[21].heading = 0.4214193
routes.ChequeredFlagRoute.arrows[21].modelId = 78
routes.ChequeredFlagRoute.arrows[22] = {}
routes.ChequeredFlagRoute.arrows[22].position = vec.vector(-3383.024, 22, -1596.18, 1)
routes.ChequeredFlagRoute.arrows[22].heading = 1.116077
routes.ChequeredFlagRoute.arrows[22].modelId = 78
routes.ChequeredFlagRoute.arrows[23] = {}
routes.ChequeredFlagRoute.arrows[23].position = vec.vector(-2679.322, 161.6, -3938.911, 1)
routes.ChequeredFlagRoute.arrows[23].heading = 1.517002
routes.ChequeredFlagRoute.arrows[23].modelId = 78
routes.ChequeredFlagRoute.roads = {}
routes.ChequeredFlagRoute.roads[1] = {}
routes.ChequeredFlagRoute.roads[1].road = "mountain_10l_w_01b AI Road 12"
routes.ChequeredFlagRoute.roads[1].direction = "with"
routes.ChequeredFlagRoute.roads[2] = {}
routes.ChequeredFlagRoute.roads[2].road = "mountain_10l_w_01b AI Road 13"
routes.ChequeredFlagRoute.roads[2].direction = "with"
routes.ChequeredFlagRoute.roads[3] = {}
routes.ChequeredFlagRoute.roads[3].road = "mountain_10l_w_01b AI Road 14"
routes.ChequeredFlagRoute.roads[3].direction = "with"
routes.ChequeredFlagRoute.roads[4] = {}
routes.ChequeredFlagRoute.roads[4].road = "mountain_10l_w_01b AI Road 15"
routes.ChequeredFlagRoute.roads[4].direction = "with"
routes.ChequeredFlagRoute.roads[5] = {}
routes.ChequeredFlagRoute.roads[5].road = "mountain_10l_w_01b AI Road 16"
routes.ChequeredFlagRoute.roads[5].direction = "with"
routes.ChequeredFlagRoute.roads[6] = {}
routes.ChequeredFlagRoute.roads[6].road = "marin_6l_west_01a AI Road 35"
routes.ChequeredFlagRoute.roads[6].direction = "against"
routes.ChequeredFlagRoute.roads[7] = {}
routes.ChequeredFlagRoute.roads[7].road = "marin_6l_west_01a AI Road 34"
routes.ChequeredFlagRoute.roads[7].direction = "against"
routes.ChequeredFlagRoute.roads[8] = {}
routes.ChequeredFlagRoute.roads[8].road = "marin_6l_west_01a AI Road 33"
routes.ChequeredFlagRoute.roads[8].direction = "against"
routes.ChequeredFlagRoute.roads[9] = {}
routes.ChequeredFlagRoute.roads[9].road = "marin_6l_west_01a AI Road 32"
routes.ChequeredFlagRoute.roads[9].direction = "against"
routes.ChequeredFlagRoute.roads[10] = {}
routes.ChequeredFlagRoute.roads[10].road = "marin_6l_west_01a AI Road 31"
routes.ChequeredFlagRoute.roads[10].direction = "against"
routes.ChequeredFlagRoute.roads[11] = {}
routes.ChequeredFlagRoute.roads[11].road = "marin_6l_west_01a AI Road 30"
routes.ChequeredFlagRoute.roads[11].direction = "against"
routes.ChequeredFlagRoute.roads[12] = {}
routes.ChequeredFlagRoute.roads[12].road = "marin_6l_west_01a AI Road 29"
routes.ChequeredFlagRoute.roads[12].direction = "against"
routes.ChequeredFlagRoute.roads[13] = {}
routes.ChequeredFlagRoute.roads[13].road = "marin_6l_west_01a AI Road 28"
routes.ChequeredFlagRoute.roads[13].direction = "against"
routes.ChequeredFlagRoute.roads[14] = {}
routes.ChequeredFlagRoute.roads[14].road = "marin_6l_west_01a AI Road 27"
routes.ChequeredFlagRoute.roads[14].direction = "against"
routes.ChequeredFlagRoute.roads[15] = {}
routes.ChequeredFlagRoute.roads[15].road = "marin_6l_west_01a AI Road 26"
routes.ChequeredFlagRoute.roads[15].direction = "against"
routes.ChequeredFlagRoute.roads[16] = {}
routes.ChequeredFlagRoute.roads[16].road = "marin_6l_west_01a AI Road 25"
routes.ChequeredFlagRoute.roads[16].direction = "against"
routes.ChequeredFlagRoute.roads[17] = {}
routes.ChequeredFlagRoute.roads[17].road = "marin_6l_west_01a AI Road 24"
routes.ChequeredFlagRoute.roads[17].direction = "against"
routes.ChequeredFlagRoute.roads[18] = {}
routes.ChequeredFlagRoute.roads[18].road = "marin_6l_west_01a AI Road 23"
routes.ChequeredFlagRoute.roads[18].direction = "against"
routes.ChequeredFlagRoute.roads[19] = {}
routes.ChequeredFlagRoute.roads[19].road = "marin_6l_west_01a AI Road 22"
routes.ChequeredFlagRoute.roads[19].direction = "against"
routes.ChequeredFlagRoute.roads[20] = {}
routes.ChequeredFlagRoute.roads[20].road = "marin_6l_west_01a AI Road 21"
routes.ChequeredFlagRoute.roads[20].direction = "against"
routes.ChequeredFlagRoute.roads[21] = {}
routes.ChequeredFlagRoute.roads[21].road = "marin_6l_west_01a AI Road 20"
routes.ChequeredFlagRoute.roads[21].direction = "against"
routes.ChequeredFlagRoute.roads[22] = {}
routes.ChequeredFlagRoute.roads[22].road = "marin_6l_west_01a AI Road 19"
routes.ChequeredFlagRoute.roads[22].direction = "against"
routes.ChequeredFlagRoute.roads[23] = {}
routes.ChequeredFlagRoute.roads[23].road = "marin_6l_west_01a AI Road 18"
routes.ChequeredFlagRoute.roads[23].direction = "against"
routes.ChequeredFlagRoute.roads[24] = {}
routes.ChequeredFlagRoute.roads[24].road = "marin_6l_west_01a AI Road 17"
routes.ChequeredFlagRoute.roads[24].direction = "against"
routes.ChequeredFlagRoute.roads[25] = {}
routes.ChequeredFlagRoute.roads[25].road = "marin_6l_west_01a AI Road 16"
routes.ChequeredFlagRoute.roads[25].direction = "against"
routes.ChequeredFlagRoute.roads[26] = {}
routes.ChequeredFlagRoute.roads[26].road = "marin_6l_west_01a AI Road 15"
routes.ChequeredFlagRoute.roads[26].direction = "against"
routes.ChequeredFlagRoute.roads[27] = {}
routes.ChequeredFlagRoute.roads[27].road = "marin_6l_west_01a AI Road 14"
routes.ChequeredFlagRoute.roads[27].direction = "against"
routes.ChequeredFlagRoute.roads[28] = {}
routes.ChequeredFlagRoute.roads[28].road = "marin_6l_west_01a AI Road 13"
routes.ChequeredFlagRoute.roads[28].direction = "against"
routes.ChequeredFlagRoute.roads[29] = {}
routes.ChequeredFlagRoute.roads[29].road = "marin_6l_west_01a AI Road 12"
routes.ChequeredFlagRoute.roads[29].direction = "against"
routes.ChequeredFlagRoute.roads[30] = {}
routes.ChequeredFlagRoute.roads[30].road = "marin_6l_west_01a AI Road 11"
routes.ChequeredFlagRoute.roads[30].direction = "against"
routes.ChequeredFlagRoute.roads[31] = {}
routes.ChequeredFlagRoute.roads[31].road = "marin_6l_west_01a AI Road 10"
routes.ChequeredFlagRoute.roads[31].direction = "against"
routes.ChequeredFlagRoute.roads[32] = {}
routes.ChequeredFlagRoute.roads[32].road = "marin_6l_west_01a AI Road 9"
routes.ChequeredFlagRoute.roads[32].direction = "against"
routes.ChequeredFlagRoute.roads[33] = {}
routes.ChequeredFlagRoute.roads[33].road = "marin_6l_west_01a AI Road 8"
routes.ChequeredFlagRoute.roads[33].direction = "against"
routes.ChequeredFlagRoute.roads[34] = {}
routes.ChequeredFlagRoute.roads[34].road = "marin_6l_west_01a AI Road 7"
routes.ChequeredFlagRoute.roads[34].direction = "against"
routes.ChequeredFlagRoute.roads[35] = {}
routes.ChequeredFlagRoute.roads[35].road = "marin_6l_west_01a AI Road 6"
routes.ChequeredFlagRoute.roads[35].direction = "against"
routes.ChequeredFlagRoute.roads[36] = {}
routes.ChequeredFlagRoute.roads[36].road = "marin_6l_west_01a AI Road 5"
routes.ChequeredFlagRoute.roads[36].direction = "against"
routes.ChequeredFlagRoute.roads[37] = {}
routes.ChequeredFlagRoute.roads[37].road = "marin_6l_west_01a AI Road 4"
routes.ChequeredFlagRoute.roads[37].direction = "against"
routes.ChequeredFlagRoute.roads[38] = {}
routes.ChequeredFlagRoute.roads[38].road = "marin_6l_west_01a AI Road 3"
routes.ChequeredFlagRoute.roads[38].direction = "against"
routes.ChequeredFlagRoute.roads[39] = {}
routes.ChequeredFlagRoute.roads[39].road = "marin_6l_west_01a AI Road 2"
routes.ChequeredFlagRoute.roads[39].direction = "against"
routes.ChequeredFlagRoute.roads[40] = {}
routes.ChequeredFlagRoute.roads[40].road = "marin_6l_west_01a AI Road 1"
routes.ChequeredFlagRoute.roads[40].direction = "against"
routes.ChequeredFlagRoute.roads[41] = {}
routes.ChequeredFlagRoute.roads[41].road = "marin_6l_west_01a AI Road 0"
routes.ChequeredFlagRoute.roads[41].direction = "against"
routes.ChequeredFlagRoute.roads[42] = {}
routes.ChequeredFlagRoute.roads[42].road = "marin_4l_west_02 AI Road 0"
routes.ChequeredFlagRoute.roads[42].direction = "with"
routes.ChequeredFlagRoute.roads[43] = {}
routes.ChequeredFlagRoute.roads[43].road = "marin_4l_west_02 AI Road 1"
routes.ChequeredFlagRoute.roads[43].direction = "with"
routes.ChequeredFlagRoute.roads[44] = {}
routes.ChequeredFlagRoute.roads[44].road = "marin_4l_west_02 AI Road 2"
routes.ChequeredFlagRoute.roads[44].direction = "with"
routes.ChequeredFlagRoute.roads[45] = {}
routes.ChequeredFlagRoute.roads[45].road = "marin_4l_west_02 AI Road 3"
routes.ChequeredFlagRoute.roads[45].direction = "with"
routes.ChequeredFlagRoute.roads[46] = {}
routes.ChequeredFlagRoute.roads[46].road = "marin_4l_west_02 AI Road 4"
routes.ChequeredFlagRoute.roads[46].direction = "with"
routes.ChequeredFlagRoute.roads[47] = {}
routes.ChequeredFlagRoute.roads[47].road = "marin_4l_west_02 AI Road 5"
routes.ChequeredFlagRoute.roads[47].direction = "with"
routes.ChequeredFlagRoute.roads[48] = {}
routes.ChequeredFlagRoute.roads[48].road = "marin_4l_west_02 AI Road 6"
routes.ChequeredFlagRoute.roads[48].direction = "with"
routes.ChequeredFlagRoute.roads[49] = {}
routes.ChequeredFlagRoute.roads[49].road = "marin_4l_west_02 AI Road 7"
routes.ChequeredFlagRoute.roads[49].direction = "with"
routes.ChequeredFlagRoute.roads[50] = {}
routes.ChequeredFlagRoute.roads[50].road = "marin_shortcut_14 AI Road 0"
routes.ChequeredFlagRoute.roads[50].direction = "with"
routes.ChequeredFlagRoute.roads[51] = {}
routes.ChequeredFlagRoute.roads[51].road = "mountain_10l_w_06 AI Road 5"
routes.ChequeredFlagRoute.roads[51].direction = "with"
routes.ChequeredFlagRoute.roads[52] = {}
routes.ChequeredFlagRoute.roads[52].road = "mountain_10l_w_06 AI Road 6"
routes.ChequeredFlagRoute.roads[52].direction = "with"
routes.ChequeredFlagRoute.roads[53] = {}
routes.ChequeredFlagRoute.roads[53].road = "mountain_10l_w_06 AI Road 7"
routes.ChequeredFlagRoute.roads[53].direction = "with"
routes.ChequeredFlagRoute.roads[54] = {}
routes.ChequeredFlagRoute.roads[54].road = "mountain_10l_w_06 AI Road 8"
routes.ChequeredFlagRoute.roads[54].direction = "with"
routes.ChequeredFlagRoute.roads[55] = {}
routes.ChequeredFlagRoute.roads[55].road = "mountain_10l_w_06 AI Road 9"
routes.ChequeredFlagRoute.roads[55].direction = "with"
routes.ChequeredFlagRoute.roads[56] = {}
routes.ChequeredFlagRoute.roads[56].road = "mountain_10l_w_06 AI Road 10"
routes.ChequeredFlagRoute.roads[56].direction = "with"
routes.ChequeredFlagRoute.roads[57] = {}
routes.ChequeredFlagRoute.roads[57].road = "mountain_10l_w_06 AI Road 11"
routes.ChequeredFlagRoute.roads[57].direction = "with"
routes.ChequeredFlagRoute.roads[58] = {}
routes.ChequeredFlagRoute.roads[58].road = "mountain_10l_w_06 AI Road 12"
routes.ChequeredFlagRoute.roads[58].direction = "with"
routes.ChequeredFlagRoute.roads[59] = {}
routes.ChequeredFlagRoute.roads[59].road = "mountain_10l_w_06 AI Road 13"
routes.ChequeredFlagRoute.roads[59].direction = "with"
routes.ChequeredFlagRoute.roads[60] = {}
routes.ChequeredFlagRoute.roads[60].road = "mountain_10l_w_06 AI Road 14"
routes.ChequeredFlagRoute.roads[60].direction = "with"
routes.ChequeredFlagRoute.roads[61] = {}
routes.ChequeredFlagRoute.roads[61].road = "mountain_10l_w_06 AI Road 15"
routes.ChequeredFlagRoute.roads[61].direction = "with"
routes.ChequeredFlagRoute.roads[62] = {}
routes.ChequeredFlagRoute.roads[62].road = "mountain_10l_w_01b AI Road 37"
routes.ChequeredFlagRoute.roads[62].direction = "against"
routes.ChequeredFlagRoute.roads[63] = {}
routes.ChequeredFlagRoute.roads[63].road = "mountain_10l_w_01b AI Road 36"
routes.ChequeredFlagRoute.roads[63].direction = "against"
routes.ChequeredFlagRoute.roads[64] = {}
routes.ChequeredFlagRoute.roads[64].road = "mountain_10l_w_01b AI Road 35"
routes.ChequeredFlagRoute.roads[64].direction = "against"
routes.ChequeredFlagRoute.roads[65] = {}
routes.ChequeredFlagRoute.roads[65].road = "mountain_10l_w_01b AI Road 34"
routes.ChequeredFlagRoute.roads[65].direction = "against"
routes.chflagwarmup = {}
routes.chflagwarmup.checkpoints = {}
routes.chflagwarmup.checkpoints[1] = {}
routes.chflagwarmup.checkpoints[1].position = vec.vector(1396.513, 45, -4749.438, 1)
routes.chflagwarmup.checkpoints[1].heading = -2.206371
routes.chflagwarmup.checkpoints[1].roadName = "mountain_10l_w_01b AI Road 13"
routes.chflagwarmup.checkpoints[2] = {}
routes.chflagwarmup.checkpoints[2].position = vec.vector(395.2874, 56.12431, -4596.02, 1)
routes.chflagwarmup.checkpoints[2].heading = -2.421246
routes.chflagwarmup.checkpoints[2].roadName = "marin_6l_west_01a AI Road 34"
routes.chflagwarmup.checkpoints[3] = {}
routes.chflagwarmup.checkpoints[3].position = vec.vector(-290.6282, 126.6118, -4764.011, 1)
routes.chflagwarmup.checkpoints[3].heading = -1.270091
routes.chflagwarmup.checkpoints[3].roadName = "marin_6l_west_01a AI Road 31"
routes.chflagwarmup.checkpoints[4] = {}
routes.chflagwarmup.checkpoints[4].position = vec.vector(-933.9968, 105.0952, -4554.238, 1)
routes.chflagwarmup.checkpoints[4].heading = -0.6689753
routes.chflagwarmup.checkpoints[4].roadName = "marin_6l_west_01a AI Road 26"
routes.chflagwarmup.checkpoints[5] = {}
routes.chflagwarmup.checkpoints[5].position = vec.vector(-1850.155, 155.6862, -4079.426, 1)
routes.chflagwarmup.checkpoints[5].heading = -1.232393
routes.chflagwarmup.checkpoints[5].roadName = "marin_6l_west_01a AI Road 18"
routes.chflagwarmup.checkpoints[6] = {}
routes.chflagwarmup.checkpoints[6].position = vec.vector(-2488.793, 165.1895, -3773.294, 1)
routes.chflagwarmup.checkpoints[6].heading = -1.113464
routes.chflagwarmup.checkpoints[6].roadName = "marin_6l_west_01a AI Road 11"
routes.chflagwarmup.checkpoints[7] = {}
routes.chflagwarmup.checkpoints[7].position = vec.vector(-3393.183, 186.3281, -3793.276, 1)
routes.chflagwarmup.checkpoints[7].heading = -1.647151
routes.chflagwarmup.checkpoints[7].roadName = "marin_6l_west_01a AI Road 4"
routes.chflagwarmup.checkpoints[8] = {}
routes.chflagwarmup.checkpoints[8].position = vec.vector(-3522.487, 125, -2802.362, 1)
routes.chflagwarmup.checkpoints[8].heading = -0.2405635
routes.chflagwarmup.checkpoints[8].roadName = "marin_4l_west_02 AI Road 0"
routes.chflagwarmup.checkpoints[9] = {}
routes.chflagwarmup.checkpoints[9].position = vec.vector(-3695.391, 117.0764, -2379.809, 1)
routes.chflagwarmup.checkpoints[9].heading = -1.321953
routes.chflagwarmup.checkpoints[9].roadName = "marin_4l_west_02 AI Road 2"
routes.chflagwarmup.checkpoints[10] = {}
routes.chflagwarmup.checkpoints[10].position = vec.vector(-4143.998, 124.5737, -2703.205, 1)
routes.chflagwarmup.checkpoints[10].heading = -0.8511664
routes.chflagwarmup.checkpoints[10].roadName = "marin_4l_west_02 AI Road 4"
routes.chflagwarmup.checkpoints[11] = {}
routes.chflagwarmup.checkpoints[11].position = vec.vector(-3713.272, 74.40627, -2182.214, 1)
routes.chflagwarmup.checkpoints[11].heading = 0.4781407
routes.chflagwarmup.checkpoints[11].roadName = "marin_shortcut_14 AI Road 0"
routes.chflagwarmup.checkpoints[12] = {}
routes.chflagwarmup.checkpoints[12].position = vec.vector(-3712.657, 63.77362, -1790.923, 1)
routes.chflagwarmup.checkpoints[12].heading = -0.3244702
routes.chflagwarmup.checkpoints[12].roadName = "mountain_10l_w_06 AI Road 6"
routes.chflagwarmup.checkpoints[13] = {}
routes.chflagwarmup.checkpoints[13].position = vec.vector(-3075.27, 23.26985, -1480.027, 1)
routes.chflagwarmup.checkpoints[13].heading = 1.320034
routes.chflagwarmup.checkpoints[13].roadName = "mountain_10l_w_06 AI Road 9"
routes.chflagwarmup.checkpoints[14] = {}
routes.chflagwarmup.checkpoints[14].position = vec.vector(-2248.455, 13.98311, -2102.976, 1)
routes.chflagwarmup.checkpoints[14].heading = 2.625887
routes.chflagwarmup.checkpoints[14].roadName = "mountain_10l_w_06 AI Road 14"
routes.chflagwarmup.checkpoints[15] = {}
routes.chflagwarmup.checkpoints[15].position = vec.vector(-1437.612, 8.25, -2560.523, 1)
routes.chflagwarmup.checkpoints[15].heading = 2.168173
routes.chflagwarmup.checkpoints[15].roadName = "mountain_10l_w_01b AI Road 34"
routes.chflagwarmup.checkpoints[16] = {}
routes.chflagwarmup.checkpoints[16].position = vec.vector(-1067.193, 24.50012, -2895.76, 1)
routes.chflagwarmup.checkpoints[16].heading = 0.7841465
routes.chflagwarmup.checkpoints[16].roadName = "mountain_6l_east_08 AI Road 0"
routes.chflagwarmup.checkpoints[17] = {}
routes.chflagwarmup.checkpoints[17].position = vec.vector(345.7808, 6.949999, -2354.118, 1)
routes.chflagwarmup.checkpoints[17].heading = 1.553671
routes.chflagwarmup.checkpoints[17].roadName = "highway02_03 AI Road 16"
routes.chflagwarmup.checkpoints[18] = {}
routes.chflagwarmup.checkpoints[18].position = vec.vector(612.082, 6.949995, -2469.476, 1)
routes.chflagwarmup.checkpoints[18].heading = 2.766831
routes.chflagwarmup.checkpoints[18].roadName = "highway02_03 AI Road 20"
routes.chflagwarmup.checkpoints[19] = {}
routes.chflagwarmup.checkpoints[19].position = vec.vector(745.1931, 34.23691, -3255.238, 1)
routes.chflagwarmup.checkpoints[19].heading = 2.123659
routes.chflagwarmup.checkpoints[19].roadName = "mountain_10l_w_01b AI Road 0"
routes.chflagwarmup.checkpoints[20] = {}
routes.chflagwarmup.checkpoints[20].position = vec.vector(1679.99, 40, -3600, 1)
routes.chflagwarmup.checkpoints[20].heading = 1.570796
routes.chflagwarmup.checkpoints[20].roadName = "mountain_10l_w_01b AI Road 4"
routes.chflagwarmup.checkpoints[21] = {}
routes.chflagwarmup.checkpoints[21].position = vec.vector(2275, 40, -3966.386, 1)
routes.chflagwarmup.checkpoints[21].heading = 3.141593
routes.chflagwarmup.checkpoints[21].roadName = "mountain_10l_w_01b AI Road 9"
routes.chflagwarmup.checkpoints[22] = {}
routes.chflagwarmup.checkpoints[22].position = vec.vector(1725.97, 45, -4348.3, 1)
routes.chflagwarmup.checkpoints[22].heading = -1.798274
routes.chflagwarmup.checkpoints[22].roadName = "mountain_10l_w_01b AI Road 12"
routes.chflagwarmup.arrows = {}
routes.chflagwarmup.roads = {}
routes.chflagwarmup.roads[1] = {}
routes.chflagwarmup.roads[1].road = "mountain_10l_w_01b AI Road 13"
routes.chflagwarmup.roads[1].direction = "with"
routes.chflagwarmup.roads[2] = {}
routes.chflagwarmup.roads[2].road = "mountain_10l_w_01b AI Road 14"
routes.chflagwarmup.roads[2].direction = "with"
routes.chflagwarmup.roads[3] = {}
routes.chflagwarmup.roads[3].road = "mountain_10l_w_01b AI Road 15"
routes.chflagwarmup.roads[3].direction = "with"
routes.chflagwarmup.roads[4] = {}
routes.chflagwarmup.roads[4].road = "mountain_10l_w_01b AI Road 16"
routes.chflagwarmup.roads[4].direction = "with"
routes.chflagwarmup.roads[5] = {}
routes.chflagwarmup.roads[5].road = "marin_6l_west_01a AI Road 35"
routes.chflagwarmup.roads[5].direction = "against"
routes.chflagwarmup.roads[6] = {}
routes.chflagwarmup.roads[6].road = "marin_6l_west_01a AI Road 34"
routes.chflagwarmup.roads[6].direction = "against"
routes.chflagwarmup.roads[7] = {}
routes.chflagwarmup.roads[7].road = "marin_6l_west_01a AI Road 33"
routes.chflagwarmup.roads[7].direction = "against"
routes.chflagwarmup.roads[8] = {}
routes.chflagwarmup.roads[8].road = "marin_6l_west_01a AI Road 32"
routes.chflagwarmup.roads[8].direction = "against"
routes.chflagwarmup.roads[9] = {}
routes.chflagwarmup.roads[9].road = "marin_6l_west_01a AI Road 31"
routes.chflagwarmup.roads[9].direction = "against"
routes.chflagwarmup.roads[10] = {}
routes.chflagwarmup.roads[10].road = "marin_6l_west_01a AI Road 30"
routes.chflagwarmup.roads[10].direction = "against"
routes.chflagwarmup.roads[11] = {}
routes.chflagwarmup.roads[11].road = "marin_6l_west_01a AI Road 29"
routes.chflagwarmup.roads[11].direction = "against"
routes.chflagwarmup.roads[12] = {}
routes.chflagwarmup.roads[12].road = "marin_6l_west_01a AI Road 28"
routes.chflagwarmup.roads[12].direction = "against"
routes.chflagwarmup.roads[13] = {}
routes.chflagwarmup.roads[13].road = "marin_6l_west_01a AI Road 27"
routes.chflagwarmup.roads[13].direction = "against"
routes.chflagwarmup.roads[14] = {}
routes.chflagwarmup.roads[14].road = "marin_6l_west_01a AI Road 26"
routes.chflagwarmup.roads[14].direction = "against"
routes.chflagwarmup.roads[15] = {}
routes.chflagwarmup.roads[15].road = "marin_6l_west_01a AI Road 25"
routes.chflagwarmup.roads[15].direction = "against"
routes.chflagwarmup.roads[16] = {}
routes.chflagwarmup.roads[16].road = "marin_6l_west_01a AI Road 24"
routes.chflagwarmup.roads[16].direction = "against"
routes.chflagwarmup.roads[17] = {}
routes.chflagwarmup.roads[17].road = "marin_6l_west_01a AI Road 23"
routes.chflagwarmup.roads[17].direction = "against"
routes.chflagwarmup.roads[18] = {}
routes.chflagwarmup.roads[18].road = "marin_6l_west_01a AI Road 22"
routes.chflagwarmup.roads[18].direction = "against"
routes.chflagwarmup.roads[19] = {}
routes.chflagwarmup.roads[19].road = "marin_6l_west_01a AI Road 21"
routes.chflagwarmup.roads[19].direction = "against"
routes.chflagwarmup.roads[20] = {}
routes.chflagwarmup.roads[20].road = "marin_6l_west_01a AI Road 20"
routes.chflagwarmup.roads[20].direction = "against"
routes.chflagwarmup.roads[21] = {}
routes.chflagwarmup.roads[21].road = "marin_6l_west_01a AI Road 19"
routes.chflagwarmup.roads[21].direction = "against"
routes.chflagwarmup.roads[22] = {}
routes.chflagwarmup.roads[22].road = "marin_6l_west_01a AI Road 18"
routes.chflagwarmup.roads[22].direction = "against"
routes.chflagwarmup.roads[23] = {}
routes.chflagwarmup.roads[23].road = "marin_6l_west_01a AI Road 17"
routes.chflagwarmup.roads[23].direction = "against"
routes.chflagwarmup.roads[24] = {}
routes.chflagwarmup.roads[24].road = "marin_6l_west_01a AI Road 16"
routes.chflagwarmup.roads[24].direction = "against"
routes.chflagwarmup.roads[25] = {}
routes.chflagwarmup.roads[25].road = "marin_6l_west_01a AI Road 15"
routes.chflagwarmup.roads[25].direction = "against"
routes.chflagwarmup.roads[26] = {}
routes.chflagwarmup.roads[26].road = "marin_6l_west_01a AI Road 14"
routes.chflagwarmup.roads[26].direction = "against"
routes.chflagwarmup.roads[27] = {}
routes.chflagwarmup.roads[27].road = "marin_6l_west_01a AI Road 13"
routes.chflagwarmup.roads[27].direction = "against"
routes.chflagwarmup.roads[28] = {}
routes.chflagwarmup.roads[28].road = "marin_6l_west_01a AI Road 12"
routes.chflagwarmup.roads[28].direction = "against"
routes.chflagwarmup.roads[29] = {}
routes.chflagwarmup.roads[29].road = "marin_6l_west_01a AI Road 11"
routes.chflagwarmup.roads[29].direction = "against"
routes.chflagwarmup.roads[30] = {}
routes.chflagwarmup.roads[30].road = "marin_6l_west_01a AI Road 10"
routes.chflagwarmup.roads[30].direction = "against"
routes.chflagwarmup.roads[31] = {}
routes.chflagwarmup.roads[31].road = "marin_6l_west_01a AI Road 9"
routes.chflagwarmup.roads[31].direction = "against"
routes.chflagwarmup.roads[32] = {}
routes.chflagwarmup.roads[32].road = "marin_6l_west_01a AI Road 8"
routes.chflagwarmup.roads[32].direction = "against"
routes.chflagwarmup.roads[33] = {}
routes.chflagwarmup.roads[33].road = "marin_6l_west_01a AI Road 7"
routes.chflagwarmup.roads[33].direction = "against"
routes.chflagwarmup.roads[34] = {}
routes.chflagwarmup.roads[34].road = "marin_6l_west_01a AI Road 6"
routes.chflagwarmup.roads[34].direction = "against"
routes.chflagwarmup.roads[35] = {}
routes.chflagwarmup.roads[35].road = "marin_6l_west_01a AI Road 5"
routes.chflagwarmup.roads[35].direction = "against"
routes.chflagwarmup.roads[36] = {}
routes.chflagwarmup.roads[36].road = "marin_6l_west_01a AI Road 4"
routes.chflagwarmup.roads[36].direction = "against"
routes.chflagwarmup.roads[37] = {}
routes.chflagwarmup.roads[37].road = "marin_6l_west_01a AI Road 3"
routes.chflagwarmup.roads[37].direction = "against"
routes.chflagwarmup.roads[38] = {}
routes.chflagwarmup.roads[38].road = "marin_6l_west_01a AI Road 2"
routes.chflagwarmup.roads[38].direction = "against"
routes.chflagwarmup.roads[39] = {}
routes.chflagwarmup.roads[39].road = "marin_6l_west_01a AI Road 1"
routes.chflagwarmup.roads[39].direction = "against"
routes.chflagwarmup.roads[40] = {}
routes.chflagwarmup.roads[40].road = "marin_6l_west_01a AI Road 0"
routes.chflagwarmup.roads[40].direction = "against"
routes.chflagwarmup.roads[41] = {}
routes.chflagwarmup.roads[41].road = "marin_4l_west_02 AI Road 0"
routes.chflagwarmup.roads[41].direction = "with"
routes.chflagwarmup.roads[42] = {}
routes.chflagwarmup.roads[42].road = "marin_4l_west_02 AI Road 1"
routes.chflagwarmup.roads[42].direction = "with"
routes.chflagwarmup.roads[43] = {}
routes.chflagwarmup.roads[43].road = "marin_4l_west_02 AI Road 2"
routes.chflagwarmup.roads[43].direction = "with"
routes.chflagwarmup.roads[44] = {}
routes.chflagwarmup.roads[44].road = "marin_4l_west_02 AI Road 3"
routes.chflagwarmup.roads[44].direction = "with"
routes.chflagwarmup.roads[45] = {}
routes.chflagwarmup.roads[45].road = "marin_4l_west_02 AI Road 4"
routes.chflagwarmup.roads[45].direction = "with"
routes.chflagwarmup.roads[46] = {}
routes.chflagwarmup.roads[46].road = "marin_4l_west_02 AI Road 5"
routes.chflagwarmup.roads[46].direction = "with"
routes.chflagwarmup.roads[47] = {}
routes.chflagwarmup.roads[47].road = "marin_4l_west_02 AI Road 6"
routes.chflagwarmup.roads[47].direction = "with"
routes.chflagwarmup.roads[48] = {}
routes.chflagwarmup.roads[48].road = "marin_4l_west_02 AI Road 7"
routes.chflagwarmup.roads[48].direction = "with"
routes.chflagwarmup.roads[49] = {}
routes.chflagwarmup.roads[49].road = "marin_shortcut_14 AI Road 0"
routes.chflagwarmup.roads[49].direction = "with"
routes.chflagwarmup.roads[50] = {}
routes.chflagwarmup.roads[50].road = "mountain_10l_w_06 AI Road 5"
routes.chflagwarmup.roads[50].direction = "with"
routes.chflagwarmup.roads[51] = {}
routes.chflagwarmup.roads[51].road = "mountain_10l_w_06 AI Road 6"
routes.chflagwarmup.roads[51].direction = "with"
routes.chflagwarmup.roads[52] = {}
routes.chflagwarmup.roads[52].road = "mountain_10l_w_06 AI Road 7"
routes.chflagwarmup.roads[52].direction = "with"
routes.chflagwarmup.roads[53] = {}
routes.chflagwarmup.roads[53].road = "mountain_10l_w_06 AI Road 8"
routes.chflagwarmup.roads[53].direction = "with"
routes.chflagwarmup.roads[54] = {}
routes.chflagwarmup.roads[54].road = "mountain_10l_w_06 AI Road 9"
routes.chflagwarmup.roads[54].direction = "with"
routes.chflagwarmup.roads[55] = {}
routes.chflagwarmup.roads[55].road = "mountain_10l_w_06 AI Road 10"
routes.chflagwarmup.roads[55].direction = "with"
routes.chflagwarmup.roads[56] = {}
routes.chflagwarmup.roads[56].road = "mountain_10l_w_06 AI Road 11"
routes.chflagwarmup.roads[56].direction = "with"
routes.chflagwarmup.roads[57] = {}
routes.chflagwarmup.roads[57].road = "mountain_10l_w_06 AI Road 12"
routes.chflagwarmup.roads[57].direction = "with"
routes.chflagwarmup.roads[58] = {}
routes.chflagwarmup.roads[58].road = "mountain_10l_w_06 AI Road 13"
routes.chflagwarmup.roads[58].direction = "with"
routes.chflagwarmup.roads[59] = {}
routes.chflagwarmup.roads[59].road = "mountain_10l_w_06 AI Road 14"
routes.chflagwarmup.roads[59].direction = "with"
routes.chflagwarmup.roads[60] = {}
routes.chflagwarmup.roads[60].road = "mountain_10l_w_06 AI Road 15"
routes.chflagwarmup.roads[60].direction = "with"
routes.chflagwarmup.roads[61] = {}
routes.chflagwarmup.roads[61].road = "mountain_10l_w_01b AI Road 37"
routes.chflagwarmup.roads[61].direction = "against"
routes.chflagwarmup.roads[62] = {}
routes.chflagwarmup.roads[62].road = "mountain_10l_w_01b AI Road 36"
routes.chflagwarmup.roads[62].direction = "against"
routes.chflagwarmup.roads[63] = {}
routes.chflagwarmup.roads[63].road = "mountain_10l_w_01b AI Road 35"
routes.chflagwarmup.roads[63].direction = "against"
routes.chflagwarmup.roads[64] = {}
routes.chflagwarmup.roads[64].road = "mountain_10l_w_01b AI Road 34"
routes.chflagwarmup.roads[64].direction = "against"
routes.chflagwarmup.roads[65] = {}
routes.chflagwarmup.roads[65].road = "mountain_10l_w_01b AI Road 33"
routes.chflagwarmup.roads[65].direction = "against"
routes.chflagwarmup.roads[66] = {}
routes.chflagwarmup.roads[66].road = "mountain_10l_w_01b AI Road 32"
routes.chflagwarmup.roads[66].direction = "against"
routes.chflagwarmup.roads[67] = {}
routes.chflagwarmup.roads[67].road = "mountain_10l_w_01b AI Road 31"
routes.chflagwarmup.roads[67].direction = "against"
routes.chflagwarmup.roads[68] = {}
routes.chflagwarmup.roads[68].road = "mountain_10l_w_01b AI Road 30"
routes.chflagwarmup.roads[68].direction = "against"
routes.chflagwarmup.roads[69] = {}
routes.chflagwarmup.roads[69].road = "mountain_6l_east_08 AI Road 0"
routes.chflagwarmup.roads[69].direction = "with"
routes.chflagwarmup.roads[70] = {}
routes.chflagwarmup.roads[70].road = "marin_shortcut_40 AI Road 0"
routes.chflagwarmup.roads[70].direction = "with"
routes.chflagwarmup.roads[71] = {}
routes.chflagwarmup.roads[71].road = "highway02_03 AI Road 10"
routes.chflagwarmup.roads[71].direction = "with"
routes.chflagwarmup.roads[72] = {}
routes.chflagwarmup.roads[72].road = "highway02_03 AI Road 11"
routes.chflagwarmup.roads[72].direction = "with"
routes.chflagwarmup.roads[73] = {}
routes.chflagwarmup.roads[73].road = "highway02_03 AI Road 12"
routes.chflagwarmup.roads[73].direction = "with"
routes.chflagwarmup.roads[74] = {}
routes.chflagwarmup.roads[74].road = "highway02_03 AI Road 13"
routes.chflagwarmup.roads[74].direction = "with"
routes.chflagwarmup.roads[75] = {}
routes.chflagwarmup.roads[75].road = "highway02_03 AI Road 14"
routes.chflagwarmup.roads[75].direction = "with"
routes.chflagwarmup.roads[76] = {}
routes.chflagwarmup.roads[76].road = "highway02_03 AI Road 15"
routes.chflagwarmup.roads[76].direction = "with"
routes.chflagwarmup.roads[77] = {}
routes.chflagwarmup.roads[77].road = "highway02_03 AI Road 16"
routes.chflagwarmup.roads[77].direction = "with"
routes.chflagwarmup.roads[78] = {}
routes.chflagwarmup.roads[78].road = "highway02_03 AI Road 17"
routes.chflagwarmup.roads[78].direction = "with"
routes.chflagwarmup.roads[79] = {}
routes.chflagwarmup.roads[79].road = "highway02_03 AI Road 18"
routes.chflagwarmup.roads[79].direction = "with"
routes.chflagwarmup.roads[80] = {}
routes.chflagwarmup.roads[80].road = "highway02_03 AI Road 19"
routes.chflagwarmup.roads[80].direction = "with"
routes.chflagwarmup.roads[81] = {}
routes.chflagwarmup.roads[81].road = "highway02_03 AI Road 20"
routes.chflagwarmup.roads[81].direction = "with"
routes.chflagwarmup.roads[82] = {}
routes.chflagwarmup.roads[82].road = "highway02_03 AI Road 21"
routes.chflagwarmup.roads[82].direction = "with"
routes.chflagwarmup.roads[83] = {}
routes.chflagwarmup.roads[83].road = "highway02_03 AI Road 22"
routes.chflagwarmup.roads[83].direction = "with"
routes.chflagwarmup.roads[84] = {}
routes.chflagwarmup.roads[84].road = "marin_complex_03 AI Road 0"
routes.chflagwarmup.roads[84].direction = "with"
routes.chflagwarmup.roads[85] = {}
routes.chflagwarmup.roads[85].road = "mountain_10l_w_01b AI Road 0"
routes.chflagwarmup.roads[85].direction = "with"
routes.chflagwarmup.roads[86] = {}
routes.chflagwarmup.roads[86].road = "mountain_10l_w_01b AI Road 1"
routes.chflagwarmup.roads[86].direction = "with"
routes.chflagwarmup.roads[87] = {}
routes.chflagwarmup.roads[87].road = "mountain_10l_w_01b AI Road 2"
routes.chflagwarmup.roads[87].direction = "with"
routes.chflagwarmup.roads[88] = {}
routes.chflagwarmup.roads[88].road = "mountain_10l_w_01b AI Road 3"
routes.chflagwarmup.roads[88].direction = "with"
routes.chflagwarmup.roads[89] = {}
routes.chflagwarmup.roads[89].road = "mountain_10l_w_01b AI Road 4"
routes.chflagwarmup.roads[89].direction = "with"
routes.chflagwarmup.roads[90] = {}
routes.chflagwarmup.roads[90].road = "mountain_10l_w_01b AI Road 5"
routes.chflagwarmup.roads[90].direction = "with"
routes.chflagwarmup.roads[91] = {}
routes.chflagwarmup.roads[91].road = "mountain_10l_w_01b AI Road 6"
routes.chflagwarmup.roads[91].direction = "with"
routes.chflagwarmup.roads[92] = {}
routes.chflagwarmup.roads[92].road = "mountain_10l_w_01b AI Road 7"
routes.chflagwarmup.roads[92].direction = "with"
routes.chflagwarmup.roads[93] = {}
routes.chflagwarmup.roads[93].road = "mountain_10l_w_01b AI Road 8"
routes.chflagwarmup.roads[93].direction = "with"
routes.chflagwarmup.roads[94] = {}
routes.chflagwarmup.roads[94].road = "mountain_10l_w_01b AI Road 9"
routes.chflagwarmup.roads[94].direction = "with"
routes.chflagwarmup.roads[95] = {}
routes.chflagwarmup.roads[95].road = "mountain_10l_w_01b AI Road 10"
routes.chflagwarmup.roads[95].direction = "with"
routes.chflagwarmup.roads[96] = {}
routes.chflagwarmup.roads[96].road = "mountain_10l_w_01b AI Road 11"
routes.chflagwarmup.roads[96].direction = "with"
routes.chflagwarmup.roads[97] = {}
routes.chflagwarmup.roads[97].road = "mountain_10l_w_01b AI Road 12"
routes.chflagwarmup.roads[97].direction = "with"
