routes = routes or {}
routes["Mass chase 1 warmup"] = {}
routes["Mass chase 1 warmup"].checkpoints = {}
routes["Mass chase 1 warmup"].checkpoints[1] = {}
routes["Mass chase 1 warmup"].checkpoints[1].position = vec.vector(-1227.889, 172.6375, 3999.186, 1)
routes["Mass chase 1 warmup"].checkpoints[1].heading = -2.819985
routes["Mass chase 1 warmup"].checkpoints[1].roadName = "sutro_4l_south_03 AI Road 2"
routes["Mass chase 1 warmup"].checkpoints[2] = {}
routes["Mass chase 1 warmup"].checkpoints[2].position = vec.vector(-1290.811, 167.6205, 3608.865, 1)
routes["Mass chase 1 warmup"].checkpoints[2].heading = -1.570485
routes["Mass chase 1 warmup"].checkpoints[2].roadName = "sutro_6l_south_02 AI Road 3"
routes["Mass chase 1 warmup"].checkpoints[3] = {}
routes["Mass chase 1 warmup"].checkpoints[3].position = vec.vector(-1396.746, 177.25, 3636.746, 1)
routes["Mass chase 1 warmup"].checkpoints[3].heading = -0.1572992
routes["Mass chase 1 warmup"].checkpoints[3].roadName = "sutro_4l_south_01 AI Road 3"
routes["Mass chase 1 warmup"].checkpoints[4] = {}
routes["Mass chase 1 warmup"].checkpoints[4].position = vec.vector(-1619.552, 181.3676, 4017.81, 1)
routes["Mass chase 1 warmup"].checkpoints[4].heading = -1.141812
routes["Mass chase 1 warmup"].checkpoints[4].roadName = "sutro_shortcut_23 AI Road 0"
routes["Mass chase 1 warmup"].checkpoints[5] = {}
routes["Mass chase 1 warmup"].checkpoints[5].position = vec.vector(-1329.315, 176.6617, 4145.251, 1)
routes["Mass chase 1 warmup"].checkpoints[5].heading = 1.63123
routes["Mass chase 1 warmup"].checkpoints[5].roadName = "sutro_south_main AI Road 23"
routes["Mass chase 1 warmup"].arrows = {}
routes["Mass chase 1 warmup"].roads = {}
routes["Mass chase 1 warmup"].roads[1] = {}
routes["Mass chase 1 warmup"].roads[1].road = "sutro_4l_south_03 AI Road 2"
routes["Mass chase 1 warmup"].roads[1].direction = "against"
routes["Mass chase 1 warmup"].roads[2] = {}
routes["Mass chase 1 warmup"].roads[2].road = "sutro_4l_south_03 AI Road 1"
routes["Mass chase 1 warmup"].roads[2].direction = "against"
routes["Mass chase 1 warmup"].roads[3] = {}
routes["Mass chase 1 warmup"].roads[3].road = "sutro_4l_south_03 AI Road 0"
routes["Mass chase 1 warmup"].roads[3].direction = "against"
routes["Mass chase 1 warmup"].roads[4] = {}
routes["Mass chase 1 warmup"].roads[4].road = "sutro_6l_south_02 AI Road 3"
routes["Mass chase 1 warmup"].roads[4].direction = "against"
routes["Mass chase 1 warmup"].roads[5] = {}
routes["Mass chase 1 warmup"].roads[5].road = "sutro_4l_south_01 AI Road 3"
routes["Mass chase 1 warmup"].roads[5].direction = "against"
routes["Mass chase 1 warmup"].roads[6] = {}
routes["Mass chase 1 warmup"].roads[6].road = "sutro_4l_south_01 AI Road 2"
routes["Mass chase 1 warmup"].roads[6].direction = "against"
routes["Mass chase 1 warmup"].roads[7] = {}
routes["Mass chase 1 warmup"].roads[7].road = "sutro_shortcut_23 AI Road 0"
routes["Mass chase 1 warmup"].roads[7].direction = "with"
routes["Mass chase 1 warmup"].roads[8] = {}
routes["Mass chase 1 warmup"].roads[8].road = "sutro_south_main AI Road 22"
routes["Mass chase 1 warmup"].roads[8].direction = "with"
routes["Mass chase 1 warmup"].roads[9] = {}
routes["Mass chase 1 warmup"].roads[9].road = "sutro_south_main AI Road 23"
routes["Mass chase 1 warmup"].roads[9].direction = "with"
routes["Mass chase 1 truck"] = {}
routes["Mass chase 1 truck"].checkpoints = {}
routes["Mass chase 1 truck"].checkpoints[1] = {}
routes["Mass chase 1 truck"].checkpoints[1].position = vec.vector(260.6146, 51.84504, 2611.179, 1)
routes["Mass chase 1 truck"].checkpoints[1].heading = 2.084353
routes["Mass chase 1 truck"].checkpoints[1].roadName = "highway01_16b AI Road 16"
routes["Mass chase 1 truck"].checkpoints[2] = {}
routes["Mass chase 1 truck"].checkpoints[2].position = vec.vector(2203.034, 48.57023, 1304.92, 1)
routes["Mass chase 1 truck"].checkpoints[2].heading = 1.999851
routes["Mass chase 1 truck"].checkpoints[2].roadName = "highway01_16b AI Road 24"
routes["Mass chase 1 truck"].arrows = {}
routes["Mass chase 1 truck"].roads = {}
routes["Mass chase 1 truck"].roads[1] = {}
routes["Mass chase 1 truck"].roads[1].road = "highway01_16b AI Road 5"
routes["Mass chase 1 truck"].roads[1].direction = "with"
routes["Mass chase 1 truck"].roads[2] = {}
routes["Mass chase 1 truck"].roads[2].road = "highway01_16b AI Road 6"
routes["Mass chase 1 truck"].roads[2].direction = "with"
routes["Mass chase 1 truck"].roads[3] = {}
routes["Mass chase 1 truck"].roads[3].road = "highway01_16b AI Road 7"
routes["Mass chase 1 truck"].roads[3].direction = "with"
routes["Mass chase 1 truck"].roads[4] = {}
routes["Mass chase 1 truck"].roads[4].road = "highway01_16b AI Road 8"
routes["Mass chase 1 truck"].roads[4].direction = "with"
routes["Mass chase 1 truck"].roads[5] = {}
routes["Mass chase 1 truck"].roads[5].road = "highway01_16b AI Road 9"
routes["Mass chase 1 truck"].roads[5].direction = "with"
routes["Mass chase 1 truck"].roads[6] = {}
routes["Mass chase 1 truck"].roads[6].road = "highway01_16b AI Road 10"
routes["Mass chase 1 truck"].roads[6].direction = "with"
routes["Mass chase 1 truck"].roads[7] = {}
routes["Mass chase 1 truck"].roads[7].road = "highway01_16b AI Road 11"
routes["Mass chase 1 truck"].roads[7].direction = "with"
routes["Mass chase 1 truck"].roads[8] = {}
routes["Mass chase 1 truck"].roads[8].road = "highway01_16b AI Road 12"
routes["Mass chase 1 truck"].roads[8].direction = "with"
routes["Mass chase 1 truck"].roads[9] = {}
routes["Mass chase 1 truck"].roads[9].road = "highway01_16b AI Road 13"
routes["Mass chase 1 truck"].roads[9].direction = "with"
routes["Mass chase 1 truck"].roads[10] = {}
routes["Mass chase 1 truck"].roads[10].road = "highway01_16b AI Road 14"
routes["Mass chase 1 truck"].roads[10].direction = "with"
routes["Mass chase 1 truck"].roads[11] = {}
routes["Mass chase 1 truck"].roads[11].road = "highway01_16b AI Road 15"
routes["Mass chase 1 truck"].roads[11].direction = "with"
routes["Mass chase 1 truck"].roads[12] = {}
routes["Mass chase 1 truck"].roads[12].road = "highway01_16b AI Road 16"
routes["Mass chase 1 truck"].roads[12].direction = "with"
routes["Mass chase 1 truck"].roads[13] = {}
routes["Mass chase 1 truck"].roads[13].road = "highway01_16b AI Road 17"
routes["Mass chase 1 truck"].roads[13].direction = "with"
routes["Mass chase 1 truck"].roads[14] = {}
routes["Mass chase 1 truck"].roads[14].road = "highway01_16b AI Road 18"
routes["Mass chase 1 truck"].roads[14].direction = "with"
routes["Mass chase 1 truck"].roads[15] = {}
routes["Mass chase 1 truck"].roads[15].road = "highway01_16b AI Road 19"
routes["Mass chase 1 truck"].roads[15].direction = "with"
routes["Mass chase 1 truck"].roads[16] = {}
routes["Mass chase 1 truck"].roads[16].road = "highway01_16b AI Road 20"
routes["Mass chase 1 truck"].roads[16].direction = "with"
routes["Mass chase 1 truck"].roads[17] = {}
routes["Mass chase 1 truck"].roads[17].road = "highway01_16b AI Road 21"
routes["Mass chase 1 truck"].roads[17].direction = "with"
routes["Mass chase 1 truck"].roads[18] = {}
routes["Mass chase 1 truck"].roads[18].road = "highway01_16b AI Road 22"
routes["Mass chase 1 truck"].roads[18].direction = "with"
routes["Mass chase 1 truck"].roads[19] = {}
routes["Mass chase 1 truck"].roads[19].road = "highway01_16b AI Road 23"
routes["Mass chase 1 truck"].roads[19].direction = "with"
routes["Mass chase 1 truck"].roads[20] = {}
routes["Mass chase 1 truck"].roads[20].road = "highway01_16b AI Road 24"
routes["Mass chase 1 truck"].roads[20].direction = "with"
