routes = routes or {}
routes["Tanner and Jones 7 Leila Route"] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[1] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[1].position = vec.vector(-93.98701, 32.4202, -2958.819, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[1].heading = -2.171449
routes["Tanner and Jones 7 Leila Route"].checkpoints[1].roadName = "marin_sliproad_17 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].checkpoints[2] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[2].position = vec.vector(-1958.091, 150, -3773.855, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[2].heading = -1.571033
routes["Tanner and Jones 7 Leila Route"].checkpoints[2].roadName = "highway01_15 AI Road 33"
routes["Tanner and Jones 7 Leila Route"].checkpoints[3] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[3].position = vec.vector(-2385.423, 154, -3580.84, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[3].heading = -0.9251494
routes["Tanner and Jones 7 Leila Route"].checkpoints[3].roadName = "highway01_15 AI Road 29"
routes["Tanner and Jones 7 Leila Route"].checkpoints[4] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[4].position = vec.vector(-2871.861, 102.0371, -3007.145, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[4].heading = -1.19046
routes["Tanner and Jones 7 Leila Route"].checkpoints[4].roadName = "highway01_15 AI Road 24"
routes["Tanner and Jones 7 Leila Route"].checkpoints[5] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[5].position = vec.vector(-3069.95, 69.96815, -804.465, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[5].heading = -0.1760353
routes["Tanner and Jones 7 Leila Route"].checkpoints[5].roadName = "highway01_15 AI Road 8"
routes["Tanner and Jones 7 Leila Route"].checkpoints[6] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[6].position = vec.vector(-2864.555, 45.93387, 219.6433, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[6].heading = 1.339414
routes["Tanner and Jones 7 Leila Route"].checkpoints[6].roadName = "highway01_15 AI Road 4"
routes["Tanner and Jones 7 Leila Route"].checkpoints[7] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[7].position = vec.vector(-2323.057, 47.25, 352.8412, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[7].heading = 1.33266
routes["Tanner and Jones 7 Leila Route"].checkpoints[7].roadName = "highway01_15 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].checkpoints[8] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[8].position = vec.vector(-1043.766, 57, 1086.926, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[8].heading = 0.3726756
routes["Tanner and Jones 7 Leila Route"].checkpoints[8].roadName = "highway01_16b AI Road 1"
routes["Tanner and Jones 7 Leila Route"].checkpoints[9] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[9].position = vec.vector(-409.8523, 76.36531, 2681.487, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[9].heading = 0.840254
routes["Tanner and Jones 7 Leila Route"].checkpoints[9].roadName = "highway01_16b AI Road 10"
routes["Tanner and Jones 7 Leila Route"].checkpoints[10] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[10].position = vec.vector(178.969, 52.1075, 2656.804, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[10].heading = 2.056976
routes["Tanner and Jones 7 Leila Route"].checkpoints[10].roadName = "highway01_16b AI Road 16"
routes["Tanner and Jones 7 Leila Route"].checkpoints[11] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[11].position = vec.vector(2810.076, 5.985681, -1984.653, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[11].heading = -2.695998
routes["Tanner and Jones 7 Leila Route"].checkpoints[11].roadName = "highway01_15 AI Road 61"
routes["Tanner and Jones 7 Leila Route"].checkpoints[12] = {}
routes["Tanner and Jones 7 Leila Route"].checkpoints[12].position = vec.vector(1118.332, 24.47847, -2506.436, 1)
routes["Tanner and Jones 7 Leila Route"].checkpoints[12].heading = -1.731111
routes["Tanner and Jones 7 Leila Route"].checkpoints[12].roadName = "highway01_15 AI Road 51"
routes["Tanner and Jones 7 Leila Route"].arrows = {}
routes["Tanner and Jones 7 Leila Route"].roads = {}
routes["Tanner and Jones 7 Leila Route"].roads[1] = {}
routes["Tanner and Jones 7 Leila Route"].roads[1].road = "marin_sliproad_17 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[1].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[2] = {}
routes["Tanner and Jones 7 Leila Route"].roads[2].road = "highway01_15 AI Road 43"
routes["Tanner and Jones 7 Leila Route"].roads[2].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[3] = {}
routes["Tanner and Jones 7 Leila Route"].roads[3].road = "highway01_15 AI Road 42"
routes["Tanner and Jones 7 Leila Route"].roads[3].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[4] = {}
routes["Tanner and Jones 7 Leila Route"].roads[4].road = "highway01_15 AI Road 41"
routes["Tanner and Jones 7 Leila Route"].roads[4].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[5] = {}
routes["Tanner and Jones 7 Leila Route"].roads[5].road = "highway01_15 AI Road 40"
routes["Tanner and Jones 7 Leila Route"].roads[5].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[6] = {}
routes["Tanner and Jones 7 Leila Route"].roads[6].road = "highway01_15 AI Road 39"
routes["Tanner and Jones 7 Leila Route"].roads[6].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[7] = {}
routes["Tanner and Jones 7 Leila Route"].roads[7].road = "highway01_15 AI Road 38"
routes["Tanner and Jones 7 Leila Route"].roads[7].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[8] = {}
routes["Tanner and Jones 7 Leila Route"].roads[8].road = "highway01_15 AI Road 37"
routes["Tanner and Jones 7 Leila Route"].roads[8].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[9] = {}
routes["Tanner and Jones 7 Leila Route"].roads[9].road = "highway01_15 AI Road 36"
routes["Tanner and Jones 7 Leila Route"].roads[9].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[10] = {}
routes["Tanner and Jones 7 Leila Route"].roads[10].road = "highway01_15 AI Road 35"
routes["Tanner and Jones 7 Leila Route"].roads[10].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[11] = {}
routes["Tanner and Jones 7 Leila Route"].roads[11].road = "highway01_15 AI Road 34"
routes["Tanner and Jones 7 Leila Route"].roads[11].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[12] = {}
routes["Tanner and Jones 7 Leila Route"].roads[12].road = "highway01_15 AI Road 33"
routes["Tanner and Jones 7 Leila Route"].roads[12].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[13] = {}
routes["Tanner and Jones 7 Leila Route"].roads[13].road = "highway01_15 AI Road 32"
routes["Tanner and Jones 7 Leila Route"].roads[13].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[14] = {}
routes["Tanner and Jones 7 Leila Route"].roads[14].road = "highway01_15 AI Road 31"
routes["Tanner and Jones 7 Leila Route"].roads[14].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[15] = {}
routes["Tanner and Jones 7 Leila Route"].roads[15].road = "highway01_15 AI Road 30"
routes["Tanner and Jones 7 Leila Route"].roads[15].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[16] = {}
routes["Tanner and Jones 7 Leila Route"].roads[16].road = "highway01_15 AI Road 29"
routes["Tanner and Jones 7 Leila Route"].roads[16].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[17] = {}
routes["Tanner and Jones 7 Leila Route"].roads[17].road = "marin_shortcut_10 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[17].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[18] = {}
routes["Tanner and Jones 7 Leila Route"].roads[18].road = "mountain_8l_w_08 AI Road 26"
routes["Tanner and Jones 7 Leila Route"].roads[18].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[19] = {}
routes["Tanner and Jones 7 Leila Route"].roads[19].road = "mountain_8l_w_08 AI Road 27"
routes["Tanner and Jones 7 Leila Route"].roads[19].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[20] = {}
routes["Tanner and Jones 7 Leila Route"].roads[20].road = "marin_shortcut_21 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[20].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[21] = {}
routes["Tanner and Jones 7 Leila Route"].roads[21].road = "highway01_15 AI Road 24"
routes["Tanner and Jones 7 Leila Route"].roads[21].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[22] = {}
routes["Tanner and Jones 7 Leila Route"].roads[22].road = "highway01_15 AI Road 23"
routes["Tanner and Jones 7 Leila Route"].roads[22].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[23] = {}
routes["Tanner and Jones 7 Leila Route"].roads[23].road = "highway01_15 AI Road 22"
routes["Tanner and Jones 7 Leila Route"].roads[23].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[24] = {}
routes["Tanner and Jones 7 Leila Route"].roads[24].road = "highway01_15 AI Road 21"
routes["Tanner and Jones 7 Leila Route"].roads[24].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[25] = {}
routes["Tanner and Jones 7 Leila Route"].roads[25].road = "highway01_15 AI Road 20"
routes["Tanner and Jones 7 Leila Route"].roads[25].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[26] = {}
routes["Tanner and Jones 7 Leila Route"].roads[26].road = "highway01_15 AI Road 19"
routes["Tanner and Jones 7 Leila Route"].roads[26].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[27] = {}
routes["Tanner and Jones 7 Leila Route"].roads[27].road = "highway01_15 AI Road 18"
routes["Tanner and Jones 7 Leila Route"].roads[27].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[28] = {}
routes["Tanner and Jones 7 Leila Route"].roads[28].road = "highway01_15 AI Road 17"
routes["Tanner and Jones 7 Leila Route"].roads[28].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[29] = {}
routes["Tanner and Jones 7 Leila Route"].roads[29].road = "highway01_15 AI Road 16"
routes["Tanner and Jones 7 Leila Route"].roads[29].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[30] = {}
routes["Tanner and Jones 7 Leila Route"].roads[30].road = "highway01_15 AI Road 15"
routes["Tanner and Jones 7 Leila Route"].roads[30].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[31] = {}
routes["Tanner and Jones 7 Leila Route"].roads[31].road = "highway01_15 AI Road 14"
routes["Tanner and Jones 7 Leila Route"].roads[31].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[32] = {}
routes["Tanner and Jones 7 Leila Route"].roads[32].road = "highway01_15 AI Road 13"
routes["Tanner and Jones 7 Leila Route"].roads[32].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[33] = {}
routes["Tanner and Jones 7 Leila Route"].roads[33].road = "highway01_15 AI Road 12"
routes["Tanner and Jones 7 Leila Route"].roads[33].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[34] = {}
routes["Tanner and Jones 7 Leila Route"].roads[34].road = "highway01_15 AI Road 11"
routes["Tanner and Jones 7 Leila Route"].roads[34].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[35] = {}
routes["Tanner and Jones 7 Leila Route"].roads[35].road = "highway01_15 AI Road 10"
routes["Tanner and Jones 7 Leila Route"].roads[35].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[36] = {}
routes["Tanner and Jones 7 Leila Route"].roads[36].road = "highway01_15 AI Road 9"
routes["Tanner and Jones 7 Leila Route"].roads[36].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[37] = {}
routes["Tanner and Jones 7 Leila Route"].roads[37].road = "highway01_15 AI Road 8"
routes["Tanner and Jones 7 Leila Route"].roads[37].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[38] = {}
routes["Tanner and Jones 7 Leila Route"].roads[38].road = "highway01_15 AI Road 7"
routes["Tanner and Jones 7 Leila Route"].roads[38].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[39] = {}
routes["Tanner and Jones 7 Leila Route"].roads[39].road = "highway01_15 AI Road 6"
routes["Tanner and Jones 7 Leila Route"].roads[39].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[40] = {}
routes["Tanner and Jones 7 Leila Route"].roads[40].road = "highway01_15 AI Road 5"
routes["Tanner and Jones 7 Leila Route"].roads[40].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[41] = {}
routes["Tanner and Jones 7 Leila Route"].roads[41].road = "highway01_15 AI Road 4"
routes["Tanner and Jones 7 Leila Route"].roads[41].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[42] = {}
routes["Tanner and Jones 7 Leila Route"].roads[42].road = "highway01_15 AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[42].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[43] = {}
routes["Tanner and Jones 7 Leila Route"].roads[43].road = "highway01_15 AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[43].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[44] = {}
routes["Tanner and Jones 7 Leila Route"].roads[44].road = "highway01_15 AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[44].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[45] = {}
routes["Tanner and Jones 7 Leila Route"].roads[45].road = "highway01_15 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[45].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[46] = {}
routes["Tanner and Jones 7 Leila Route"].roads[46].road = "highway_split_sanfran_02 AI Road 5"
routes["Tanner and Jones 7 Leila Route"].roads[46].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[47] = {}
routes["Tanner and Jones 7 Leila Route"].roads[47].road = "highway_split_sanfran_02 AI Road 4"
routes["Tanner and Jones 7 Leila Route"].roads[47].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[48] = {}
routes["Tanner and Jones 7 Leila Route"].roads[48].road = "highway_split_sanfran_02 AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[48].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[49] = {}
routes["Tanner and Jones 7 Leila Route"].roads[49].road = "highway_split_sanfran_02 AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[49].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[50] = {}
routes["Tanner and Jones 7 Leila Route"].roads[50].road = "highway_split_sanfran_02 AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[50].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[51] = {}
routes["Tanner and Jones 7 Leila Route"].roads[51].road = "highway_split_sanfran_02 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[51].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[52] = {}
routes["Tanner and Jones 7 Leila Route"].roads[52].road = "highway01_16b AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[52].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[53] = {}
routes["Tanner and Jones 7 Leila Route"].roads[53].road = "highway01_16b AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[53].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[54] = {}
routes["Tanner and Jones 7 Leila Route"].roads[54].road = "highway01_16b AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[54].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[55] = {}
routes["Tanner and Jones 7 Leila Route"].roads[55].road = "highway01_16b AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[55].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[56] = {}
routes["Tanner and Jones 7 Leila Route"].roads[56].road = "highway01_16b AI Road 4"
routes["Tanner and Jones 7 Leila Route"].roads[56].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[57] = {}
routes["Tanner and Jones 7 Leila Route"].roads[57].road = "highway01_16b AI Road 5"
routes["Tanner and Jones 7 Leila Route"].roads[57].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[58] = {}
routes["Tanner and Jones 7 Leila Route"].roads[58].road = "highway01_16b AI Road 6"
routes["Tanner and Jones 7 Leila Route"].roads[58].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[59] = {}
routes["Tanner and Jones 7 Leila Route"].roads[59].road = "highway01_16b AI Road 7"
routes["Tanner and Jones 7 Leila Route"].roads[59].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[60] = {}
routes["Tanner and Jones 7 Leila Route"].roads[60].road = "highway01_16b AI Road 8"
routes["Tanner and Jones 7 Leila Route"].roads[60].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[61] = {}
routes["Tanner and Jones 7 Leila Route"].roads[61].road = "highway01_16b AI Road 9"
routes["Tanner and Jones 7 Leila Route"].roads[61].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[62] = {}
routes["Tanner and Jones 7 Leila Route"].roads[62].road = "highway01_16b AI Road 10"
routes["Tanner and Jones 7 Leila Route"].roads[62].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[63] = {}
routes["Tanner and Jones 7 Leila Route"].roads[63].road = "highway01_16b AI Road 11"
routes["Tanner and Jones 7 Leila Route"].roads[63].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[64] = {}
routes["Tanner and Jones 7 Leila Route"].roads[64].road = "highway01_16b AI Road 12"
routes["Tanner and Jones 7 Leila Route"].roads[64].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[65] = {}
routes["Tanner and Jones 7 Leila Route"].roads[65].road = "highway01_16b AI Road 13"
routes["Tanner and Jones 7 Leila Route"].roads[65].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[66] = {}
routes["Tanner and Jones 7 Leila Route"].roads[66].road = "highway01_16b AI Road 14"
routes["Tanner and Jones 7 Leila Route"].roads[66].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[67] = {}
routes["Tanner and Jones 7 Leila Route"].roads[67].road = "highway01_16b AI Road 15"
routes["Tanner and Jones 7 Leila Route"].roads[67].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[68] = {}
routes["Tanner and Jones 7 Leila Route"].roads[68].road = "highway01_16b AI Road 16"
routes["Tanner and Jones 7 Leila Route"].roads[68].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[69] = {}
routes["Tanner and Jones 7 Leila Route"].roads[69].road = "highway01_16b AI Road 17"
routes["Tanner and Jones 7 Leila Route"].roads[69].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[70] = {}
routes["Tanner and Jones 7 Leila Route"].roads[70].road = "highway01_16b AI Road 18"
routes["Tanner and Jones 7 Leila Route"].roads[70].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[71] = {}
routes["Tanner and Jones 7 Leila Route"].roads[71].road = "highway01_16b AI Road 19"
routes["Tanner and Jones 7 Leila Route"].roads[71].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[72] = {}
routes["Tanner and Jones 7 Leila Route"].roads[72].road = "highway01_16b AI Road 20"
routes["Tanner and Jones 7 Leila Route"].roads[72].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[73] = {}
routes["Tanner and Jones 7 Leila Route"].roads[73].road = "highway01_16b AI Road 21"
routes["Tanner and Jones 7 Leila Route"].roads[73].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[74] = {}
routes["Tanner and Jones 7 Leila Route"].roads[74].road = "highway01_16b AI Road 22"
routes["Tanner and Jones 7 Leila Route"].roads[74].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[75] = {}
routes["Tanner and Jones 7 Leila Route"].roads[75].road = "highway01_16b AI Road 23"
routes["Tanner and Jones 7 Leila Route"].roads[75].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[76] = {}
routes["Tanner and Jones 7 Leila Route"].roads[76].road = "highway01_16b AI Road 24"
routes["Tanner and Jones 7 Leila Route"].roads[76].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[77] = {}
routes["Tanner and Jones 7 Leila Route"].roads[77].road = "highway01_16b AI Road 25"
routes["Tanner and Jones 7 Leila Route"].roads[77].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[78] = {}
routes["Tanner and Jones 7 Leila Route"].roads[78].road = "highway01_16b AI Road 26"
routes["Tanner and Jones 7 Leila Route"].roads[78].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[79] = {}
routes["Tanner and Jones 7 Leila Route"].roads[79].road = "highway01_16b AI Road 27"
routes["Tanner and Jones 7 Leila Route"].roads[79].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[80] = {}
routes["Tanner and Jones 7 Leila Route"].roads[80].road = "highway01_16b AI Road 28"
routes["Tanner and Jones 7 Leila Route"].roads[80].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[81] = {}
routes["Tanner and Jones 7 Leila Route"].roads[81].road = "highway01_16b AI Road 29"
routes["Tanner and Jones 7 Leila Route"].roads[81].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[82] = {}
routes["Tanner and Jones 7 Leila Route"].roads[82].road = "superhighway_split_02 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[82].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[83] = {}
routes["Tanner and Jones 7 Leila Route"].roads[83].road = "superhighway_split_02 AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[83].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[84] = {}
routes["Tanner and Jones 7 Leila Route"].roads[84].road = "superhighway_split_02 AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[84].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[85] = {}
routes["Tanner and Jones 7 Leila Route"].roads[85].road = "superhighway_split_02 AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[85].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[86] = {}
routes["Tanner and Jones 7 Leila Route"].roads[86].road = "superhighway_road_01 AI Road 6"
routes["Tanner and Jones 7 Leila Route"].roads[86].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[87] = {}
routes["Tanner and Jones 7 Leila Route"].roads[87].road = "superhighway_road_01 AI Road 5"
routes["Tanner and Jones 7 Leila Route"].roads[87].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[88] = {}
routes["Tanner and Jones 7 Leila Route"].roads[88].road = "superhighway_road_01 AI Road 4"
routes["Tanner and Jones 7 Leila Route"].roads[88].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[89] = {}
routes["Tanner and Jones 7 Leila Route"].roads[89].road = "superhighway_road_01 AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[89].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[90] = {}
routes["Tanner and Jones 7 Leila Route"].roads[90].road = "superhighway_road_01 AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[90].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[91] = {}
routes["Tanner and Jones 7 Leila Route"].roads[91].road = "superhighway_road_01 AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[91].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[92] = {}
routes["Tanner and Jones 7 Leila Route"].roads[92].road = "superhighway_road_01 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[92].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[93] = {}
routes["Tanner and Jones 7 Leila Route"].roads[93].road = "superhighway_split_04 AI Road 0"
routes["Tanner and Jones 7 Leila Route"].roads[93].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[94] = {}
routes["Tanner and Jones 7 Leila Route"].roads[94].road = "superhighway_split_04 AI Road 1"
routes["Tanner and Jones 7 Leila Route"].roads[94].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[95] = {}
routes["Tanner and Jones 7 Leila Route"].roads[95].road = "superhighway_split_04 AI Road 2"
routes["Tanner and Jones 7 Leila Route"].roads[95].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[96] = {}
routes["Tanner and Jones 7 Leila Route"].roads[96].road = "superhighway_split_04 AI Road 3"
routes["Tanner and Jones 7 Leila Route"].roads[96].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[97] = {}
routes["Tanner and Jones 7 Leila Route"].roads[97].road = "superhighway_split_04 AI Road 4"
routes["Tanner and Jones 7 Leila Route"].roads[97].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[98] = {}
routes["Tanner and Jones 7 Leila Route"].roads[98].road = "superhighway_split_04 AI Road 5"
routes["Tanner and Jones 7 Leila Route"].roads[98].direction = "with"
routes["Tanner and Jones 7 Leila Route"].roads[99] = {}
routes["Tanner and Jones 7 Leila Route"].roads[99].road = "highway01_15 AI Road 62"
routes["Tanner and Jones 7 Leila Route"].roads[99].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[100] = {}
routes["Tanner and Jones 7 Leila Route"].roads[100].road = "highway01_15 AI Road 61"
routes["Tanner and Jones 7 Leila Route"].roads[100].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[101] = {}
routes["Tanner and Jones 7 Leila Route"].roads[101].road = "highway01_15 AI Road 60"
routes["Tanner and Jones 7 Leila Route"].roads[101].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[102] = {}
routes["Tanner and Jones 7 Leila Route"].roads[102].road = "highway01_15 AI Road 59"
routes["Tanner and Jones 7 Leila Route"].roads[102].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[103] = {}
routes["Tanner and Jones 7 Leila Route"].roads[103].road = "highway01_15 AI Road 58"
routes["Tanner and Jones 7 Leila Route"].roads[103].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[104] = {}
routes["Tanner and Jones 7 Leila Route"].roads[104].road = "highway01_15 AI Road 57"
routes["Tanner and Jones 7 Leila Route"].roads[104].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[105] = {}
routes["Tanner and Jones 7 Leila Route"].roads[105].road = "highway01_15 AI Road 56"
routes["Tanner and Jones 7 Leila Route"].roads[105].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[106] = {}
routes["Tanner and Jones 7 Leila Route"].roads[106].road = "highway01_15 AI Road 55"
routes["Tanner and Jones 7 Leila Route"].roads[106].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[107] = {}
routes["Tanner and Jones 7 Leila Route"].roads[107].road = "highway01_15 AI Road 54"
routes["Tanner and Jones 7 Leila Route"].roads[107].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[108] = {}
routes["Tanner and Jones 7 Leila Route"].roads[108].road = "highway01_15 AI Road 53"
routes["Tanner and Jones 7 Leila Route"].roads[108].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[109] = {}
routes["Tanner and Jones 7 Leila Route"].roads[109].road = "highway01_15 AI Road 52"
routes["Tanner and Jones 7 Leila Route"].roads[109].direction = "against"
routes["Tanner and Jones 7 Leila Route"].roads[110] = {}
routes["Tanner and Jones 7 Leila Route"].roads[110].road = "highway01_15 AI Road 51"
routes["Tanner and Jones 7 Leila Route"].roads[110].direction = "against"
routes["Tanner and Jones 7 Truck Route"] = {}
routes["Tanner and Jones 7 Truck Route"].checkpoints = {}
routes["Tanner and Jones 7 Truck Route"].checkpoints[1] = {}
routes["Tanner and Jones 7 Truck Route"].checkpoints[1].position = vec.vector(-53.58718, 23.68248, -2972.585, 1)
routes["Tanner and Jones 7 Truck Route"].checkpoints[1].heading = 0.240966
routes["Tanner and Jones 7 Truck Route"].checkpoints[1].roadName = "marin_shortcut_38 AI Road 0"
routes["Tanner and Jones 7 Truck Route"].checkpoints[2] = {}
routes["Tanner and Jones 7 Truck Route"].checkpoints[2].position = vec.vector(159.1201, 18.79864, -2882.618, 1)
routes["Tanner and Jones 7 Truck Route"].checkpoints[2].heading = 1.271604
routes["Tanner and Jones 7 Truck Route"].checkpoints[2].roadName = "marin_shortcut_38 AI Road 1"
routes["Tanner and Jones 7 Truck Route"].arrows = {}
routes["Tanner and Jones 7 Truck Route"].roads = {}
routes["Tanner and Jones 7 Truck Route"].roads[1] = {}
routes["Tanner and Jones 7 Truck Route"].roads[1].road = "marin_shortcut_38 AI Road 0"
routes["Tanner and Jones 7 Truck Route"].roads[1].direction = "with"
routes["Tanner and Jones 7 Truck Route"].roads[2] = {}
routes["Tanner and Jones 7 Truck Route"].roads[2].road = "marin_shortcut_38 AI Road 1"
routes["Tanner and Jones 7 Truck Route"].roads[2].direction = "with"
routes["Tanner and Jones 7 Leila Route2"] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[1] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[1].position = vec.vector(-316.1244, 52.33338, -3701.504, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[1].heading = -0.7483885
routes["Tanner and Jones 7 Leila Route2"].checkpoints[1].roadName = "mountain_10l_w_01b AI Road 24"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[2] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[2].position = vec.vector(-736.6318, 41.30601, -3281.726, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[2].heading = -0.8045971
routes["Tanner and Jones 7 Leila Route2"].checkpoints[2].roadName = "mountain_10l_w_01b AI Road 26"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[3] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[3].position = vec.vector(-929.4109, 31.1335, -3095.208, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[3].heading = -0.8019156
routes["Tanner and Jones 7 Leila Route2"].checkpoints[3].roadName = "mountain_10l_w_01b AI Road 27"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[4] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[4].position = vec.vector(-1156.307, 24.5003, -2878.418, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[4].heading = -0.8042356
routes["Tanner and Jones 7 Leila Route2"].checkpoints[4].roadName = "mountain_10l_w_01b AI Road 30"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[5] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[5].position = vec.vector(-1306.466, 8.25, -2703.261, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[5].heading = -0.488203
routes["Tanner and Jones 7 Leila Route2"].checkpoints[5].roadName = "mountain_10l_w_01b AI Road 33"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[6] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[6].position = vec.vector(-1412.873, 8.25, -2575.582, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[6].heading = -0.8846089
routes["Tanner and Jones 7 Leila Route2"].checkpoints[6].roadName = "mountain_10l_w_01b AI Road 34"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[7] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[7].position = vec.vector(-1780.672, 8.25, -2464.999, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[7].heading = -1.236205
routes["Tanner and Jones 7 Leila Route2"].checkpoints[7].roadName = "mountain_10l_w_01b AI Road 36"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[8] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[8].position = vec.vector(-2207.209, 9.347418, -2173.73, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[8].heading = -0.5295805
routes["Tanner and Jones 7 Leila Route2"].checkpoints[8].roadName = "mountain_10l_w_06 AI Road 14"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[9] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[9].position = vec.vector(-2523.288, 18.80249, -1617.709, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[9].heading = -0.5231935
routes["Tanner and Jones 7 Leila Route2"].checkpoints[9].roadName = "mountain_10l_w_06 AI Road 12"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[10] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[10].position = vec.vector(-2855.398, 20.95037, -1425.09, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[10].heading = -1.774484
routes["Tanner and Jones 7 Leila Route2"].checkpoints[10].roadName = "mountain_10l_w_06 AI Road 10"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[11] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[11].position = vec.vector(-3232.832, 25.12008, -1520.312, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[11].heading = -1.822267
routes["Tanner and Jones 7 Leila Route2"].checkpoints[11].roadName = "mountain_10l_w_06 AI Road 8"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[12] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[12].position = vec.vector(-3692.208, 47.47929, -1675.749, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[12].heading = -2.78913
routes["Tanner and Jones 7 Leila Route2"].checkpoints[12].roadName = "mountain_10l_w_06 AI Road 6"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[13] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[13].position = vec.vector(-3584.934, 63.80382, -1878.13, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[13].heading = 1.915912
routes["Tanner and Jones 7 Leila Route2"].checkpoints[13].roadName = "mountain_10l_w_06 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[14] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[14].position = vec.vector(-3459.077, 53.9461, -1979.399, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[14].heading = 2.509469
routes["Tanner and Jones 7 Leila Route2"].checkpoints[14].roadName = "mountain_10l_w_06 AI Road 2"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[15] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[15].position = vec.vector(-3343.591, 41.98941, -2137.052, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[15].heading = 2.50931
routes["Tanner and Jones 7 Leila Route2"].checkpoints[15].roadName = "mountain_10l_w_06 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[16] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[16].position = vec.vector(-2997.749, 41.88807, -2544.375, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[16].heading = 2.442584
routes["Tanner and Jones 7 Leila Route2"].checkpoints[16].roadName = "marin_highway_split_02 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[17] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[17].position = vec.vector(-2662.939, 79.28538, -2940.648, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[17].heading = 2.428418
routes["Tanner and Jones 7 Leila Route2"].checkpoints[17].roadName = "marin_highway_split_02 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[18] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[18].position = vec.vector(-2420.215, 87.69516, -3260.63, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[18].heading = 2.495219
routes["Tanner and Jones 7 Leila Route2"].checkpoints[18].roadName = "mountain_8l_w_08 AI Road 26"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[19] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[19].position = vec.vector(-2223, 66.84827, -3191.022, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[19].heading = 0
routes["Tanner and Jones 7 Leila Route2"].checkpoints[19].roadName = "mountain_8l_w_08 AI Road 23"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[20] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[20].position = vec.vector(-1915.404, 50, -2880.148, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[20].heading = 1.570796
routes["Tanner and Jones 7 Leila Route2"].checkpoints[20].roadName = "mountain_8l_w_08 AI Road 19"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[21] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[21].position = vec.vector(-1534.409, 50, -2914.139, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[21].heading = 1.852252
routes["Tanner and Jones 7 Leila Route2"].checkpoints[21].roadName = "mountain_8l_w_08 AI Road 17"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[22] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[22].position = vec.vector(-1287.434, 42.58877, -3044.449, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[22].heading = 2.249966
routes["Tanner and Jones 7 Leila Route2"].checkpoints[22].roadName = "mountain_8l_w_08 AI Road 15"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[23] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[23].position = vec.vector(-1041.081, 50, -3443.09, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[23].heading = 2.999774
routes["Tanner and Jones 7 Leila Route2"].checkpoints[23].roadName = "mountain_8l_w_08 AI Road 11"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[24] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[24].position = vec.vector(-968.1481, 50, -3892.565, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[24].heading = 2.971222
routes["Tanner and Jones 7 Leila Route2"].checkpoints[24].roadName = "mountain_8l_w_08 AI Road 9"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[25] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[25].position = vec.vector(-842.5203, 56.49808, -4204.589, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[25].heading = 2.459446
routes["Tanner and Jones 7 Leila Route2"].checkpoints[25].roadName = "mountain_8l_w_08 AI Road 5"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[26] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[26].position = vec.vector(-687.5318, 63.00142, -4346.019, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[26].heading = 1.991572
routes["Tanner and Jones 7 Leila Route2"].checkpoints[26].roadName = "mountain_8l_w_08 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[27] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[27].position = vec.vector(-257.4129, 45.50856, -4307.391, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[27].heading = 0.8209092
routes["Tanner and Jones 7 Leila Route2"].checkpoints[27].roadName = "mountain_8l_w_08 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[28] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[28].position = vec.vector(-110.4624, 48.65625, -4037.953, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[28].heading = 0.1383997
routes["Tanner and Jones 7 Leila Route2"].checkpoints[28].roadName = "marin_complex_turn_03 AI Road 0"
routes["Tanner and Jones 7 Leila Route2"].checkpoints[29] = {}
routes["Tanner and Jones 7 Leila Route2"].checkpoints[29].position = vec.vector(-220.1749, 53.46687, -3804.944, 1)
routes["Tanner and Jones 7 Leila Route2"].checkpoints[29].heading = -0.7448713
routes["Tanner and Jones 7 Leila Route2"].checkpoints[29].roadName = "mountain_10l_w_01b AI Road 24"
routes["Tanner and Jones 7 Leila Route2"].arrows = {}
routes["Tanner and Jones 7 Leila Route2"].roads = {}
routes["Tanner and Jones 7 Leila Route2"].roads[1] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[1].road = "mountain_10l_w_01b AI Road 24"
routes["Tanner and Jones 7 Leila Route2"].roads[1].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[2] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[2].road = "mountain_10l_w_01b AI Road 25"
routes["Tanner and Jones 7 Leila Route2"].roads[2].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[3] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[3].road = "mountain_10l_w_01b AI Road 26"
routes["Tanner and Jones 7 Leila Route2"].roads[3].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[4] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[4].road = "mountain_10l_w_01b AI Road 27"
routes["Tanner and Jones 7 Leila Route2"].roads[4].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[5] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[5].road = "mountain_10l_w_01b AI Road 28"
routes["Tanner and Jones 7 Leila Route2"].roads[5].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[6] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[6].road = "mountain_10l_w_01b AI Road 29"
routes["Tanner and Jones 7 Leila Route2"].roads[6].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[7] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[7].road = "mountain_10l_w_01b AI Road 30"
routes["Tanner and Jones 7 Leila Route2"].roads[7].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[8] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[8].road = "mountain_10l_w_01b AI Road 31"
routes["Tanner and Jones 7 Leila Route2"].roads[8].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[9] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[9].road = "mountain_10l_w_01b AI Road 32"
routes["Tanner and Jones 7 Leila Route2"].roads[9].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[10] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[10].road = "mountain_10l_w_01b AI Road 33"
routes["Tanner and Jones 7 Leila Route2"].roads[10].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[11] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[11].road = "mountain_10l_w_01b AI Road 34"
routes["Tanner and Jones 7 Leila Route2"].roads[11].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[12] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[12].road = "mountain_10l_w_01b AI Road 35"
routes["Tanner and Jones 7 Leila Route2"].roads[12].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[13] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[13].road = "mountain_10l_w_01b AI Road 36"
routes["Tanner and Jones 7 Leila Route2"].roads[13].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[14] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[14].road = "mountain_10l_w_01b AI Road 37"
routes["Tanner and Jones 7 Leila Route2"].roads[14].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[15] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[15].road = "mountain_10l_w_06 AI Road 15"
routes["Tanner and Jones 7 Leila Route2"].roads[15].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[16] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[16].road = "mountain_10l_w_06 AI Road 14"
routes["Tanner and Jones 7 Leila Route2"].roads[16].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[17] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[17].road = "mountain_10l_w_06 AI Road 13"
routes["Tanner and Jones 7 Leila Route2"].roads[17].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[18] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[18].road = "mountain_10l_w_06 AI Road 12"
routes["Tanner and Jones 7 Leila Route2"].roads[18].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[19] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[19].road = "mountain_10l_w_06 AI Road 11"
routes["Tanner and Jones 7 Leila Route2"].roads[19].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[20] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[20].road = "mountain_10l_w_06 AI Road 10"
routes["Tanner and Jones 7 Leila Route2"].roads[20].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[21] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[21].road = "mountain_10l_w_06 AI Road 9"
routes["Tanner and Jones 7 Leila Route2"].roads[21].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[22] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[22].road = "mountain_10l_w_06 AI Road 8"
routes["Tanner and Jones 7 Leila Route2"].roads[22].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[23] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[23].road = "mountain_10l_w_06 AI Road 7"
routes["Tanner and Jones 7 Leila Route2"].roads[23].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[24] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[24].road = "mountain_10l_w_06 AI Road 6"
routes["Tanner and Jones 7 Leila Route2"].roads[24].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[25] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[25].road = "mountain_10l_w_06 AI Road 5"
routes["Tanner and Jones 7 Leila Route2"].roads[25].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[26] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[26].road = "mountain_10l_w_06 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].roads[26].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[27] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[27].road = "mountain_10l_w_06 AI Road 3"
routes["Tanner and Jones 7 Leila Route2"].roads[27].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[28] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[28].road = "mountain_10l_w_06 AI Road 2"
routes["Tanner and Jones 7 Leila Route2"].roads[28].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[29] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[29].road = "mountain_10l_w_06 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].roads[29].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[30] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[30].road = "mountain_10l_w_06 AI Road 0"
routes["Tanner and Jones 7 Leila Route2"].roads[30].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[31] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[31].road = "marin_highway_split_02 AI Road 0"
routes["Tanner and Jones 7 Leila Route2"].roads[31].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[32] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[32].road = "marin_highway_split_02 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].roads[32].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[33] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[33].road = "marin_highway_split_02 AI Road 2"
routes["Tanner and Jones 7 Leila Route2"].roads[33].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[34] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[34].road = "marin_highway_split_02 AI Road 3"
routes["Tanner and Jones 7 Leila Route2"].roads[34].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[35] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[35].road = "marin_highway_split_02 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].roads[35].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[36] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[36].road = "mountain_8l_w_08 AI Road 29"
routes["Tanner and Jones 7 Leila Route2"].roads[36].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[37] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[37].road = "mountain_8l_w_08 AI Road 28"
routes["Tanner and Jones 7 Leila Route2"].roads[37].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[38] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[38].road = "mountain_8l_w_08 AI Road 27"
routes["Tanner and Jones 7 Leila Route2"].roads[38].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[39] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[39].road = "mountain_8l_w_08 AI Road 26"
routes["Tanner and Jones 7 Leila Route2"].roads[39].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[40] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[40].road = "mountain_8l_w_08 AI Road 25"
routes["Tanner and Jones 7 Leila Route2"].roads[40].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[41] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[41].road = "mountain_8l_w_08 AI Road 24"
routes["Tanner and Jones 7 Leila Route2"].roads[41].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[42] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[42].road = "mountain_8l_w_08 AI Road 23"
routes["Tanner and Jones 7 Leila Route2"].roads[42].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[43] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[43].road = "mountain_8l_w_08 AI Road 22"
routes["Tanner and Jones 7 Leila Route2"].roads[43].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[44] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[44].road = "mountain_8l_w_08 AI Road 21"
routes["Tanner and Jones 7 Leila Route2"].roads[44].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[45] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[45].road = "mountain_8l_w_08 AI Road 20"
routes["Tanner and Jones 7 Leila Route2"].roads[45].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[46] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[46].road = "mountain_8l_w_08 AI Road 19"
routes["Tanner and Jones 7 Leila Route2"].roads[46].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[47] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[47].road = "mountain_8l_w_08 AI Road 18"
routes["Tanner and Jones 7 Leila Route2"].roads[47].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[48] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[48].road = "mountain_8l_w_08 AI Road 17"
routes["Tanner and Jones 7 Leila Route2"].roads[48].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[49] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[49].road = "mountain_8l_w_08 AI Road 16"
routes["Tanner and Jones 7 Leila Route2"].roads[49].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[50] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[50].road = "mountain_8l_w_08 AI Road 15"
routes["Tanner and Jones 7 Leila Route2"].roads[50].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[51] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[51].road = "mountain_8l_w_08 AI Road 14"
routes["Tanner and Jones 7 Leila Route2"].roads[51].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[52] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[52].road = "mountain_8l_w_08 AI Road 13"
routes["Tanner and Jones 7 Leila Route2"].roads[52].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[53] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[53].road = "mountain_8l_w_08 AI Road 12"
routes["Tanner and Jones 7 Leila Route2"].roads[53].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[54] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[54].road = "mountain_8l_w_08 AI Road 11"
routes["Tanner and Jones 7 Leila Route2"].roads[54].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[55] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[55].road = "mountain_8l_w_08 AI Road 10"
routes["Tanner and Jones 7 Leila Route2"].roads[55].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[56] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[56].road = "mountain_8l_w_08 AI Road 9"
routes["Tanner and Jones 7 Leila Route2"].roads[56].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[57] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[57].road = "mountain_8l_w_08 AI Road 8"
routes["Tanner and Jones 7 Leila Route2"].roads[57].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[58] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[58].road = "mountain_8l_w_08 AI Road 7"
routes["Tanner and Jones 7 Leila Route2"].roads[58].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[59] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[59].road = "mountain_8l_w_08 AI Road 6"
routes["Tanner and Jones 7 Leila Route2"].roads[59].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[60] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[60].road = "mountain_8l_w_08 AI Road 5"
routes["Tanner and Jones 7 Leila Route2"].roads[60].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[61] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[61].road = "mountain_8l_w_08 AI Road 4"
routes["Tanner and Jones 7 Leila Route2"].roads[61].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[62] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[62].road = "mountain_8l_w_08 AI Road 3"
routes["Tanner and Jones 7 Leila Route2"].roads[62].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[63] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[63].road = "mountain_8l_w_08 AI Road 2"
routes["Tanner and Jones 7 Leila Route2"].roads[63].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[64] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[64].road = "mountain_8l_w_08 AI Road 1"
routes["Tanner and Jones 7 Leila Route2"].roads[64].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[65] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[65].road = "mountain_8l_w_08 AI Road 0"
routes["Tanner and Jones 7 Leila Route2"].roads[65].direction = "against"
routes["Tanner and Jones 7 Leila Route2"].roads[66] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[66].road = "marin_complex_turn_03 AI Road 0"
routes["Tanner and Jones 7 Leila Route2"].roads[66].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[67] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[67].road = "mountain_10l_w_01b AI Road 22"
routes["Tanner and Jones 7 Leila Route2"].roads[67].direction = "with"
routes["Tanner and Jones 7 Leila Route2"].roads[68] = {}
routes["Tanner and Jones 7 Leila Route2"].roads[68].road = "mountain_10l_w_01b AI Road 23"
routes["Tanner and Jones 7 Leila Route2"].roads[68].direction = "with"
